/**
 * Lời giải mẫu ĐÃ VERIFY của J1.S.P0001 (bubble sort), chép nguyên văn từ
 * `docs/codelab-authoring/lab211/solutions` — nơi `solkit.py` đã biên dịch và
 * CHẠY THẬT nó, khớp output dưới cả `en_US` lẫn `vi_VN`.
 *
 * Nó nằm đây để làm PHÉP KIỂM NGƯỢC cho bộ chạy: cho `boChayJava` chạy đúng
 * project này, kết quả phải trùng thứ solkit đã chứng minh. Lệch thì lỗi ở bộ
 * chạy chứ không phải ở bài — đúng tinh thần "kiểm bộ kiểm trước khi tin nó".
 *
 * ⚠️ KHÔNG bao giờ đưa nội dung này ra màn hình người học. Đây là đáp án.
 */
export const P0001_TEP: Array<[string, string]> = [
  ["src/bo/ArraySorter.java", "package bo;\n\nimport java.util.Random;\n\n/**\n * Array generation and the sort itself. No printing: the ui layer owns the\n * screen, which is what lets this class be reused and tested.\n */\npublic class ArraySorter {\n\n    private final Random random = new Random();\n\n    /** Fills an array of the requested size with values in [0, bound). */\n    public int[] generate(int size, int bound) {\n        int[] array = new int[size];\n        for (int i = 0; i < size; i++) {\n            array[i] = random.nextInt(bound);\n        }\n        return array;\n    }\n\n    /**\n     * Bubble sort, ascending.\n     *\n     * Two details the brief's own algorithm description asks for, and that an\n     * examiner will look at:\n     *   - the inner loop stops at length-1-i, because after i passes the last i\n     *     elements are already in their final places;\n     *   - the swapped flag ends the sort as soon as a whole pass changes\n     *     nothing, which is the \"if at least one swap has been done, repeat\"\n     *     rule stated in the brief.\n     */\n    public void bubbleSort(int[] array) {\n        for (int i = 0; i < array.length - 1; i++) {\n            boolean swapped = false;\n            for (int j = 0; j < array.length - 1 - i; j++) {\n                if (array[j] > array[j + 1]) {\n                    int temp = array[j];\n                    array[j] = array[j + 1];\n                    array[j + 1] = temp;\n                    swapped = true;\n                }\n            }\n            if (!swapped) {\n                return;\n            }\n        }\n    }\n}\n"],
  ["src/ui/Main.java", "package ui;\n\nimport bo.ArraySorter;\nimport java.util.Arrays;\nimport utils.Validator;\n\n/** Screen only. */\npublic class Main {\n\n    private static final int BOUND = 100;\n\n    public static void main(String[] args) {\n        ArraySorter sorter = new ArraySorter();\n\n        System.out.println(\"===== Bubble Sort Program =====\");\n        int size = Validator.getInt(\"Please input the number of array: \", 1, 1000);\n\n        int[] array = sorter.generate(size, BOUND);\n        System.out.println(\"Unsorted array: \" + Arrays.toString(array));\n\n        sorter.bubbleSort(array);\n        System.out.println(\"Sorted array: \" + Arrays.toString(array));\n    }\n}\n"],
  ["src/utils/Validator.java", "package utils;\n\nimport java.util.Scanner;\n\n/** Every keyboard read in the program, in one place. */\npublic class Validator {\n\n    private static final Scanner SCANNER = new Scanner(System.in);\n\n    private Validator() {\n    }\n\n    /**\n     * A positive int inside [min, max]. The brief asks for \"a positive decimal\n     * number\", so zero and negatives are refused as well as letters.\n     */\n    public static int getInt(String message, int min, int max) {\n        while (true) {\n            System.out.print(message);\n            String line = SCANNER.nextLine().trim();\n            try {\n                int value = Integer.parseInt(line);\n                if (value < min || value > max) {\n                    System.out.println(\"Number must be between \" + min + \" and \" + max + \".\");\n                    continue;\n                }\n                return value;\n            } catch (NumberFormatException e) {\n                System.out.println(\"You must input a number.\");\n            }\n        }\n    }\n}\n"],
];

/** Đúng chuỗi phím `solkit` đã dùng: nhập sai chữ, nhập số âm, rồi nhập 8. */
export const P0001_STDIN = 'abc\n-5\n8\n';
export const P0001_MAIN = 'ui.Main';
