/**
 * SWR302 · Academy Chapter 1 (Essentials) — slide-by-slide walkthrough of book
 * chapter Ch.1 "Essentials of software requirements" (28 slides), SPLIT into
 * four focused lessons by sub-topic so no lesson is overloaded and each idea
 * gets room for deep analysis:
 *   1.3 Why RE & what a requirement is           (slides 1–5)
 *   1.4 The levels and types of requirements     (slides 6–16)   ← core taxonomy
 *   1.5 The requirements process                 (slides 17–20)
 *   1.6 Six requirements problems & the payoff   (slides 21–28)
 * Grounded slide-by-slide in CHAPTER_1_Essential of SW requirement.pdf.
 * Spliced into academy Chapter 1 before its quiz; existing 1.1 / 1.2 untouched.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* ───────── 1.3 — Why requirements engineering & what a requirement is ───────── */
const L3 = {
  title: '1.3 — Slides: why requirements engineering, and what a requirement is (Ch.1 · 1–5)|||1.3 — Slide: vì sao cần kỹ nghệ yêu cầu, và requirement là gì (Ch.1 · 1–5)',
  slug: 'swr302-1-3-ch1-why-and-defined',
  type: 'DOCUMENT',
  description: 'Slide 1–5 của Chương 1 sách: mục tiêu chương, vì sao kỹ nghệ yêu cầu quan trọng (phân bố lỗi ~50% từ yêu cầu & chi phí sửa muộn), và hai định nghĩa kinh điển về "requirement".',
  content: [
    bi(
      `<span class="eyebrow">Chapter 1 · Lesson 1.3 · Book Ch.1 slides 1–5</span>
<h2>Why requirements engineering — and what a “requirement” even is</h2>
<p class="lead">Before any technique, two questions: <em>why</em> does careful requirements work matter, and <em>what</em> exactly is a requirement? These five slides answer both — the cost-of-defects data that justifies the whole discipline, and the definitions the rest of the course relies on.</p>`,
      `<span class="eyebrow">Chương 1 · Bài 1.3 · Slide 1–5 sách Ch.1</span>
<h2>Vì sao cần kỹ nghệ yêu cầu — và “requirement” rốt cuộc là gì</h2>
<p class="lead">Trước mọi kỹ thuật là hai câu hỏi: <em>vì sao</em> làm yêu cầu cẩn thận lại quan trọng, và <em>requirement</em> chính xác là gì? Năm slide này trả lời cả hai — dữ liệu chi phí lỗi biện minh cho cả môn học, và các định nghĩa mà phần còn lại của môn dựa vào.</p>`,
    ),
    walkHead('ch1', 1, 5),
    walk('ch1', [
      [1, 'The essentials of software requirements', `<p>Title slide of the course's first lecture.</p>`, `<p>Slide bìa của buổi giảng đầu tiên.</p>`],
      [2, 'Objectives', `<p>Four goals: understand key terms of the requirements domain, distinguish <strong>product</strong> from <strong>project</strong> requirements, distinguish requirements <strong>development</strong> from <strong>management</strong>, and be alert to common requirements problems. These four framings recur all term.</p>`, `<p>Bốn mục tiêu: hiểu thuật ngữ chính của lĩnh vực yêu cầu, phân biệt yêu cầu <strong>sản phẩm</strong> với <strong>dự án</strong>, phân biệt <strong>phát triển</strong> yêu cầu với <strong>quản lý</strong> yêu cầu, và cảnh giác với các vấn đề yêu cầu thường gặp. Bốn cách nhìn này lặp lại suốt học kỳ.</p>`],
      [3, 'Contents', `<p>The chapter's road map: why requirements engineering, software requirements defined, development vs management, "when bad requirements happen to good people", and the benefits of a high-quality process. Lessons 1.3–1.6 follow this order.</p>`, `<p>Bản đồ chương: vì sao cần kỹ nghệ yêu cầu, định nghĩa yêu cầu phần mềm, phát triển vs quản lý, "khi yêu cầu tồi rơi vào người tốt", và lợi ích của quy trình chất lượng cao. Bài 1.3–1.6 theo đúng thứ tự này.</p>`],
      [4, 'Why requirements engineering? (cost of defects)', `<p>The money slide. Studies (Martin &amp; Leffingwell) show <strong>~50% of defects originate in requirements</strong>, and requirements errors are the <em>most expensive</em> to fix because they surface late — a requirement defect caught in coding, testing or production costs many times what it costs to fix during requirements. This single fact justifies the entire discipline: time spent getting requirements right is the cheapest time on the project.</p>`, `<p>Slide "tiền bạc". Nghiên cứu (Martin &amp; Leffingwell) cho thấy <strong>~50% lỗi bắt nguồn từ yêu cầu</strong>, và lỗi yêu cầu <em>tốn kém nhất</em> để sửa vì lộ ra muộn — một lỗi yêu cầu bắt ở giai đoạn code, test hay vận hành tốn gấp nhiều lần sửa ngay từ khâu yêu cầu. Chỉ một sự thật này đã biện minh cho cả môn: thời gian làm yêu cầu cho đúng là thời gian rẻ nhất của dự án.</p>`],
      [5, 'Software requirements defined', `<p>Two classic definitions to quote in an exam. <strong>Lawrence (1997):</strong> a requirement is <em>"anything that drives design choices."</em> <strong>Sommerville &amp; Sawyer (1997):</strong> requirements are <em>"a specification of what should be implemented — descriptions of how the system should behave, or of a system property or attribute, or a constraint on the development process."</em> Note the breadth: <strong>behaviour, properties, AND constraints</strong> all count as requirements.</p>`, `<p>Hai định nghĩa kinh điển nên thuộc để trích trong bài thi. <strong>Lawrence (1997):</strong> requirement là <em>"bất cứ điều gì chi phối lựa chọn thiết kế."</em> <strong>Sommerville &amp; Sawyer (1997):</strong> yêu cầu là <em>"đặc tả về những gì cần được hiện thực — mô tả hệ thống nên hành xử ra sao, một thuộc tính/đặc tính của hệ thống, hoặc một ràng buộc lên quá trình phát triển."</em> Chú ý độ rộng: <strong>hành vi, thuộc tính, VÀ ràng buộc</strong> đều tính là yêu cầu.</p>`],
    ]),
    books([['wiegers', 'Chapter 1, sections "Why is requirement engineering" and "Software requirements defined"', 'Chương 1, mục "Why is requirement engineering" và "Software requirements defined"']]),
  ].join('\n'),
};

/* ───────── 1.4 — The levels and types of requirements (core taxonomy) ───────── */
const L4 = {
  title: '1.4 — Slides: the levels and types of requirements (Ch.1 · 6–16)|||1.4 — Slide: các cấp và loại yêu cầu (Ch.1 · 6–16)',
  slug: 'swr302-1-4-ch1-levels-types',
  type: 'DOCUMENT',
  description: 'Trọng tâm Chương 1 (slide 6–16): Hình 1-1 và toàn bộ phân loại — business / user / functional / system requirements, SRS, business rules, nonfunctional (quality attributes), và product vs project requirements. Đây là từ vựng cả môn dựa vào.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 1 · Lesson 1.4 · Book Ch.1 slides 6–16</span>
<h2>The levels and types of requirements — the map of the whole course</h2>
<p class="lead">This is the densest and most examined part of Chapter 1, so it gets its own lesson. Figure 1-1 and the slides around it define every term you will use all term: <strong>business → user → functional</strong> requirements, the <strong>SRS</strong>, <strong>system</strong> requirements, <strong>business rules</strong>, <strong>nonfunctional</strong> requirements, and the <strong>product vs project</strong> split. Learn these precisely — the exam lives here.</p>`,
      `<span class="eyebrow">Chương 1 · Bài 1.4 · Slide 6–16 sách Ch.1</span>
<h2>Các cấp và loại yêu cầu — bản đồ của cả môn học</h2>
<p class="lead">Đây là phần dày và hay ra thi nhất của Chương 1, nên tách riêng một bài. Hình 1-1 và các slide quanh nó định nghĩa mọi thuật ngữ bạn sẽ dùng cả kỳ: yêu cầu <strong>business → user → functional</strong>, <strong>SRS</strong>, yêu cầu <strong>system</strong>, <strong>business rules</strong>, yêu cầu <strong>phi chức năng</strong>, và phân biệt <strong>product vs project</strong>. Học thật chính xác — đề thi nằm ở đây.</p>`,
    ),
    walkHead('ch1', 6, 16),
    walk('ch1', [
      [6, 'Types of requirements', `<p>Section divider — the next slides lay out the levels and types, the single most-tested concept of Chapter 1.</p>`, `<p>Slide phân mục — các slide sau trình bày các cấp và loại yêu cầu, khái niệm hay được kiểm tra nhất của Chương 1.</p>`],
      [7, 'Levels and types (Figure 1-1)', `<p>The famous Figure 1-1 — memorise it. Read top-down: <strong>Business requirements</strong> (why) → <strong>User requirements</strong> (what users do) → <strong>Functional requirements</strong> (what the system does), each stored in an artifact (Vision &amp; Scope → user stories/use cases → SRS). From the sides, <strong>business rules</strong>, <strong>quality attributes</strong> (nonfunctional) and <strong>constraints</strong> feed in. Arrow legend: <em>solid</em> = "are stored in"; <em>dotted</em> = "are the origin of / influence." If you learn one diagram in SWR302, learn this one.</p>`, `<p>Hình 1-1 nổi tiếng — hãy thuộc. Đọc từ trên xuống: <strong>Business requirements</strong> (vì sao) → <strong>User requirements</strong> (người dùng làm gì) → <strong>Functional requirements</strong> (hệ thống làm gì), mỗi cấp lưu trong một sản phẩm (Vision &amp; Scope → user story/use case → SRS). Từ hai bên, <strong>business rules</strong>, <strong>thuộc tính chất lượng</strong> (phi chức năng) và <strong>ràng buộc</strong> đổ vào. Chú thích mũi tên: <em>liền</em> = "được lưu trong"; <em>đứt</em> = "là nguồn gốc của / ảnh hưởng." Nếu chỉ thuộc một sơ đồ trong SWR302, hãy thuộc sơ đồ này.</p>`],
      [8, 'Business requirements', `<p><strong>Why</strong> the organisation is building the system — the business benefits it hopes to achieve. Example: an airline wanting to cut counter-staff cost 25% → the idea of a check-in kiosk. They come from the funding sponsor, acquiring customer, users' manager, marketing, or a product visionary, and are recorded in a <strong>Vision &amp; Scope document</strong> (Chapter 5). One project has <em>one</em> set of business requirements.</p>`, `<p><strong>Vì sao</strong> tổ chức xây hệ thống — lợi ích nghiệp vụ mong đạt. Ví dụ: hãng bay muốn giảm 25% chi phí nhân viên quầy → ý tưởng kiosk tự check-in. Chúng đến từ nhà tài trợ, khách hàng mua, quản lý người dùng, marketing, hoặc người có tầm nhìn sản phẩm, và được ghi trong <strong>tài liệu Vision &amp; Scope</strong> (Chương 5). Một dự án có <em>một</em> tập business requirement.</p>`],
      [9, 'User requirements', `<p>Goals or tasks users must be able to perform to get value, plus product characteristics important to user satisfaction. Represented with <strong>use cases, user stories, event-response tables</strong> — ideally from real user representatives. Example task "Check in for a flight"; as a user story: <em>"As a passenger, I want to check in for a flight so I can board my airplane."</em> Key point: most projects have <strong>multiple user classes</strong> whose needs all must be elicited.</p>`, `<p>Mục tiêu hoặc công việc người dùng phải làm được để có giá trị, cộng các đặc tính sản phẩm quan trọng cho sự hài lòng. Biểu diễn bằng <strong>use case, user story, bảng event-response</strong> — lý tưởng từ đại diện người dùng thật. Ví dụ công việc "Check in cho chuyến bay"; dạng user story: <em>"Là hành khách, tôi muốn check-in để lên máy bay."</em> Ý chính: đa số dự án có <strong>nhiều lớp người dùng</strong> mà nhu cầu đều phải khai thác.</p>`],
      [10, 'Functional requirements', `<p>Specification of the <strong>behaviours the product exhibits under specific conditions</strong> — what developers must build so users accomplish their tasks (thereby satisfying business requirements). This alignment across the three levels is essential for success. Often written as "shall" statements: <em>"The Passenger shall be able to print boarding passes for all flight segments for which he has checked in."</em></p>`, `<p>Đặc tả <strong>hành vi sản phẩm thể hiện dưới điều kiện cụ thể</strong> — thứ lập trình viên phải xây để người dùng hoàn thành công việc (nhờ đó thoả mãn business requirement). Sự thẳng hàng ba cấp này thiết yếu cho thành công. Thường viết dạng "shall": <em>"Hành khách <b>shall</b> in được thẻ lên máy bay cho mọi chặng đã check-in."</em></p>`],
      [11, 'Software Requirements Specification (SRS)', `<p>The BA documents functional requirements in an <strong>SRS</strong> — describing as fully as needed the expected behaviour of the system, used in development, testing, QA and project management. It goes by many names (functional spec, requirements document…) and can be a report from a requirements tool. The SRS is the central deliverable of this course (Chapters 10–11).</p>`, `<p>BA ghi các yêu cầu chức năng vào một <strong>SRS</strong> — mô tả đầy đủ đến mức cần thiết hành vi mong đợi của hệ thống, dùng trong phát triển, kiểm thử, QA và quản lý dự án. Có nhiều tên gọi (functional spec, requirements document…) và có thể là báo cáo xuất từ công cụ. SRS là sản phẩm trung tâm của môn (Chương 10–11).</p>`],
      [12, 'System requirements', `<p>Requirements for a product made of <strong>multiple components/subsystems</strong> — a "system" here can be all software, or software + hardware, and even people and processes (some functions may be allocated to humans). The book's caution: it does <em>not</em> use "system requirements" to mean "detailed software requirements", a common source of confusion.</p>`, `<p>Yêu cầu cho một sản phẩm gồm <strong>nhiều thành phần/hệ con</strong> — "hệ thống" ở đây có thể toàn phần mềm, hoặc phần mềm + phần cứng, và cả con người và quy trình (một số chức năng giao cho con người). Sách lưu ý: nó <em>không</em> dùng "system requirements" để chỉ "yêu cầu phần mềm chi tiết", một chỗ hay nhầm.</p>`],
      [13, 'Business rules', `<p>Corporate policies, government regulations, industry standards, computational algorithms. A business rule is <strong>not itself a requirement</strong> — it exists beyond any one application — but it often <em>dictates</em> functionality the system must have to comply. You can trace certain functional requirements back to a business rule (Chapter 9 covers this in depth).</p>`, `<p>Chính sách công ty, quy định nhà nước, chuẩn ngành, thuật toán tính. Một business rule <strong>tự nó không phải requirement</strong> — nó tồn tại ngoài phạm vi bất kỳ ứng dụng nào — nhưng thường <em>bắt buộc</em> hệ thống phải có chức năng tuân thủ. Có thể truy vết một số yêu cầu chức năng về một business rule (Chương 9 đi sâu).</p>`],
      [14, 'Nonfunctional requirements', `<p>Beyond functions, the SRS holds nonfunctional requirements: <strong>quality attributes</strong> (the "–ilities": performance, safety, availability, portability…), <strong>external interfaces</strong> (to other systems, hardware, users), and <strong>design/implementation constraints</strong>. These are as important as functions and are the subject of Chapter 14.</p>`, `<p>Ngoài chức năng, SRS chứa yêu cầu phi chức năng: <strong>thuộc tính chất lượng</strong> (các "–ility": hiệu năng, an toàn, sẵn sàng, khả chuyển…), <strong>giao diện ngoài</strong> (tới hệ khác, phần cứng, người dùng), và <strong>ràng buộc thiết kế/hiện thực</strong>. Chúng quan trọng ngang chức năng và là chủ đề Chương 14.</p>`],
      [15, 'Stakeholder participation in requirements', `<p>Section divider — a reminder that requirements are produced <em>with</em> stakeholders, not written in isolation. Who participates and how is Chapter 2 and Chapter 6.</p>`, `<p>Slide phân mục — nhắc rằng yêu cầu được tạo <em>cùng</em> các bên liên quan, không viết một mình. Ai tham gia và tham gia thế nào là Chương 2 và Chương 6.</p>`],
      [16, 'Product vs. project requirements', `<p>A key distinction (Objective 2). <strong>Product requirements</strong> = properties of the software to be built. <strong>Project requirements</strong> = other deliverables the project needs but that are <em>not</em> in the software: hardware/workstations, staff training, user documentation, support docs, infrastructure changes, third-party licensing, beta testing, packaging, marketing, SLAs. The SRS holds product requirements; the project plan holds project requirements — do not mix them in the SRS.</p>`, `<p>Một phân biệt then chốt (Mục tiêu 2). <strong>Product requirements</strong> = thuộc tính của phần mềm cần xây. <strong>Project requirements</strong> = các sản phẩm khác dự án cần nhưng <em>không</em> nằm trong phần mềm: phần cứng/máy trạm, đào tạo nhân sự, tài liệu người dùng, tài liệu hỗ trợ, thay đổi hạ tầng, license bên thứ ba, beta test, đóng gói, marketing, SLA. SRS giữ product requirement; kế hoạch dự án giữ project requirement — đừng trộn chúng vào SRS.</p>`],
    ]),
    books([
      ['wiegers', 'Chapter 1, "Software requirements defined" → the levels-and-types figure; also skim Ch.5 (business req) and Ch.10 (SRS)', 'Chương 1, "Software requirements defined" → hình các cấp/loại; lướt thêm Ch.5 (business req) và Ch.10 (SRS)'],
      ['cos', 'find each level in the COS artifacts: Vision &amp; Scope (business), Use Cases (user), SRS (functional + nonfunctional), Business Rules', 'tìm từng cấp trong sản phẩm COS: Vision &amp; Scope (business), Use Cases (user), SRS (functional + phi chức năng), Business Rules'],
    ]),
  ].join('\n'),
};

/* ───────── 1.5 — The requirements process: development & management ───────── */
const L5 = {
  title: '1.5 — Slides: the requirements process — development & management (Ch.1 · 17–20)|||1.5 — Slide: quy trình yêu cầu — phát triển & quản lý (Ch.1 · 17–20)',
  slug: 'swr302-1-5-ch1-process',
  type: 'DOCUMENT',
  description: 'Slide 17–20: hai nửa của kỹ nghệ yêu cầu — phát triển (elicitation, analysis, specification, validation) và quản lý — với các hoạt động chính của từng bước.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 1 · Lesson 1.5 · Book Ch.1 slides 17–20</span>
<h2>The requirements process: development vs management</h2>
<p class="lead">Objective 3 in detail. Requirements engineering has two halves. <strong>Development</strong> = discovering and writing the requirements (four activities: elicitation, analysis, specification, validation). <strong>Management</strong> = controlling them once baselined. These four activities are the backbone the whole course expands on.</p>`,
      `<span class="eyebrow">Chương 1 · Bài 1.5 · Slide 17–20 sách Ch.1</span>
<h2>Quy trình yêu cầu: phát triển vs quản lý</h2>
<p class="lead">Mục tiêu 3 ở mức chi tiết. Kỹ nghệ yêu cầu có hai nửa. <strong>Phát triển</strong> = khám phá và viết yêu cầu (bốn hoạt động: elicitation, analysis, specification, validation). <strong>Quản lý</strong> = kiểm soát chúng sau khi baseline. Bốn hoạt động này là xương sống mà cả môn học mở rộng ra.</p>`,
    ),
    walkHead('ch1', 17, 20),
    walk('ch1', [
      [17, 'Requirements development and management', `<p>Section divider — the two halves. <em>Development</em> = elicitation + analysis + specification + validation (this lesson). <em>Management</em> = handling changes and versions after a baseline (Chapters 27–29). Keep the two straight: development creates requirements, management controls them over time.</p>`, `<p>Slide phân mục — hai nửa. <em>Phát triển</em> = elicitation + analysis + specification + validation (bài này). <em>Quản lý</em> = xử lý thay đổi và phiên bản sau khi baseline (Chương 27–29). Nhớ rõ: phát triển tạo ra yêu cầu, quản lý kiểm soát chúng theo thời gian.</p>`],
      [18, 'Elicitation', `<p>All activities to <strong>discover</strong> requirements: interviews, workshops, document analysis, prototyping. Key actions: identify the product's user classes and stakeholders; understand user tasks/goals and the business objectives they align to; learn the usage environment; and work with each user class's representatives on their functionality needs and quality expectations. This is Chapters 6–8.</p>`, `<p>Mọi hoạt động để <strong>khám phá</strong> yêu cầu: phỏng vấn, workshop, phân tích tài liệu, prototyping. Hành động chính: xác định lớp người dùng và bên liên quan; hiểu công việc/mục tiêu người dùng và mục tiêu nghiệp vụ chúng gắn tới; tìm hiểu môi trường sử dụng; và làm việc với đại diện từng lớp người dùng về nhu cầu chức năng và kỳ vọng chất lượng. Đây là Chương 6–8.</p>`],
      [19, 'Analysis', `<p>Reaching a richer, more precise understanding and representing requirements multiple ways: separate task goals from functional requirements/quality expectations/business rules/proposed solutions; decompose high-level into detail; derive functional requirements; judge relative importance of quality attributes; allocate to architecture components; negotiate priorities; find gaps and unnecessary requirements against scope. Modeling (Chapters 12–13) is the main tool here.</p>`, `<p>Đạt hiểu biết sâu và chính xác hơn, biểu diễn yêu cầu theo nhiều cách: tách mục tiêu công việc khỏi yêu cầu chức năng/kỳ vọng chất lượng/business rule/giải pháp đề xuất; phân rã cấp cao thành chi tiết; suy ra yêu cầu chức năng; đánh giá tầm quan trọng tương đối của thuộc tính chất lượng; phân bổ cho thành phần kiến trúc; thương lượng ưu tiên; tìm lỗ hổng và yêu cầu thừa so với phạm vi. Mô hình hoá (Chương 12–13) là công cụ chính.</p>`],
      [20, 'Specification & Validation', `<p><strong>Specification</strong> = store the collected knowledge persistently and well-organised: translate user needs into written requirements and diagrams suited to their audiences (the SRS). <strong>Validation</strong> = confirm you have the <em>correct</em> set: review the documented requirements to fix problems before the development group accepts them, and develop acceptance tests/criteria to confirm a product built from them would meet business objectives. Validation is Chapter 17.</p>`, `<p><strong>Specification</strong> = lưu tri thức đã thu thập một cách bền vững và có tổ chức: chuyển nhu cầu người dùng thành yêu cầu viết và sơ đồ phù hợp người đọc (SRS). <strong>Validation</strong> = xác nhận bạn có tập <em>đúng</em>: review yêu cầu đã ghi để sửa lỗi trước khi nhóm phát triển chấp nhận, và xây acceptance test/tiêu chí để chắc sản phẩm xây từ chúng đạt mục tiêu nghiệp vụ. Validation là Chương 17.</p>`],
    ]),
    books([['wiegers', 'Chapter 1, "Requirements development and management"; then Figure of the requirements engineering process', 'Chương 1, "Requirements development and management"; rồi hình quy trình kỹ nghệ yêu cầu']]),
  ].join('\n'),
};

/* ───────── 1.6 — Six requirements problems & the payoff ───────── */
const L6 = {
  title: '1.6 — Slides: six requirements problems & the payoff (Ch.1 · 21–28)|||1.6 — Slide: sáu vấn đề yêu cầu & lợi ích (Ch.1 · 21–28)',
  slug: 'swr302-1-6-ch1-problems-benefits',
  type: 'DOCUMENT',
  description: 'Slide 21–28: sáu thất bại yêu cầu kinh điển (thiếu người dùng, kế hoạch sai, phình phạm vi, mơ hồ, gold plating, bỏ sót bên liên quan) — mỗi cái một slide phân tích — và lợi ích của quy trình yêu cầu chất lượng cao.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 1 · Lesson 1.6 · Book Ch.1 slides 21–28</span>
<h2>Six requirements problems — and the payoff of getting it right</h2>
<p class="lead">"When bad requirements happen to good people." Each of the six classic failures gets its own slide and its own fix, so you can diagnose a real project by name. The last slide is the business case: what a high-quality requirements process buys you.</p>`,
      `<span class="eyebrow">Chương 1 · Bài 1.6 · Slide 21–28 sách Ch.1</span>
<h2>Sáu vấn đề yêu cầu — và lợi ích khi làm đúng</h2>
<p class="lead">"Khi yêu cầu tồi rơi vào người tốt." Mỗi trong sáu thất bại kinh điển có slide riêng và cách sửa riêng, để bạn chẩn đúng tên vấn đề của một dự án thật. Slide cuối là lý do kinh doanh: quy trình yêu cầu chất lượng cao mang lại gì.</p>`,
    ),
    walkHead('ch1', 21, 28),
    walk('ch1', [
      [21, 'When bad requirements happen to good people', `<p>The six classic requirements failures, each unpacked next: <strong>insufficient user involvement, inaccurate planning, creeping requirements, ambiguous requirements, gold plating, overlooked stakeholders</strong>. This is the exam's favourite list and the real reasons projects fail.</p>`, `<p>Sáu thất bại yêu cầu kinh điển, mỗi cái mổ xẻ ngay sau: <strong>thiếu sự tham gia của người dùng, lập kế hoạch không chính xác, yêu cầu phình dần, yêu cầu mơ hồ, gold plating, bỏ sót bên liên quan</strong>. Đây là danh sách đề thi hay hỏi và là lý do thật khiến dự án thất bại.</p>`],
      [22, '1. Insufficient user involvement', `<p>Customers don't see why eliciting requirements matters; developers assume they already know; real users are hard to reach and surrogates miss real needs. Result: late-breaking requirements → rework and delay, and sometimes a "perfect" solution nobody uses because the business problem was misunderstood. <strong>Fix:</strong> ongoing conversations with real users and careful review of the requirements by them.</p>`, `<p>Khách hàng không thấy vì sao khai thác yêu cầu quan trọng; lập trình viên tưởng đã hiểu; người dùng thật khó tiếp cận và người thay thế bỏ lỡ nhu cầu thật. Hậu quả: yêu cầu đến muộn → làm lại và trễ, đôi khi một giải pháp "hoàn hảo" không ai dùng vì hiểu sai bài toán nghiệp vụ. <strong>Cách sửa:</strong> trò chuyện liên tục với người dùng thật và để họ review yêu cầu kỹ.</p>`],
      [23, '2. Inaccurate planning', `<p>"When will you be done?" should never be answered before the problem is understood. Vague requirements → optimistic estimates → overruns; a quick guess sounds like a commitment. Top causes of bad cost estimates: frequent changes, missing requirements, poor user communication, poor specification, insufficient analysis. <strong>Fix:</strong> estimate from the <em>size</em> of the requirements and the team's productivity, not a gut number.</p>`, `<p>"Khi nào xong?" không nên trả lời trước khi hiểu bài toán. Yêu cầu mơ hồ → ước lượng lạc quan → vượt kế hoạch; một câu đoán nhanh nghe như một cam kết. Nguyên nhân hàng đầu của ước lượng tồi: thay đổi liên tục, thiếu yêu cầu, giao tiếp kém với người dùng, đặc tả kém, phân tích không đủ. <strong>Cách sửa:</strong> ước lượng từ <em>kích cỡ</em> yêu cầu và năng suất nhóm, không phải con số cảm tính.</p>`],
      [24, '3. Creeping (scope) requirements', `<p>Requirements evolve; projects exceed schedule/budget. <strong>Fix:</strong> start from a clear statement of business objectives, vision, scope, limitations and success criteria, and evaluate every proposed change against it; build contingency buffers. Agile fits scope to a fixed iteration budget and pushes new items to the backlog by priority. Change is fine — but change always has a price.</p>`, `<p>Yêu cầu tiến hoá; dự án vượt lịch/ngân sách. <strong>Cách sửa:</strong> bắt đầu từ tuyên bố rõ về mục tiêu nghiệp vụ, tầm nhìn, phạm vi, giới hạn và tiêu chí thành công, và đánh giá mọi thay đổi so với nó; dựng đệm dự phòng. Agile nắn phạm vi vừa ngân sách một iteration cố định và đẩy mục mới vào backlog theo ưu tiên. Thay đổi thì được — nhưng luôn có giá.</p>`],
      [25, '4. Ambiguous requirements', `<p>Symptoms: one reader interprets a statement several ways, or different readers understand it differently → mismatched expectations, wasted time building/testing the wrong thing. <strong>Fix:</strong> have people of different perspectives inspect the requirements (collaborative elicitation/validation in a workshop), write tests against them, and build prototypes to expose the ambiguity.</p>`, `<p>Dấu hiệu: một người đọc hiểu một câu theo nhiều nghĩa, hoặc nhiều người hiểu khác nhau → kỳ vọng lệch nhau, tốn công xây/test sai. <strong>Cách sửa:</strong> để người ở các góc nhìn khác nhau soi yêu cầu (elicitation/validation cộng tác trong workshop), viết test dựa trên chúng, và dựng prototype để lộ chỗ mơ hồ.</p>`],
      [26, '5. Gold plating', `<p>A developer (or BA) adds functionality not in the spec because "users will love it". If users don't care, the time is wasted. <strong>Fix:</strong> present ideas to stakeholders for consideration; strive for leanness and simplicity; never exceed what's requested without approval; and <strong>trace every function back to its origin and business justification</strong>, keeping within scope.</p>`, `<p>Lập trình viên (hoặc BA) thêm chức năng không có trong spec vì "người dùng sẽ thích". Nếu người dùng không quan tâm, công sức phí. <strong>Cách sửa:</strong> trình ý tưởng cho bên liên quan cân nhắc; hướng tới gọn và đơn giản; đừng vượt yêu cầu khi chưa được duyệt; và <strong>truy vết mỗi chức năng về nguồn gốc và lý do nghiệp vụ</strong>, giữ trong phạm vi.</p>`],
      [27, '6. Overlooked stakeholders', `<p>Most products have several user classes (different feature subsets, usage frequency, experience); miss one early and its needs go unmet. <strong>Fix:</strong> identify all user classes and give each a voice; think about maintenance/field-support staff (their own functional + nonfunctional needs), data-conversion/transition needs from legacy systems, and even stakeholders who don't know the project exists (e.g. regulators mandating standards). Chapter 6 systematises finding them.</p>`, `<p>Đa số sản phẩm có nhiều lớp người dùng (tập tính năng, tần suất, kinh nghiệm khác nhau); bỏ sót một lớp từ sớm là nhu cầu của nó không được đáp ứng. <strong>Cách sửa:</strong> xác định mọi lớp người dùng và cho mỗi lớp một tiếng nói; nghĩ tới nhân viên bảo trì/hỗ trợ hiện trường (nhu cầu chức năng + phi chức năng riêng), nhu cầu chuyển đổi dữ liệu từ hệ cũ, và cả bên liên quan không biết dự án tồn tại (vd cơ quan quản lý áp chuẩn). Chương 6 hệ thống hoá việc tìm họ.</p>`],
      [28, 'Benefits from a high-quality requirements process', `<p>The payoff: fewer defects in requirements and product, less rework, faster delivery, fewer unused features, lower enhancement cost, fewer miscommunications, less scope creep and project chaos, higher satisfaction, and products that do what they should. This is the return on everything the course teaches — the business case for taking requirements seriously.</p>`, `<p>Phần thưởng: ít lỗi trong yêu cầu và sản phẩm, ít làm lại, giao nhanh hơn, ít tính năng thừa, chi phí nâng cấp thấp hơn, ít hiểu lầm, ít scope creep và hỗn loạn dự án, hài lòng cao hơn, và sản phẩm làm đúng việc cần làm. Đây là lợi tức của mọi thứ môn học dạy — lý do kinh doanh để coi trọng yêu cầu.</p>`],
    ]),
    books([
      ['wiegers', 'Chapter 1, "When bad requirements happen to good people" and "Benefits from a high-quality requirements process"', 'Chương 1, "When bad requirements happen to good people" và "Benefits from a high-quality requirements process"'],
      ['more', 'the "Thorny Issues" essays expand several of these six problems with real cases', 'các tiểu luận "Thorny Issues" mở rộng vài trong sáu vấn đề này bằng ca thật'],
    ]),
  ].join('\n'),
};

export default [L3, L4, L5, L6];
