/**
 * SWR302 · Academy Chapter 4 (Analysis & modeling) additions — book chapter Ch.12
 * "A picture is worth 1024 words" (25 slides), split into THREE focused lessons:
 * why & how to model (1–9), flow & behavioral models (10–17), and decision
 * models + UML + agile modeling (18–25). Exported as an array spliced into
 * academy Chapter 4 before its quiz. Grounded slide-by-slide in
 * CHAPTER_12_A picture is worth 1024 words.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 4.7 — why & how to model */
const V1 = {
  title: '4.7 — Slides: why models, and choosing one (Ch.12 · 1–9)|||4.7 — Slide: vì sao mô hình hoá, và chọn loại nào (Ch.12 · 1–9)',
  slug: 'swr302-4-7-ch12-why-model',
  type: 'DOCUMENT',
  description: 'Slide 1–9: tại sao một hình đáng 1024 từ, mô hình giúp lộ yêu cầu thiếu/thừa/mâu thuẫn, dịch "tiếng nói khách hàng" thành phần tử mô hình (Bảng 12-1), và chọn kỹ thuật biểu diễn phù hợp (Bảng 12-2).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 4 · Lesson 4.7 · Book Ch.12 slides 1–9</span>
<h2>Why models, and choosing the right one</h2>
<p class="lead">A diagram communicates some things far better than prose and bridges vocabulary gaps. More importantly, the <em>act</em> of modeling surfaces missing, extraneous and inconsistent requirements a human can't spot in a 1,000-item list. This lesson covers the purpose of models and how to pick one.</p>`,
      `<span class="eyebrow">Chương 4 · Bài 4.7 · Slide 1–9 sách Ch.12</span>
<h2>Vì sao mô hình hoá, và chọn loại nào</h2>
<p class="lead">Một sơ đồ truyền đạt vài thứ tốt hơn hẳn văn xuôi và bắc cầu qua rào từ vựng. Quan trọng hơn, <em>hành động</em> mô hình hoá làm lộ yêu cầu thiếu, thừa, mâu thuẫn mà con người không thấy trong danh sách 1.000 mục. Bài này nói về mục đích của mô hình và cách chọn.</p>`,
    ),
    walkHead('ch12', 1, 9),
    walk('ch12', [
      [1, 'A picture is worth 1024 words', `<p>Title slide — visual models as a requirements representation, complementing (not replacing) written requirements.</p>`, `<p>Slide bìa — mô hình trực quan như một cách biểu diễn yêu cầu, bổ trợ (không thay) yêu cầu viết.</p>`],
      [2, 'Objectives', `<p>Understand the purpose of every diagram type, when and how to build each, and how to plan which models to use for a given set of requirements.</p>`, `<p>Hiểu mục đích của mỗi loại sơ đồ, khi nào và cách dựng từng cái, và cách lên kế hoạch dùng mô hình nào cho một tập yêu cầu.</p>`],
      [3, 'Contents', `<p>Road map: why pictures help, modeling to find defects, voice-of-customer → models, selecting representations, then the concrete diagrams — DFD, swimlane, state-transition, decision tables/trees, and agile modeling.</p>`, `<p>Bản đồ: vì sao hình giúp ích, mô hình để bắt lỗi, tiếng nói khách → mô hình, chọn cách biểu diễn, rồi các sơ đồ cụ thể — DFD, swimlane, state-transition, decision table/tree, và mô hình hoá agile.</p>`],
      [4, '1. A useful picture in representation', `<p>Diagrams communicate <strong>certain types of information more efficiently than text can</strong> — flows, relationships, states, decision logic. Pictures also <strong>bridge language and vocabulary barriers</strong> among team members who describe the same idea with different words. A model is a shared, unambiguous artefact everyone can point at.</p>`, `<p>Sơ đồ truyền đạt <strong>vài loại thông tin hiệu quả hơn văn</strong> — luồng, quan hệ, trạng thái, logic quyết định. Hình cũng <strong>bắc cầu qua rào ngôn ngữ và từ vựng</strong> giữa các thành viên mô tả cùng ý bằng từ khác nhau. Mô hình là một hiện vật chung, không mơ hồ, ai cũng chỉ vào được.</p>`],
      [5, '2. Modeling the requirements', `<p>Visual models help you <strong>identify missing, extraneous, and inconsistent requirements</strong>. Given human short-term memory limits, analyzing a list of a thousand requirements for inconsistency, duplication and extraneous items by eye is nearly impossible — a model compresses them into a structure your brain <em>can</em> reason about, so the gaps become visible.</p>`, `<p>Mô hình trực quan giúp bạn <strong>nhận ra yêu cầu thiếu, thừa, và mâu thuẫn</strong>. Với giới hạn trí nhớ ngắn hạn, phân tích danh sách nghìn yêu cầu để tìm mâu thuẫn, trùng lặp, thừa bằng mắt là gần như bất khả. Mô hình nén chúng thành cấu trúc mà não <em>có thể</em> suy luận, nên lỗ hổng lộ ra.</p>`],
      [6, '3. Voice of the customer → analysis models', `<p>By listening carefully to <em>how</em> customers phrase requirements, the BA picks out <strong>keywords that translate into specific model elements</strong>. Table 12-1 maps the "customer's voice" to model components: nouns → entities/data objects, verbs → processes/functions, "when/if" → states/conditions, "who" → actors/external entities. The language of the requirement tells you which model it belongs in.</p>`, `<p>Nghe kỹ <em>cách</em> khách diễn đạt yêu cầu, BA nhặt ra <strong>từ khoá dịch thành phần tử mô hình cụ thể</strong>. Bảng 12-1 ánh xạ "tiếng nói khách hàng" sang thành phần mô hình: danh từ → thực thể/đối tượng dữ liệu, động từ → tiến trình/hàm, "khi/nếu" → trạng thái/điều kiện, "ai" → actor/thực thể ngoài. Ngôn ngữ của yêu cầu cho biết nó thuộc mô hình nào.</p>`],
      [7, '4. Selecting the right representation', `<p>Table 12-2 helps choose the most appropriate technique per need. No single diagram shows everything — pick by <strong>what you must communicate</strong>: data flow → DFD; sequence of steps across roles → swimlane; how a thing changes over time → state-transition; complex conditional logic → decision table/tree; data structure → ER/class diagram.</p>`, `<p>Bảng 12-2 giúp chọn kỹ thuật phù hợp nhất theo nhu cầu. Không sơ đồ nào chỉ ra mọi thứ — chọn theo <strong>điều bạn cần truyền đạt</strong>: luồng dữ liệu → DFD; chuỗi bước qua các vai → swimlane; một thứ đổi theo thời gian → state-transition; logic điều kiện phức tạp → decision table/tree; cấu trúc dữ liệu → ER/class diagram.</p>`],
      [8, 'Selecting the right representation (matrix)', `<p>The selection matrix continues — cross-referencing requirement types (functional, data, business rules, quality) against diagram types so you can see at a glance which models cover which concerns, and where a project needs more than one.</p>`, `<p>Ma trận chọn tiếp tục — đối chiếu loại yêu cầu (chức năng, dữ liệu, business rule, chất lượng) với loại sơ đồ để thấy nhanh mô hình nào phủ mối quan tâm nào, và chỗ nào dự án cần nhiều hơn một.</p>`],
      [9, 'Selecting the right representation (guidance)', `<p>Practical guidance closes the topic: you rarely need every model. Build the <strong>few that reduce the most risk</strong> for this project, at the detail your stakeholders actually need — a theme the chapter returns to under "modeling on agile projects."</p>`, `<p>Hướng dẫn thực tế khép chủ đề: hiếm khi cần mọi mô hình. Dựng <strong>vài cái giảm nhiều rủi ro nhất</strong> cho dự án này, ở mức chi tiết stakeholder thật sự cần — một ý mà chương quay lại ở "mô hình hoá trên dự án agile".</p>`],
    ]),
    books([['wiegers', 'Chapter 12, "Modeling the requirements", "From the customer\'s voice to analysis models" (Table 12-1), "Selecting the right representation" (Table 12-2)', 'Chương 12, "Modeling the requirements", "From the customer\'s voice to analysis models" (Bảng 12-1), "Selecting the right representation" (Bảng 12-2)']]),
  ].join('\n'),
};

/* 4.8 — flow & behavioral models */
const V2 = {
  title: '4.8 — Slides: flow & behavioral models (Ch.12 · 10–17)|||4.8 — Slide: mô hình luồng & hành vi (Ch.12 · 10–17)',
  slug: 'swr302-4-8-ch12-flow-models',
  type: 'DOCUMENT',
  description: 'Slide 10–17: data flow diagram (context/level-0), swimlane diagram, và state-transition diagram + state table — ba mô hình về cách dữ liệu chảy, các bước qua nhiều vai, và cách hệ thống đổi trạng thái.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 4 · Lesson 4.8 · Book Ch.12 slides 10–17</span>
<h2>Flow &amp; behavioral models</h2>
<p class="lead">Three workhorse diagrams: the <strong>data flow diagram</strong> (how data moves), the <strong>swimlane diagram</strong> (steps across actors), and the <strong>state-transition diagram &amp; state table</strong> (how the system changes state). Each exposes a different class of missing requirement.</p>`,
      `<span class="eyebrow">Chương 4 · Bài 4.8 · Slide 10–17 sách Ch.12</span>
<h2>Mô hình luồng &amp; hành vi</h2>
<p class="lead">Ba sơ đồ chủ lực: <strong>data flow diagram</strong> (dữ liệu chảy thế nào), <strong>swimlane diagram</strong> (các bước qua nhiều vai), và <strong>state-transition diagram &amp; state table</strong> (hệ thống đổi trạng thái thế nào). Mỗi cái lộ một loại yêu cầu thiếu khác nhau.</p>`,
    ),
    walkHead('ch12', 10, 17),
    walk('ch12', [
      [10, 'Data flow diagram — context diagram', `<p><strong>Purpose:</strong> DFDs give a big-picture view of how data moves through a system — something other models show poorly. A DFD gives <strong>context</strong> to functional requirements: it shows how the user performs specific tasks, and it's a technique for <strong>identifying missing data requirements</strong> (a process that produces output with no matching input, or vice versa, is a red flag). The context diagram is the top level: the whole system as one bubble with external entities around it.</p>`, `<p><strong>Mục đích:</strong> DFD cho cái nhìn tổng thể về cách dữ liệu chảy qua hệ thống — thứ mô hình khác thể hiện kém. DFD cho <strong>ngữ cảnh</strong> cho yêu cầu chức năng: nó chỉ cách người dùng làm từng tác vụ, và là kỹ thuật <strong>tìm yêu cầu dữ liệu thiếu</strong> (một process tạo output mà không có input tương ứng, hoặc ngược lại, là cờ đỏ). Context diagram là cấp trên cùng: cả hệ thống là một bong bóng, các thực thể ngoài quanh nó.</p>`],
      [11, 'Data flow diagram — example', `<p>The example shows the pieces of DFD notation: <strong>external entities</strong> (Initiator, Participant) as sources/sinks, <strong>data flows</strong> as labeled arrows (Request, Constraints, Notification), <strong>processes</strong> as bubbles (Check Request, Ask Constraints, Collect, Merge, Determine Schedule), and a <strong>data store</strong> as the repository. Following an arrow from input to output is how you check each process is complete.</p>`, `<p>Ví dụ chỉ các thành phần ký hiệu DFD: <strong>thực thể ngoài</strong> (Initiator, Participant) là nguồn/đích, <strong>data flow</strong> là mũi tên có nhãn (Request, Constraints, Notification), <strong>process</strong> là bong bóng (Check Request, Ask Constraints, Collect, Merge, Determine Schedule), và một <strong>data store</strong> là kho. Theo mũi tên từ input tới output là cách kiểm mỗi process đủ.</p>`],
      [12, 'DFD — Chemical Tracking System (level 0)', `<p>Figure 12-1: a partial <strong>level-0</strong> DFD for the Chemical Tracking System. Level 0 decomposes the single context bubble into the major processes and shows the data stores between them — the next level of detail down from the context diagram. Each bubble can be exploded further if needed.</p>`, `<p>Hình 12-1: DFD <strong>level-0</strong> một phần cho Chemical Tracking System. Level 0 phân rã bong bóng context đơn thành các process chính và chỉ các data store giữa chúng — cấp chi tiết ngay dưới context diagram. Mỗi bong bóng có thể nổ tiếp nếu cần.</p>`],
      [13, 'Swimlane diagram', `<p><strong>Purpose:</strong> represent the steps in a business process or system operation, subdivided into <strong>lanes</strong> — each lane is a different system or actor that executes some steps. A variation of the flowchart, most commonly used to show business processes, workflows, or system↔user interactions; similar to UML activity diagrams and also called <strong>cross-functional diagrams</strong>. Lanes make it obvious <em>who</em> is responsible for each step and where hand-offs happen.</p>`, `<p><strong>Mục đích:</strong> biểu diễn các bước trong một quy trình nghiệp vụ hay hoạt động hệ thống, chia thành <strong>lane</strong> — mỗi lane là một hệ thống hoặc actor thực hiện vài bước. Một biến thể của flowchart, hay dùng nhất để chỉ quy trình nghiệp vụ, workflow, hoặc tương tác hệ thống↔người dùng; giống UML activity diagram và còn gọi là <strong>cross-functional diagram</strong>. Lane làm rõ <em>ai</em> chịu trách nhiệm mỗi bước và chỗ nào bàn giao.</p>`],
      [14, 'Swimlane example', `<p>Figure 12-2: a partial swimlane diagram for a Chemical Tracking System process. Reading down a lane shows one actor's steps; following an arrow that crosses a lane boundary marks a <strong>hand-off</strong> — a common place for dropped requirements ("who does this next, and what data do they get?").</p>`, `<p>Hình 12-2: swimlane một phần cho một quy trình của Chemical Tracking System. Đọc dọc một lane thấy các bước của một actor; theo mũi tên vượt biên lane đánh dấu một <strong>bàn giao</strong> — chỗ hay rơi yêu cầu ("ai làm tiếp, và họ nhận dữ liệu gì?").</p>`],
      [15, 'State-transition diagram & state table', `<p><strong>Purpose:</strong> systems combine functional behavior, data manipulation, and <strong>state changes</strong>. Real-time and process-control apps exist in one of a limited number of states at any time. A state change happens only when <strong>well-defined criteria</strong> are met (e.g. a specific input under certain conditions). A state-transition diagram has three elements: <strong>states</strong> (rectangles), <strong>transitions</strong> (arrows between them), and <strong>events/conditions</strong> that cause each transition (labels on the arrows).</p>`, `<p><strong>Mục đích:</strong> hệ thống kết hợp hành vi chức năng, thao tác dữ liệu, và <strong>đổi trạng thái</strong>. Ứng dụng real-time và điều khiển tiến trình tồn tại ở một trong số hữu hạn trạng thái tại mỗi thời điểm. Đổi trạng thái chỉ xảy ra khi thoả <strong>tiêu chí xác định rõ</strong> (vd một input cụ thể trong điều kiện nào đó). State-transition diagram có ba thành phần: <strong>trạng thái</strong> (chữ nhật), <strong>chuyển</strong> (mũi tên giữa chúng), và <strong>sự kiện/điều kiện</strong> gây mỗi chuyển (nhãn trên mũi tên).</p>`],
      [16, 'State-transition diagram example', `<p>Figure 12-3: a partial state-transition diagram for a chemical request. Each rectangle is a status the request can hold; each arrow is a legal move with its trigger. The power of this model: it forces you to ask <strong>"can you get from state A to state B, and what triggers it?"</strong> — exposing illegal or missing transitions text would hide.</p>`, `<p>Hình 12-3: state-transition một phần cho một yêu cầu hoá chất. Mỗi chữ nhật là một trạng thái yêu cầu có thể mang; mỗi mũi tên là một bước hợp lệ kèm trigger. Sức mạnh của mô hình: nó buộc bạn hỏi <strong>"đi từ trạng thái A sang B được không, và gì kích hoạt?"</strong> — lộ các chuyển bất hợp lệ hoặc thiếu mà văn xuôi giấu.</p>`],
      [17, 'State table example', `<p>Figure 12-4: the same behavior as a <strong>state table</strong> — a grid of states × events whose cells give the resulting state (or "—" for a disallowed event). The table is exhaustive where the diagram is intuitive: <strong>every empty cell is a question</strong> ("what happens if this event arrives in this state?"), so the table catches missing transitions the diagram's arrows can silently omit.</p>`, `<p>Hình 12-4: cùng hành vi dạng <strong>state table</strong> — lưới trạng thái × sự kiện, ô cho trạng thái kết quả (hoặc "—" cho sự kiện không cho phép). Bảng vét cạn nơi sơ đồ trực quan: <strong>mỗi ô trống là một câu hỏi</strong> ("gì xảy ra nếu sự kiện này tới ở trạng thái này?"), nên bảng bắt các chuyển thiếu mà mũi tên của sơ đồ có thể âm thầm bỏ.</p>`],
    ]),
    books([['wiegers', 'Chapter 12, "Data flow diagram", "Swimlane diagram", "State-transition diagram and state table" (Figures 12-1 … 12-4)', 'Chương 12, "Data flow diagram", "Swimlane diagram", "State-transition diagram and state table" (Hình 12-1 … 12-4)']]),
  ].join('\n'),
};

/* 4.9 — decision models, UML, agile */
const V3 = {
  title: '4.9 — Slides: decision models, UML & agile modeling (Ch.12 · 18–25)|||4.9 — Slide: mô hình quyết định, UML & mô hình hoá agile (Ch.12 · 18–25)',
  slug: 'swr302-4-9-ch12-decision-uml-agile',
  type: 'DOCUMENT',
  description: 'Slide 18–25: dialog map, decision table & decision tree, event-response table, các sơ đồ UML dùng cho phân tích yêu cầu (class/use case/activity/state), và mô hình hoá trên dự án agile (chỉ dựng cái cần, khi cần, ở mức cần).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 4 · Lesson 4.9 · Book Ch.12 slides 18–25</span>
<h2>Decision models, UML &amp; agile modeling</h2>
<p class="lead">The self-study diagrams — dialog map, decision table/tree, event-response table — plus which UML diagrams are useful at requirements level, and the agile principle: build only the models you need, when you need them, to the detail you need.</p>`,
      `<span class="eyebrow">Chương 4 · Bài 4.9 · Slide 18–25 sách Ch.12</span>
<h2>Mô hình quyết định, UML &amp; mô hình hoá agile</h2>
<p class="lead">Các sơ đồ tự học — dialog map, decision table/tree, event-response table — cộng những sơ đồ UML hữu ích ở mức yêu cầu, và nguyên tắc agile: chỉ dựng mô hình cần, khi cần, ở mức cần.</p>`,
    ),
    walkHead('ch12', 18, 25),
    walk('ch12', [
      [18, 'Several diagrams for self-study', `<p>The chapter flags three more models to study: <strong>dialog map</strong>, <strong>decision tables and decision trees</strong>, and <strong>event-response tables</strong> — each covered next.</p>`, `<p>Chương nêu ba mô hình nữa để học: <strong>dialog map</strong>, <strong>decision table và decision tree</strong>, và <strong>event-response table</strong> — mỗi cái ngay sau.</p>`],
      [19, 'Dialog map', `<p>Figure 12-5: a partial dialog map for the "Request a Chemical" use case. A dialog map is an <strong>abstract UI model</strong> — boxes are dialog elements (screens/states of the interaction) and arrows are navigation between them, driven by user actions. It captures the <em>flow</em> of a user's interaction without committing to screen layout, so you can validate the conversation before designing pixels.</p>`, `<p>Hình 12-5: dialog map một phần cho use case "Request a Chemical". Dialog map là một <strong>mô hình UI trừu tượng</strong> — hộp là phần tử hội thoại (màn hình/trạng thái tương tác) và mũi tên là điều hướng giữa chúng, do hành động người dùng dẫn dắt. Nó nắm <em>luồng</em> tương tác mà chưa cam kết bố cục màn hình, nên bạn kiểm được "cuộc hội thoại" trước khi thiết kế pixel.</p>`],
      [20, 'Decision table', `<p>Figure 12-6: a sample decision table. Rows are <strong>conditions</strong>, columns are the <strong>combinations</strong> of those conditions (each column a rule), and the bottom rows give the <strong>action</strong> for each combination. With n binary conditions there are 2ⁿ columns — the table forces you to specify <strong>every</strong> combination, which is exactly how it catches the "silent combinations" trap from writing requirements.</p>`, `<p>Hình 12-6: một decision table mẫu. Hàng là <strong>điều kiện</strong>, cột là các <strong>tổ hợp</strong> điều kiện đó (mỗi cột một luật), và các hàng dưới cho <strong>hành động</strong> cho mỗi tổ hợp. Với n điều kiện nhị phân có 2ⁿ cột — bảng buộc bạn đặc tả <strong>mọi</strong> tổ hợp, đúng cách nó bắt bẫy "tổ hợp im lặng" từ phần viết yêu cầu.</p>`],
      [21, 'Decision tree', `<p>Figure 12-7: the same logic as a <strong>decision tree</strong> — branches split on each condition, leaves are the actions. A tree reads more naturally for <strong>nested/sequential</strong> decisions (this, then that), while a decision table is better for <strong>exhaustively comparing</strong> all combinations at once. Same information, two shapes — pick whichever your audience reads faster.</p>`, `<p>Hình 12-7: cùng logic dạng <strong>decision tree</strong> — nhánh rẽ theo mỗi điều kiện, lá là hành động. Cây đọc tự nhiên hơn cho quyết định <strong>lồng/tuần tự</strong> (cái này, rồi cái kia), còn decision table hợp cho <strong>so vét cạn</strong> mọi tổ hợp cùng lúc. Cùng thông tin, hai hình — chọn cái người đọc nắm nhanh hơn.</p>`],
      [22, 'Event-response table', `<p>Table 12-3: a partial event-response table (for an automobile windshield-wiper system). It lists each <strong>event</strong> the system can receive, the <strong>state/condition</strong> it's in, and the <strong>required response</strong> — a compact way to enumerate a reactive system's behavior and make sure no event is left unhandled in any state.</p>`, `<p>Bảng 12-3: event-response table một phần (hệ gạt nước ô tô). Nó liệt kê mỗi <strong>sự kiện</strong> hệ thống có thể nhận, <strong>trạng thái/điều kiện</strong> đang ở, và <strong>phản hồi yêu cầu</strong> — cách gọn để liệt kê hành vi của một hệ phản ứng và bảo đảm không sự kiện nào bị bỏ chưa xử lý ở bất kỳ trạng thái nào.</p>`],
      [23, 'A few words about UML diagrams', `<p>UML for requirements representation — the why, when, and what. UML is the standard object-oriented modeling language; the chapter frames <em>when</em> it earns its place in requirements (vs design) work.</p>`, `<p>UML để biểu diễn yêu cầu — vì sao, khi nào, và cái gì. UML là ngôn ngữ mô hình hướng đối tượng chuẩn; chương nêu <em>khi nào</em> nó xứng chỗ trong công việc yêu cầu (so với thiết kế).</p>`],
      [24, 'Useful UML models at requirements level', `<p>UML is primarily for <strong>design</strong> models, but at the abstraction level of requirements analysis several are useful: <strong>class diagrams</strong> (domain object classes, attributes, relations — also limited data modeling); <strong>use case diagrams</strong> (relationships between external actors and use cases); <strong>activity diagrams</strong> (how flows in a use case interlace, or which role does what — like a swimlane); <strong>state (machine) diagrams</strong> (states a system/object takes and allowed transitions).</p>`, `<p>UML chủ yếu cho mô hình <strong>thiết kế</strong>, nhưng ở mức trừu tượng của phân tích yêu cầu vài cái hữu ích: <strong>class diagram</strong> (lớp đối tượng miền, thuộc tính, quan hệ — cũng làm data modeling hạn chế); <strong>use case diagram</strong> (quan hệ giữa actor ngoài và use case); <strong>activity diagram</strong> (các luồng trong use case đan nhau, hay vai nào làm gì — như swimlane); <strong>state (machine) diagram</strong> (các trạng thái hệ/đối tượng mang và chuyển cho phép).</p>`],
      [25, 'Modeling on agile projects', `<p>The difference between traditional and agile modeling is <strong>when</strong> models are created and <strong>how detailed</strong> they are. The key point — on agile projects <em>or really any project</em> — is to create <strong>only the models you need, only when you need them, and only to the detail you need</strong> to be sure stakeholders adequately understand the requirements. Models are a means to understanding, not a deliverable to complete for its own sake.</p>`, `<p>Khác biệt giữa mô hình hoá truyền thống và agile là <strong>khi nào</strong> mô hình được tạo và <strong>chi tiết ra sao</strong>. Điểm mấu chốt — trên dự án agile <em>hay thật ra mọi dự án</em> — là tạo <strong>chỉ mô hình cần, chỉ khi cần, và chỉ ở mức cần</strong> để chắc stakeholder hiểu đủ yêu cầu. Mô hình là phương tiện để hiểu, không phải một sản phẩm phải hoàn thành vì chính nó.</p>`],
    ]),
    books([['wiegers', 'Chapter 12, "Dialog map", "Decision tables and decision trees", "Event-response table", "A few words about UML diagrams", "Modeling on agile projects" (Figures 12-5 … 12-7, Table 12-3)', 'Chương 12, "Dialog map", "Decision tables and decision trees", "Event-response table", "A few words about UML diagrams", "Modeling on agile projects" (Hình 12-5 … 12-7, Bảng 12-3)']]),
  ].join('\n'),
};

export default [V1, V2, V3];
