/**
 * SWR302 · Academy Chapter 5 (SRS) additions — book chapter Ch.14
 * "Beyond functionality" (nonfunctional / quality attributes, 19 slides), split
 * into THREE focused lessons: quality attributes & exploring them (1–10),
 * defining/specifying with Planguage + trade-offs (11–15), and constraints +
 * agile quality (16–19). Exported as an array spliced into academy Chapter 5
 * before its quiz. Grounded slide-by-slide in CHAPTER_14_Beyond functionality.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 5.7 — quality attributes & exploring them */
const Q1 = {
  title: '5.7 — Slides: quality attributes & exploring them (Ch.14 · 1–10)|||5.7 — Slide: thuộc tính chất lượng & cách khám phá (Ch.14 · 1–10)',
  slug: 'swr302-5-7-ch14-quality-attributes',
  type: 'DOCUMENT',
  description: 'Slide 1–10: nonfunctional requirements = quality attributes; external vs internal (Bảng 14-1); quy trình 5 bước khám phá (taxonomy → rút gọn → ưu tiên pairwise → khơi gợi kỳ vọng cụ thể → viết yêu cầu có cấu trúc); mnemonic SMART & fit criteria.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 5 · Lesson 5.7 · Book Ch.14 slides 1–10</span>
<h2>Quality attributes &amp; how to explore them</h2>
<p class="lead">Functional requirements say what the system does; <strong>quality attributes</strong> (nonfunctional requirements) say how well. They decide the architecture, are easy to overlook, and — unspecified — no one should be surprised when the product lacks them. This lesson: the attribute taxonomy and a five-step process to pin them down.</p>`,
      `<span class="eyebrow">Chương 5 · Bài 5.7 · Slide 1–10 sách Ch.14</span>
<h2>Thuộc tính chất lượng &amp; cách khám phá</h2>
<p class="lead">Yêu cầu chức năng nói hệ thống làm gì; <strong>thuộc tính chất lượng</strong> (nonfunctional) nói làm tốt ra sao. Chúng quyết định kiến trúc, dễ bị bỏ sót, và — không đặc tả — thì đừng ngạc nhiên khi sản phẩm thiếu chúng. Bài này: phân loại thuộc tính và quy trình năm bước để chốt chúng.</p>`,
    ),
    walkHead('ch14', 1, 10),
    walk('ch14', [
      [1, 'Beyond functionality', `<p>Title slide — nonfunctional requirements: the quality characteristics and constraints beyond what the system does.</p>`, `<p>Slide bìa — yêu cầu phi chức năng: các đặc tính chất lượng và ràng buộc vượt ngoài việc hệ thống làm gì.</p>`],
      [2, 'Objectives', `<p>Learn to detect and specify nonfunctional requirements, and understand the role of quality requirements in software development.</p>`, `<p>Học cách phát hiện và đặc tả yêu cầu phi chức năng, và hiểu vai trò của yêu cầu chất lượng trong phát triển phần mềm.</p>`],
      [3, 'Contents', `<p>Eight topics: quality attributes, exploring them, defining quality requirements, specifying with Planguage, trade-offs, implementing them, constraints, and quality on agile projects. Lessons 5.7–5.9 cover all eight.</p>`, `<p>Tám chủ đề: thuộc tính chất lượng, khám phá chúng, định nghĩa yêu cầu chất lượng, đặc tả bằng Planguage, đánh đổi, hiện thực, ràng buộc, và chất lượng trên dự án agile. Bài 5.7–5.9 phủ cả tám.</p>`],
      [4, 'Software quality attributes', `<p>Dozens of product characteristics count as quality attributes; knowing <strong>which are most crucial</strong> lets developers pick suitable design/construction approaches. One classification splits attributes discernible <strong>through execution</strong> (<strong>external quality</strong> — matter mostly to users) from those that aren't (<strong>internal quality</strong> — matter to development/maintenance; they indirectly aid customers by making the product easier to enhance, correct, test and port). <strong>Section 6 of the SRS template (Chapter 10)</strong> is devoted to quality attributes; feature-specific ones attach to the relevant item in the repository.</p>`, `<p>Hàng chục đặc tính sản phẩm là thuộc tính chất lượng; biết <strong>cái nào quan trọng nhất</strong> giúp developer chọn cách thiết kế/xây phù hợp. Một cách phân loại tách thuộc tính thấy được <strong>qua chạy</strong> (<strong>external quality</strong> — chủ yếu quan trọng với người dùng) khỏi cái không (<strong>internal quality</strong> — quan trọng với phát triển/bảo trì; gián tiếp giúp khách bằng cách làm sản phẩm dễ nâng cấp, sửa, test, chuyển nền). <strong>Mục 6 của template SRS (Chương 10)</strong> dành cho thuộc tính chất lượng; cái riêng theo feature gắn vào mục tương ứng trong repository.</p>`],
      [5, 'Which attributes matter per project type', `<p>Table 14-1 lists many attributes; certain ones dominate certain project types. <strong>Embedded systems:</strong> performance, efficiency, reliability, robustness, safety, security, usability. <strong>Internet/corporate apps:</strong> availability, integrity, interoperability, performance, scalability, security, usability. <strong>Desktop/mobile:</strong> performance, security, usability. Start from the set that fits your domain rather than treating all attributes equally.</p>`, `<p>Bảng 14-1 liệt kê nhiều thuộc tính; vài cái trội ở vài loại dự án. <strong>Hệ nhúng:</strong> performance, efficiency, reliability, robustness, safety, security, usability. <strong>Ứng dụng Internet/doanh nghiệp:</strong> availability, integrity, interoperability, performance, scalability, security, usability. <strong>Desktop/di động:</strong> performance, security, usability. Bắt đầu từ tập hợp phù hợp miền của bạn thay vì coi mọi thuộc tính như nhau.</p>`],
      [6, 'Exploring quality attributes — 5 steps', `<p>A repeatable process: <strong>Step 1</strong> start with a broad taxonomy; <strong>Step 2</strong> reduce the list; <strong>Step 3</strong> prioritize; <strong>Step 4</strong> elicit specific expectations for each; <strong>Step 5</strong> specify well-structured quality requirements. The next slides detail each.</p>`, `<p>Một quy trình lặp được: <strong>Bước 1</strong> bắt đầu từ taxonomy rộng; <strong>Bước 2</strong> rút gọn danh sách; <strong>Bước 3</strong> ưu tiên; <strong>Bước 4</strong> khơi gợi kỳ vọng cụ thể cho từng cái; <strong>Bước 5</strong> đặc tả yêu cầu chất lượng có cấu trúc tốt. Các slide sau chi tiết từng bước.</p>`],
      [7, 'Steps 1 & 2 — taxonomy, then reduce', `<p><strong>Step 1 — broad taxonomy:</strong> begin with a rich set (Table 14-1) so you're less likely to overlook an important dimension. <strong>Step 2 — reduce:</strong> engage a cross-section of stakeholders to decide which attributes matter here (an airport check-in kiosk emphasizes <em>usability</em> — infrequent users — and <em>security</em> — it handles payments). Drop irrelevant ones, but <strong>record the rationale</strong> for each in/out decision. Warning: if you don't specify quality goals, don't be surprised the product lacks them. In practice some are clearly in, some clearly out, and only a few need discussion.</p>`, `<p><strong>Bước 1 — taxonomy rộng:</strong> bắt đầu từ tập phong phú (Bảng 14-1) để ít bỏ sót chiều quan trọng. <strong>Bước 2 — rút gọn:</strong> huy động nhiều nhóm stakeholder quyết thuộc tính nào quan trọng ở đây (kiosk check-in sân bay nhấn <em>usability</em> — người dùng ít khi gặp — và <em>security</em> — xử lý thanh toán). Bỏ cái không liên quan, nhưng <strong>ghi lý do</strong> mỗi quyết định vào/ra. Cảnh báo: không đặc tả mục tiêu chất lượng thì đừng ngạc nhiên sản phẩm thiếu. Thực tế vài cái rõ vào, vài cái rõ ra, chỉ ít cần bàn.</p>`],
      [8, 'Step 3 — prioritize (pairwise)', `<p><strong>Prioritizing</strong> the pertinent attributes focuses future elicitation. Pairwise ranking works well for a small list (Figure 14-1, airport kiosk): a <code>&lt;</code> in a cell means the <strong>row</strong> attribute is more important; a <code>^</code> points to the <strong>column</strong> attribute as more important; the spreadsheet computes a relative score. Prioritization helps twice: it focuses elicitation on attributes most aligned with success, and it tells you how to respond when quality requirements <strong>conflict</strong>.</p>`, `<p><strong>Ưu tiên</strong> các thuộc tính liên quan giúp tập trung khơi gợi về sau. Xếp hạng cặp (pairwise) hợp cho danh sách nhỏ (Hình 14-1, kiosk sân bay): dấu <code>&lt;</code> trong ô nghĩa thuộc tính <strong>hàng</strong> quan trọng hơn; dấu <code>^</code> chỉ thuộc tính <strong>cột</strong> quan trọng hơn; bảng tính tính điểm tương đối. Ưu tiên giúp hai lần: tập trung khơi gợi vào thuộc tính hợp thành công nhất, và cho biết cách xử khi yêu cầu chất lượng <strong>xung đột</strong>.</p>`],
      [9, 'Step 4 — elicit specific expectations', `<p>Users can't answer "What are your interoperability requirements?" — the BA must <strong>guide their thinking</strong> with concrete questions. For performance of a patent-application system, ask: acceptable response time for a typical query? unacceptable response time? average simultaneous users? maximum? peak usage times (day/week/month/year)? Send such questions <strong>in advance</strong> so people can research answers. End with "Is there anything I haven't asked that we should discuss?" Also ask what would be <strong>unacceptable</strong> — defining the unacceptable lets you design tests that try to force it. A stakeholder's quality goal can be decomposed into functional and nonfunctional subgoals.</p>`, `<p>Người dùng không trả lời được "Yêu cầu interoperability của bạn là gì?" — BA phải <strong>dẫn dắt suy nghĩ</strong> bằng câu hỏi cụ thể. Với performance của hệ đơn đăng ký sáng chế, hỏi: thời gian phản hồi chấp nhận được cho một truy vấn điển hình? thời gian không chấp nhận được? số người dùng đồng thời trung bình? tối đa? giờ cao điểm (ngày/tuần/tháng/năm)? Gửi câu hỏi <strong>trước</strong> để họ nghiên cứu. Kết bằng "Có gì tôi chưa hỏi mà nên bàn không?" Cũng hỏi cái gì là <strong>không chấp nhận được</strong> — định nghĩa cái không chấp nhận cho phép thiết kế test cố ép nó lộ ra. Mục tiêu chất lượng của stakeholder phân rã được thành mục tiêu con chức năng và phi chức năng.</p>`],
      [10, 'Step 5 — write SMART, measurable requirements', `<p>Craft <strong>specific and verifiable</strong> requirements from what was elicited. Use the <strong>SMART</strong> mnemonic — Specific, Measurable, Attainable, Relevant, Time-sensitive. Quality requirements must be <strong>measurable</strong> to fix a precise agreement among BA, customers and developers: <em>if a tester can't test it, it's not good enough.</em> Give the <strong>scale/units</strong> and the <strong>target, minimum and maximum</strong> values (Planguage, next, helps). <strong>Fit criteria</strong> describe a measurable way to check correct implementation — guiding designers to a solution and testers to an evaluation. Reuse an existing <strong>requirement pattern</strong> rather than inventing your own format.</p>`, `<p>Soạn yêu cầu <strong>cụ thể và kiểm chứng được</strong> từ cái đã khơi gợi. Dùng mnemonic <strong>SMART</strong> — Specific, Measurable, Attainable, Relevant, Time-sensitive. Yêu cầu chất lượng phải <strong>đo được</strong> để chốt thoả thuận chính xác giữa BA, khách, developer: <em>nếu tester không test được, nó chưa đủ tốt.</em> Cho <strong>thang/đơn vị</strong> và giá trị <strong>mục tiêu, tối thiểu, tối đa</strong> (Planguage, ngay sau, giúp việc này). <strong>Fit criteria</strong> mô tả cách đo để kiểm hiện thực đúng — dẫn designer tới giải pháp và tester tới đánh giá. Tái dùng một <strong>requirement pattern</strong> có sẵn thay vì tự chế định dạng.</p>`],
    ]),
    books([['wiegers', 'Chapter 14, "Software quality attributes" (Table 14-1), "Exploring quality attributes" (5 steps, Figure 14-1)', 'Chương 14, "Software quality attributes" (Bảng 14-1), "Exploring quality attributes" (5 bước, Hình 14-1)']]),
  ].join('\n'),
};

/* 5.8 — defining, Planguage, trade-offs, implementing */
const Q2 = {
  title: '5.8 — Slides: Planguage, trade-offs & implementing quality (Ch.14 · 11–15)|||5.8 — Slide: Planguage, đánh đổi & hiện thực chất lượng (Ch.14 · 11–15)',
  slug: 'swr302-5-8-ch14-planguage',
  type: 'DOCUMENT',
  description: 'Slide 11–15: danh sách thuộc tính external/internal; Planguage (TAG/AMBITION/SCALE/METER/GOAL/STRETCH/WISH/DEFINED) để đặc tả chất lượng chính xác đo được; bảng đánh đổi giữa các thuộc tính (Fig 14-2); dịch thuộc tính chất lượng thành thông tin kỹ thuật (Bảng 14-5).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 5 · Lesson 5.8 · Book Ch.14 slides 11–15</span>
<h2>Planguage, trade-offs &amp; implementing quality</h2>
<p class="lead">How to write a quality requirement so precisely a stopwatch can judge it — Gilb's Planguage — plus the reality that quality attributes fight each other (increasing one hurts another) and that they translate into concrete architecture and derived functional requirements.</p>`,
      `<span class="eyebrow">Chương 5 · Bài 5.8 · Slide 11–15 sách Ch.14</span>
<h2>Planguage, đánh đổi &amp; hiện thực chất lượng</h2>
<p class="lead">Cách viết một yêu cầu chất lượng chính xác đến mức một chiếc đồng hồ bấm giờ phán được — Planguage của Gilb — cộng thực tế rằng các thuộc tính chất lượng chọi nhau (tăng cái này hại cái kia) và chúng dịch thành kiến trúc cụ thể cùng yêu cầu chức năng dẫn xuất.</p>`,
    ),
    walkHead('ch14', 11, 15),
    walk('ch14', [
      [11, 'Defining quality requirements — the attributes', `<p>The vocabulary. <strong>External</strong> attributes (visible in execution, matter to users): Availability, Installability, Integrity, Interoperability, Performance, Reliability, Robustness, Safety, Security, Usability. <strong>Internal</strong> attributes (matter to developers/maintainers): Efficiency, Modifiability, Portability, Reusability, Scalability, Verifiability. Know which bucket an attribute is in — it tells you who cares and how you'll measure it.</p>`, `<p>Từ vựng. Thuộc tính <strong>external</strong> (thấy khi chạy, quan trọng với người dùng): Availability, Installability, Integrity, Interoperability, Performance, Reliability, Robustness, Safety, Security, Usability. Thuộc tính <strong>internal</strong> (quan trọng với developer/bảo trì): Efficiency, Modifiability, Portability, Reusability, Scalability, Verifiability. Biết một thuộc tính thuộc nhóm nào — nó cho biết ai quan tâm và bạn đo thế nào.</p>`],
      [12, 'Specifying with Planguage — the idea', `<p><strong>Planguage</strong> (Tom Gilb; "planning language") is a language with a rich set of keywords for <strong>precise statements of quality attributes</strong> and project goals. <strong>Purpose:</strong> cure ambiguous, incomplete nonfunctional requirements. A traditional-form example: <em>"At least 95% of the time, the system shall take no more than 8 seconds to display any of the predefined accounting reports."</em> Planguage decomposes that one sentence into labeled, measurable parts (next slide).</p>`, `<p><strong>Planguage</strong> (Tom Gilb; "ngôn ngữ lập kế hoạch") là ngôn ngữ với bộ từ khoá phong phú để <strong>phát biểu chính xác thuộc tính chất lượng</strong> và mục tiêu dự án. <strong>Mục đích:</strong> chữa yêu cầu phi chức năng mơ hồ, thiếu. Ví dụ dạng truyền thống: <em>"Ít nhất 95% thời gian, hệ thống shall mất không quá 8 giây để hiển thị bất kỳ báo cáo kế toán định sẵn nào."</em> Planguage phân rã câu đó thành các phần có nhãn, đo được (slide sau).</p>`],
      [13, 'Planguage keywords — a worked example', `<p>The same performance requirement in Planguage:</p>
<ul>
<li><strong>TAG</strong> — Performance.Report.ResponseTime (unique name)</li>
<li><strong>AMBITION</strong> — fast response generating accounting reports on the base platform</li>
<li><strong>SCALE</strong> — seconds of elapsed time from pressing Enter/OK to the report beginning to display (the unit of measure)</li>
<li><strong>METER</strong> — stopwatch testing on 30 reports matching a defined operational profile (how you'll measure)</li>
<li><strong>GOAL</strong> — ≤ 8 s for 95% of reports ← Field Office Manager (the committed target + its source)</li>
<li><strong>STRETCH</strong> — ≤ 2 s predefined, ≤ 5 s all reports (a desirable stretch)</li>
<li><strong>WISH</strong> — ≤ 1.5 s for all reports (ideal, uncommitted)</li>
<li><strong>DEFINED</strong> — "base user platform" = quad-core, 8GB RAM, Windows 8, QueryGen 3.3, single user, ≥50% RAM &amp; ≥70% CPU free, ≥30 Mbps network</li>
</ul>
<p>Every fuzzy word is now a number a tester can check — and GOAL/STRETCH/WISH capture graduated levels of satisfaction.</p>`, `<p>Cùng yêu cầu performance đó bằng Planguage:</p>
<ul>
<li><strong>TAG</strong> — Performance.Report.ResponseTime (tên duy nhất)</li>
<li><strong>AMBITION</strong> — phản hồi nhanh khi sinh báo cáo kế toán trên nền cơ sở</li>
<li><strong>SCALE</strong> — số giây từ lúc nhấn Enter/OK đến khi báo cáo bắt đầu hiển thị (đơn vị đo)</li>
<li><strong>METER</strong> — bấm giờ trên 30 báo cáo khớp một operational profile xác định (cách đo)</li>
<li><strong>GOAL</strong> — ≤ 8 giây cho 95% báo cáo ← Field Office Manager (mục tiêu cam kết + nguồn)</li>
<li><strong>STRETCH</strong> — ≤ 2 giây báo cáo định sẵn, ≤ 5 giây mọi báo cáo (mức vươn mong muốn)</li>
<li><strong>WISH</strong> — ≤ 1.5 giây mọi báo cáo (lý tưởng, không cam kết)</li>
<li><strong>DEFINED</strong> — "nền người dùng cơ sở" = quad-core, 8GB RAM, Windows 8, QueryGen 3.3, đơn người dùng, ≥50% RAM &amp; ≥70% CPU rảnh, mạng ≥30 Mbps</li>
</ul>
<p>Mọi từ mơ hồ giờ là một con số tester kiểm được — và GOAL/STRETCH/WISH nắm các mức thoả mãn phân bậc.</p>`],
      [14, 'Quality attribute trade-offs', `<p>Attributes interact. Figure 14-2 is a matrix: a <strong>plus</strong> in a cell means increasing the <strong>row</strong> attribute usually helps the <strong>column</strong> attribute; a <strong>minus</strong> means it usually hurts it; an <strong>empty</strong> cell means little effect. Classic tensions: more security often costs usability and performance; more portability can cost efficiency. Use Figure 14-2 to <strong>avoid committing to conflicting goals</strong> — when two prioritized attributes pull opposite ways, the priority ranking (Step 3) decides which wins.</p>`, `<p>Các thuộc tính tương tác. Hình 14-2 là một ma trận: dấu <strong>cộng</strong> trong ô nghĩa tăng thuộc tính <strong>hàng</strong> thường giúp thuộc tính <strong>cột</strong>; dấu <strong>trừ</strong> nghĩa thường hại; ô <strong>trống</strong> nghĩa ít ảnh hưởng. Căng thẳng kinh điển: nhiều security thường tốn usability và performance; nhiều portability có thể tốn efficiency. Dùng Hình 14-2 để <strong>tránh cam kết mục tiêu xung đột</strong> — khi hai thuộc tính ưu tiên kéo ngược nhau, xếp hạng ưu tiên (Bước 3) quyết cái nào thắng.</p>`],
      [15, 'Implementing quality attribute requirements', `<p>Table 14-5 translates quality attributes into technical specifications. Though nonfunctional, they lead to <strong>derived functional requirements, design guidelines, or architecture</strong> that produce the desired characteristics. Example: a medical device with stringent availability/reliability needs a <strong>backup battery</strong> (architecture) <em>plus</em> functional requirements to indicate battery-power mode, low-battery warnings, and so on. This translation from quality requirement → technical information is part of requirements analysis and high-level design.</p>`, `<p>Bảng 14-5 dịch thuộc tính chất lượng thành đặc tả kỹ thuật. Dù phi chức năng, chúng dẫn tới <strong>yêu cầu chức năng dẫn xuất, hướng dẫn thiết kế, hoặc kiến trúc</strong> tạo ra đặc tính mong muốn. Ví dụ: thiết bị y tế cần availability/reliability nghiêm ngặt phải có <strong>pin dự phòng</strong> (kiến trúc) <em>cộng</em> yêu cầu chức năng báo chế độ chạy pin, cảnh báo pin yếu, v.v. Việc dịch từ yêu cầu chất lượng → thông tin kỹ thuật là một phần của phân tích yêu cầu và thiết kế cấp cao.</p>`],
    ]),
    books([['wiegers', 'Chapter 14, "Defining quality requirements", "Specifying quality requirements with Planguage", "Quality attribute trade-offs" (Figure 14-2), "Implementing quality attribute requirements" (Table 14-5)', 'Chương 14, "Defining quality requirements", "Specifying quality requirements with Planguage", "Quality attribute trade-offs" (Hình 14-2), "Implementing quality attribute requirements" (Bảng 14-5)']]),
  ].join('\n'),
};

/* 5.9 — constraints & agile quality */
const Q3 = {
  title: '5.9 — Slides: constraints & quality on agile (Ch.14 · 16–19)|||5.9 — Slide: ràng buộc & chất lượng trên agile (Ch.14 · 16–19)',
  slug: 'swr302-5-9-ch14-constraints-agile',
  type: 'DOCUMENT',
  description: 'Slide 16–19: constraints (định nghĩa, nguồn, ví dụ CON-1..CON-6 các loại design/implementation/architecture/physical/data), và xử lý thuộc tính chất lượng trên dự án agile (đặc tả sớm, ưu tiên ngang user story, viết acceptance test đo được).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 5 · Lesson 5.9 · Book Ch.14 slides 16–19</span>
<h2>Constraints &amp; quality on agile projects</h2>
<p class="lead">The other kind of nonfunctional requirement — <strong>constraints</strong> that restrict the developer's design/implementation choices — and why even agile projects must specify significant quality attributes early rather than retrofitting them late.</p>`,
      `<span class="eyebrow">Chương 5 · Bài 5.9 · Slide 16–19 sách Ch.14</span>
<h2>Ràng buộc &amp; chất lượng trên dự án agile</h2>
<p class="lead">Loại yêu cầu phi chức năng còn lại — <strong>constraint</strong> hạn chế lựa chọn thiết kế/hiện thực của developer — và vì sao ngay cả dự án agile cũng phải đặc tả các thuộc tính chất lượng quan trọng sớm thay vì gắn thêm muộn.</p>`,
    ),
    walkHead('ch14', 16, 19),
    walk('ch14', [
      [16, 'Constraints — examples', `<p>A constraint restricts design/implementation choices. Six typed examples: <strong>CON-1</strong> click the top of the project list to change sort order [UI control as a <em>design constraint</em> on a functional requirement]; <strong>CON-2</strong> only GPL open-source software may be used [<em>implementation constraint</em>]; <strong>CON-3</strong> must use Microsoft .NET 4.5 [<em>architecture constraint</em>]; <strong>CON-4</strong> ATMs contain only \$20 bills [<em>physical constraint</em>]; <strong>CON-5</strong> online payments only via PayPal [<em>design constraint</em>]; <strong>CON-6</strong> all textual data stored as XML files [<em>data constraint</em>]. Labeling the type clarifies why the restriction exists.</p>`, `<p>Một constraint hạn chế lựa chọn thiết kế/hiện thực. Sáu ví dụ có phân loại: <strong>CON-1</strong> bấm đầu danh sách project để đổi thứ tự sắp [điều khiển UI như <em>design constraint</em> lên một yêu cầu chức năng]; <strong>CON-2</strong> chỉ được dùng phần mềm nguồn mở GPL [<em>implementation constraint</em>]; <strong>CON-3</strong> phải dùng Microsoft .NET 4.5 [<em>architecture constraint</em>]; <strong>CON-4</strong> ATM chỉ chứa tờ \$20 [<em>physical constraint</em>]; <strong>CON-5</strong> thanh toán online chỉ qua PayPal [<em>design constraint</em>]; <strong>CON-6</strong> mọi dữ liệu văn bản lưu dạng file XML [<em>data constraint</em>]. Gán loại làm rõ vì sao có hạn chế.</p>`],
      [17, 'Sources of constraints', `<p>Constraints come from many places: mandated or forbidden <strong>technologies/tools/languages/databases</strong>; the product's <strong>operating environment/platform</strong> (browser or OS types and versions); required <strong>development conventions/standards</strong> (design notation, coding standards a subcontractor must follow); <strong>backward/forward compatibility</strong> (which version created a data file); <strong>regulations and business rules</strong>; <strong>hardware limits</strong> (timing, memory, processor, size, weight, materials, cost); <strong>physical/user limitations</strong>; existing <strong>interface conventions</strong> when enhancing a product; <strong>interfaces to other systems</strong> (data formats, protocols); <strong>display size</strong> (tablet/phone); and <strong>standard interchange formats</strong> (XML, RosettaNet). Capture them because they bound every downstream decision.</p>`, `<p>Constraint đến từ nhiều chỗ: <strong>công nghệ/công cụ/ngôn ngữ/database</strong> buộc dùng hay cấm; <strong>môi trường vận hành/nền</strong> của sản phẩm (loại và phiên bản trình duyệt hay OS); <strong>quy ước/chuẩn phát triển</strong> yêu cầu (ký hiệu thiết kế, chuẩn code mà nhà thầu phụ phải theo); <strong>tương thích ngược/xuôi</strong> (phiên bản nào tạo một file dữ liệu); <strong>quy định và business rule</strong>; <strong>giới hạn phần cứng</strong> (timing, bộ nhớ, vi xử lý, kích thước, trọng lượng, vật liệu, chi phí); <strong>hạn chế vật lý/người dùng</strong>; <strong>quy ước giao diện</strong> có sẵn khi nâng cấp sản phẩm; <strong>giao diện với hệ khác</strong> (định dạng dữ liệu, giao thức); <strong>kích thước màn hình</strong> (tablet/điện thoại); và <strong>định dạng trao đổi chuẩn</strong> (XML, RosettaNet). Nắm chúng vì chúng chặn mọi quyết định phía sau.</p>`],
      [18, 'Handling quality attributes on agile projects', `<p>Retrofitting quality late in development or after delivery is difficult and expensive — so even agile projects delivering in small increments must <strong>specify significant quality attributes and constraints early</strong>. This lets developers make the right <strong>architectural and design decisions</strong> as a foundation. Nonfunctional requirements must have <strong>priority alongside user stories</strong>; you can't defer their implementation to a later iteration and bolt them on.</p>`, `<p>Gắn thêm chất lượng muộn trong phát triển hay sau khi giao thì khó và tốn — nên ngay cả dự án agile giao theo tăng dần nhỏ cũng phải <strong>đặc tả các thuộc tính chất lượng và ràng buộc quan trọng sớm</strong>. Điều này cho developer ra <strong>quyết định kiến trúc và thiết kế</strong> đúng làm nền. Yêu cầu phi chức năng phải có <strong>ưu tiên ngang user story</strong>; không thể hoãn hiện thực chúng sang iteration sau rồi lắp vào.</p>`],
      [19, 'Quality as stories & acceptance tests', `<p>You <em>can</em> phrase a quality attribute as a story — <em>"As a help desk technician, I want the knowledge base to respond within 5 seconds so the customer doesn't get frustrated and hang up"</em> — but quality requirements aren't implemented discretely like stories: they <strong>span multiple stories and iterations</strong>. Write <strong>acceptance tests</strong> to quantify them. "Return search results quickly" is untestable; better: <em>"Keyword search takes less than 5 seconds, preferably less than 3, to return a result."</em> Such tests can present several acceptable levels — like Planguage's GOAL/STRETCH/WISH — and you can use Planguage's SCALE and METER to pin down exactly what "return a result" means and how to test it.</p>`, `<p>Bạn <em>có thể</em> viết một thuộc tính chất lượng dạng story — <em>"Là kỹ thuật viên help desk, tôi muốn knowledge base phản hồi trong 5 giây để khách không bực rồi cúp máy"</em> — nhưng yêu cầu chất lượng không hiện thực rời rạc như story: chúng <strong>trải nhiều story và iteration</strong>. Viết <strong>acceptance test</strong> để lượng hoá. "Trả kết quả tìm nhanh" thì không test được; tốt hơn: <em>"Tìm theo từ khoá mất dưới 5 giây, tốt nhất dưới 3, để trả một kết quả."</em> Test như vậy trình bày nhiều mức chấp nhận được — như GOAL/STRETCH/WISH của Planguage — và bạn dùng SCALE, METER của Planguage để chốt chính xác "trả một kết quả" nghĩa gì và test ra sao.</p>`],
    ]),
    books([['wiegers', 'Chapter 14, "Constraints" (CON-1…CON-6), "Handling quality attributes on agile projects"', 'Chương 14, "Constraints" (CON-1…CON-6), "Handling quality attributes on agile projects"']]),
  ].join('\n'),
};

export default [Q1, Q2, Q3];
