/**
 * SWR302 · Academy Chapter 8 (OO design & prototyping) additions — book chapter
 * Ch.15 "Risk reduction through prototyping" (24 slides), split into THREE focused
 * lessons: what/why + attributes + mock-ups/PoC (1–8), throwaway/evolutionary +
 * paper/electronic + working with prototypes (9–17), and evaluation + risks +
 * success factors (18–24). Exported as an array spliced into academy Chapter 8
 * before its quiz. Grounded slide-by-slide in
 * CHAPTER_15_Risk reduction through prototyping.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 8.2 — what/why, attributes, mock-ups & PoC */
const P1 = {
  title: '8.2 — Slides: prototyping — what, why, mock-ups & PoC (Ch.15 · 1–8)|||8.2 — Slide: prototyping — là gì, vì sao, mock-up & PoC (Ch.15 · 1–8)',
  slug: 'swr302-8-2-ch15-what-why',
  type: 'DOCUMENT',
  description: 'Slide 1–8: prototype = hiện thực một phần/thử của sản phẩm (làm rõ yêu cầu, khám phá thiết kế, dựng subset); ba lớp thuộc tính (scope: mock-up vs proof-of-concept; future use: throwaway vs evolutionary; form: paper vs electronic); mock-up = horizontal (UI), proof-of-concept = vertical/spike (một lát xuyên tầng kỹ thuật).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 8 · Lesson 8.2 · Book Ch.15 slides 1–8</span>
<h2>Prototyping: what, why, mock-ups &amp; proofs of concept</h2>
<p class="lead">A prototype is a partial or preliminary implementation that clarifies requirements, explores design, or seeds the real product. Every prototype is a combination of three attribute choices — and the first, scope, splits into the horizontal mock-up (the UI) and the vertical proof-of-concept (a slice through all layers).</p>`,
      `<span class="eyebrow">Chương 8 · Bài 8.2 · Slide 1–8 sách Ch.15</span>
<h2>Prototyping: là gì, vì sao, mock-up &amp; proof of concept</h2>
<p class="lead">Một prototype là hiện thực một phần hoặc sơ bộ giúp làm rõ yêu cầu, khám phá thiết kế, hoặc gieo mầm sản phẩm thật. Mỗi prototype là một tổ hợp ba lựa chọn thuộc tính — và cái đầu, scope, tách thành mock-up ngang (UI) và proof-of-concept dọc (một lát xuyên mọi tầng).</p>`,
    ),
    walkHead('ch15', 1, 8),
    walk('ch15', [
      [1, 'Risk reduction through prototyping', `<p>Title slide — how prototyping adds value, the kinds of prototypes for different purposes, and how to make prototyping an effective part of the process.</p>`, `<p>Slide bìa — prototyping thêm giá trị ra sao, các loại prototype cho mục đích khác nhau, và cách làm prototyping một phần hiệu quả của quy trình.</p>`],
      [2, 'Objectives', `<p>Describe how prototyping provides value and the different kinds of prototypes for different purposes; give guidance on using them during requirements development and making prototyping an effective part of software engineering.</p>`, `<p>Mô tả prototyping đem giá trị thế nào và các loại prototype cho mục đích khác nhau; hướng dẫn dùng chúng khi phát triển yêu cầu và làm prototyping một phần hiệu quả của kỹ nghệ phần mềm.</p>`],
      [3, 'Prototyping: what and why', `<p>A <strong>software prototype</strong> is a partial, possible, or preliminary implementation of a proposed product. Three purposes: <strong>clarify, complete and validate requirements</strong>; <strong>explore design alternatives</strong>; and <strong>create a subset that grows into the ultimate product</strong>. Every prototype is described by three classes of attributes — <strong>Scope, Future use, Form</strong> — covered next.</p>`, `<p>Một <strong>software prototype</strong> là hiện thực một phần, khả dĩ, hoặc sơ bộ của một sản phẩm đề xuất. Ba mục đích: <strong>làm rõ, hoàn thiện và thẩm định yêu cầu</strong>; <strong>khám phá phương án thiết kế</strong>; và <strong>dựng một subset lớn thành sản phẩm cuối</strong>. Mỗi prototype được mô tả bởi ba lớp thuộc tính — <strong>Scope, Future use, Form</strong> — ngay sau.</p>`],
      [4, 'The three purposes in depth', `<p><strong>As a requirements tool:</strong> the prototype helps obtain agreement, find errors/omissions, and assess requirement accuracy/quality — user evaluation points out problems and uncovers overlooked requirements you can fix cheaply before construction (especially for poorly-understood, risky or complex parts). <strong>As a design tool:</strong> stakeholders explore interaction techniques, envision the product, optimize usability and evaluate technical approaches; prototypes demonstrate <strong>feasibility</strong> and confirm the developer's understanding before building. <strong>As a construction tool:</strong> a functional subset elaborated into the complete product through small development cycles — safe only if designed for eventual release from the start.</p>`, `<p><strong>Như công cụ yêu cầu:</strong> prototype giúp đạt đồng thuận, tìm lỗi/thiếu sót, và đánh giá độ chính xác/chất lượng yêu cầu — người dùng đánh giá chỉ ra vấn đề và lộ yêu cầu bị bỏ sót mà bạn sửa rẻ trước khi xây (nhất là phần chưa hiểu rõ, rủi ro hoặc phức tạp). <strong>Như công cụ thiết kế:</strong> stakeholder khám phá kỹ thuật tương tác, hình dung sản phẩm, tối ưu usability và đánh giá cách kỹ thuật; prototype chứng minh <strong>khả thi</strong> và xác nhận developer hiểu đúng trước khi xây. <strong>Như công cụ xây dựng:</strong> một subset chức năng khai triển thành sản phẩm đầy đủ qua các chu kỳ nhỏ — chỉ an toàn nếu thiết kế để phát hành ngay từ đầu.</p>`],
      [5, 'Three classes of prototype attributes', `<p>Each attribute class has two alternatives. <strong>Scope:</strong> a <strong>mock-up</strong> focuses on the user experience; a <strong>proof-of-concept</strong> explores technical soundness. <strong>Future use:</strong> a <strong>throwaway</strong> is discarded after generating feedback; an <strong>evolutionary</strong> grows into the final product over iterations. <strong>Form:</strong> a <strong>paper</strong> prototype is a sketch on paper/whiteboard/drawing tool; an <strong>electronic</strong> prototype is working software for part of the solution. Each prototype has a specific combination — e.g. a throwaway paper mock-up, or an evolutionary electronic proof-of-concept — but some combinations make no sense (you can't build an <em>evolutionary paper proof-of-concept</em>).</p>`, `<p>Mỗi lớp thuộc tính có hai lựa chọn. <strong>Scope:</strong> một <strong>mock-up</strong> tập trung trải nghiệm người dùng; một <strong>proof-of-concept</strong> khám phá tính vững kỹ thuật. <strong>Future use:</strong> một <strong>throwaway</strong> bị bỏ sau khi tạo phản hồi; một <strong>evolutionary</strong> lớn thành sản phẩm cuối qua các iteration. <strong>Form:</strong> một prototype <strong>giấy</strong> là bản phác trên giấy/whiteboard/công cụ vẽ; một prototype <strong>điện tử</strong> là phần mềm chạy được cho một phần giải pháp. Mỗi prototype có một tổ hợp cụ thể — vd một throwaway paper mock-up, hoặc một evolutionary electronic proof-of-concept — nhưng vài tổ hợp vô nghĩa (không thể dựng một <em>evolutionary paper proof-of-concept</em>).</p>`],
      [6, 'Mock-ups (horizontal prototypes)', `<p>When people say "prototype" they usually mean a <strong>mock-up</strong> of a possible UI — also called a <strong>horizontal prototype</strong> because it covers a portion of the UI <strong>without diving into architectural layers or detailed functionality</strong>. Purpose: demonstrate the functional options, the look-and-feel (colors, layout, graphics, controls) and the navigation structure; explore specific behaviors to refine requirements; and represent the developer's concept of how a use case might be implemented. User evaluation points out <strong>alternative flows, missing interaction steps, additional exceptions, overlooked postconditions, and pertinent business rules</strong>.</p>`, `<p>Khi người ta nói "prototype" thường là một <strong>mock-up</strong> của một UI khả dĩ — còn gọi <strong>horizontal prototype</strong> vì nó phủ một phần UI <strong>mà không lặn vào các tầng kiến trúc hay chức năng chi tiết</strong>. Mục đích: trình bày các tuỳ chọn chức năng, look-and-feel (màu, bố cục, đồ hoạ, control) và cấu trúc điều hướng; khám phá hành vi cụ thể để làm sắc yêu cầu; và biểu diễn ý niệm của developer về cách một use case có thể hiện thực. Người dùng đánh giá chỉ ra <strong>luồng thay thế, bước tương tác thiếu, ngoại lệ thêm, postcondition bị bỏ, và business rule liên quan</strong>.</p>`],
      [7, 'Proofs of concept (vertical prototypes / spikes)', `<p>A <strong>proof of concept</strong> (a <strong>vertical prototype</strong>) implements a <strong>slice of functionality from the UI down through all the technical service layers</strong>. Agile projects sometimes call it a <strong>"spike."</strong> Build one when you're unsure whether a proposed <strong>architecture is feasible and sound</strong>, or to optimize algorithms, evaluate a database schema, confirm a cloud solution, or test <strong>critical timing requirements</strong>. It's also useful for gathering information to <strong>improve effort estimates</strong> for a specific user story or block of functionality.</p>`, `<p>Một <strong>proof of concept</strong> (một <strong>vertical prototype</strong>) hiện thực một <strong>lát chức năng từ UI xuống xuyên mọi tầng dịch vụ kỹ thuật</strong>. Dự án agile đôi khi gọi nó là <strong>"spike."</strong> Dựng một cái khi bạn chưa chắc một <strong>kiến trúc đề xuất khả thi và vững</strong> không, hoặc để tối ưu thuật toán, đánh giá database schema, xác nhận giải pháp cloud, hoặc test <strong>yêu cầu timing trọng yếu</strong>. Nó cũng hữu ích để thu thập thông tin <strong>cải thiện ước lượng công sức</strong> cho một user story hay khối chức năng cụ thể.</p>`],
      [8, 'Mock-up vs proof-of-concept — summary', `<p>The two scope choices answer different questions. A <strong>mock-up (horizontal)</strong> answers "is this the <em>right</em> user experience and set of requirements?" — broad but shallow. A <strong>proof-of-concept (vertical)</strong> answers "can we <em>build</em> this technically, and how fast?" — narrow but deep through the stack. Choose the one that targets your biggest current uncertainty.</p>`, `<p>Hai lựa chọn scope trả lời câu hỏi khác nhau. Một <strong>mock-up (horizontal)</strong> trả lời "đây có phải trải nghiệm và tập yêu cầu <em>đúng</em> không?" — rộng nhưng nông. Một <strong>proof-of-concept (vertical)</strong> trả lời "ta <em>xây</em> được về mặt kỹ thuật không, và nhanh cỡ nào?" — hẹp nhưng sâu xuyên stack. Chọn cái nhắm vào bất định lớn nhất hiện tại của bạn.</p>`],
    ]),
    books([['wiegers', 'Chapter 15, "Prototyping: what and why", "Mock-ups and proofs of concept"', 'Chương 15, "Prototyping: what and why", "Mock-ups and proofs of concept"']]),
  ].join('\n'),
};

/* 8.3 — throwaway/evolutionary, paper/electronic, working with */
const P2 = {
  title: '8.3 — Slides: throwaway vs evolutionary, paper vs electronic (Ch.15 · 9–17)|||8.3 — Slide: throwaway vs evolutionary, giấy vs điện tử (Ch.15 · 9–17)',
  slug: 'swr302-8-3-ch15-types',
  type: 'DOCUMENT',
  description: 'Slide 9–17: throwaway (wireframe) vs evolutionary (nền kiến trúc vững, agile) prototype (Bảng 15-1, các cách kết hợp Fig 15-1); paper (low-fidelity, nhanh, rẻ) vs electronic prototype; và quy trình làm việc use case → dialog map → wireframe → tối ưu UI (Fig 15-2).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 8 · Lesson 8.3 · Book Ch.15 slides 9–17</span>
<h2>Throwaway vs evolutionary, paper vs electronic</h2>
<p class="lead">The other two attribute axes. A throwaway prototype answers questions then is discarded; an evolutionary one becomes the product. Paper prototypes iterate fastest and cheapest; electronic ones look real. And a working sequence carries you from use cases to a refined UI design.</p>`,
      `<span class="eyebrow">Chương 8 · Bài 8.3 · Slide 9–17 sách Ch.15</span>
<h2>Throwaway vs evolutionary, giấy vs điện tử</h2>
<p class="lead">Hai trục thuộc tính còn lại. Một throwaway prototype trả lời câu hỏi rồi bị bỏ; một evolutionary trở thành sản phẩm. Prototype giấy lặp nhanh nhất, rẻ nhất; điện tử trông thật. Và một trình tự làm việc đưa bạn từ use case tới thiết kế UI đã tinh chỉnh.</p>`,
    ),
    walkHead('ch15', 9, 17),
    walk('ch15', [
      [9, 'Throwaway prototypes', `<p>Build a <strong>throwaway</strong> prototype to <strong>answer questions, resolve uncertainties, and improve requirements quality</strong> (Davis 1993). A <strong>wireframe</strong> is a particular throwaway approach common for custom UI and website design. Wireframes help you understand three aspects of a website: the <strong>conceptual requirements</strong>, the <strong>information architecture / navigation design</strong>, and the <strong>high-resolution detailed design</strong> of the pages.</p>`, `<p>Dựng một prototype <strong>throwaway</strong> để <strong>trả lời câu hỏi, giải bất định, và cải thiện chất lượng yêu cầu</strong> (Davis 1993). Một <strong>wireframe</strong> là một cách throwaway cụ thể hay dùng cho UI tuỳ chỉnh và thiết kế website. Wireframe giúp bạn hiểu ba khía cạnh của một website: <strong>yêu cầu khái niệm</strong>, <strong>information architecture / thiết kế điều hướng</strong>, và <strong>thiết kế chi tiết độ phân giải cao</strong> của các trang.</p>`],
      [10, 'Evolutionary prototypes', `<p>An <strong>evolutionary</strong> prototype provides a <strong>solid architectural foundation</strong> for building the product incrementally as requirements become clear over time (McConnell 1996). <strong>Agile development is a form of evolutionary prototyping</strong> — teams construct the product through iterations, using early feedback to steer future cycles. Evolutionary prototyping suits <strong>web development</strong> well. Unlike a throwaway, it's real production code from the start.</p>`, `<p>Một prototype <strong>evolutionary</strong> cho một <strong>nền kiến trúc vững</strong> để xây sản phẩm tăng dần khi yêu cầu rõ dần theo thời gian (McConnell 1996). <strong>Phát triển agile là một dạng evolutionary prototyping</strong> — đội xây sản phẩm qua các iteration, dùng phản hồi sớm để lái các chu kỳ sau. Evolutionary prototyping hợp <strong>phát triển web</strong>. Khác throwaway, nó là code production thật ngay từ đầu.</p>`],
      [11, 'Applications & combining prototypes', `<p>Table 15-1 summarizes typical applications of throwaway, evolutionary, mock-up and proof-of-concept prototypes. Figure 15-1 shows ways to <strong>combine</strong> them: use knowledge from a series of <strong>throwaway prototypes to refine requirements</strong>, then implement incrementally via an <strong>evolutionary sequence</strong>. An alternative path runs a <strong>throwaway mock-up</strong> to clarify requirements before finalizing the UI <em>while a concurrent</em> <strong>proof-of-concept</strong> validates the architecture and core algorithms.</p>`, `<p>Bảng 15-1 tóm tắt ứng dụng điển hình của prototype throwaway, evolutionary, mock-up và proof-of-concept. Hình 15-1 chỉ cách <strong>kết hợp</strong> chúng: dùng kiến thức từ một loạt <strong>throwaway prototype để làm sắc yêu cầu</strong>, rồi hiện thực tăng dần qua một <strong>chuỗi evolutionary</strong>. Một đường khác chạy một <strong>throwaway mock-up</strong> để làm rõ yêu cầu trước khi chốt UI <em>trong khi song song một</em> <strong>proof-of-concept</strong> thẩm định kiến trúc và thuật toán lõi.</p>`],
      [12, 'Paper prototypes', `<p>A <strong>paper prototype</strong> (low-fidelity) is a cheap, fast, low-tech way to explore how part of a system might look — testing whether users and developers share an understanding of the requirements, a low-risk step before production code. Tools: paper, index cards, sticky notes, whiteboards; the designer sketches screens without worrying about exact control placement. In evaluation, <strong>someone plays the computer</strong> while a user walks through a scenario — if a response is wrong, grab a blank card and try again. No tool beats paper for speed, and <strong>rapid iteration is a key success factor</strong> in requirements development. It's excellent for refining requirements before detailed UI design or an evolutionary prototype, and it helps manage customer expectations.</p>`, `<p>Một <strong>paper prototype</strong> (low-fidelity) là cách rẻ, nhanh, low-tech để khám phá một phần hệ thống có thể trông thế nào — kiểm xem người dùng và developer có hiểu chung yêu cầu không, một bước ít rủi ro trước code production. Công cụ: giấy, thẻ, sticky note, whiteboard; designer phác màn hình không lo vị trí chính xác của control. Khi đánh giá, <strong>ai đó đóng vai máy tính</strong> trong khi người dùng đi qua một kịch bản — nếu một phản hồi sai, lấy một thẻ trắng và thử lại. Không công cụ nào hơn giấy về tốc độ, và <strong>lặp nhanh là yếu tố thành công then chốt</strong> trong phát triển yêu cầu. Nó tuyệt để làm sắc yêu cầu trước thiết kế UI chi tiết hay một evolutionary prototype, và giúp quản lý kỳ vọng khách.</p>`],
      [13, 'Electronic prototypes', `<p><strong>Electronic prototypes</strong> use tools from simple drawing (Visio, PowerPoint) to commercial prototyping tools and GUI builders, plus dedicated <strong>website wireframe</strong> tools — letting you implement and modify UI components regardless of how inefficient the throwaway code behind them is. But if you're building an <strong>evolutionary</strong> prototype, you must use <strong>production development tools from the outset</strong>. <strong>Application simulation</strong> tools let you assemble screens, controls, navigation and functionality into something resembling the intended product, and iterating on the simulation is a valuable way to interact with users to clarify requirements.</p>`, `<p><strong>Electronic prototype</strong> dùng công cụ từ vẽ đơn giản (Visio, PowerPoint) tới công cụ prototyping thương mại và GUI builder, cộng công cụ <strong>wireframe website</strong> chuyên — cho bạn hiện thực và sửa component UI bất kể code throwaway phía sau kém hiệu quả ra sao. Nhưng nếu dựng một prototype <strong>evolutionary</strong>, bạn phải dùng <strong>công cụ phát triển production ngay từ đầu</strong>. Công cụ <strong>application simulation</strong> cho bạn ráp màn hình, control, điều hướng và chức năng thành cái giống sản phẩm dự định, và lặp trên mô phỏng là cách quý để tương tác với người dùng làm rõ yêu cầu.</p>`],
      [14, 'Working with prototypes — the sequence', `<p>Figure 15-2 shows a sequence from use cases to detailed UI design via a throwaway prototype. Each use case's <strong>actor actions and system responses</strong> are modeled with a <strong>dialog map</strong> (a possible UI architecture). A <strong>throwaway prototype or wireframe</strong> elaborates the dialog elements into specific screens, menus and dialog boxes. User evaluation may change the <strong>use case descriptions</strong> (e.g. a discovered alternative flow) or the <strong>dialog map</strong>.</p>`, `<p>Hình 15-2 chỉ một trình tự từ use case tới thiết kế UI chi tiết qua một throwaway prototype. <strong>Hành động actor và phản hồi hệ thống</strong> của mỗi use case được mô hình bằng một <strong>dialog map</strong> (một kiến trúc UI khả dĩ). Một <strong>throwaway prototype hay wireframe</strong> khai triển các phần tử dialog thành màn hình, menu và hộp thoại cụ thể. Người dùng đánh giá có thể đổi <strong>mô tả use case</strong> (vd một luồng thay thế phát hiện được) hoặc <strong>dialog map</strong>.</p>`],
      [15, 'Iterating to a UI design', `<p>After the requirements are refined and screens sketched, each UI element can be <strong>optimized for usability</strong>. These activities needn't be strictly sequential — <strong>iterating on the use case, the dialog map, and the wireframe</strong> together is the fastest way to reach an acceptable, agreed UI design. Iteration, not a single perfect pass, is the point.</p>`, `<p>Sau khi yêu cầu được làm sắc và màn hình phác, mỗi phần tử UI có thể <strong>tối ưu cho usability</strong>. Các hoạt động này không cần tuần tự nghiêm ngặt — <strong>lặp trên use case, dialog map, và wireframe</strong> cùng nhau là cách nhanh nhất đạt một thiết kế UI chấp nhận được, đồng thuận. Lặp, không phải một lượt hoàn hảo duy nhất, mới là điểm mấu chốt.</p>`],
      [16, 'Working with prototypes (illustration)', `<p>A companion illustration of the same use-case → dialog-map → wireframe → optimized-UI flow — a reminder that the prototype is a <em>conversation piece</em> between users and developers, not a one-way deliverable. Each loop through it tightens the shared understanding.</p>`, `<p>Một minh hoạ đi kèm của cùng luồng use-case → dialog-map → wireframe → UI-tối-ưu — nhắc rằng prototype là một <em>vật để đối thoại</em> giữa người dùng và developer, không phải một sản phẩm một chiều. Mỗi vòng qua nó siết chặt cách hiểu chung.</p>`],
      [17, 'Prototype evaluation — the questions', `<p>Ask evaluators: Does the prototype implement the functionality <strong>as you expected</strong>? What functionality is <strong>missing</strong>? Any <strong>error conditions</strong> it doesn't address? Any <strong>unnecessary</strong> functions present? How <strong>logical and complete</strong> is the navigation? Can any tasks with <strong>too many steps</strong> be simplified? Were you ever <strong>unsure what to do next</strong>? These questions turn a demo into structured feedback that improves the requirements.</p>`, `<p>Hỏi người đánh giá: Prototype có hiện thực chức năng <strong>như bạn mong</strong> không? Chức năng nào <strong>thiếu</strong>? Có <strong>điều kiện lỗi</strong> nào nó không xử? Có chức năng <strong>thừa</strong> nào không? Điều hướng <strong>logic và đầy đủ</strong> ra sao? Có tác vụ nào <strong>quá nhiều bước</strong> để đơn giản hoá không? Bạn có lúc nào <strong>không chắc làm gì tiếp</strong> không? Các câu hỏi này biến một demo thành phản hồi có cấu trúc cải thiện yêu cầu.</p>`],
    ]),
    books([['wiegers', 'Chapter 15, "Throwaway prototypes", "Evolutionary prototypes" (Table 15-1, Figure 15-1), "Paper and electronic prototypes", "Working with prototypes" (Figure 15-2), "Prototype evaluation"', 'Chương 15, "Throwaway prototypes", "Evolutionary prototypes" (Bảng 15-1, Hình 15-1), "Paper and electronic prototypes", "Working with prototypes" (Hình 15-2), "Prototype evaluation"']]),
  ].join('\n'),
};

/* 8.4 — risks & success factors */
const P3 = {
  title: '8.4 — Slides: prototyping risks & success factors (Ch.15 · 18–24)|||8.4 — Slide: rủi ro & yếu tố thành công của prototyping (Ch.15 · 18–24)',
  slug: 'swr302-8-4-ch15-risks-success',
  type: 'DOCUMENT',
  description: 'Slide 18–24: bốn rủi ro của prototyping (áp lực phát hành prototype, sa đà chi tiết, kỳ vọng hiệu năng phi thực tế, đầu tư quá mức) và các yếu tố thành công (đặt mục đích trước khi dựng, dựng throwaway nhanh & rẻ, dùng dữ liệu hợp lý, không thay yêu cầu viết).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 8 · Lesson 8.4 · Book Ch.15 slides 18–24</span>
<h2>Prototyping risks &amp; success factors</h2>
<p class="lead">Prototyping's biggest danger is a stakeholder seeing a running throwaway and declaring the product "nearly done." This lesson: the four risks — pressure to ship, distraction, unrealistic performance expectations, over-investment — and the practices that keep prototyping an experiment, not a trap.</p>`,
      `<span class="eyebrow">Chương 8 · Bài 8.4 · Slide 18–24 sách Ch.15</span>
<h2>Rủi ro &amp; yếu tố thành công của prototyping</h2>
<p class="lead">Nguy hiểm lớn nhất của prototyping là một stakeholder thấy một throwaway đang chạy và tuyên bố sản phẩm "gần xong." Bài này: bốn rủi ro — áp lực ship, sa đà, kỳ vọng hiệu năng phi thực tế, đầu tư quá mức — và các thực hành giữ prototyping là một thí nghiệm, không phải một cái bẫy.</p>`,
    ),
    walkHead('ch15', 18, 24),
    walk('ch15', [
      [18, 'Risks of prototyping', `<p>Four risks: <strong>pressure to release the prototype</strong>, <strong>distraction by details</strong>, <strong>unrealistic performance expectations</strong>, and <strong>investing excessive effort in prototypes</strong>. Each is covered next, with mitigations.</p>`, `<p>Bốn rủi ro: <strong>áp lực phát hành prototype</strong>, <strong>sa đà vào chi tiết</strong>, <strong>kỳ vọng hiệu năng phi thực tế</strong>, và <strong>đầu tư quá mức vào prototype</strong>. Mỗi cái ngay sau, kèm giảm nhẹ.</p>`],
      [19, '1. Pressure to release the prototype', `<p>The biggest risk: a stakeholder sees a running throwaway and concludes the product is nearly done. <strong>NO</strong> — a throwaway is <em>never</em> for production, however real it looks; it's a model, a simulation, an experiment. Shipping it will likely <strong>delay the project</strong>, since its design/code were intentionally built without regard to quality or durability. Everyone who sees it must understand its purpose and limits. Mitigations: use <strong>paper</strong> rather than electronic prototypes; use <strong>different tools</strong> than production (no one mistakes a navigable PowerPoint or a simple wireframe for the real thing); and leave the prototype <strong>a bit rough and unpolished</strong>.</p>`, `<p>Rủi ro lớn nhất: một stakeholder thấy một throwaway đang chạy và kết luận sản phẩm gần xong. <strong>KHÔNG</strong> — một throwaway <em>không bao giờ</em> để production, dù trông thật thế nào; nó là một mô hình, mô phỏng, thí nghiệm. Ship nó có thể <strong>làm trễ dự án</strong>, vì design/code của nó cố ý dựng không màng chất lượng hay độ bền. Ai thấy nó phải hiểu mục đích và giới hạn. Giảm nhẹ: dùng prototype <strong>giấy</strong> thay điện tử; dùng <strong>công cụ khác</strong> production (không ai nhầm một PowerPoint điều hướng được hay một wireframe đơn giản với hàng thật); và để prototype <strong>hơi thô và chưa đánh bóng</strong>.</p>`],
      [20, '2. Distraction by details', `<p>Users can become <strong>fixated on how the UI will look and operate</strong>. With real-looking prototypes it's easy to forget that at the requirements stage the focus should be <strong>conceptual issues</strong>, not pixels. Mitigation: <strong>limit the prototype</strong> to the displays, functions and navigation needed to clear up the <em>uncertain</em> requirements — nothing more.</p>`, `<p>Người dùng có thể <strong>chăm chăm vào UI trông và hoạt động thế nào</strong>. Với prototype trông thật, dễ quên rằng ở giai đoạn yêu cầu trọng tâm nên là <strong>vấn đề khái niệm</strong>, không phải pixel. Giảm nhẹ: <strong>giới hạn prototype</strong> vào các màn hình, chức năng và điều hướng cần để làm rõ các yêu cầu <em>còn bất định</em> — không hơn.</p>`],
      [21, '3. Unrealistic performance expectations', `<p>Users may <strong>infer the final product's performance from the prototype's</strong>. But a mock-up may use less-efficient tools (interpreted scripts vs compiled code); a proof-of-concept may skip tuned algorithms or security layers; an instant response to a query using hard-coded results won't reflect a huge distributed database. Mitigations: <strong>build in time delays</strong> to simulate realistic behavior (and make it look less ready to ship); put a <strong>message on screen</strong> stating it's not representative of the final system. For evolutionary prototyping, <strong>design a robust, extendable architecture and write high-quality code from the start</strong> — you're building production software a bit at a time; refactor later, but don't substitute future refactoring for thinking about design today.</p>`, `<p>Người dùng có thể <strong>suy hiệu năng sản phẩm cuối từ prototype</strong>. Nhưng một mock-up có thể dùng công cụ kém hiệu quả (script thông dịch vs code biên dịch); một proof-of-concept có thể bỏ thuật toán đã tinh chỉnh hay tầng bảo mật; một phản hồi tức thì cho một truy vấn dùng kết quả hard-code không phản ánh một database phân tán khổng lồ. Giảm nhẹ: <strong>thêm độ trễ</strong> để mô phỏng hành vi thực (và làm nó trông ít sẵn sàng ship hơn); đặt một <strong>thông điệp trên màn hình</strong> nói nó không đại diện hệ cuối. Với evolutionary prototyping, <strong>thiết kế kiến trúc vững, mở rộng được và viết code chất lượng cao ngay từ đầu</strong> — bạn đang xây phần mềm production từng chút; refactor sau, nhưng đừng thay việc nghĩ về thiết kế hôm nay bằng refactor tương lai.</p>`],
      [22, '4. Investing excessive effort in prototypes', `<p>Beware prototyping that consumes so much effort the team <strong>runs out of time and is forced to ship the prototype as the product</strong>. This happens when you prototype the <strong>whole solution</strong> rather than only the most uncertain, high-risk or complex portions. Treat a prototype as an <strong>experiment</strong> — testing the hypothesis that the requirements are sufficiently defined and the key HCI and architecture issues are resolved enough to proceed. Do <strong>just enough prototyping</strong> to test the hypothesis, answer the questions, and refine the requirements.</p>`, `<p>Coi chừng prototyping ngốn nhiều công đến mức đội <strong>hết thời gian và buộc ship prototype làm sản phẩm</strong>. Điều này xảy ra khi bạn prototype <strong>cả giải pháp</strong> thay vì chỉ phần bất định, rủi ro cao hoặc phức tạp nhất. Coi một prototype là một <strong>thí nghiệm</strong> — kiểm giả thuyết rằng yêu cầu đủ rõ và các vấn đề HCI và kiến trúc then chốt được giải đủ để tiến. Làm <strong>vừa đủ prototyping</strong> để kiểm giả thuyết, trả lời câu hỏi, và làm sắc yêu cầu.</p>`],
      [23, 'Prototyping success factors', `<p>Practices that make prototyping pay off: <strong>include prototyping tasks in the project plan</strong>; <strong>state each prototype's purpose before building it</strong> and what happens to the outcome (discard/archive but keep the knowledge, or grow it into the solution); <strong>plan for multiple prototypes</strong>; create throwaways <strong>as quickly and cheaply as possible</strong>; <strong>don't</strong> put input validation, defensive coding, error handling or extensive documentation in a throwaway; <strong>don't prototype requirements you already understand</strong> (except to explore design alternatives); use <strong>plausible data</strong> in screens and reports; and <strong>don't expect a prototype to replace written requirements</strong>.</p>`, `<p>Thực hành làm prototyping sinh lợi: <strong>đưa task prototyping vào kế hoạch dự án</strong>; <strong>nêu mục đích mỗi prototype trước khi dựng</strong> và điều gì xảy ra với kết quả (bỏ/lưu trữ nhưng giữ kiến thức, hoặc lớn thành giải pháp); <strong>lên kế hoạch nhiều prototype</strong>; tạo throwaway <strong>nhanh và rẻ nhất có thể</strong>; <strong>đừng</strong> đưa validate input, defensive coding, xử lý lỗi hay tài liệu dài vào một throwaway; <strong>đừng prototype yêu cầu bạn đã hiểu</strong> (trừ để khám phá phương án thiết kế); dùng <strong>dữ liệu hợp lý</strong> trong màn hình và report; và <strong>đừng mong một prototype thay yêu cầu viết</strong>.</p>`],
      [24, 'Prototyping — the takeaway', `<p>The chapter's synthesis: a prototype is <strong>risk reduction</strong>, not a shortcut to a product. Choose its three attributes (scope, future use, form) to target your biggest uncertainty; iterate quickly and cheaply; guard against the four risks; and always know, before you build, whether you'll throw it away or grow it. Used this way, prototyping cheaply buys the requirements clarity that would otherwise cost a rebuilt product.</p>`, `<p>Tổng hợp của chương: một prototype là <strong>giảm rủi ro</strong>, không phải lối tắt tới sản phẩm. Chọn ba thuộc tính của nó (scope, future use, form) để nhắm bất định lớn nhất; lặp nhanh và rẻ; đề phòng bốn rủi ro; và luôn biết, trước khi dựng, bạn sẽ bỏ hay lớn nó. Dùng cách này, prototyping mua rẻ sự rõ ràng yêu cầu mà nếu không sẽ tốn một sản phẩm xây lại.</p>`],
    ]),
    books([['wiegers', 'Chapter 15, "Risks of prototyping", "Prototyping success factors"', 'Chương 15, "Risks of prototyping", "Prototyping success factors"']]),
  ].join('\n'),
};

export default [P1, P2, P3];
