/**
 * SWR302 · New section — book chapter Ch.18 "Requirements reuse" (21 slides).
 * A stand-alone section (this book chapter has no matching academy chapter),
 * split into THREE focused lessons: why reuse + the three dimensions (1–8),
 * types + scenarios + patterns (9–14), and barriers + success factors (15–21).
 * Exported as a SECTION object inserted into the sections array. Grounded
 * slide-by-slide in CHAPTER_18_Requirements reuse.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 18R.1 — why reuse & the three dimensions */
const U1 = {
  title: '18R.1 — Slides: why reuse & its three dimensions (Ch.18 · 1–8)|||18R.1 — Slide: vì sao tái dùng & ba chiều (Ch.18 · 1–8)',
  slug: 'swr302-18r-1-ch18-why-dimensions',
  type: 'DOCUMENT',
  description: 'Slide 1–8: lợi ích tái dùng yêu cầu (nhanh hơn, rẻ hơn, nhất quán, ít lỗi); ba chiều của reuse (Bảng 18-1) — extent of reuse (một câu → cả gói req+model+code+test), extent of modification (không đổi → sửa thuộc tính/thiết kế), reuse mechanism (copy-paste vs copy-by-reference/pointer).',
  content: [
    bi(
      `<span class="eyebrow">Requirements reuse · Lesson 18R.1 · Book Ch.18 slides 1–8</span>
<h2>Why reuse requirements, and its three dimensions</h2>
<p class="lead">Requirements are corporate assets. Reusing trusted ones delivers faster and cheaper, with more consistency and fewer defects. Reuse varies along three dimensions: how much you reuse, how much you modify, and the mechanism (copy vs reference).</p>`,
      `<span class="eyebrow">Tái dùng yêu cầu · Bài 18R.1 · Slide 1–8 sách Ch.18</span>
<h2>Vì sao tái dùng yêu cầu, và ba chiều của nó</h2>
<p class="lead">Yêu cầu là tài sản của công ty. Tái dùng cái đã tin cậy giao nhanh hơn và rẻ hơn, nhất quán hơn và ít lỗi hơn. Reuse biến thiên theo ba chiều: tái dùng bao nhiêu, sửa bao nhiêu, và cơ chế (sao chép vs tham chiếu).</p>`,
    ),
    walkHead('ch18', 1, 8),
    walk('ch18', [
      [1, 'Requirements reuse', `<p>Title slide — kinds of requirements reuse, what information has reuse potential, how to do it, and the barriers and success factors around it.</p>`, `<p>Slide bìa — các kiểu tái dùng yêu cầu, thông tin nào có tiềm năng tái dùng, cách làm, và các rào cản cùng yếu tố thành công.</p>`],
      [2, 'Objectives', `<p>Describe several kinds of requirements reuse and the classes of requirements information with reuse potential; offer suggestions on how to perform reuse and how to make requirements reusable; and conclude with the barriers to effective reuse and the success factors that help an organization exploit its existing requirements knowledge.</p>`, `<p>Mô tả vài kiểu tái dùng yêu cầu và các lớp thông tin yêu cầu có tiềm năng tái dùng; gợi ý cách thực hiện reuse và cách làm yêu cầu tái dùng được; và kết bằng rào cản của reuse hiệu quả cùng yếu tố thành công giúp tổ chức khai thác kiến thức yêu cầu sẵn có.</p>`],
      [3, 'Why reuse requirements?', `<p>Benefits: <strong>faster delivery, lower cost, consistency</strong> within and across applications, higher productivity, <strong>fewer defects, less rework</strong>. Reusing <em>trusted</em> requirements saves review time, speeds the approval cycle and testing. It improves <strong>effort estimation</strong> if you have data from implementing the same requirements before. From the user's view, reuse improves <strong>functional consistency</strong> across a product line or set of business applications. And note: even if the <em>implementation</em> varies across environments, the <em>requirements</em> might be the same.</p>`, `<p>Lợi ích: <strong>giao nhanh hơn, chi phí thấp hơn, nhất quán</strong> trong và giữa các ứng dụng, năng suất cao hơn, <strong>ít lỗi, ít làm lại</strong>. Tái dùng yêu cầu <em>đã tin cậy</em> tiết kiệm thời gian review, tăng tốc chu trình duyệt và test. Nó cải thiện <strong>ước lượng công sức</strong> nếu có dữ liệu từ hiện thực cùng yêu cầu trước đó. Từ góc người dùng, reuse cải thiện <strong>nhất quán chức năng</strong> qua một product line hay tập ứng dụng nghiệp vụ. Và lưu ý: kể cả khi <em>hiện thực</em> khác nhau giữa các môi trường, <em>yêu cầu</em> có thể vẫn như nhau.</p>`],
      [4, 'Dimensions of requirements reuse', `<p>Table 18-1 frames reuse along <strong>three dimensions</strong>: (1) the <strong>extent of reuse</strong> (how much material), (2) the <strong>extent of modification</strong> (how much you change it), and (3) the <strong>reuse mechanism</strong> (copy vs reference). The next slides detail each — together they describe any reuse situation.</p>`, `<p>Bảng 18-1 khung reuse theo <strong>ba chiều</strong>: (1) <strong>extent of reuse</strong> (bao nhiêu tài liệu), (2) <strong>extent of modification</strong> (sửa bao nhiêu), và (3) <strong>reuse mechanism</strong> (sao chép vs tham chiếu). Các slide sau chi tiết từng cái — cùng nhau chúng mô tả mọi tình huống reuse.</p>`],
      [5, '1. Extent of reuse', `<p>The quantity reused ranges widely: a single functional requirement; that statement <strong>plus its attributes</strong> (rationale, origin, priority…) if relevant; or the requirement <strong>plus associated artifacts</strong> (data definitions, acceptance tests, business rules, constraints, assumptions). Often a <strong>set of related requirements</strong> reuses well — e.g. all functional requirements for a feature (apps on similar platforms like different smartphone OSes might reuse requirements and design but little code). Ideally you reuse a <strong>whole package</strong> — requirements, models, design, code and tests — an entire chunk of functionality essentially unchanged from a related product (works for common operations like error handling, logging, communication protocols, help systems, built for reuse with clear <strong>APIs</strong> and full docs/tests).</p>`, `<p>Lượng tái dùng biến thiên rộng: một functional requirement đơn; câu đó <strong>cộng thuộc tính</strong> (rationale, origin, priority…) nếu liên quan; hoặc yêu cầu <strong>cộng hiện vật đi kèm</strong> (định nghĩa dữ liệu, acceptance test, business rule, constraint, giả định). Thường một <strong>tập yêu cầu liên quan</strong> tái dùng tốt — vd mọi functional requirement của một feature (app trên nền tương tự như các OS smartphone khác nhau có thể tái dùng yêu cầu và thiết kế nhưng ít code). Lý tưởng bạn tái dùng <strong>cả gói</strong> — requirement, model, design, code và test — một mảng chức năng gần như không đổi từ sản phẩm liên quan (hợp cho thao tác chung như xử lý lỗi, logging, giao thức truyền thông, hệ trợ giúp, dựng để reuse với <strong>API</strong> rõ và tài liệu/test đầy đủ).</p>`],
      [6, '2. Extent of modification', `<p>How much change is needed to reuse on the new project? Sometimes you reuse a requirement <strong>unchanged</strong> — the airline check-in kiosk and a check-in website share many identical functional requirements. Sometimes you reuse the statement unchanged but <strong>modify attributes</strong> (priority, rationale) for the new system; often you start with an existing requirement and <strong>tweak it to fit exactly</strong>. And whether or not you change the requirement, you may need to <strong>modify designs and tests</strong> — e.g. porting from a PC to a touch-screen tablet rather than mouse-and-keyboard.</p>`, `<p>Cần sửa bao nhiêu để tái dùng trên dự án mới? Đôi khi bạn tái dùng một yêu cầu <strong>không đổi</strong> — kiosk check-in hàng không và một website check-in chung nhiều functional requirement giống hệt. Đôi khi bạn tái dùng câu không đổi nhưng <strong>sửa thuộc tính</strong> (priority, rationale) cho hệ mới; thường bạn bắt đầu từ một yêu cầu có sẵn và <strong>chỉnh cho khớp chính xác</strong>. Và dù có đổi yêu cầu hay không, bạn có thể phải <strong>sửa thiết kế và test</strong> — vd chuyển từ PC sang tablet cảm ứng thay vì chuột-bàn phím.</p>`],
      [7, '3. Reuse mechanism — copy vs reference', `<p>The crudest form is <strong>copy-and-paste</strong> from a spec or a library: no history of origin, copies are editable, and copying within a project <em>bloats</em> the spec through duplication. Usually better: reuse by <strong>reference</strong> instead of replication — the original source must be accessible and persistent. In a document, a word-processor <strong>cross-reference</strong> links copies to the master, so editing the master echoes everywhere (avoiding the inconsistency of hand-editing one copy) — though it also risks all copies changing if the master is altered. A third mechanism stores a <strong>pointer</strong> (a unique identifier, ideally a hyperlink) to reusable info collected in a shared location (file, spreadsheet, XML, database, or RM tool); a reader follows the link to the master, always current if the collection is maintained.</p>`, `<p>Dạng thô nhất là <strong>copy-and-paste</strong> từ một spec hay thư viện: không lịch sử nguồn, bản sao sửa được, và sao chép trong một dự án <em>phình</em> spec do trùng lặp. Thường tốt hơn: tái dùng bằng <strong>tham chiếu</strong> thay vì sao chép — nguồn gốc phải truy cập được và bền. Trong một tài liệu, một <strong>cross-reference</strong> của word-processor nối bản sao tới bản chính, nên sửa bản chính vọng khắp nơi (tránh bất nhất khi sửa tay một bản) — dù cũng rủi ro mọi bản đổi nếu bản chính bị sửa. Cơ chế thứ ba lưu một <strong>pointer</strong> (một ID duy nhất, lý tưởng là hyperlink) tới thông tin tái dùng được gom ở một nơi chung (file, spreadsheet, XML, database, hay công cụ RM); người đọc theo link tới bản chính, luôn cập nhật nếu bộ sưu tập được bảo trì.</p>`],
      [8, 'Reuse by reference (continued)', `<p>To reuse, say, user-class descriptions from other projects: first <strong>collect the reusable information into a shared location</strong> and give each object a <strong>unique identifier</strong>; then to incorporate by reference, enter that identifier in the appropriate section of your document — and, if the technology allows, a <strong>direct hyperlink</strong> to the master object. Maintained properly, those links and their destinations always stay current — the whole benefit of reference over copy.</p>`, `<p>Để tái dùng, chẳng hạn, mô tả user-class từ dự án khác: trước hết <strong>gom thông tin tái dùng vào một nơi chung</strong> và cho mỗi đối tượng một <strong>ID duy nhất</strong>; rồi để đưa vào bằng tham chiếu, nhập ID đó vào mục thích hợp trong tài liệu — và, nếu công nghệ cho phép, một <strong>hyperlink trực tiếp</strong> tới đối tượng chính. Bảo trì đúng, các link đó và đích của chúng luôn cập nhật — chính là lợi ích của tham chiếu so với sao chép.</p>`],
    ]),
    books([['wiegers', 'Chapter 18, "Why reuse requirements?", "Dimensions of requirements reuse" (Table 18-1)', 'Chương 18, "Why reuse requirements?", "Dimensions of requirements reuse" (Bảng 18-1)']]),
  ].join('\n'),
};

/* 18R.2 — types, scenarios, patterns */
const U2 = {
  title: '18R.2 — Slides: types, scenarios & requirement patterns (Ch.18 · 9–14)|||18R.2 — Slide: loại, kịch bản & requirement pattern (Ch.18 · 9–14)',
  slug: 'swr302-18r-2-ch18-patterns',
  type: 'DOCUMENT',
  description: 'Slide 9–14: các loại thông tin yêu cầu tái dùng được (Bảng 18-2); kịch bản reuse phổ biến (software product line — common/optional/variant features; hệ reengineered/replacement; Bảng 18-3); và requirement pattern (Withall) — cấu trúc Guidance/Content/Template/Examples/Extra/Dev&Test considerations.',
  content: [
    bi(
      `<span class="eyebrow">Requirements reuse · Lesson 18R.2 · Book Ch.18 slides 9–14</span>
<h2>Types, scenarios &amp; requirement patterns</h2>
<p class="lead">What information is reusable, where reuse most naturally happens — product lines and system replacements — and the requirement pattern: a systematic, sectioned template that makes a whole <em>type</em> of requirement reusable.</p>`,
      `<span class="eyebrow">Tái dùng yêu cầu · Bài 18R.2 · Slide 9–14 sách Ch.18</span>
<h2>Loại, kịch bản &amp; requirement pattern</h2>
<p class="lead">Thông tin nào tái dùng được, reuse xảy ra tự nhiên nhất ở đâu — product line và thay thế hệ thống — và requirement pattern: một template có cấu trúc, chia mục, làm cả một <em>loại</em> yêu cầu tái dùng được.</p>`,
    ),
    walkHead('ch18', 9, 14),
    walk('ch18', [
      [9, 'Types of requirements information to reuse', `<p>Table 18-2 lists reusable requirements information — not just functional requirements but user-class descriptions, glossary/data-dictionary entries, business rules, quality attributes, constraints, use cases, acceptance tests, analysis models, and more. Recognizing the full range widens what you can harvest: often the most reusable assets are the <em>supporting</em> artifacts, not the requirement statements themselves.</p>`, `<p>Bảng 18-2 liệt kê thông tin yêu cầu tái dùng được — không chỉ functional requirement mà mô tả user-class, mục glossary/data-dictionary, business rule, thuộc tính chất lượng, constraint, use case, acceptance test, mô hình phân tích, và hơn nữa. Nhận ra toàn dải mở rộng cái bạn thu hoạch được: thường tài sản tái dùng nhất là các hiện vật <em>hỗ trợ</em>, không phải bản thân câu yêu cầu.</p>`],
      [10, 'Common reuse scenarios', `<p>Three scenarios where reuse is natural: <strong>software product lines</strong>, <strong>reengineered and replacement systems</strong>, and <strong>other likely opportunities</strong> (Table 18-3). The next slides detail the first two.</p>`, `<p>Ba kịch bản reuse tự nhiên: <strong>software product line</strong>, <strong>hệ reengineered và replacement</strong>, và <strong>các cơ hội khả dĩ khác</strong> (Bảng 18-3). Các slide sau chi tiết hai cái đầu.</p>`],
      [11, '1. Software product lines', `<p>A <strong>product line</strong> (a family of related products) has much common functionality — often variations of a base product for different customers/markets (e.g. a tax package's free/basic/deluxe/premier/business versions). Analyze the features to classify them as <strong>Common</strong> (in all members), <strong>Optional</strong> (in some), or <strong>Variant</strong> (different versions in different members). <strong>Common features</strong> offer the greatest reuse — not just requirements but downstream architecture, design, code and tests. Watch for <strong>environment/platform constraints</strong>: if the implementation must differ across members, you're limited to reusing only requirements, not design and code.</p>`, `<p>Một <strong>product line</strong> (một họ sản phẩm liên quan) có nhiều chức năng chung — thường là biến thể của một sản phẩm gốc cho khách/thị trường khác nhau (vd gói thuế bản free/basic/deluxe/premier/business). Phân tích feature để phân loại chúng là <strong>Common</strong> (ở mọi thành viên), <strong>Optional</strong> (ở vài cái), hoặc <strong>Variant</strong> (bản khác nhau ở thành viên khác nhau). <strong>Feature chung</strong> cho reuse nhiều nhất — không chỉ yêu cầu mà kiến trúc, thiết kế, code và test phía sau. Coi chừng <strong>ràng buộc môi trường/nền</strong>: nếu hiện thực phải khác giữa các thành viên, bạn chỉ tái dùng được yêu cầu, không phải design và code.</p>`],
      [12, '2. Reengineered & replacement systems', `<p>Reengineered/replacement systems <strong>always reuse some requirements</strong> from the original — even if those "requirements" were never written down. If you must <strong>reverse-engineer</strong> requirements from an old system, raise your thinking to a <strong>higher level of abstraction</strong> to escape specific implementation details. You can often <strong>harvest business rules</strong> embedded in the old system and reuse them (updating regulatory/compliance rules as needed). <strong>Trap:</strong> don't reuse too much of the old system to save time — you'll miss the opportunities of new platforms, architectures and workflows.</p>`, `<p>Hệ reengineered/replacement <strong>luôn tái dùng vài yêu cầu</strong> từ bản gốc — kể cả khi các "yêu cầu" đó chưa từng được viết. Nếu phải <strong>reverse-engineer</strong> yêu cầu từ hệ cũ, nâng tư duy lên <strong>mức trừu tượng cao hơn</strong> để thoát chi tiết hiện thực cụ thể. Bạn thường <strong>thu hoạch được business rule</strong> nhúng trong hệ cũ và tái dùng (cập nhật rule quy định/tuân thủ khi cần). <strong>Bẫy:</strong> đừng tái dùng quá nhiều hệ cũ để tiết kiệm thời gian — bạn sẽ bỏ lỡ cơ hội của nền, kiến trúc và workflow mới.</p>`],
      [13, 'Other reuse opportunities', `<p>Table 18-3 lists other common situations where reusing requirements information is valuable — across projects in the same domain, between related applications, when adopting an off-the-shelf package, and so on. The lesson: scan for reuse opportunities deliberately rather than assuming every project starts from a blank page.</p>`, `<p>Bảng 18-3 liệt kê các tình huống phổ biến khác mà tái dùng thông tin yêu cầu có giá trị — qua các dự án cùng miền, giữa ứng dụng liên quan, khi nhận một gói off-the-shelf, v.v. Bài học: quét cơ hội reuse có chủ đích thay vì cho rằng mọi dự án bắt đầu từ trang trắng.</p>`],
      [14, 'Requirement patterns', `<p>A <strong>requirement pattern</strong> offers a systematic approach to specifying a particular <em>type</em> of requirement; its structure and content make requirements of that type reusable. A pattern (Withall 2007) has sections: <strong>Guidance</strong> (basics, related patterns, when it does/doesn't apply, how to write this type); <strong>Content</strong> (item-by-item explanation of what such a requirement should convey); <strong>Template</strong> (a fill-in-the-blanks definition with placeholders for variable pieces); <strong>Examples</strong> (illustrative requirements of the type); <strong>Extra requirements</strong> (additional requirements or how to detail the high-level one); and <strong>Considerations for development and testing</strong> (factors for developers implementing and testers testing this type).</p>`, `<p>Một <strong>requirement pattern</strong> cho một cách tiếp cận có hệ thống để đặc tả một <em>loại</em> yêu cầu cụ thể; cấu trúc và nội dung của nó làm yêu cầu loại đó tái dùng được. Một pattern (Withall 2007) có các mục: <strong>Guidance</strong> (cơ bản, pattern liên quan, khi nào áp/không áp, cách viết loại này); <strong>Content</strong> (giải thích từng mục cái mà yêu cầu như vậy nên truyền đạt); <strong>Template</strong> (một định nghĩa điền-vào-chỗ-trống với placeholder cho phần biến thiên); <strong>Examples</strong> (yêu cầu minh hoạ của loại); <strong>Extra requirements</strong> (yêu cầu thêm hoặc cách chi tiết hoá cái cấp cao); và <strong>Considerations for development and testing</strong> (yếu tố cho developer hiện thực và tester test loại này).</p>`],
    ]),
    books([['wiegers', 'Chapter 18, "Types of requirements information to reuse" (Table 18-2), "Common reuse scenarios" (Table 18-3), "Requirement patterns" (Withall 2007)', 'Chương 18, "Types of requirements information to reuse" (Bảng 18-2), "Common reuse scenarios" (Bảng 18-3), "Requirement patterns" (Withall 2007)']]),
  ].join('\n'),
};

/* 18R.3 — barriers & success factors */
const U3 = {
  title: '18R.3 — Slides: reuse barriers & success factors (Ch.18 · 15–21)|||18R.3 — Slide: rào cản & yếu tố thành công của reuse (Ch.18 · 15–21)',
  slug: 'swr302-18r-3-ch18-barriers-success',
  type: 'DOCUMENT',
  description: 'Slide 15–21: rào cản reuse (yêu cầu thiếu/kém, NIH/NAH, writing style, tổ chức không nhất quán, loại dự án, quyền sở hữu) và yếu tố thành công (repository tìm kiếm được, quality, interactions/traceability, terminology chung, văn hoá tổ chức "mượn trước, tạo sau").',
  content: [
    bi(
      `<span class="eyebrow">Requirements reuse · Lesson 18R.3 · Book Ch.18 slides 15–21</span>
<h2>Reuse barriers &amp; success factors</h2>
<p class="lead">Reuse fails for predictable reasons — undocumented or badly written requirements, "not invented here" attitudes, inconsistent style and organization, ownership rights. It succeeds when an organization builds a searchable repository, insists on quality, and cultivates a "borrow first, create second" culture.</p>`,
      `<span class="eyebrow">Tái dùng yêu cầu · Bài 18R.3 · Slide 15–21 sách Ch.18</span>
<h2>Rào cản &amp; yếu tố thành công của reuse</h2>
<p class="lead">Reuse thất bại vì các lý do đoán được — yêu cầu không tài liệu hoá hay viết dở, thái độ "không phải do ta làm", style và tổ chức không nhất quán, quyền sở hữu. Nó thành công khi tổ chức dựng một repository tìm kiếm được, đòi chất lượng, và nuôi văn hoá "mượn trước, tạo sau".</p>`,
    ),
    walkHead('ch18', 15, 21),
    walk('ch18', [
      [15, 'Barriers — the two lists', `<p><strong>Reuse barriers:</strong> missing or poor requirements; NIH &amp; NAH; writing style; inconsistent organization; project type; ownership. <strong>Success factors:</strong> repository; quality; interactions; terminology; organizational culture. The next slides work through both.</p>`, `<p><strong>Rào cản reuse:</strong> yêu cầu thiếu hoặc kém; NIH &amp; NAH; writing style; tổ chức không nhất quán; loại dự án; quyền sở hữu. <strong>Yếu tố thành công:</strong> repository; quality; interactions; terminology; văn hoá tổ chức. Các slide sau đi qua cả hai.</p>`],
      [16, 'Barriers: missing/poor requirements, NIH & NAH', `<p><strong>Missing or poor requirements:</strong> previous projects often didn't document their requirements, so there's nothing to reuse — and even documented ones may be badly written, incomplete, a poor fit, or obsolete (not kept current as the app evolved). <strong>NIH ("not invented here"):</strong> reluctance to reuse requirements from another org or a public collection — outside requirements can be harder to understand (different terminology, references to unavailable documents, missing context/background). <strong>NAH ("not applicable here"):</strong> "we're different, our project is unique, no existing requirement could apply." Sometimes true — but often NIH and NAH just reveal an <strong>inflexible attitude</strong>.</p>`, `<p><strong>Yêu cầu thiếu hoặc kém:</strong> dự án trước thường không tài liệu hoá yêu cầu, nên không có gì để tái dùng — và cái đã tài liệu hoá có thể viết dở, thiếu, không hợp, hoặc lỗi thời (không cập nhật khi app tiến hoá). <strong>NIH ("not invented here"):</strong> ngại tái dùng yêu cầu từ tổ chức khác hay bộ sưu tập công khai — yêu cầu bên ngoài khó hiểu hơn (thuật ngữ khác, tham chiếu tài liệu không có, thiếu ngữ cảnh/bối cảnh). <strong>NAH ("not applicable here"):</strong> "chúng tôi khác, dự án chúng tôi độc nhất, không yêu cầu có sẵn nào áp được." Đôi khi đúng — nhưng thường NIH và NAH chỉ lộ một <strong>thái độ cứng nhắc</strong>.</p>`],
      [17, 'Barriers: writing style & inconsistent organization', `<p><strong>Writing style:</strong> past BAs used varied representation techniques — adopt <strong>standard notations</strong> (e.g. patterns) and a <strong>common level of granularity</strong> so future BAs can search at the right detail. <strong>Consistent terminology</strong> matters — you may overlook a reusable requirement just because its terms differ from your stakeholders'. Natural-language requirements are prone to ambiguity, missing info and hidden assumptions, all reducing reuse potential. Requirements with <strong>embedded design constraints</strong> reuse poorly in a different environment (kiosk UI details baked into a requirement block its reuse for the same functionality on a website). <strong>Inconsistent organization:</strong> authors organize requirements many ways (by project, process flow, business unit, feature, category, subsystem…), making reusable ones hard to find.</p>`, `<p><strong>Writing style:</strong> BA cũ dùng kỹ thuật biểu diễn đa dạng — nhận <strong>ký hiệu chuẩn</strong> (vd pattern) và một <strong>mức granularity chung</strong> để BA tương lai tìm ở đúng chi tiết. <strong>Thuật ngữ nhất quán</strong> quan trọng — bạn có thể bỏ sót một yêu cầu tái dùng được chỉ vì từ ngữ khác của stakeholder bạn. Yêu cầu ngôn ngữ tự nhiên dễ mơ hồ, thiếu thông tin và giả định ẩn, đều giảm tiềm năng reuse. Yêu cầu có <strong>ràng buộc thiết kế nhúng</strong> tái dùng kém ở môi trường khác (chi tiết UI kiosk nhét vào một yêu cầu chặn reuse cho cùng chức năng trên website). <strong>Tổ chức không nhất quán:</strong> tác giả tổ chức yêu cầu nhiều kiểu (theo dự án, luồng, đơn vị nghiệp vụ, feature, category, subsystem…), làm cái tái dùng được khó tìm.</p>`],
      [18, 'Barriers: project type & ownership', `<p><strong>Project type:</strong> requirements tightly coupled to a specific implementation environment/platform are less likely to yield reusable requirements or benefit from an existing pool; and <strong>rapidly evolving domains</strong> have no pool yet — today's relevant requirement may be obsolete tomorrow. <strong>Ownership:</strong> if you build a product for a specific customer, its requirements are likely the customer's <strong>proprietary intellectual property</strong> — you may have no legal right to reuse them in a different system for your own company or other customers.</p>`, `<p><strong>Loại dự án:</strong> yêu cầu gắn chặt vào một môi trường/nền hiện thực cụ thể ít khả năng sinh yêu cầu tái dùng được hoặc hưởng lợi từ một kho có sẵn; và <strong>miền tiến hoá nhanh</strong> chưa có kho — yêu cầu hôm nay có thể lỗi thời mai. <strong>Quyền sở hữu:</strong> nếu bạn xây sản phẩm cho một khách cụ thể, yêu cầu của nó có thể là <strong>tài sản trí tuệ độc quyền</strong> của khách — bạn có thể không có quyền pháp lý tái dùng chúng trong hệ khác cho công ty mình hay khách khác.</p>`],
      [19, 'Success factors: repository', `<p><strong>You can't reuse what you can't find</strong> — so the enabling tool for large-scale reuse is a <strong>searchable repository</strong>. Forms: a single network folder of previous requirements documents; a collection in an RM tool searchable across projects; or a database of requirements culled for reuse potential and <strong>enhanced with keywords</strong> so future BAs know their origin, judge suitability, and learn their limitations. Consider giving someone <strong>responsibility to manage the repository</strong> — adapting and storing assets for efficient discovery, retrieval and reuse (a scheme like managing business rules as an enterprise asset works well).</p>`, `<p><strong>Không thể tái dùng cái không tìm được</strong> — nên công cụ then chốt cho reuse quy mô lớn là một <strong>repository tìm kiếm được</strong>. Dạng: một network folder chứa tài liệu yêu cầu trước; một bộ sưu tập trong công cụ RM tìm kiếm được qua các dự án; hoặc một database yêu cầu chọn lọc theo tiềm năng reuse và <strong>bổ sung từ khoá</strong> để BA tương lai biết nguồn, phán độ phù hợp, và học giới hạn. Cân nhắc giao ai đó <strong>trách nhiệm quản lý repository</strong> — điều chỉnh và lưu tài sản cho khám phá, truy xuất và reuse hiệu quả (một scheme như quản lý business rule làm tài sản doanh nghiệp là hợp).</p>`],
      [20, 'Success factors: quality, interactions, terminology', `<p><strong>Quality:</strong> no one reuses junk — reusers need <strong>confidence</strong> in the information; and when you reuse an imperfect requirement, <strong>improve it</strong>, iteratively raising its reuse potential. <strong>Interactions:</strong> requirements have logical links/dependencies — use <strong>traceability links</strong> so people know what they're getting into when selecting one for reuse, and ensure reused requirements <strong>conform to existing business rules, constraints, standards, interfaces</strong> and quality expectations. <strong>Terminology:</strong> establish common terminology/definitions across projects — variations won't <em>prevent</em> reuse but you'll have to reconcile them; <strong>glossaries and data dictionaries</strong> are good reusable sources — link key terms to the shared glossary rather than embedding the whole glossary in every spec.</p>`, `<p><strong>Quality:</strong> không ai tái dùng rác — người reuse cần <strong>tin tưởng</strong> vào thông tin; và khi tái dùng một yêu cầu chưa hoàn hảo, <strong>cải thiện nó</strong>, nâng dần tiềm năng reuse. <strong>Interactions:</strong> yêu cầu có link/phụ thuộc logic — dùng <strong>traceability link</strong> để người ta biết mình dấn vào gì khi chọn một cái để reuse, và bảo đảm yêu cầu tái dùng <strong>tuân business rule, constraint, chuẩn, interface</strong> và kỳ vọng chất lượng hiện có. <strong>Terminology:</strong> lập thuật ngữ/định nghĩa chung qua các dự án — biến thể không <em>ngăn</em> reuse nhưng bạn phải hoà giải chúng; <strong>glossary và data dictionary</strong> là nguồn tái dùng tốt — link từ khoá quan trọng tới glossary chung thay vì nhúng cả glossary vào mọi spec.</p>`],
      [21, 'Success factors: organizational culture', `<p><strong>Management should encourage reuse from two sides:</strong> contributing high-quality, reusable components, and effectively reusing existing artifacts. The teams that reuse best enjoy the highest productivity. In a reuse culture, BAs <strong>look at the repository before creating their own requirements</strong> — starting from a user story or high-level statement and filling in details through reuse. Your project requirements are <strong>valuable corporate information</strong>; treat reusable requirements knowledge as an <strong>enterprise-level asset</strong>. Reused requirements needn't be perfect to be valuable — even saving 20% of new-writing effort is a big gain. A culture of <strong>"borrow first, create second"</strong>, plus a little extra investment in making requirements reusable, raises the productivity of analysts and developers and yields higher-quality products.</p>`, `<p><strong>Quản lý nên khuyến khích reuse từ hai phía:</strong> đóng góp thành phần chất lượng cao, tái dùng được, và tái dùng hiệu quả hiện vật sẵn có. Đội tái dùng giỏi nhất hưởng năng suất cao nhất. Trong văn hoá reuse, BA <strong>xem repository trước khi tạo yêu cầu của mình</strong> — bắt đầu từ một user story hay câu cấp cao và điền chi tiết qua reuse. Yêu cầu dự án của bạn là <strong>thông tin công ty giá trị</strong>; coi kiến thức yêu cầu tái dùng như <strong>tài sản cấp doanh nghiệp</strong>. Yêu cầu tái dùng không cần hoàn hảo mới có giá trị — kể cả tiết kiệm 20% công viết mới cũng là lợi lớn. Một văn hoá <strong>"mượn trước, tạo sau"</strong>, cộng chút đầu tư thêm làm yêu cầu tái dùng được, nâng năng suất của analyst và developer và cho sản phẩm chất lượng cao hơn.</p>`],
    ]),
    books([['wiegers', 'Chapter 18, "Requirements reuse barriers and success factors"', 'Chương 18, "Requirements reuse barriers and success factors"']]),
  ].join('\n'),
};

export default {
  title: 'Requirements reuse (book Ch.18)|||Tái dùng yêu cầu (Ch.18 sách)',
  description: 'Chương 18 sách Wiegers: vì sao & cách tái dùng yêu cầu — ba chiều (extent/modification/mechanism), loại thông tin tái dùng được, kịch bản (product line, replacement), requirement pattern, và rào cản + yếu tố thành công. Tách 3 bài.',
  lessons: [U1, U2, U3],
};
