/**
 * SWR302 · New section — book chapter Ch.19 "Beyond requirements development"
 * (13 slides). A stand-alone section, split into TWO focused lessons: effects +
 * estimation + project plans (1–6), and designs/code/tests/success (7–13).
 * Exported as a SECTION object inserted into the sections array. Grounded
 * slide-by-slide in CHAPTER_19_Beyond requirements development.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 19B.1 — effects, estimation, project plans */
const B1 = {
  title: '19B.1 — Slides: effects, estimation & project plans (Ch.19 · 1–6)|||19B.1 — Slide: ảnh hưởng, ước lượng & kế hoạch dự án (Ch.19 · 1–6)',
  slug: 'swr302-19b-1-ch19-plans',
  type: 'DOCUMENT',
  description: 'Slide 1–6: yêu cầu dẫn dắt lập kế hoạch, thiết kế, code, test (Fig 19-1); ước lượng công sức requirements theo vòng đời (waterfall/iterative/incremental); và từ yêu cầu tới project plan — ước lượng cỡ/công sức (testable req, function points, story/use case points) và các yếu tố lập lịch.',
  content: [
    bi(
      `<span class="eyebrow">Beyond requirements development · Lesson 19B.1 · Book Ch.19 slides 1–6</span>
<h2>Effects, estimation &amp; project plans</h2>
<p class="lead">Requirements don't stop at the SRS — they drive planning, design, code and tests. This lesson: how requirements ripple into the whole project, how to estimate the requirements effort itself, and how requirements feed project size estimates and schedules.</p>`,
      `<span class="eyebrow">Ngoài phát triển yêu cầu · Bài 19B.1 · Slide 1–6 sách Ch.19</span>
<h2>Ảnh hưởng, ước lượng &amp; kế hoạch dự án</h2>
<p class="lead">Yêu cầu không dừng ở SRS — chúng dẫn dắt lập kế hoạch, thiết kế, code và test. Bài này: yêu cầu lan vào cả dự án ra sao, cách ước lượng chính công sức làm yêu cầu, và cách yêu cầu nuôi ước lượng cỡ dự án và lịch.</p>`,
    ),
    walkHead('ch19', 1, 6),
    walk('ch19', [
      [1, 'Beyond requirements development', `<p>Title slide — approaches for bridging the gap between requirements development and a successful product release.</p>`, `<p>Slide bìa — các cách bắc cầu giữa phát triển yêu cầu và một lần phát hành sản phẩm thành công.</p>`],
      [2, 'Objectives', `<p>Explore approaches for bridging requirements development and a successful release; understand the <strong>influence of requirements on project plans, designs, code, and tests</strong>.</p>`, `<p>Khám phá các cách bắc cầu phát triển yêu cầu và một lần phát hành thành công; hiểu <strong>ảnh hưởng của yêu cầu lên kế hoạch dự án, thiết kế, code, và test</strong>.</p>`],
      [3, 'Contents', `<p>Six topics: the effects of requirements on development, estimating requirements effort, requirements → project plans, requirements → designs and code, requirements → tests, and requirements → success. Lessons 19B.1–19B.2 cover them.</p>`, `<p>Sáu chủ đề: ảnh hưởng của yêu cầu lên phát triển, ước lượng công sức yêu cầu, yêu cầu → kế hoạch dự án, yêu cầu → thiết kế và code, yêu cầu → test, và yêu cầu → thành công. Bài 19B.1–19B.2 phủ chúng.</p>`],
      [4, 'The effects of requirements on development', `<p>Figure 19-1: requirements are the hub — they <strong>drive project planning, design, coding, and testing</strong>. Every downstream activity traces back to the requirements, which is why a defect there ripples so widely. This chapter follows each of those four arrows in turn.</p>`, `<p>Hình 19-1: yêu cầu là trung tâm — chúng <strong>dẫn dắt lập kế hoạch, thiết kế, code, và test</strong>. Mọi hoạt động phía sau truy ngược về yêu cầu, vì thế một lỗi ở đó lan rộng đến vậy. Chương này theo từng mũi tên trong bốn cái đó.</p>`],
      [5, 'Estimating requirements effort', `<p>Requirements engineering effort is <strong>distributed throughout the project in different ways</strong> depending on the life cycle: a <strong>sequential (waterfall)</strong> project front-loads most requirements work; an <strong>iterative</strong> or <strong>incremental</strong> project spreads it across iterations, revisiting requirements as the product grows. Plan the requirements effort to match the life cycle rather than assuming it's a one-time upfront phase.</p>`, `<p>Công sức requirements engineering được <strong>phân bố suốt dự án theo cách khác nhau</strong> tuỳ vòng đời: một dự án <strong>tuần tự (waterfall)</strong> dồn phần lớn việc yêu cầu lên đầu; một dự án <strong>iterative</strong> hay <strong>incremental</strong> trải nó qua các iteration, xem lại yêu cầu khi sản phẩm lớn lên. Lên kế hoạch công sức yêu cầu khớp vòng đời thay vì cho rằng nó là một pha đầu một lần.</p>`],
      [6, 'From requirements to project plans', `<p><strong>Estimating size and effort</strong> from requirements uses: the number of <strong>individually testable requirements</strong>; <strong>function points</strong>; <strong>story points</strong> or <strong>use case points</strong>; the number/type/complexity of <strong>UI elements</strong>; or estimated <strong>lines of code</strong> per requirement. <strong>Effective scheduling</strong> then needs: an estimated product <strong>size</strong>; the team's <strong>known productivity</strong> (from historical performance); a <strong>task list</strong> to fully implement and verify each feature/use case; <strong>reasonably stable requirements</strong> (at least for the coming iteration); and <strong>experience</strong> to adjust for intangibles and each project's unique aspects.</p>`, `<p><strong>Ước lượng cỡ và công sức</strong> từ yêu cầu dùng: số <strong>yêu cầu kiểm chứng riêng được</strong>; <strong>function point</strong>; <strong>story point</strong> hoặc <strong>use case point</strong>; số/loại/độ phức tạp của <strong>phần tử UI</strong>; hoặc <strong>số dòng code</strong> ước lượng cho mỗi yêu cầu. <strong>Lập lịch hiệu quả</strong> rồi cần: một <strong>cỡ</strong> sản phẩm ước lượng; <strong>năng suất đã biết</strong> của đội (từ hiệu suất lịch sử); một <strong>danh sách task</strong> để hiện thực và verify đầy đủ mỗi feature/use case; <strong>yêu cầu ổn định hợp lý</strong> (ít nhất cho iteration tới); và <strong>kinh nghiệm</strong> để điều chỉnh cho yếu tố vô hình và nét riêng mỗi dự án.</p>`],
    ]),
    books([['wiegers', 'Chapter 19, "The effects of requirements on software development" (Figure 19-1), "Estimating requirements effort", "From requirements to project plans"', 'Chương 19, "The effects of requirements on software development" (Hình 19-1), "Estimating requirements effort", "From requirements to project plans"']]),
  ].join('\n'),
};

/* 19B.2 — designs, code, tests, success */
const B2 = {
  title: '19B.2 — Slides: designs, code, tests & success (Ch.19 · 7–13)|||19B.2 — Slide: thiết kế, code, test & thành công (Ch.19 · 7–13)',
  slug: 'swr302-19b-2-ch19-design-tests',
  type: 'DOCUMENT',
  description: 'Slide 7–13: từ yêu cầu tới thiết kế & code (architecture & allocation top-down, software design với cohesion/coupling/information hiding, UI design với DAR model); từ yêu cầu tới test (test theo yêu cầu, đưa tester vào review, mỗi FR ≥1 test); và từ yêu cầu tới thành công (đọc trước rẻ hơn xây sai, cân bằng hợp lý).',
  content: [
    bi(
      `<span class="eyebrow">Beyond requirements development · Lesson 19B.2 · Book Ch.19 slides 7–13</span>
<h2>Designs, code, tests &amp; success</h2>
<p class="lead">Following the last three arrows out of the requirements hub: into architecture and design, into tests, and finally into success. "It's faster to read the requirements before implementation than to build the wrong system and build it again correctly."</p>`,
      `<span class="eyebrow">Ngoài phát triển yêu cầu · Bài 19B.2 · Slide 7–13 sách Ch.19</span>
<h2>Thiết kế, code, test &amp; thành công</h2>
<p class="lead">Theo ba mũi tên cuối ra khỏi trung tâm yêu cầu: vào kiến trúc và thiết kế, vào test, và cuối cùng vào thành công. "Đọc yêu cầu trước khi hiện thực nhanh hơn xây sai hệ thống rồi xây lại cho đúng."</p>`,
    ),
    walkHead('ch19', 7, 13),
    walk('ch19', [
      [7, 'From requirements to designs and code', `<p>Requirements flow into design along three fronts covered next: <strong>architecture and allocation</strong>, <strong>software design</strong>, and <strong>user interface design</strong> — then on to tests and to overall success.</p>`, `<p>Yêu cầu chảy vào thiết kế theo ba mặt ngay sau: <strong>architecture và allocation</strong>, <strong>software design</strong>, và <strong>user interface design</strong> — rồi tới test và thành công tổng thể.</p>`],
      [8, '1. Architecture and allocation', `<p>A product's <strong>functionality, quality attributes and constraints drive its architecture</strong> — and analyzing a proposed architecture (like prototyping) helps verify and sharpen the requirements. Architecture is especially critical for <strong>combined software+hardware</strong> systems and complex software-only ones: an analyst/system engineer/architect <strong>decomposes system requirements into functional requirements for each subsystem</strong>. Allocation of capabilities to subsystems must be <strong>top-down</strong>. Example (Figure 19-3): a Blu-ray player has tray/spin motors, an optical subsystem, image rendering, a remote — subsystems that interact (e.g. pressing "open tray" while playing); system requirements drive the architecture, and the architecture influences requirements allocation.</p>`, `<p><strong>Chức năng, thuộc tính chất lượng và ràng buộc</strong> của sản phẩm <strong>dẫn dắt kiến trúc</strong> — và phân tích một kiến trúc đề xuất (như prototyping) giúp verify và làm sắc yêu cầu. Kiến trúc đặc biệt trọng yếu cho hệ <strong>kết hợp phần mềm+phần cứng</strong> và hệ chỉ-phần-mềm phức tạp: một analyst/system engineer/architect <strong>phân rã yêu cầu hệ thống thành yêu cầu chức năng cho mỗi subsystem</strong>. Phân bổ năng lực cho subsystem phải <strong>top-down</strong>. Ví dụ (Hình 19-3): đầu Blu-ray có motor tray/quay, optical subsystem, image rendering, một remote — các subsystem tương tác (vd bấm "mở tray" khi đang phát); yêu cầu hệ thống dẫn kiến trúc, và kiến trúc ảnh hưởng phân bổ yêu cầu.</p>`],
      [9, '2. Software design', `<p>Time spent translating requirements into design is an excellent investment in robust products. OO projects may start from <strong>OO analysis</strong> (class diagrams/UML), which designers elaborate into detailed object models. All projects benefit from: a <strong>solid architecture</strong> of subsystems/components allowing lifelong enhancement; identifying <strong>key modules/classes</strong> and their interfaces, responsibilities and collaborations; ensuring the design <strong>covers all functional requirements and no unnecessary functionality</strong>; defining each unit's function with <strong>strong cohesion, loose coupling, information hiding</strong>; handling <strong>exception conditions</strong>; meeting <strong>performance/security/quality goals</strong>; identifying <strong>reusable components</strong>; and respecting significant <strong>constraints</strong>. When developers hit ambiguity, they should route it back to customers/BAs via the <strong>issue-tracking process</strong>.</p>`, `<p>Thời gian dịch yêu cầu thành thiết kế là đầu tư tuyệt vời cho sản phẩm bền. Dự án OO có thể bắt đầu từ <strong>phân tích OO</strong> (class diagram/UML), designer khai triển thành object model chi tiết. Mọi dự án hưởng lợi từ: một <strong>kiến trúc vững</strong> của subsystem/component cho nâng cấp suốt đời; nhận diện <strong>module/class chính</strong> cùng interface, trách nhiệm và cộng tác; bảo đảm thiết kế <strong>phủ mọi yêu cầu chức năng và không chức năng thừa</strong>; định mỗi đơn vị với <strong>cohesion mạnh, coupling lỏng, information hiding</strong>; xử <strong>điều kiện ngoại lệ</strong>; đạt <strong>mục tiêu performance/security/chất lượng</strong>; nhận diện <strong>component tái dùng được</strong>; và tôn trọng <strong>ràng buộc</strong> quan trọng. Khi developer gặp mơ hồ, họ nên chuyển ngược về khách/BA qua <strong>issue-tracking process</strong>.</p>`],
      [10, '3. User interface design & the DAR model', `<p>Requirements exploration usually takes tentative steps into UI design — UI is so close to requirements you <strong>shouldn't push it downstream without end-user engagement</strong>. Chapter 15 showed use cases → dialog maps → wireframes/prototypes → detailed UI designs. A <strong>display-action-response (DAR) model</strong> documents the UI elements on each screen and how the system responds to user actions: it combines a <strong>visual screen layout</strong> with <strong>tables describing each element and its behavior under different conditions</strong>. A DAR model has enough detail (Figures 19-4/19-5) that a developer can implement the screen with confidence.</p>`, `<p>Khám phá yêu cầu thường bước dè dặt vào UI design — UI gần yêu cầu đến mức bạn <strong>không nên đẩy nó xuống phía sau mà không có end-user tham gia</strong>. Chương 15 chỉ use case → dialog map → wireframe/prototype → UI design chi tiết. Một <strong>display-action-response (DAR) model</strong> ghi các phần tử UI trên mỗi màn hình và cách hệ thống phản hồi hành động người dùng: nó kết hợp một <strong>bố cục màn hình trực quan</strong> với <strong>bảng mô tả mỗi phần tử và hành vi của nó trong điều kiện khác nhau</strong>. Một DAR model đủ chi tiết (Hình 19-4/19-5) để developer hiện thực màn hình tự tin.</p>`],
      [11, '3. UI design (DAR example)', `<p>Figure 19-4 shows a high-fidelity webpage design and Figure 19-5 its corresponding DAR model — the visual layout paired with behavior tables. Together they bridge "what the screen looks like" and "what it does," which neither a wireframe nor prose alone conveys completely.</p>`, `<p>Hình 19-4 chỉ một thiết kế webpage high-fidelity và Hình 19-5 là DAR model tương ứng — bố cục trực quan ghép với bảng hành vi. Cùng nhau chúng bắc cầu "màn hình trông thế nào" và "nó làm gì," điều mà wireframe hay văn xuôi một mình không truyền đạt trọn.</p>`],
      [12, '4. From requirements to tests', `<p>Requirements analysis and testing fit beautifully: <em>"good requirements engineering produces better tests; good test analysis produces better requirements."</em> The product should be tested against <strong>what it was intended to do (the requirements)</strong>, not its design or code. <strong>Include testers in requirements reviews</strong> so requirements are verifiable. Agile teams often write <strong>acceptance tests in lieu of precise requirements</strong>, fleshing out a story's expected behavior. <strong>Each functional requirement should map to at least one test</strong> so no behavior goes unverified. Early test thinking isn't wasted — conceptual tests transform readily into scenarios/automation, and moving testing earlier yields better requirements, common expectations, and early defect removal.</p>`, `<p>Phân tích yêu cầu và test khớp đẹp: <em>"requirements engineering tốt sinh test tốt hơn; test analysis tốt sinh yêu cầu tốt hơn."</em> Sản phẩm nên được test với <strong>cái nó định làm (yêu cầu)</strong>, không phải thiết kế hay code. <strong>Đưa tester vào review yêu cầu</strong> để yêu cầu kiểm chứng được. Đội agile thường viết <strong>acceptance test thay yêu cầu chính xác</strong>, khai triển hành vi mong đợi của một story. <strong>Mỗi functional requirement nên ánh xạ tới ít nhất một test</strong> để không hành vi nào chưa được verify. Tư duy test sớm không lãng phí — conceptual test dễ biến thành kịch bản/tự động hoá, và đưa test sớm hơn cho yêu cầu tốt hơn, kỳ vọng chung, và bắt lỗi sớm.</p>`],
      [13, '5. From requirements to success', `<p>It's <strong>faster to read the requirements — however extensive — before implementation</strong> than to build the wrong system and build it again correctly; faster still to <strong>engage the development team early</strong> so they join requirements work and do early prototyping or iterative development (they'll still read the whole spec eventually, but spread across the project). The ultimate deliverable is <strong>a solution that meets customers' needs</strong> — requirements are an essential step from business need to satisfied customers; without a foundation of high-quality requirements under your plans, designs and tests, you'll waste effort. But <strong>don't become a slave to the process</strong>: no ritual documents or meetings for their own sake — strike a sensible balance between rigorous specification and off-the-cuff coding that reduces the risk of building the wrong product to an acceptable level.</p>`, `<p><strong>Đọc yêu cầu — dù dài — trước khi hiện thực nhanh hơn</strong> xây sai hệ thống rồi xây lại cho đúng; nhanh hơn nữa là <strong>lôi đội phát triển vào sớm</strong> để họ tham gia việc yêu cầu và làm prototyping sớm hoặc phát triển iterative (họ vẫn phải đọc cả spec cuối cùng, nhưng trải qua dự án). Sản phẩm cuối là <strong>một giải pháp thoả nhu cầu khách</strong> — yêu cầu là bước thiết yếu từ nhu cầu nghiệp vụ tới khách hài lòng; không có nền yêu cầu chất lượng cao dưới kế hoạch, thiết kế và test, bạn sẽ phí công. Nhưng <strong>đừng thành nô lệ của quy trình</strong>: không tài liệu hay họp nghi thức vì chính chúng — cân bằng hợp lý giữa đặc tả nghiêm ngặt và code tuỳ hứng để giảm rủi ro xây sai sản phẩm xuống mức chấp nhận được.</p>`],
    ]),
    books([['wiegers', 'Chapter 19, "From requirements to designs and code" (Figures 19-3/19-4/19-5), "From requirements to tests", "From requirements to success"', 'Chương 19, "From requirements to designs and code" (Hình 19-3/19-4/19-5), "From requirements to tests", "From requirements to success"']]),
  ].join('\n'),
};

export default {
  title: 'Beyond requirements development (book Ch.19)|||Ngoài phát triển yêu cầu (Ch.19 sách)',
  description: 'Chương 19 sách Wiegers: yêu cầu ảnh hưởng cả dự án — ước lượng công sức, từ yêu cầu tới project plan, thiết kế & code (architecture, DAR model), test, và thành công. Tách 2 bài.',
  lessons: [B1, B2],
};
