/**
 * SWR302 · Academy Chapter 2 (Customer's perspective) — slide-by-slide of book
 * chapter Ch.2 "Requirements from the customer's perspective" (34 slides),
 * SPLIT into four focused lessons so no lesson is overloaded:
 *   2.2 The expectation gap & who is the customer   (slides 1–7)
 *   2.3 The customer's Bill of Rights (10)           (slides 8–18)
 *   2.4 The customer's Bill of Responsibilities (10) (slides 19–29)
 *   2.5 Decision makers & reaching agreement         (slides 30–34)
 * Grounded slide-by-slide in CHAPTER_2_Requirement from Customer perspective.pdf.
 * Spliced into academy Chapter 2 before its quiz; existing 2.1 untouched.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* ───────── 2.2 — The expectation gap & who is the customer ───────── */
const L2 = {
  title: '2.2 — Slides: the expectation gap & who is the customer (Ch.2 · 1–7)|||2.2 — Slide: khoảng cách kỳ vọng & khách hàng là ai (Ch.2 · 1–7)',
  slug: 'swr302-2-2-ch2-who-is-customer',
  type: 'DOCUMENT',
  description: 'Slide 1–7: khoảng cách kỳ vọng giữa khách hàng và nhóm phát triển, và phân biệt customer / user (direct & indirect) / stakeholder — ai cung cấp business requirement, ai cung cấp user requirement.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 2 · Lesson 2.2 · Book Ch.2 slides 1–7</span>
<h2>The expectation gap — and who exactly the “customer” is</h2>
<p class="lead">Software succeeds or fails on the customer–development relationship. Before the rights and responsibilities, this lesson pins down the vocabulary that trips people up: <strong>customer vs user vs stakeholder</strong>, and who supplies which level of requirements.</p>`,
      `<span class="eyebrow">Chương 2 · Bài 2.2 · Slide 1–7 sách Ch.2</span>
<h2>Khoảng cách kỳ vọng — và “khách hàng” chính xác là ai</h2>
<p class="lead">Phần mềm thành hay bại nằm ở quan hệ khách hàng–phát triển. Trước khi tới quyền và trách nhiệm, bài này chốt bộ từ vựng hay gây nhầm: <strong>customer vs user vs stakeholder</strong>, và ai cung cấp cấp yêu cầu nào.</p>`,
    ),
    walkHead('ch2', 1, 7),
    walk('ch2', [
      [1, 'Requirements from the customer’s perspective', `<p>Title slide — the chapter takes the customer's point of view on requirements.</p>`, `<p>Slide bìa — chương nhìn yêu cầu từ góc của khách hàng.</p>`],
      [2, 'Objectives', `<p>Understand why the customer–development relationship is critical to success; how to reach agreement on the requirements planned for a release/iteration; and the <strong>Bill of Rights</strong> and <strong>Bill of Responsibilities</strong> that make customer — especially end-user — involvement work.</p>`, `<p>Hiểu vì sao quan hệ khách hàng–phát triển quyết định thành công; cách đạt đồng thuận về yêu cầu cho một release/iteration; và <strong>Bill of Rights</strong> và <strong>Bill of Responsibilities</strong> giúp sự tham gia của khách hàng — nhất là người dùng cuối — thực sự hiệu quả.</p>`],
      [3, 'Contents', `<p>Road map: the expectation gap, who is the customer, the customer–development partnership, the Bill of Rights, the Bill of Responsibilities, creating a culture that respects requirements, identifying decision makers, and reaching agreement. Lessons 2.2–2.5 follow this.</p>`, `<p>Bản đồ: khoảng cách kỳ vọng, khách hàng là ai, quan hệ đối tác khách hàng–phát triển, Bill of Rights, Bill of Responsibilities, tạo văn hoá tôn trọng yêu cầu, xác định người ra quyết định, và đạt đồng thuận. Bài 2.2–2.5 theo đúng đây.</p>`],
      [4, 'The expectation gap', `<p>The core problem: what the customer <em>expects</em> and what the team <em>delivers</em> diverge because needs were never fully shared or understood. Every practice in this chapter exists to close that gap — through participation, clear communication and explicit agreement, not mind-reading.</p>`, `<p>Vấn đề cốt lõi: cái khách hàng <em>kỳ vọng</em> và cái nhóm <em>giao</em> lệch nhau vì nhu cầu chưa từng được chia sẻ hay hiểu đầy đủ. Mọi thực hành trong chương này tồn tại để khép khoảng cách đó — bằng sự tham gia, giao tiếp rõ ràng và đồng thuận tường minh, không phải đoán ý.</p>`],
      [5, 'Who is the customer?', `<p>Section divider (Figure 2-1/2-2): <strong>users are a subset of customers</strong>, and <strong>customers are a subset of stakeholders</strong>. Getting these nested sets right decides whom you must talk to.</p>`, `<p>Slide phân mục (Hình 2-1/2-2): <strong>user là tập con của customer</strong>, và <strong>customer là tập con của stakeholder</strong>. Xác định đúng các tập lồng nhau này quyết định bạn phải nói chuyện với ai.</p>`],
      [6, 'Customers are a subset of stakeholders', `<p>A <strong>customer</strong> derives direct or indirect benefit from the product — someone who requests, pays for, selects, specifies, uses, or receives its output (Figure 2-2: direct/indirect user, executive sponsor, procurement, acquirer). Some stakeholders are <em>not</em> customers (legal staff, compliance auditors, suppliers, contractors, investors). Key: <strong>customers like executive sponsors provide the business requirements</strong> — the framework all other requirements must align to.</p>`, `<p>Một <strong>customer</strong> hưởng lợi trực tiếp hoặc gián tiếp từ sản phẩm — người yêu cầu, chi trả, chọn, đặc tả, dùng, hoặc nhận đầu ra (Hình 2-2: user trực tiếp/gián tiếp, nhà tài trợ điều hành, mua sắm, bên mua). Một số stakeholder <em>không</em> phải customer (pháp chế, kiểm toán tuân thủ, nhà cung cấp, nhà thầu, nhà đầu tư). Then chốt: <strong>customer như nhà tài trợ điều hành cung cấp business requirement</strong> — khung mà mọi yêu cầu khác phải thẳng hàng theo.</p>`],
      [7, 'Users', `<p><strong>Users</strong> (a subset of customers) supply the <em>user requirements</em>. <strong>Direct users</strong> operate the product hands-on; <strong>indirect users</strong> receive its outputs without touching it (e.g. a warehouse manager emailed a daily activity report). Users can describe their tasks, the outputs they need, and the quality characteristics they expect. Reach the real users — not just their managers.</p>`, `<p><strong>User</strong> (tập con của customer) cung cấp <em>user requirement</em>. <strong>User trực tiếp</strong> thao tác sản phẩm; <strong>user gián tiếp</strong> nhận đầu ra mà không chạm vào (vd quản lý kho nhận email báo cáo hoạt động hằng ngày). User mô tả được công việc, đầu ra cần, và đặc tính chất lượng mong đợi. Hãy tiếp cận người dùng thật — không chỉ quản lý của họ.</p>`],
    ]),
    books([['wiegers', 'Chapter 2, "The expectation gap" and "Who is the customer?" (Figures 2-1, 2-2)', 'Chương 2, "The expectation gap" và "Who is the customer?" (Hình 2-1, 2-2)']]),
  ].join('\n'),
};

/* ───────── 2.3 — The customer's Bill of Rights ───────── */
const L3 = {
  title: '2.3 — Slides: the customer’s Requirements Bill of Rights (Ch.2 · 8–18)|||2.3 — Slide: Bill of Rights của khách hàng về yêu cầu (Ch.2 · 8–18)',
  slug: 'swr302-2-3-ch2-bill-of-rights',
  type: 'DOCUMENT',
  description: 'Slide 8–18: 10 quyền của khách hàng phần mềm trong quan hệ với BA/nhóm phát triển — mỗi quyền một slide phân tích (nói ngôn ngữ nghiệp vụ, hiểu business, ghi đúng dạng, giải thích, đổi yêu cầu, tôn trọng, nghe ý tưởng, mô tả dễ dùng, tái sử dụng, nhận hệ thống đạt nhu cầu).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 2 · Lesson 2.3 · Book Ch.2 slides 8–18</span>
<h2>The customer’s Requirements Bill of Rights (ten rights)</h2>
<p class="lead">What a software customer is entitled to expect from the BA and development team. Each right gets its own slide — read them as a checklist you can hold a project to.</p>`,
      `<span class="eyebrow">Chương 2 · Bài 2.3 · Slide 8–18 sách Ch.2</span>
<h2>Bill of Rights của khách hàng về yêu cầu (mười quyền)</h2>
<p class="lead">Những gì một khách hàng phần mềm có quyền mong đợi từ BA và nhóm phát triển. Mỗi quyền một slide — đọc như một checklist để soi một dự án.</p>`,
    ),
    walkHead('ch2', 8, 18),
    walk('ch2', [
      [8, 'The customer–development partnership: 10 rights', `<p>The full list, unpacked one per slide next: expect BAs to (1) speak your language, (2) learn your business, (3) record requirements appropriately, (4) explain practices &amp; deliverables; (5) change your requirements; (6) mutual respect; (7) hear ideas &amp; alternatives; (8) describe usability characteristics; (9) hear reuse options; (10) receive a system that meets your needs.</p>`, `<p>Danh sách đầy đủ, mổ xẻ mỗi slide một quyền: mong BA (1) nói ngôn ngữ của bạn, (2) tìm hiểu nghiệp vụ, (3) ghi yêu cầu đúng dạng, (4) giải thích thực hành &amp; sản phẩm; (5) đổi yêu cầu; (6) tôn trọng lẫn nhau; (7) nghe ý tưởng &amp; phương án; (8) mô tả đặc tính dễ dùng; (9) nghe phương án tái sử dụng; (10) nhận hệ thống đạt nhu cầu.</p>`],
      [9, 'Right #1 — BAs speak your language', `<p>Requirements discussions should center on your <strong>business needs and tasks, in business vocabulary</strong> — not technical jargon. Help by giving the BAs a <strong>glossary</strong> of your terms. If you're wading through tech-speak, the conversation is in the wrong language.</p>`, `<p>Thảo luận yêu cầu phải xoay quanh <strong>nhu cầu và công việc nghiệp vụ, bằng từ vựng nghiệp vụ</strong> — không phải thuật ngữ kỹ thuật. Giúp bằng cách đưa BA một <strong>bảng thuật ngữ (glossary)</strong> của bạn. Nếu bạn phải lội qua tiếng kỹ thuật thì cuộc trò chuyện đang sai ngôn ngữ.</p>`],
      [10, 'Right #2 — BAs learn your business & objectives', `<p>By eliciting from you, BAs understand your tasks and how the system fits your world. <strong>Invite them to observe you at work</strong>; if replacing a system, have them use the current one as you do. Don't assume the BA already knows your operations (pairs with Responsibility #1).</p>`, `<p>Bằng cách khai thác từ bạn, BA hiểu công việc và cách hệ thống khớp vào thế giới của bạn. <strong>Mời họ quan sát bạn làm việc</strong>; nếu thay hệ cũ, cho họ dùng hệ hiện tại như bạn dùng. Đừng cho rằng BA đã biết hoạt động của bạn (đi cặp Trách nhiệm #1).</p>`],
      [11, 'Right #3 — record requirements in an appropriate form', `<p>The BA sorts stakeholder input and asks follow-ups to separate user requirements from business rules, functional requirements and quality goals, producing a refined set stored appropriately (an <strong>SRS</strong> or a requirements tool). That set <strong>is the agreement</strong> among stakeholders; it must be written so <em>you</em> find it easy to understand and review.</p>`, `<p>BA sàng lọc thông tin từ các bên và hỏi thêm để tách user requirement khỏi business rule, yêu cầu chức năng và mục tiêu chất lượng, tạo ra một tập tinh gọn lưu đúng dạng (một <strong>SRS</strong> hoặc công cụ). Tập đó <strong>chính là thoả thuận</strong> giữa các bên; phải viết sao cho <em>bạn</em> thấy dễ hiểu và review được.</p>`],
      [12, 'Right #4 — explanations of practices & deliverables', `<p>The BA should explain the practices recommended and what goes into each deliverable — including any <strong>diagrams</strong> that complement text (their purpose, symbols, how to spot errors). Unfamiliar notations shouldn't be hard to grasp; if the BA doesn't explain, ask.</p>`, `<p>BA nên giải thích các thực hành khuyến nghị và nội dung từng sản phẩm — kể cả các <strong>sơ đồ</strong> bổ trợ cho văn bản (mục đích, ký hiệu, cách tìm lỗi). Ký hiệu lạ không nên khó hiểu; BA không giải thích thì bạn cứ hỏi.</p>`],
      [13, 'Right #5 — change your requirements', `<p>It's unrealistic to expect all requirements up front or that they stay static. You may change requirements as the business evolves or as understanding grows — <strong>but change always has a price</strong> (trade-offs with other functions, schedule or budget). The BA must assess, manage and communicate change impact; agree on a simple, effective change process together.</p>`, `<p>Không thực tế khi đòi mọi yêu cầu ngay từ đầu hoặc bất biến. Bạn được đổi yêu cầu khi nghiệp vụ tiến hoá hoặc hiểu rõ hơn — <strong>nhưng thay đổi luôn có giá</strong> (đánh đổi với chức năng khác, lịch hoặc ngân sách). BA phải đánh giá, quản lý và truyền đạt tác động thay đổi; cùng thống nhất một quy trình thay đổi đơn giản mà hiệu quả.</p>`],
      [14, 'Right #6 — an environment of mutual respect', `<p>The customer–developer relationship can turn adversarial when people don't understand each other. Working together reveals each side's constraints. Customers who participate deserve respect for their time; likewise they should respect the dev team — <strong>everyone is on the same side</strong> aiming at a successful project.</p>`, `<p>Quan hệ khách hàng–lập trình viên dễ thành đối đầu khi hai bên không hiểu nhau. Làm việc cùng nhau cho thấy ràng buộc của mỗi bên. Khách hàng tham gia xứng đáng được tôn trọng thời gian; ngược lại họ nên tôn trọng nhóm phát triển — <strong>tất cả cùng một phía</strong> hướng tới một dự án thành công.</p>`],
      [15, 'Right #7 — hear ideas & alternatives', `<p>Tell the BA where your existing systems don't fit your processes so the new one doesn't automate obsolete ones — avoid <em>“paving the cow paths.”</em> A good BA suggests process improvements and even proposes capabilities you hadn't envisioned.</p>`, `<p>Nói cho BA biết chỗ hệ hiện tại không khớp quy trình để hệ mới không tự động hoá quy trình lỗi thời — tránh <em>“trải nhựa lối mòn của bò.”</em> Một BA giỏi gợi ý cải tiến quy trình và cả đề xuất năng lực bạn chưa hình dung.</p>`],
      [16, 'Right #8 — describe usability characteristics', `<p>Expect BAs to ask about <strong>quality attributes</strong> beyond functions. Vague words like “user-friendly” or “robust” are too subjective — the BA should draw out the <em>specific</em> characteristics you mean, using examples from your current apps of what feels friendly and what doesn't. Skip this and you'll only be lucky if the product feels right.</p>`, `<p>Mong BA hỏi về <strong>thuộc tính chất lượng</strong> ngoài chức năng. Từ mơ hồ như “dễ dùng” hay “bền” quá chủ quan — BA nên moi ra đặc tính <em>cụ thể</em> bạn muốn, dùng ví dụ từ ứng dụng hiện tại về cái gì thấy thân thiện và cái gì không. Bỏ qua thì sản phẩm hợp ý chỉ là may rủi.</p>`],
      [17, 'Right #9 — hear reuse options', `<p>Requirements are often flexible. The BA might know of existing components or requirements that partly match your need; adjusting slightly to reuse them can <strong>accelerate development and cut cost</strong>. Be open to small changes that unlock reuse (Chapter 18).</p>`, `<p>Yêu cầu thường linh hoạt. BA có thể biết các thành phần hoặc yêu cầu sẵn có khớp một phần nhu cầu; chỉnh nhẹ để tái dùng có thể <strong>đẩy nhanh phát triển và giảm chi phí</strong>. Hãy cởi mở với thay đổi nhỏ mở khoá tái sử dụng (Chương 18).</p>`],
      [18, 'Right #10 — receive a system that meets your needs', `<p>The ultimate right — but conditional: it happens only if <em>you</em> communicate all the information developers need, developers communicate options and constraints, and both reach agreement. <strong>State your assumptions and expectations</strong>; validating a shared understanding matters as much as stating something new.</p>`, `<p>Quyền tối thượng — nhưng có điều kiện: chỉ xảy ra nếu <em>bạn</em> cung cấp đủ thông tin nhóm cần, nhóm truyền đạt phương án và ràng buộc, và cả hai đạt đồng thuận. <strong>Nêu rõ giả định và kỳ vọng</strong>; xác nhận một hiểu biết chung quan trọng ngang với nói ra điều mới.</p>`],
    ]),
    books([['wiegers', 'Chapter 2, "The customer–development partnership" — the Bill of Rights (rights 1–10)', 'Chương 2, "The customer–development partnership" — Bill of Rights (quyền 1–10)']]),
  ].join('\n'),
};

/* ───────── 2.4 — The customer's Bill of Responsibilities ───────── */
const L4 = {
  title: '2.4 — Slides: the customer’s Requirements Bill of Responsibilities (Ch.2 · 19–29)|||2.4 — Slide: Bill of Responsibilities của khách hàng (Ch.2 · 19–29)',
  slug: 'swr302-2-4-ch2-bill-of-responsibilities',
  type: 'DOCUMENT',
  description: 'Slide 19–29: 10 trách nhiệm của khách hàng — mỗi cái một slide (giáo dục BA về nghiệp vụ, dành thời gian, cụ thể-chính xác, quyết định kịp thời, tôn trọng đánh giá chi phí/khả thi, đặt ưu tiên thực tế, review & đánh giá prototype, lập acceptance criteria, báo thay đổi kịp, tôn trọng quy trình).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 2 · Lesson 2.4 · Book Ch.2 slides 19–29</span>
<h2>The customer’s Requirements Bill of Responsibilities (ten duties)</h2>
<p class="lead">Rights come with duties. These ten are what a customer owes the project — the other half of closing the expectation gap. Each responsibility gets its own slide.</p>`,
      `<span class="eyebrow">Chương 2 · Bài 2.4 · Slide 19–29 sách Ch.2</span>
<h2>Bill of Responsibilities của khách hàng (mười trách nhiệm)</h2>
<p class="lead">Có quyền thì có nghĩa vụ. Mười điều này là những gì khách hàng nợ dự án — nửa còn lại để khép khoảng cách kỳ vọng. Mỗi trách nhiệm một slide.</p>`,
    ),
    walkHead('ch2', 19, 29),
    walk('ch2', [
      [19, 'The partnership: 10 responsibilities', `<p>The list, one per slide next: (1) educate BAs about your business, (2) dedicate time, (3) be specific and precise, (4) make timely decisions, (5) respect cost/feasibility assessments, (6) set realistic priorities, (7) review requirements &amp; evaluate prototypes, (8) establish acceptance criteria, (9) promptly communicate changes, (10) respect the requirements process.</p>`, `<p>Danh sách, mỗi slide một trách nhiệm: (1) giáo dục BA về nghiệp vụ, (2) dành thời gian, (3) cụ thể và chính xác, (4) quyết định kịp thời, (5) tôn trọng đánh giá chi phí/khả thi, (6) đặt ưu tiên thực tế, (7) review yêu cầu &amp; đánh giá prototype, (8) lập acceptance criteria, (9) báo thay đổi kịp thời, (10) tôn trọng quy trình yêu cầu.</p>`],
      [20, 'Responsibility #1 — educate BAs about your business', `<p>The team depends on you to explain your business concepts and jargon. The goal isn't to turn BAs into business experts, but to help them understand your problems and objectives — they can't know what you and your peers take for granted.</p>`, `<p>Nhóm dựa vào bạn để giải thích khái niệm và thuật ngữ nghiệp vụ. Mục tiêu không phải biến BA thành chuyên gia nghiệp vụ, mà giúp họ hiểu bài toán và mục tiêu của bạn — họ không thể biết những gì bạn và đồng nghiệp coi là hiển nhiên.</p>`],
      [21, 'Responsibility #2 — dedicate the time it takes', `<p>Requirements people are often the busiest, but you must give time to workshops, interviews and validation. Expect an <strong>iterative</strong> approach (the BA may need to re-clarify) — be patient. Focused effort for a few hours beats time scattered in bits over weeks.</p>`, `<p>Người làm yêu cầu thường bận nhất, nhưng bạn phải dành thời gian cho workshop, phỏng vấn và validation. Chấp nhận cách làm <strong>lặp</strong> (BA có thể cần làm rõ lại) — hãy kiên nhẫn. Tập trung vài giờ hơn là rải rác từng chút suốt nhiều tuần.</p>`],
      [22, 'Responsibility #3 — be specific and precise', `<p>Vague requirements are tempting (details are tedious, or someone avoids accountability), but ambiguity must be resolved eventually — and <strong>you</strong> are the best person to decide, not developers guessing. <strong>TBD</strong> markers are fine to flag needed exploration, but don't let TBD hide a hard decision no one will make.</p>`, `<p>Yêu cầu mơ hồ rất cám dỗ (chi tiết thì mệt, hoặc ai đó né trách nhiệm), nhưng mơ hồ rồi cũng phải giải — và <strong>bạn</strong> là người quyết tốt nhất, không phải lập trình viên đoán. Dấu <strong>TBD</strong> ổn để đánh dấu chỗ cần tìm hiểu thêm, nhưng đừng để TBD giấu một quyết định khó không ai chịu làm.</p>`],
      [23, 'Responsibility #4 — make timely decisions', `<p>Like a contractor building your house, the BA will ask you to decide many things — resolving conflicting requests, choosing between incompatible quality attributes, judging accuracy. Authorised customers must decide <strong>promptly</strong>; developers often can't proceed until you do. Ask the BA to help you think it through if stuck.</p>`, `<p>Như nhà thầu xây nhà cho bạn, BA sẽ nhờ bạn quyết nhiều thứ — giải xung đột yêu cầu, chọn giữa các thuộc tính chất lượng khắc nhau, đánh giá độ chính xác. Khách hàng có thẩm quyền phải quyết <strong>kịp thời</strong>; nhóm thường không tiến được tới khi bạn quyết. Bí thì nhờ BA giúp suy nghĩ.</p>`],
      [24, 'Responsibility #5 — respect cost & feasibility assessments', `<p>Every function has a cost, and developers estimate it best. Some features aren't technically feasible or are surprisingly expensive. Respect that judgment even if you don't get exactly what you envisioned — and consider <strong>rewriting a requirement to make it attainable</strong> (e.g. “instantaneously” → “within 50 ms”).</p>`, `<p>Mọi chức năng có giá, và lập trình viên ước lượng tốt nhất. Vài tính năng bất khả thi kỹ thuật hoặc đắt bất ngờ. Tôn trọng phán đoán đó dù không được đúng như hình dung — và cân nhắc <strong>viết lại yêu cầu cho khả thi</strong> (vd “tức thì” → “trong 50 ms”).</p>`],
      [25, 'Responsibility #6 — set realistic priorities', `<p>Few projects can build everything. You lead on priorities (developers add cost/risk info) to help deliver <strong>maximum value at lowest cost at the right time</strong> — essential on agile. If it doesn't all fit, decision makers cut scope, extend schedule, or add resources. <strong>Declaring everything “high priority” is neither realistic nor collaborative.</strong></p>`, `<p>Ít dự án làm được mọi thứ. Bạn dẫn dắt ưu tiên (lập trình viên bổ sung chi phí/rủi ro) để giao <strong>giá trị cao nhất, chi phí thấp nhất, đúng lúc</strong> — thiết yếu với agile. Không vừa hết thì người quyết cắt phạm vi, kéo lịch, hoặc thêm nguồn lực. <strong>Gán mọi yêu cầu “ưu tiên cao” là không thực tế và không hợp tác.</strong></p>`],
      [26, 'Responsibility #7 — review requirements & evaluate prototypes', `<p><strong>Peer review</strong> is one of the most powerful quality activities. Customer participation checks whether requirements are complete, correct and necessary. The BA should hand you requirements in <strong>manageable chunks</strong> throughout — not a giant tome at the end. Evaluate <strong>prototypes</strong> too: your feedback on partial implementations is gold.</p>`, `<p><strong>Peer review</strong> là một trong những hoạt động chất lượng mạnh nhất. Khách hàng tham gia kiểm được yêu cầu có đầy đủ, đúng và cần thiết không. BA nên đưa yêu cầu theo <strong>từng phần vừa sức</strong> suốt quá trình — không dồn một tập khổng lồ ở cuối. Đánh giá cả <strong>prototype</strong>: phản hồi của bạn về bản hiện thực một phần là vàng.</p>`],
      [27, 'Responsibility #8 — establish acceptance criteria', `<p>How do developers know they're done? You define <strong>acceptance criteria</strong> — predefined conditions the product must satisfy — including <strong>acceptance tests</strong> that check users can do key business operations correctly, plus criteria on defect levels, performance, or external certification. Agile leans heavily on acceptance tests to flesh out user-story details.</p>`, `<p>Làm sao lập trình viên biết đã xong? Bạn định nghĩa <strong>acceptance criteria</strong> — điều kiện định trước sản phẩm phải đạt — gồm <strong>acceptance test</strong> kiểm người dùng làm đúng các thao tác nghiệp vụ chính, cộng tiêu chí về mức lỗi, hiệu năng, hoặc chứng nhận bên ngoài. Agile dựa nhiều vào acceptance test để làm rõ chi tiết user story.</p>`],
      [28, 'Responsibility #9 — promptly communicate changes', `<p>Constantly changing requirements risk on-time, high-quality delivery. Change is inevitable and often valuable, but <strong>the later it comes, the bigger the impact</strong>. Notify the BA the moment you know, and route it through the project's <strong>change-control process</strong> so no change is lost and every impact is analysed consistently.</p>`, `<p>Yêu cầu đổi liên tục đe doạ giao đúng hạn, chất lượng cao. Thay đổi là tất yếu và thường có giá trị, nhưng <strong>càng muộn, tác động càng lớn</strong>. Báo BA ngay khi biết, và đưa qua <strong>quy trình kiểm soát thay đổi</strong> của dự án để không mất thay đổi nào và mọi tác động được phân tích nhất quán.</p>`],
      [29, 'Responsibility #10 — respect the requirements process', `<p>Eliciting and specifying requirements is one of the hardest parts of software; there's a rationale behind the BA's approach. It's an excellent investment even when frustrating, and less painful if you respect the techniques. Ask the BA <em>why</em> they need certain information — mutual understanding makes the collaboration effective, even enjoyable.</p>`, `<p>Khai thác và đặc tả yêu cầu là một trong những phần khó nhất; có lý do sau cách làm của BA. Đó là khoản đầu tư tuyệt vời dù đôi lúc bực bội, và bớt đau nếu bạn tôn trọng kỹ thuật. Cứ hỏi BA <em>vì sao</em> họ cần thông tin nào đó — hiểu nhau làm cộng tác hiệu quả, thậm chí dễ chịu.</p>`],
    ]),
    books([['wiegers', 'Chapter 2, "The customer–development partnership" — the Bill of Responsibilities (1–10)', 'Chương 2, "The customer–development partnership" — Bill of Responsibilities (1–10)']]),
  ].join('\n'),
};

/* ───────── 2.5 — Decision makers & reaching agreement ───────── */
const L5 = {
  title: '2.5 — Slides: identifying decision makers & reaching agreement (Ch.2 · 30–34)|||2.5 — Slide: xác định người ra quyết định & đạt đồng thuận (Ch.2 · 30–34)',
  slug: 'swr302-2-5-ch2-agreement',
  type: 'DOCUMENT',
  description: 'Slide 30–34: xác định người ra quyết định & các luật ra quyết định, đạt đồng thuận trên yêu cầu (baseline, sign-off là cột mốc không phải vũ khí), xử lý khi không đồng thuận, và đồng thuận trên dự án Agile.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 2 · Lesson 2.5 · Book Ch.2 slides 30–34</span>
<h2>Decision makers & reaching agreement on requirements</h2>
<p class="lead">Requirements aren't done until the right people agree. This lesson covers <strong>who decides</strong> (decision leader + decision rule), what agreement means, the <strong>requirements baseline</strong>, what to do when you can't get sign-off, and how agile handles it.</p>`,
      `<span class="eyebrow">Chương 2 · Bài 2.5 · Slide 30–34 sách Ch.2</span>
<h2>Người ra quyết định & đạt đồng thuận trên yêu cầu</h2>
<p class="lead">Yêu cầu chưa xong tới khi đúng người đồng thuận. Bài này nói <strong>ai quyết</strong> (decision leader + luật quyết định), đồng thuận nghĩa là gì, <strong>requirements baseline</strong>, làm gì khi không lấy được sign-off, và Agile xử lý ra sao.</p>`,
    ),
    walkHead('ch2', 30, 34),
    walk('ch2', [
      [30, 'Identifying decision makers', `<p>Name the <strong>decision leader</strong> and agree a <strong>decision rule</strong> up front: the leader decides (with/without discussion); majority vote; unanimous vote; consensus (everyone can live with it and commits); the leader delegates to one person; or the group decides but someone holds veto. Deciding <em>how</em> you'll decide prevents deadlock later.</p>`, `<p>Chỉ định <strong>decision leader</strong> và thống nhất <strong>luật quyết định</strong> từ đầu: leader quyết (có/không thảo luận); đa số; nhất trí tuyệt đối; đồng thuận (mọi người chấp nhận và cam kết); leader uỷ quyền cho một người; hoặc nhóm quyết nhưng một người có quyền phủ quyết. Quyết <em>cách</em> quyết ngăn bế tắc về sau.</p>`],
      [31, 'Reaching agreement on requirements', `<p>Agreement means: <strong>customers</strong> agree the requirements address their needs; <strong>developers</strong> agree they understand and they're feasible; <strong>testers</strong> agree they're verifiable; <strong>management</strong> agrees they'll achieve the business objectives. Coming up: the baseline, no-agreement, and agile. <em>Important: don't use sign-off as a weapon — treat it as a milestone with a shared understanding of what it implies for future changes.</em></p>`, `<p>Đồng thuận nghĩa là: <strong>khách hàng</strong> đồng ý yêu cầu đáp ứng nhu cầu; <strong>lập trình viên</strong> đồng ý đã hiểu và khả thi; <strong>tester</strong> đồng ý kiểm chứng được; <strong>quản lý</strong> đồng ý đạt mục tiêu nghiệp vụ. Sắp tới: baseline, không đồng thuận, và agile. <em>Quan trọng: đừng dùng sign-off làm vũ khí — coi nó là cột mốc với hiểu biết chung về hệ quả cho thay đổi sau này.</em></p>`],
      [32, 'The requirements baseline', `<p>More important than the sign-off ritual: a <strong>baseline</strong> is a set of requirements reviewed and agreed at a point in time, serving as the basis for further development. Its subtext: <em>“this represents our best understanding today; future changes go through the defined change process; changes may force renegotiating cost, resources and schedule.”</em> Some teams print exactly this on the signature page so approvers know what sign-off means.</p>`, `<p>Quan trọng hơn nghi thức sign-off: một <strong>baseline</strong> là tập yêu cầu đã review và đồng thuận tại một thời điểm, làm cơ sở phát triển tiếp. Ngụ ý của nó: <em>“đây là hiểu biết tốt nhất hôm nay; thay đổi sau đi qua quy trình thay đổi đã định; thay đổi có thể buộc thương lượng lại chi phí, nguồn lực và lịch.”</em> Vài nhóm in đúng câu này trên trang ký để người duyệt biết sign-off nghĩa là gì.</p>`],
      [33, 'What if you don’t reach agreement?', `<p>Full sign-off is hard (logistics, busy schedules, reluctance to be accountable). The “reply-by-Friday-or-I-assume-you-agree” email really equals <em>not</em> agreeing. Better: understand why they're uncomfortable and address it; then move forward <strong>cautiously</strong> assuming no approval — record the non-sign-off and its likely impact in your <strong>risk list</strong>, keep following up, and tell them the project proceeds on this baseline with a process available to change things.</p>`, `<p>Sign-off đủ là khó (hậu cần, lịch bận, ngại chịu trách nhiệm). Email “trả lời trước thứ Sáu, không thì coi như đồng ý” thực ra là <em>không</em> đồng ý. Tốt hơn: hiểu vì sao họ chưa yên tâm và xử lý; rồi tiến tới <strong>thận trọng</strong> giả định chưa có duyệt — ghi việc chưa sign-off và tác động có thể có vào <strong>risk list</strong>, tiếp tục theo dõi, và báo họ dự án tiến trên baseline này với một quy trình sẵn để đổi.</p>`],
      [34, 'Agreeing on requirements on agile projects', `<p>Agile has <strong>no formal sign-off</strong>. Requirements live as user stories in a <strong>product backlog</strong>. Each iteration, the product owner and team agree in a planning session which stories to build, chosen by priority and team <strong>velocity</strong>; that set is then <strong>frozen</strong> for the iteration and new requests go to future iterations. There's no up-front approval of the full scope — but the vision and business requirements still must be set at the outset.</p>`, `<p>Agile <strong>không có sign-off chính thức</strong>. Yêu cầu tồn tại dạng user story trong <strong>product backlog</strong>. Mỗi iteration, product owner và nhóm thống nhất trong buổi planning story nào sẽ làm, chọn theo ưu tiên và <strong>velocity</strong> của nhóm; tập đó rồi được <strong>đóng băng</strong> cho iteration và yêu cầu mới đẩy sang iteration sau. Không duyệt trước toàn bộ phạm vi — nhưng tầm nhìn và business requirement vẫn phải đặt từ đầu.</p>`],
    ]),
    books([
      ['wiegers', 'Chapter 2, "Identifying decision makers" and "Reaching agreement on requirements" (baseline, sign-off, agile)', 'Chương 2, "Identifying decision makers" và "Reaching agreement on requirements" (baseline, sign-off, agile)'],
      ['cos', 'the COS Vision &amp; Scope names its stakeholders and decision makers — a real example of this chapter', 'COS Vision &amp; Scope nêu tên các bên liên quan và người quyết — ví dụ thật của chương này'],
    ]),
  ].join('\n'),
};

export default [L2, L3, L4, L5];
