/**
 * SWR302 · Academy Chapter 9 (Agile requirements) additions — book chapter Ch.20
 * "Agile" (17 slides), split into THREE focused lessons: waterfall limits + the
 * agile approach (1–7), essential aspects I — customer/docs/backlog (8–11), and
 * essential aspects II + transitioning (12–17). Exported as an array spliced into
 * academy Chapter 9 before its quiz. Grounded slide-by-slide in
 * CHAPTER_20_Agile.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 9.2 — waterfall limits & the agile approach */
const A1 = {
  title: '9.2 — Slides: waterfall limits & the agile approach (Ch.20 · 1–7)|||9.2 — Slide: giới hạn waterfall & cách tiếp cận agile (Ch.20 · 1–7)',
  slug: 'swr302-9-2-ch20-waterfall-agile',
  type: 'DOCUMENT',
  description: 'Slide 1–7: giới hạn của waterfall (chốt hết yêu cầu sớm, khó đáp ứng thay đổi, dự án lớn hay trễ/thiếu tính năng); và cách tiếp cận agile (iteration/sprint ngắn, thêm chức năng nhỏ theo ưu tiên khách, khách tham gia liên tục, mỗi iteration cho phần mềm có thể ship).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 9 · Lesson 9.2 · Book Ch.20 slides 1–7</span>
<h2>Waterfall limits &amp; the agile approach</h2>
<p class="lead">Waterfall tries to get the full requirement set "right" up front — but stakeholders change their minds, and long dependency chains make late change expensive. Agile answers with short iterations, continuous customer involvement, and shippable software at the end of each cycle.</p>`,
      `<span class="eyebrow">Chương 9 · Bài 9.2 · Slide 1–7 sách Ch.20</span>
<h2>Giới hạn waterfall &amp; cách tiếp cận agile</h2>
<p class="lead">Waterfall cố chốt cả tập yêu cầu "đúng" từ đầu — nhưng stakeholder đổi ý, và chuỗi phụ thuộc dài làm thay đổi muộn tốn kém. Agile đáp bằng iteration ngắn, khách tham gia liên tục, và phần mềm ship được ở cuối mỗi chu kỳ.</p>`,
    ),
    walkHead('ch20', 1, 7),
    walk('ch20', [
      [1, 'Agile', `<p>Title slide — the characteristics of agile approaches as they relate to requirements activities, the major adaptations of traditional practices for agile, and a road map to more detailed guidance.</p>`, `<p>Slide bìa — đặc điểm của cách tiếp cận agile khi liên quan đến hoạt động yêu cầu, các điều chỉnh lớn của thực hành truyền thống cho agile, và một bản đồ tới hướng dẫn chi tiết hơn.</p>`],
      [2, 'Objectives', `<p>Describe agile characteristics relating to requirements activities, the major adaptations of traditional requirements practices for agile, and a road map of where to find more detailed guidance; recognize what to do at every stage of an agile project.</p>`, `<p>Mô tả đặc điểm agile liên quan hoạt động yêu cầu, các điều chỉnh lớn của thực hành yêu cầu truyền thống cho agile, và bản đồ nơi tìm hướng dẫn chi tiết hơn; nhận ra làm gì ở mỗi giai đoạn dự án agile.</p>`],
      [3, 'Contents', `<p>Five topics: limitations of the waterfall, the agile development approach, essential aspects of an agile approach to requirements, adapting requirements practices to agile, and transitioning to agile. Lessons 9.2–9.4 cover them.</p>`, `<p>Năm chủ đề: giới hạn của waterfall, cách tiếp cận phát triển agile, các khía cạnh thiết yếu của agile với yêu cầu, điều chỉnh thực hành yêu cầu cho agile, và chuyển sang agile. Bài 9.2–9.4 phủ chúng.</p>`],
      [4, 'Limitations of the waterfall — the questions', `<p>Frame waterfall by asking: what is it, its advantages, its disadvantages, and when to use it. It's a linear sequence — fully specify requirements, then design, then code, then test — with the appeal of catching flaws <strong>early</strong>, when fixing is cheaper than during construction/testing/maintenance. The next slide examines why it struggles in practice.</p>`, `<p>Khung waterfall bằng cách hỏi: nó là gì, ưu điểm, nhược điểm, và khi nào dùng. Nó là một chuỗi tuyến tính — đặc tả đủ yêu cầu, rồi thiết kế, rồi code, rồi test — với sức hút bắt lỗi <strong>sớm</strong>, khi sửa rẻ hơn lúc xây/test/bảo trì. Slide sau soi vì sao nó chật vật trong thực tế.</p>`],
      [5, 'Why the waterfall struggles', `<p>Few projects are purely sequential — there's always overlap and feedback — but waterfall teams put heavy effort into getting the full requirement set "right" early. A key differentiator across the predictive↔adaptive spectrum is the <strong>time between when a requirement is created and when software based on it reaches customers</strong>. Large waterfall projects are often <strong>delivered late, lack needed features, and miss expectations</strong> because of the layers of dependency built on the requirements. Stakeholders <strong>will change requirements</strong> — they don't know precisely what they want at the start, can sometimes articulate their vision only after seeing something that <em>doesn't</em> match it, and business needs shift mid-project.</p>`, `<p>Ít dự án thuần tuần tự — luôn có chồng lấn và phản hồi — nhưng đội waterfall dồn nhiều công để chốt cả tập yêu cầu "đúng" sớm. Một khác biệt then chốt trên phổ predictive↔adaptive là <strong>thời gian giữa khi một yêu cầu được tạo và khi phần mềm dựa trên nó tới khách</strong>. Dự án waterfall lớn thường <strong>giao trễ, thiếu tính năng cần, và trượt kỳ vọng</strong> vì các tầng phụ thuộc dựng trên yêu cầu. Stakeholder <strong>sẽ đổi yêu cầu</strong> — họ không biết chính xác muốn gì lúc đầu, đôi khi chỉ diễn đạt được tầm nhìn sau khi thấy cái <em>không</em> khớp, và nhu cầu nghiệp vụ đổi giữa dự án.</p>`],
      [6, 'The agile development approach', `<p>Agile methods address waterfall's limits with <strong>iterative and incremental development</strong> — breaking work into short cycles called <strong>iterations</strong> (or <strong>sprints</strong> in Scrum), one week to a month. Each iteration adds a <strong>small set of functionality</strong> based on the customer's priorities, tests it, and validates it against customer <strong>acceptance criteria</strong>. Later increments modify what exists, enrich features, add new ones, and fix defects. <strong>Ongoing customer participation</strong> lets the team spot problems and direction changes early, correcting course before going far down the wrong path. The goal: <strong>potentially shippable software at the end of every iteration</strong>, even if it's only a small part of the final product.</p>`, `<p>Phương pháp agile giải giới hạn của waterfall bằng <strong>phát triển iterative và incremental</strong> — chia việc thành chu kỳ ngắn gọi <strong>iteration</strong> (hay <strong>sprint</strong> trong Scrum), một tuần tới một tháng. Mỗi iteration thêm một <strong>tập chức năng nhỏ</strong> theo ưu tiên của khách, test nó, và thẩm định với <strong>acceptance criteria</strong> của khách. Increment sau sửa cái đã có, làm giàu tính năng, thêm mới, và sửa lỗi. <strong>Khách tham gia liên tục</strong> giúp đội thấy vấn đề và đổi hướng sớm, chỉnh trước khi đi xa đường sai. Mục tiêu: <strong>phần mềm có thể ship ở cuối mỗi iteration</strong>, kể cả khi chỉ là một phần nhỏ sản phẩm cuối.</p>`],
      [7, 'When agile fits', `<p>Agile shines when requirements are <strong>uncertain or expected to evolve</strong>, when customers can be <strong>continuously available</strong>, and when delivering value <strong>incrementally and early</strong> matters. It shortens the gap between creating a requirement and delivering software from it — the very gap that makes waterfall brittle. But agile isn't "no requirements" or "no discipline"; it's the same requirements activities, redistributed and done just-in-time — which the essential aspects (next lessons) make concrete.</p>`, `<p>Agile toả sáng khi yêu cầu <strong>bất định hoặc dự kiến tiến hoá</strong>, khi khách có thể <strong>sẵn sàng liên tục</strong>, và khi giao giá trị <strong>tăng dần và sớm</strong> là quan trọng. Nó rút ngắn khoảng cách giữa tạo một yêu cầu và giao phần mềm từ nó — chính khoảng cách làm waterfall giòn. Nhưng agile không phải "không yêu cầu" hay "không kỷ luật"; nó là cùng các hoạt động yêu cầu, phân bố lại và làm đúng-lúc-cần — điều mà các khía cạnh thiết yếu (bài sau) cụ thể hoá.</p>`],
    ]),
    books([['wiegers', 'Chapter 20, "Limitations of the waterfall", "The agile development approach"', 'Chương 20, "Limitations of the waterfall", "The agile development approach"']]),
  ].join('\n'),
};

/* 9.3 — essential aspects I */
const A2 = {
  title: '9.3 — Slides: agile requirements — customer, docs & backlog (Ch.20 · 8–11)|||9.3 — Slide: yêu cầu agile — khách, tài liệu & backlog (Ch.20 · 8–11)',
  slug: 'swr302-9-3-ch20-essentials-1',
  type: 'DOCUMENT',
  description: 'Slide 8–11: các khía cạnh thiết yếu (phần 1) — customer involvement (khách/product owner tham gia liên tục, ai viết story cũng cần BA review); documentation detail (ít tài liệu hơn nhưng KHÔNG phải không viết — tối thiểu đủ dẫn dev/test); backlog & prioritization (một backlog duy nhất, ưu tiên liên tục, truy về business requirement).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 9 · Lesson 9.3 · Book Ch.20 slides 8–11</span>
<h2>Agile requirements: customer, documentation &amp; backlog</h2>
<p class="lead">Three of the six essential aspects. Customers are involved continuously, not just up front. Documentation is lighter — but agile does <em>not</em> mean writing no requirements. And a single prioritized backlog drives what the team builds next.</p>`,
      `<span class="eyebrow">Chương 9 · Bài 9.3 · Slide 8–11 sách Ch.20</span>
<h2>Yêu cầu agile: khách, tài liệu &amp; backlog</h2>
<p class="lead">Ba trong sáu khía cạnh thiết yếu. Khách tham gia liên tục, không chỉ lúc đầu. Tài liệu nhẹ hơn — nhưng agile <em>không</em> nghĩa là không viết yêu cầu. Và một backlog ưu tiên duy nhất dẫn dắt đội xây gì tiếp.</p>`,
    ),
    walkHead('ch20', 8, 11),
    walk('ch20', [
      [8, 'Essential aspects — overview', `<p>Six essential aspects of an agile approach to requirements: <strong>customer involvement</strong>, <strong>documentation detail</strong>, <strong>the backlog and prioritization</strong>, <strong>timing</strong>, <strong>epics/user stories/features</strong>, and <strong>expect change</strong>. This lesson covers the first three; the next covers the rest.</p>`, `<p>Sáu khía cạnh thiết yếu của agile với yêu cầu: <strong>customer involvement</strong>, <strong>documentation detail</strong>, <strong>backlog và prioritization</strong>, <strong>timing</strong>, <strong>epic/user story/feature</strong>, và <strong>expect change</strong>. Bài này phủ ba cái đầu; bài sau phủ phần còn lại.</p>`],
      [9, '1. Customer involvement', `<p>Collaboration boosts success on any project — the difference is <strong>timing</strong>. On <strong>waterfall</strong>, customers invest heavily up front and again at UAT, but little during construction, so adapting to change is hard. On <strong>agile</strong>, customers (or a <strong>product owner</strong> representing them) are engaged <strong>continuously</strong>: an initial planning iteration identifies and prioritizes user stories as a preliminary road map, and because stories are less detailed than traditional requirements, customers must stay available during iterations to clarify and to test/give feedback on new features. Product owners, customers and end users often write stories — but they may not be trained in requirements methods, so <strong>someone with solid BA skills should review and edit the stories</strong> before implementation.</p>`, `<p>Cộng tác tăng thành công ở mọi dự án — khác biệt là <strong>thời điểm</strong>. Ở <strong>waterfall</strong>, khách đầu tư nhiều lúc đầu và lại ở UAT, nhưng ít khi xây, nên khó đáp ứng thay đổi. Ở <strong>agile</strong>, khách (hoặc một <strong>product owner</strong> đại diện) tham gia <strong>liên tục</strong>: một iteration lập kế hoạch đầu nhận diện và ưu tiên user story làm road map sơ bộ, và vì story ít chi tiết hơn yêu cầu truyền thống, khách phải sẵn sàng trong iteration để làm rõ và test/phản hồi tính năng mới. Product owner, khách và end user thường viết story — nhưng có thể chưa được huấn luyện phương pháp yêu cầu, nên <strong>người có kỹ năng BA vững nên review và sửa story</strong> trước khi hiện thực.</p>`],
      [10, '2. Documentation detail', `<p>On waterfall, with little customer interaction after construction begins, requirements must specify behavior, data relationships and UX in <strong>considerable detail</strong>. On agile, close customer collaboration means requirements can be documented in <strong>less detail</strong> — precision develops through <strong>conversations and just-in-time documentation</strong>. But it's a myth that agile teams don't write requirements: agile encourages the <strong>minimum documentation needed to accurately guide developers and testers</strong>. Anything beyond what dev/test need (or what regulations/standards require) is <strong>wasted effort</strong>; some stories carry little detail, with only the riskiest/highest-impact functionality specified further, typically as <strong>acceptance tests</strong>.</p>`, `<p>Ở waterfall, ít tương tác khách sau khi bắt đầu xây, yêu cầu phải đặc tả hành vi, quan hệ dữ liệu và UX <strong>khá chi tiết</strong>. Ở agile, cộng tác khách sát nghĩa là yêu cầu được ghi <strong>ít chi tiết hơn</strong> — độ chính xác phát triển qua <strong>trò chuyện và tài liệu đúng-lúc</strong>. Nhưng là hiểu lầm rằng đội agile không viết yêu cầu: agile khuyến khích <strong>tài liệu tối thiểu đủ dẫn chính xác developer và tester</strong>. Bất cứ gì ngoài cái dev/test cần (hoặc quy định/chuẩn đòi) là <strong>công lãng phí</strong>; vài story mang ít chi tiết, chỉ chức năng rủi ro/tác động cao nhất được đặc tả thêm, thường dạng <strong>acceptance test</strong>.</p>`],
      [11, '3. The backlog and prioritization', `<p>The <strong>product backlog</strong> lists work the team might do — usually user stories, sometimes also other requirements, business processes and defects. Keep <strong>only one backlog</strong>, so defects may need to be represented there for prioritization against new stories (some teams rewrite defects as stories). Backlogs live on <strong>story cards or in tools</strong> — purists prefer cards, but cards don't scale to large or distributed teams, where agile PM/backlog tools help. <strong>Prioritization is ongoing</strong>: choose which items enter upcoming iterations and which are discarded; priorities need only hold <strong>for the next iteration</strong>. Tracing backlog items <strong>back to business requirements</strong> aids prioritization — and every project, not just agile ones, should manage its remaining backlog's priorities.</p>`, `<p><strong>Product backlog</strong> liệt kê việc đội có thể làm — thường là user story, đôi khi cả yêu cầu khác, quy trình nghiệp vụ và lỗi. Giữ <strong>chỉ một backlog</strong>, nên lỗi có thể cần biểu diễn ở đó để ưu tiên so với story mới (vài đội viết lại lỗi thành story). Backlog nằm trên <strong>thẻ story hoặc trong công cụ</strong> — người thuần tuý thích thẻ, nhưng thẻ không mở rộng cho đội lớn hoặc phân tán, nơi công cụ PM/backlog agile giúp. <strong>Ưu tiên là liên tục</strong>: chọn mục nào vào iteration tới và mục nào bỏ; ưu tiên chỉ cần đúng <strong>cho iteration kế</strong>. Truy mục backlog <strong>về business requirement</strong> hỗ trợ ưu tiên — và mọi dự án, không chỉ agile, nên quản lý ưu tiên backlog còn lại.</p>`],
    ]),
    books([['wiegers', 'Chapter 20, "Essential aspects of an agile approach to requirements" — customer involvement, documentation detail, the backlog and prioritization', 'Chương 20, "Essential aspects of an agile approach to requirements" — customer involvement, documentation detail, the backlog and prioritization']]),
  ].join('\n'),
};

/* 9.4 — essential aspects II & transitioning */
const A3 = {
  title: '9.4 — Slides: timing, epics/stories & transitioning (Ch.20 · 12–17)|||9.4 — Slide: timing, epic/story & chuyển sang agile (Ch.20 · 12–17)',
  slug: 'swr302-9-4-ch20-essentials-2',
  type: 'DOCUMENT',
  description: 'Slide 12–17: timing (yêu cầu chi tiết dần theo iteration nhưng NFR phải biết sớm — Fig 20-1); epic/user story/feature & story decomposition, minimum marketable feature (Fig 20-2); expect change (đón thay đổi + loại khỏi scope); adapting practices (road map Bảng 20-1); và transitioning to agile.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 9 · Lesson 9.4 · Book Ch.20 slides 12–17</span>
<h2>Timing, epics/stories &amp; transitioning to agile</h2>
<p class="lead">The remaining essential aspects — when requirements get detailed, the epic→story→feature hierarchy, and welcoming change — plus how to actually transition a team to agile without betting the whole organization on it at once.</p>`,
      `<span class="eyebrow">Chương 9 · Bài 9.4 · Slide 12–17 sách Ch.20</span>
<h2>Timing, epic/story &amp; chuyển sang agile</h2>
<p class="lead">Các khía cạnh thiết yếu còn lại — khi nào yêu cầu chi tiết hoá, phân cấp epic→story→feature, và đón thay đổi — cộng cách chuyển một đội sang agile mà không đặt cược cả tổ chức cùng một lúc.</p>`,
    ),
    walkHead('ch20', 12, 17),
    walk('ch20', [
      [12, '4. Timing', `<p>Agile needs fundamentally the <strong>same requirements activities</strong> as traditional projects — someone still elicits, analyzes, documents at appropriate detail, and validates that requirements meet the business objectives. The difference: detailed requirements aren't documented all at once at the start. Instead, <strong>high-level requirements (user stories) populate the product backlog early</strong> for planning and prioritization; stories are allocated to iterations and their <strong>details clarified during that iteration</strong> (Figure 20-1). Important exception: learn about <strong>nonfunctional requirements early</strong> so the architecture can be designed to achieve critical performance, usability, availability and other quality goals — those can't be bolted on late.</p>`, `<p>Agile cần về cơ bản <strong>cùng các hoạt động yêu cầu</strong> như dự án truyền thống — vẫn có người khơi gợi, phân tích, ghi ở mức chi tiết phù hợp, và thẩm định yêu cầu đạt mục tiêu nghiệp vụ. Khác biệt: yêu cầu chi tiết không được ghi hết cùng lúc lúc đầu. Thay vào đó, <strong>yêu cầu cấp cao (user story) đổ vào product backlog sớm</strong> để lập kế hoạch và ưu tiên; story được phân cho iteration và <strong>chi tiết làm rõ trong iteration đó</strong> (Hình 20-1). Ngoại lệ quan trọng: học về <strong>yêu cầu phi chức năng sớm</strong> để kiến trúc được thiết kế đạt performance, usability, availability và mục tiêu chất lượng trọng yếu — những cái đó không lắp thêm muộn được.</p>`],
      [13, '5. Epics, user stories, and features', `<p>A <strong>user story</strong> is a concise statement of something a user needs, a starting point for conversations to flesh out details, and is sized to be <strong>fully implementable in one iteration</strong>. An <strong>epic</strong> (Cohn 2010) is a user story too large for one iteration — epics span iterations, so they're split into smaller stories (sometimes into smaller epics first), a process called <strong>story decomposition</strong>, until each story can be reliably estimated, implemented and tested in a single iteration (Figure 20-2). A <strong>feature</strong> is a grouping of capabilities that provides user value — it may be one story, several stories, an epic, or multiple epics (e.g. a phone camera's <em>zoom</em> feature serves both "a mother photographing her daughter" and "a birdwatcher photographing birds from afar"). Identifying the lowest-level stories still aligned with business requirements defines the <strong>minimum marketable feature (MMF)</strong> — the smallest deliverable that provides customer value.</p>`, `<p>Một <strong>user story</strong> là một phát biểu gọn về điều một người dùng cần, một điểm khởi đầu cho trò chuyện làm rõ chi tiết, và có cỡ để <strong>hiện thực trọn trong một iteration</strong>. Một <strong>epic</strong> (Cohn 2010) là một story quá lớn cho một iteration — epic trải nhiều iteration, nên bị tách thành story nhỏ hơn (đôi khi thành epic nhỏ hơn trước), quá trình gọi <strong>story decomposition</strong>, tới khi mỗi story ước lượng, hiện thực và test được đáng tin trong một iteration (Hình 20-2). Một <strong>feature</strong> là một nhóm năng lực đem giá trị cho người dùng — có thể là một story, nhiều story, một epic, hoặc nhiều epic (vd tính năng <em>zoom</em> của camera điện thoại phục vụ cả "mẹ chụp con gái" lẫn "người xem chim chụp chim từ xa"). Nhận diện story cấp thấp nhất vẫn khớp business requirement định nghĩa <strong>minimum marketable feature (MMF)</strong> — cái giao được nhỏ nhất mà đem giá trị cho khách.</p>`],
      [14, 'Story decomposition (illustration)', `<p>Figure 20-2 shows epics subdivided into smaller epics and then into user stories — the decomposition tree. The practical goal is to reach stories small enough to <strong>estimate reliably and finish inside one iteration</strong>, so each iteration ends with genuinely done, shippable functionality rather than half-built epics.</p>`, `<p>Hình 20-2 chỉ epic được chia thành epic nhỏ hơn rồi thành user story — cây phân rã. Mục tiêu thực tế là đạt story đủ nhỏ để <strong>ước lượng đáng tin và xong trong một iteration</strong>, để mỗi iteration kết thúc với chức năng thật sự xong, ship được thay vì epic dở dang.</p>`],
      [15, '6. Expect change', `<p>Change will happen — even business objectives change. The biggest adaptation a BA makes when a change arises on agile is to say <strong>"Okay, let's talk about the change"</strong> — collaborating to create/change stories and prioritize each request against everything in the backlog. Teams still <strong>manage change thoughtfully</strong> to reduce negative impact, but they anticipate and embrace it. Embracing change doesn't mean ignoring the future: still <strong>look ahead</strong> — given a glimpse of what's coming, developers can build a more expandable architecture or design hooks for easy extension. Change also includes <strong>removing items from scope</strong> — because implementation issues block completion in the time frame, testing/product-owner findings make a story unacceptable, or higher-priority items must replace planned ones.</p>`, `<p>Thay đổi sẽ xảy ra — kể cả mục tiêu nghiệp vụ đổi. Điều chỉnh lớn nhất một BA làm khi thay đổi nảy sinh trên agile là nói <strong>"Được, hãy bàn về thay đổi"</strong> — cộng tác tạo/đổi story và ưu tiên mỗi request so với mọi thứ trong backlog. Đội vẫn <strong>quản lý thay đổi cẩn trọng</strong> để giảm tác động xấu, nhưng đón và ôm lấy nó. Ôm thay đổi không nghĩa bỏ qua tương lai: vẫn <strong>nhìn xa</strong> — có một thoáng cái sắp tới, developer dựng được kiến trúc mở rộng hơn hoặc thiết kế hook cho mở rộng dễ. Thay đổi cũng gồm <strong>loại mục khỏi scope</strong> — vì vấn đề hiện thực chặn hoàn thành trong khung giờ, phát hiện của test/product-owner làm một story không chấp nhận được, hoặc mục ưu tiên cao hơn phải thay cái đã lên kế hoạch.</p>`],
      [16, 'Adapting requirements practices to agile', `<p>Table 20-1 is a <strong>road map</strong> to the chapters that address agile development topics — elicitation, writing, prioritization, validation and management all have agile adaptations covered elsewhere in the book. The message: agile doesn't discard the requirements disciplines you've learned; it <strong>reshapes when and how much</strong> you apply each, pointing you to detailed guidance per topic.</p>`, `<p>Bảng 20-1 là một <strong>bản đồ</strong> tới các chương bàn về chủ đề phát triển agile — elicitation, viết, ưu tiên, thẩm định và quản lý đều có điều chỉnh agile phủ ở nơi khác trong sách. Thông điệp: agile không vứt các kỷ luật yêu cầu bạn đã học; nó <strong>tái định hình khi nào và bao nhiêu</strong> bạn áp mỗi cái, chỉ bạn tới hướng dẫn chi tiết theo chủ đề.</p>`],
      [17, 'Transitioning to agile: now what?', `<p>Practical transition steps: <strong>determine your role</strong> on the team; <strong>identify the agile practices that fit your organization</strong> best; <strong>pilot a small project</strong> with agile methods first, or adopt only a few agile practices on your next project; and if you choose a <strong>hybrid</strong> model (some agile practices, not all), start with a few <strong>low-risk practices</strong> that work in any methodology. Transition incrementally — the same iterative, feedback-driven spirit that agile applies to software applies to adopting agile itself.</p>`, `<p>Các bước chuyển đổi thực tế: <strong>xác định vai của bạn</strong> trong đội; <strong>nhận diện các thực hành agile hợp tổ chức bạn</strong> nhất; <strong>thử một dự án nhỏ</strong> với phương pháp agile trước, hoặc áp chỉ vài thực hành agile ở dự án kế; và nếu chọn mô hình <strong>hybrid</strong> (vài thực hành agile, không hết), bắt đầu với vài <strong>thực hành ít rủi ro</strong> chạy được trong mọi phương pháp. Chuyển đổi tăng dần — cùng tinh thần iterative, dựa phản hồi mà agile áp cho phần mềm cũng áp cho việc nhận agile.</p>`],
    ]),
    books([['wiegers', 'Chapter 20, "Timing", "Epics, user stories, and features" (Figures 20-1/20-2), "Expect change", "Adapting requirements practices to agile projects" (Table 20-1), "Transitioning to agile"', 'Chương 20, "Timing", "Epics, user stories, and features" (Hình 20-1/20-2), "Expect change", "Adapting requirements practices to agile projects" (Bảng 20-1), "Transitioning to agile"']]),
  ].join('\n'),
};

export default [A1, A2, A3];
