/**
 * SWR302 · Academy Chapter 7 (Requirements management) additions — book chapter
 * Ch.27 "Requirements management practices" (13 slides), split into TWO focused
 * lessons: the RM process + attributes + status tracking (1–7), and issues +
 * effort + agile management (8–13). Exported as an array spliced into academy
 * Chapter 7 before its quiz. Grounded slide-by-slide in
 * CHAPTER_27_Requirements management practices.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 7.3 — RM process, attributes, status */
const M1 = {
  title: '7.3 — Slides: the RM process, attributes & status (Ch.27 · 1–7)|||7.3 — Slide: quy trình RM, thuộc tính & trạng thái (Ch.27 · 1–7)',
  slug: 'swr302-7-3-ch27-rm-process',
  type: 'DOCUMENT',
  description: 'Slide 1–7: requirements management = 4 nhóm hoạt động (version control, change control, status tracking, tracing); requirement attributes (mỗi yêu cầu là một object có thuộc tính — ngày, phiên bản, tác giả, priority, status, nguồn, rationale...); và theo dõi trạng thái yêu cầu (Bảng 27-1, biểu đồ phân bố 27-2).',
  content: [
    bi(
      `<span class="eyebrow">Chapter 7 · Lesson 7.3 · Book Ch.27 slides 1–7</span>
<h2>The RM process, attributes &amp; status tracking</h2>
<p class="lead">Once requirements are baselined, managing them keeps the agreement accurate and current. The RM process has four activity groups, each requirement carries attributes beyond its text, and tracking status across the project makes progress visible.</p>`,
      `<span class="eyebrow">Chương 7 · Bài 7.3 · Slide 1–7 sách Ch.27</span>
<h2>Quy trình RM, thuộc tính &amp; theo dõi trạng thái</h2>
<p class="lead">Sau khi yêu cầu được baseline, quản lý chúng giữ thoả thuận chính xác và cập nhật. Quy trình RM có bốn nhóm hoạt động, mỗi yêu cầu mang thuộc tính ngoài phần chữ, và theo dõi trạng thái xuyên dự án làm tiến độ lộ rõ.</p>`,
    ),
    walkHead('ch27', 1, 7),
    walk('ch27', [
      [1, 'Requirements management practices', `<p>Title slide — the principles and practices for managing requirements after they're agreed, and why communication among participants is central to great requirements.</p>`, `<p>Slide bìa — nguyên tắc và thực hành quản lý yêu cầu sau khi thống nhất, và vì sao giao tiếp giữa người tham gia là trung tâm của yêu cầu tốt.</p>`],
      [2, 'Objectives', `<p>Cover the principles and practices of requirements management; appreciate that effective management and communication among project participants is essential to great requirements; and understand the <strong>basic concepts</strong> here — later chapters clarify each process in detail.</p>`, `<p>Nói về nguyên tắc và thực hành quản lý yêu cầu; hiểu rằng quản lý và giao tiếp hiệu quả giữa người tham gia là thiết yếu cho yêu cầu tốt; và nắm <strong>khái niệm cơ bản</strong> ở đây — các chương sau làm rõ từng quy trình chi tiết.</p>`],
      [3, 'Contents', `<p>Topics: the RM process, requirement attributes, tracking status, resolving issues, common issue types, measuring effort, and managing requirements on agile projects. Lessons 7.3–7.4 cover them.</p>`, `<p>Chủ đề: quy trình RM, thuộc tính yêu cầu, theo dõi trạng thái, giải quyết vấn đề, các loại vấn đề phổ biến, đo công sức, và quản lý yêu cầu trên dự án agile. Bài 7.3–7.4 phủ chúng.</p>`],
      [4, 'The requirements management process', `<p>Requirements management includes <strong>all activities that maintain the integrity, accuracy, and currency</strong> of requirements agreements throughout the project. Figure 27-1 groups the core activities into <strong>four categories</strong>: <strong>version control</strong> (which version is current), <strong>change control</strong> (how changes are proposed and decided), <strong>requirements status tracking</strong> (where each requirement is in its lifecycle), and <strong>requirements tracing</strong> (links to origins, design, code, tests). Development <em>creates</em> the baseline; management <em>protects</em> it.</p>`, `<p>Quản lý yêu cầu gồm <strong>mọi hoạt động duy trì tính toàn vẹn, chính xác và cập nhật</strong> của thoả thuận yêu cầu suốt dự án. Hình 27-1 gom các hoạt động lõi thành <strong>bốn nhóm</strong>: <strong>version control</strong> (phiên bản nào hiện hành), <strong>change control</strong> (thay đổi được đề xuất và quyết thế nào), <strong>status tracking</strong> (mỗi yêu cầu đang ở đâu trong vòng đời), và <strong>tracing</strong> (liên kết tới nguồn, thiết kế, code, test). Phát triển <em>tạo</em> baseline; quản lý <em>bảo vệ</em> nó.</p>`],
      [5, 'Requirement attributes', `<p>Think of each requirement as an <strong>object with properties</strong> that distinguish it — beyond its text, it should carry <strong>attributes</strong> giving context and background. Store attribute values in a document, spreadsheet, database, or — most effectively — a <strong>requirements management tool</strong>. Potential attributes: date created; current version number; author; priority; status; origin/source; rationale; the release/iteration it's allocated to; the stakeholder to contact for questions or change decisions; and the validation method or acceptance criteria. These attributes are what make requirements manageable at scale.</p>`, `<p>Coi mỗi yêu cầu là một <strong>object có thuộc tính</strong> phân biệt nó — ngoài phần chữ, nó nên mang <strong>attribute</strong> cho ngữ cảnh và bối cảnh. Lưu giá trị thuộc tính trong tài liệu, spreadsheet, database, hoặc — hiệu quả nhất — một <strong>công cụ RM</strong>. Thuộc tính tiềm năng: ngày tạo; số phiên bản hiện tại; tác giả; priority; status; nguồn/origin; rationale; release/iteration được phân bổ; stakeholder liên hệ cho câu hỏi hoặc quyết định thay đổi; và phương pháp validate hoặc acceptance criteria. Các thuộc tính này làm cho yêu cầu quản lý được ở quy mô lớn.</p>`],
      [6, 'Tracking requirements status', `<p>Table 27-1 suggests a set of <strong>requirement statuses</strong> for the lifecycle — e.g. <em>Proposed, Approved, Implemented, Verified, Deferred, Deleted, Rejected</em>. Assigning a status to each requirement turns a flat list into a live view of where the work stands. A requirement counts as truly done only when it reaches a terminal status like <em>Verified</em> — not merely <em>Implemented</em>.</p>`, `<p>Bảng 27-1 gợi ý một tập <strong>trạng thái yêu cầu</strong> cho vòng đời — vd <em>Proposed, Approved, Implemented, Verified, Deferred, Deleted, Rejected</em>. Gán một trạng thái cho mỗi yêu cầu biến một danh sách phẳng thành cái nhìn sống về tình hình công việc. Một yêu cầu chỉ thật sự xong khi đạt trạng thái cuối như <em>Verified</em> — không phải chỉ <em>Implemented</em>.</p>`],
      [7, 'Status distribution over time', `<p>Figure 27-2 charts the <strong>distribution of requirement statuses</strong> throughout the development cycle — the fraction Proposed vs Approved vs Implemented vs Verified over time. As the project progresses the mass should shift toward Verified; a stalled distribution (many still Proposed late in the cycle) is an early warning that scope isn't converging. This chart is a project-health gauge management can read at a glance.</p>`, `<p>Hình 27-2 vẽ <strong>phân bố trạng thái yêu cầu</strong> suốt chu kỳ phát triển — tỷ lệ Proposed vs Approved vs Implemented vs Verified theo thời gian. Khi dự án tiến, khối lượng nên dịch về Verified; một phân bố đứng im (nhiều cái vẫn Proposed muộn trong chu kỳ) là cảnh báo sớm rằng phạm vi chưa hội tụ. Biểu đồ này là một thước sức khoẻ dự án mà quản lý đọc được trong nháy mắt.</p>`],
    ]),
    books([['wiegers', 'Chapter 27, "Requirements management process" (Figure 27-1), "Requirement attributes", "Tracking requirements status" (Table 27-1, Figure 27-2)', 'Chương 27, "Requirements management process" (Hình 27-1), "Requirement attributes", "Tracking requirements status" (Bảng 27-1, Hình 27-2)']]),
  ].join('\n'),
};

/* 7.4 — issues, effort, agile */
const M2 = {
  title: '7.4 — Slides: issues, effort & agile management (Ch.27 · 8–13)|||7.4 — Slide: vấn đề, công sức & quản lý agile (Ch.27 · 8–13)',
  slug: 'swr302-7-4-ch27-issues-agile',
  type: 'DOCUMENT',
  description: 'Slide 8–13: giải quyết requirements issues bằng issue-tracking tool; các loại issue phổ biến (Bảng 27-2); đo công sức RM (development vs management effort — đầu tư chứ không chỉ chi phí); và quản lý yêu cầu trên agile (backlog, story status, iteration burndown chart tránh hội chứng "90% done").',
  content: [
    bi(
      `<span class="eyebrow">Chapter 7 · Lesson 7.4 · Book Ch.27 slides 8–13</span>
<h2>Issues, effort &amp; agile management</h2>
<p class="lead">Open questions must not slip through the cracks — track them. RM effort is an investment, not just a cost. And agile projects manage requirements as a dynamic backlog, watching an iteration burndown chart to see the truth about how much work remains.</p>`,
      `<span class="eyebrow">Chương 7 · Bài 7.4 · Slide 8–13 sách Ch.27</span>
<h2>Vấn đề, công sức &amp; quản lý agile</h2>
<p class="lead">Các câu hỏi mở không được lọt khe — hãy theo dõi chúng. Công sức RM là đầu tư, không chỉ chi phí. Và dự án agile quản lý yêu cầu như một backlog động, xem iteration burndown chart để thấy sự thật về lượng việc còn lại.</p>`,
    ),
    walkHead('ch27', 8, 13),
    walk('ch27', [
      [8, 'Resolving requirements issues', `<p>Many questions, decisions and issues arise during a project — items flagged <strong>TBD</strong>, pending decisions, needed information, conflicts awaiting resolution. These open issues are easy to lose sight of, so record them in an <strong>issue-tracking tool</strong> accessible to all affected stakeholders, and keep the process simple. Benefits: issues from multiple reviews are collected so <strong>none is lost</strong>; the PM can see current status of all issues; a <strong>single owner</strong> is assigned per issue; the discussion history is retained; and the team can <strong>start development earlier</strong> with a known set of open issues rather than waiting for a complete SRS.</p>`, `<p>Nhiều câu hỏi, quyết định và vấn đề nảy sinh trong dự án — mục đánh dấu <strong>TBD</strong>, quyết định chờ, thông tin cần, mâu thuẫn chờ giải. Các open issue này dễ bị quên, nên ghi vào một <strong>issue-tracking tool</strong> mọi stakeholder liên quan truy cập được, và giữ quy trình đơn giản. Lợi ích: issue từ nhiều lần review được gom nên <strong>không mất cái nào</strong>; PM thấy trạng thái hiện tại của mọi issue; một <strong>chủ sở hữu duy nhất</strong> gán mỗi issue; lịch sử thảo luận được giữ; và nhóm có thể <strong>bắt đầu phát triển sớm</strong> với một tập open issue đã biết thay vì đợi SRS hoàn chỉnh.</p>`],
      [9, 'Common types of requirements issues', `<p>Nearly all defects logged early in a project relate to requirements: requests to <strong>clarify</strong> a requirement, <strong>scope</strong> decisions, questions about development <strong>feasibility</strong>, and <strong>to-do items</strong> on the requirements themselves. All stakeholders can log questions as they review. Table 27-2 catalogs several common issue types — categorizing them helps route each to the right owner and spot patterns (e.g. many feasibility questions may signal over-ambitious requirements).</p>`, `<p>Gần như mọi lỗi ghi nhận sớm trong dự án liên quan tới yêu cầu: yêu cầu <strong>làm rõ</strong> một requirement, quyết định <strong>phạm vi</strong>, câu hỏi về <strong>khả thi</strong> phát triển, và <strong>to-do</strong> trên chính các yêu cầu. Mọi stakeholder ghi câu hỏi khi review. Bảng 27-2 liệt kê vài loại issue phổ biến — phân loại giúp định tuyến mỗi cái tới đúng chủ và thấy mẫu (vd nhiều câu hỏi khả thi có thể báo yêu cầu quá tham vọng).</p>`],
      [10, 'Measuring requirements effort (development)', `<p>Your project plan should include tasks and resources for RM. If you <strong>track effort</strong> spent on requirements activities, you can judge whether it was too little, about right, or too much, and adjust future planning. Note: work effort ≠ elapsed calendar time (tasks get interrupted, need others). Record hours on <strong>requirements development</strong>: planning requirements activities; workshops, interviews, document analysis and other elicitation; writing specs, building analysis models, prioritizing; and creating/evaluating prototypes; plus reviewing and other validation.</p>`, `<p>Kế hoạch dự án nên gồm task và tài nguyên cho RM. Nếu bạn <strong>theo dõi công sức</strong> dành cho hoạt động yêu cầu, bạn phán được nó quá ít, vừa, hay quá nhiều, và điều chỉnh kế hoạch tương lai. Lưu ý: công sức ≠ thời gian lịch trôi (task bị ngắt, cần người khác). Ghi giờ cho <strong>phát triển yêu cầu</strong>: lập kế hoạch hoạt động yêu cầu; workshop, phỏng vấn, phân tích tài liệu và elicitation khác; viết spec, dựng mô hình phân tích, ưu tiên; và tạo/đánh giá prototype; cộng review và validation khác.</p>`],
      [11, 'Measuring effort (management) — an investment', `<p>Count as <strong>requirements management effort</strong>: configuring an RM tool; submitting changes and proposing new requirements; <strong>evaluating proposed changes</strong> (impact analysis, decisions); updating the repository; communicating changes to affected stakeholders; tracking/reporting status; and creating trace information. Crucially, this time is an <strong>investment in project success, not just a cost</strong> — justify it by comparing it against the time the team spends dealing with problems that arose <em>because</em> these things weren't done (the cost of poor quality).</p>`, `<p>Tính là <strong>công sức quản lý yêu cầu</strong>: cấu hình công cụ RM; nộp thay đổi và đề xuất yêu cầu mới; <strong>đánh giá thay đổi đề xuất</strong> (impact analysis, quyết định); cập nhật repository; truyền đạt thay đổi tới stakeholder liên quan; theo dõi/báo cáo trạng thái; và tạo thông tin trace. Quan trọng, thời gian này là <strong>đầu tư cho thành công dự án, không chỉ chi phí</strong> — biện minh bằng cách so nó với thời gian nhóm xử lý vấn đề nảy sinh <em>vì</em> không làm các việc này (chi phí của chất lượng kém).</p>`],
      [12, 'Managing requirements on agile projects', `<p>Agile accommodates change via a series of iterations and a <strong>dynamic product backlog</strong>. Stakeholders agree the stories for each iteration; new stories added mid-iteration are <strong>prioritized against the remaining backlog</strong> and allocated to future iterations — the goal is always to work the highest-priority stories for maximum value soonest. Large/distributed teams may use an agile PM tool to track iteration and story status, storing stories with their acceptance criteria/tests in a backlog tool. Story statuses parallel Table 27-1: <strong>In backlog, Defined, In progress, Completed, Accepted, Blocked</strong>.</p>`, `<p>Agile đón thay đổi qua một chuỗi iteration và một <strong>product backlog động</strong>. Stakeholder thống nhất các story cho mỗi iteration; story mới thêm giữa iteration được <strong>ưu tiên so với backlog còn lại</strong> và phân sang iteration sau — mục tiêu luôn là làm story ưu tiên cao nhất cho giá trị lớn nhất sớm nhất. Nhóm lớn/phân tán có thể dùng công cụ PM agile theo dõi trạng thái iteration và story, lưu story kèm acceptance criteria/test trong công cụ backlog. Trạng thái story song song Bảng 27-1: <strong>In backlog, Defined, In progress, Completed, Accepted, Blocked</strong>.</p>`],
      [13, 'The iteration burndown chart', `<p>Agile projects monitor progress with an <strong>iteration burndown chart</strong>. The team estimates total work, sized in <strong>story points</strong> derived from understanding the backlog stories — the story-point total is proportional to the effort to implement the requirements. Each iteration, the team charts <strong>story points remaining</strong> in the backlog (not the count/status of individual features, which vary in size). The burndown avoids the <strong>"90% done" syndrome</strong> by making <em>work remaining</em> visible rather than work completed (which ignores inevitable scope growth); the chart's <strong>slope reveals the projected end date</strong> — where the backlog reaches zero (Figure 27-3).</p>`, `<p>Dự án agile theo dõi tiến độ bằng <strong>iteration burndown chart</strong>. Nhóm ước lượng tổng việc, đo bằng <strong>story point</strong> dẫn từ hiểu các story backlog — tổng story point tỷ lệ với công sức hiện thực yêu cầu. Mỗi iteration, nhóm vẽ <strong>story point còn lại</strong> trong backlog (không phải số/trạng thái từng feature, vốn khác cỡ). Burndown tránh <strong>hội chứng "90% done"</strong> bằng cách làm <em>việc còn lại</em> lộ rõ thay vì việc đã xong (vốn bỏ qua tăng phạm vi tất yếu); <strong>độ dốc</strong> của biểu đồ lộ ngày kết thúc dự kiến — nơi backlog về 0 (Hình 27-3).</p>`],
    ]),
    books([['wiegers', 'Chapter 27, "Resolving requirements issues", "Common types of requirements issues" (Table 27-2), "Measuring requirements effort", "Managing requirements on agile projects" (Figure 27-3)', 'Chương 27, "Resolving requirements issues", "Common types of requirements issues" (Bảng 27-2), "Measuring requirements effort", "Managing requirements on agile projects" (Hình 27-3)']]),
  ].join('\n'),
};

export default [M1, M2];
