/**
 * SWR302 · NEW section for book chapter Ch.3 "Requirements engineering good
 * practices" (65 slides — the biggest deck: a catalog of ~50 practices in 7
 * groups). It does not map to any single existing thematic chapter, so it is
 * its own section, inserted after academy Chapter 2. Split into SEVEN focused
 * lessons by practice group so nothing is overloaded. Grounded slide-by-slide
 * in CHAPTER_3_Requirements engineering good practices.pdf. Exports a full
 * section object (title + lessons) that SWR302.mjs inserts into `sections`.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 3G.1 — overview */
const G1 = {
  title: '3G.1 — Slides: how the good practices are organized (Ch.3 · 1–6)|||3G.1 — Slide: các thực hành tốt được tổ chức ra sao (Ch.3 · 1–6)',
  slug: 'swr302-3g-1-ch3-overview',
  type: 'DOCUMENT',
  description: 'Slide 1–6: bức tranh tổng của ~50 thực hành tốt về kỹ nghệ yêu cầu (Bảng 3-1), khung quy trình phát triển yêu cầu lặp, và một quy trình phát triển yêu cầu tiêu biểu (7 bước làm một lần đầu dự án, phần còn lại lặp mỗi release/iteration).',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.1 · Book Ch.3 slides 1–6</span>
<h2>A catalog of good practices — the big picture</h2>
<p class="lead">This chapter is a <strong>survey of ~50 practices</strong> that make requirements work well, grouped into seven areas: elicitation, analysis, specification, validation, management, knowledge, and project management. Later chapters teach each in depth; here you see the whole toolbox at once and how the process fits together.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.1 · Slide 1–6 sách Ch.3</span>
<h2>Danh mục thực hành tốt — bức tranh tổng</h2>
<p class="lead">Chương này là <strong>tổng quan ~50 thực hành</strong> giúp làm yêu cầu tốt, chia bảy nhóm: elicitation, analysis, specification, validation, management, knowledge, và project management. Các chương sau dạy sâu từng cái; ở đây bạn thấy cả hộp công cụ một lần và cách quy trình khớp lại.</p>`,
    ),
    walkHead('ch3', 1, 6),
    walk('ch3', [
      [1, 'Requirements engineering good practices', `<p>Title slide of the survey chapter.</p>`, `<p>Slide bìa của chương tổng quan.</p>`],
      [2, 'Objectives', `<p>Get a map of the good practices across the full requirements lifecycle so you know <em>what</em> good looks like, then study the details in later chapters.</p>`, `<p>Có một bản đồ các thực hành tốt suốt vòng đời yêu cầu để biết <em>thế nào là tốt</em>, rồi học chi tiết ở các chương sau.</p>`],
      [3, 'Contents', `<p>The seven groups: elicitation, analysis, specification, validation, management, knowledge, and project management. Lessons 3G.2–3G.7 cover them in that order.</p>`, `<p>Bảy nhóm: elicitation, analysis, specification, validation, management, knowledge, và project management. Bài 3G.2–3G.7 đi theo thứ tự đó.</p>`],
      [4, 'Table 3-1 — the practices grouped', `<p>Table 3-1 lists every practice under its group. Treat it as a <strong>checklist</strong>: on a real project you rarely do all fifty, but you should consciously choose which to apply and why.</p>`, `<p>Bảng 3-1 liệt kê mọi thực hành theo nhóm. Coi nó như một <strong>checklist</strong>: trên dự án thật hiếm khi làm cả năm mươi, nhưng nên chủ động chọn cái nào áp dụng và vì sao.</p>`],
      [5, 'A requirements development process framework', `<p>Requirements development is <strong>iterative</strong> — elicit, analyse, specify, validate, then loop — continuing throughout development, and on agile projects throughout the whole project. It is never a one-pass, done-forever phase.</p>`, `<p>Phát triển yêu cầu là <strong>lặp</strong> — elicit, analyse, specify, validate, rồi vòng lại — tiếp diễn suốt quá trình phát triển, và với dự án agile là suốt cả dự án. Không bao giờ là một pha làm-một-lần-xong-mãi.</p>`],
      [6, 'A representative requirements development process', `<p>A typical sequence: the <strong>first seven steps</strong> (vision &amp; scope, user classes, product champions, etc.) are done <em>once early</em> in the project (revisited periodically); the <strong>remaining steps</strong> are repeated <em>for each release or iteration</em>. This split — set the foundation once, refine per iteration — is the shape of most real projects.</p>`, `<p>Một trình tự tiêu biểu: <strong>bảy bước đầu</strong> (vision &amp; scope, lớp người dùng, product champion…) làm <em>một lần đầu</em> dự án (rà lại định kỳ); <strong>các bước còn lại</strong> lặp <em>cho mỗi release/iteration</em>. Cách chia này — đặt nền một lần, tinh chỉnh theo iteration — là hình dạng của đa số dự án thật.</p>`],
    ]),
    books([['wiegers', 'Chapter 3 opening and Table 3-1 "Requirements engineering good practices"', 'Chương 3 phần mở đầu và Bảng 3-1 "Requirements engineering good practices"']]),
  ].join('\n'),
};

/* 3G.2 — elicitation practices */
const G2 = {
  title: '3G.2 — Slides: elicitation good practices (Ch.3 · 7–20)|||3G.2 — Slide: thực hành tốt khi khai thác (Ch.3 · 7–20)',
  slug: 'swr302-3g-2-ch3-elicitation',
  type: 'DOCUMENT',
  description: 'Slide 7–20: 13 thực hành khai thác yêu cầu — vision & scope, lớp người dùng, product champion, focus group, user requirement, sự kiện & phản hồi, phỏng vấn, workshop (JAD), quan sát, bảng hỏi, phân tích tài liệu, xem problem report, tái sử dụng.',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.2 · Book Ch.3 slides 7–20</span>
<h2>Elicitation good practices (13)</h2>
<p class="lead">Thirteen ways to <strong>discover</strong> requirements. You will meet most again in depth (Chapters 5–8); here each is a one-line tool for your kit.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.2 · Slide 7–20 sách Ch.3</span>
<h2>Thực hành tốt khi khai thác (13)</h2>
<p class="lead">Mười ba cách <strong>khám phá</strong> yêu cầu. Bạn sẽ gặp lại đa số ở mức sâu (Chương 5–8); ở đây mỗi cái là một công cụ một dòng cho hộp đồ nghề.</p>`,
    ),
    walkHead('ch3', 7, 20),
    walk('ch3', [
      [7, 'Elicitation practices — the list', `<p>The thirteen, unpacked next: define vision &amp; scope · identify user classes · pick product champions · run focus groups · identify user requirements · list events &amp; responses · interviews · facilitated workshops · observe users · questionnaires · document analysis · mine problem reports · reuse requirements.</p>`, `<p>Mười ba cái, mổ xẻ ngay sau: định vision &amp; scope · xác định lớp người dùng · chọn product champion · chạy focus group · xác định user requirement · liệt kê sự kiện &amp; phản hồi · phỏng vấn · workshop có điều phối · quan sát người dùng · bảng hỏi · phân tích tài liệu · đào problem report · tái sử dụng yêu cầu.</p>`],
      [8, '1. Define product vision & project scope', `<p>The <strong>Vision &amp; Scope document</strong> holds the business requirements: a vision statement (a shared understanding of the outcome) and a scope (the in/out boundary for a release). Together they are the reference to judge every proposed requirement. Vision stays stable; each release needs its own scope. (Chapter 5.)</p>`, `<p><strong>Tài liệu Vision &amp; Scope</strong> giữ business requirement: một tuyên bố tầm nhìn (hiểu chung về kết quả) và một phạm vi (ranh giới trong/ngoài cho một release). Cùng nhau chúng là mốc để đánh giá mọi yêu cầu đề xuất. Tầm nhìn giữ ổn định; mỗi release cần phạm vi riêng. (Chương 5.)</p>`],
      [9, '2. Identify user classes & their characteristics', `<p>Identify the distinct groups of users (differing by frequency of use, features used, privilege, experience) so no community is overlooked. Describe their tasks, attitudes, location and traits, and create <strong>personas</strong> — imaginary people representing a user class. (Chapter 6.)</p>`, `<p>Xác định các nhóm người dùng khác nhau (khác nhau về tần suất, tính năng dùng, quyền, kinh nghiệm) để không sót cộng đồng nào. Mô tả công việc, thái độ, vị trí và đặc điểm của họ, và tạo <strong>persona</strong> — nhân vật tưởng tượng đại diện một lớp người dùng. (Chương 6.)</p>`],
      [10, '3. Select a product champion for each user class', `<p>Name one person who is the <strong>literal voice</strong> of each user class — presents its needs and decides on its behalf. Easy for internal IT (users are colleagues); for commercial products, use major customers or beta sites.</p>`, `<p>Chỉ định một người là <strong>tiếng nói đại diện</strong> của mỗi lớp người dùng — trình bày nhu cầu và quyết định thay lớp đó. Dễ với IT nội bộ (người dùng là đồng nghiệp); với sản phẩm thương mại, dùng khách hàng lớn hoặc site beta.</p>`],
      [11, '4. Conduct focus groups with typical users', `<p>Convene representative users of your previous or similar products to collect input on functionality and quality. Valuable for commercial products with a large, diverse base. Unlike product champions, focus groups usually have <strong>no decision authority</strong>.</p>`, `<p>Tập hợp người dùng đại diện của sản phẩm trước hoặc tương tự để thu ý kiến về chức năng và chất lượng. Có giá trị với sản phẩm thương mại có tệp lớn, đa dạng. Khác product champion, focus group thường <strong>không có quyền quyết</strong>.</p>`],
      [12, '5. Work with user representatives to identify user requirements', `<p>Explore the <strong>tasks users must accomplish</strong> and the value they seek, expressed as use cases, user stories or scenarios. Discuss the user–system interactions that complete each task. (Chapter 8.)</p>`, `<p>Khám phá <strong>công việc người dùng phải hoàn thành</strong> và giá trị họ tìm, diễn đạt dạng use case, user story hoặc scenario. Thảo luận tương tác người–hệ thống để hoàn thành mỗi công việc. (Chương 8.)</p>`],
      [13, '6. Identify system events & responses', `<p>List external events and the system's response to each. Three classes: <strong>signal</strong> events (control signals/data from hardware), <strong>temporal</strong> events (time-triggered, e.g. a nightly feed), and <strong>business</strong> events (trigger use cases). An event-response table is a great completeness check.</p>`, `<p>Liệt kê sự kiện ngoài và phản hồi của hệ thống với từng cái. Ba loại: sự kiện <strong>signal</strong> (tín hiệu/dữ liệu từ phần cứng), <strong>temporal</strong> (kích theo thời gian, vd feed hằng đêm), và <strong>business</strong> (kích use case). Bảng event-response là cách kiểm tính đầy đủ rất tốt.</p>`],
      [14, '7. Hold elicitation interviews', `<p>One-on-one or small-group interviews — an efficient way to elicit without consuming much stakeholder time, since you discuss only what matters to each person. Useful to gather views separately <em>before</em> a workshop where conflicts get resolved.</p>`, `<p>Phỏng vấn 1-1 hoặc nhóm nhỏ — cách khai thác hiệu quả mà không tốn nhiều thời gian của bên liên quan, vì chỉ bàn cái quan trọng với mỗi người. Hữu ích để thu quan điểm riêng <em>trước</em> một workshop nơi xử lý xung đột.</p>`],
      [15, '8. Hold facilitated elicitation workshops', `<p>Facilitated workshops let analysts and customers <strong>collaborate</strong> to explore needs and draft requirements — sometimes called <strong>JAD (Joint Application Design)</strong> sessions. Powerful for building shared understanding fast.</p>`, `<p>Workshop có điều phối để analyst và khách hàng <strong>cộng tác</strong> khám phá nhu cầu và soạn nháp yêu cầu — đôi khi gọi là phiên <strong>JAD (Joint Application Design)</strong>. Mạnh để dựng hiểu biết chung nhanh.</p>`],
      [16, '9. Observe users performing their jobs', `<p>Watching users at work reveals the real context of a new app. Simple <strong>process-flow diagrams</strong> capture the steps, decisions and how user groups interact — and documenting the business process helps derive requirements to support it.</p>`, `<p>Quan sát người dùng làm việc cho thấy ngữ cảnh thật của app mới. <strong>Sơ đồ process-flow</strong> đơn giản ghi lại các bước, quyết định và cách các nhóm tương tác — và ghi lại quy trình nghiệp vụ giúp suy ra yêu cầu hỗ trợ nó.</p>`],
      [17, '10. Distribute questionnaires', `<p>Surveys reach <strong>large or distributed</strong> user populations. Well-written questions quickly yield analytical information about needs; use the results to focus further, deeper elicitation.</p>`, `<p>Bảng hỏi tiếp cận tệp người dùng <strong>lớn hoặc phân tán</strong>. Câu hỏi viết tốt cho thông tin phân tích nhanh về nhu cầu; dùng kết quả để tập trung khai thác sâu tiếp theo.</p>`],
      [18, '11. Perform document analysis', `<p>Existing docs reveal how systems work or should work: current-system docs, business processes, old specs, competitor research, COTS manuals. Analysing them shows what to keep, what's unused, how people work now, and what vendors claim.</p>`, `<p>Tài liệu sẵn có tiết lộ hệ thống chạy ra sao hoặc nên ra sao: tài liệu hệ hiện tại, quy trình nghiệp vụ, spec cũ, nghiên cứu đối thủ, manual COTS. Phân tích cho thấy giữ gì, cái gì không dùng, người ta làm việc thế nào, và nhà cung cấp tuyên bố gì.</p>`],
      [19, '12. Examine problem reports for requirement ideas', `<p>Problem reports and enhancement requests from users are a rich source of ideas for a later release. Help-desk and support staff give valuable input for future requirements.</p>`, `<p>Problem report và yêu cầu nâng cấp từ người dùng là nguồn ý tưởng phong phú cho release sau. Nhân viên help-desk và hỗ trợ cho đầu vào quý cho yêu cầu tương lai.</p>`],
      [20, '13. Reuse existing requirements', `<p>If a request resembles existing functionality, check whether the requirements (and customers!) are flexible enough to reuse or adapt existing components. Great reuse candidates: requirements enforcing business rules (security) or regulations (accessibility), plus glossaries, data models, stakeholder profiles, user-class descriptions and personas. (Chapter 18.)</p>`, `<p>Nếu một yêu cầu giống chức năng có sẵn, kiểm xem yêu cầu (và khách hàng!) có đủ linh hoạt để tái dùng/điều chỉnh thành phần sẵn có không. Ứng viên tái dùng tốt: yêu cầu thực thi business rule (bảo mật) hoặc quy định (khả năng tiếp cận), cùng glossary, data model, hồ sơ stakeholder, mô tả lớp người dùng và persona. (Chương 18.)</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Requirements elicitation" practices; then Chapters 5–8 for depth', 'Chương 3, các thực hành "Requirements elicitation"; rồi Chương 5–8 để đào sâu']]),
  ].join('\n'),
};

/* 3G.3 — analysis practices */
const G3 = {
  title: '3G.3 — Slides: analysis good practices (Ch.3 · 21–29)|||3G.3 — Slide: thực hành tốt khi phân tích (Ch.3 · 21–29)',
  slug: 'swr302-3g-3-ch3-analysis',
  type: 'DOCUMENT',
  description: 'Slide 21–29: 8 thực hành phân tích — mô hình môi trường (context diagram/ecosystem map), prototype, phân tích khả thi, ưu tiên, data dictionary, mô hình hoá yêu cầu, phân tích giao diện ngoài, phân bổ cho hệ con.',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.3 · Book Ch.3 slides 21–29</span>
<h2>Analysis good practices (8)</h2>
<p class="lead">Turning raw input into a precise, well-structured understanding — modeling, prototyping, feasibility, prioritization and allocation.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.3 · Slide 21–29 sách Ch.3</span>
<h2>Thực hành tốt khi phân tích (8)</h2>
<p class="lead">Biến đầu vào thô thành hiểu biết chính xác, có cấu trúc — mô hình hoá, prototype, khả thi, ưu tiên và phân bổ.</p>`,
    ),
    walkHead('ch3', 21, 29),
    walk('ch3', [
      [21, 'Analysis practices — the list', `<p>Eight practices next: model the environment · UI/technical prototypes · analyse feasibility · prioritize · data dictionary · model the requirements · analyse external interfaces · allocate to subsystems.</p>`, `<p>Tám thực hành ngay sau: mô hình môi trường · prototype UI/kỹ thuật · phân tích khả thi · ưu tiên · data dictionary · mô hình hoá yêu cầu · phân tích giao diện ngoài · phân bổ cho hệ con.</p>`],
      [22, '1. Model the application environment', `<p>A <strong>context diagram</strong> shows how the new system fits its environment — the boundary and interfaces to users, devices and other systems. An <strong>ecosystem map</strong> shows the systems in the solution space and how they interconnect. (Chapter 12.)</p>`, `<p>Một <strong>context diagram</strong> cho thấy hệ mới khớp môi trường ra sao — ranh giới và giao diện tới người dùng, thiết bị và hệ khác. Một <strong>ecosystem map</strong> cho thấy các hệ trong không gian giải pháp và cách chúng nối nhau. (Chương 12.)</p>`],
      [23, '2. Create UI & technical prototypes', `<p>When requirements are uncertain, build a <strong>prototype</strong> (partial/preliminary implementation) to make concepts tangible, reach mutual understanding, and validate requirements. (Chapter 15.)</p>`, `<p>Khi yêu cầu chưa chắc, dựng một <strong>prototype</strong> (bản hiện thực một phần/sơ bộ) để làm khái niệm hữu hình, đạt hiểu biết chung, và validate yêu cầu. (Chương 15.)</p>`],
      [24, '3. Analyze requirement feasibility', `<p>Work with developers to judge whether each requirement can be built at acceptable cost/performance in the target environment. This surfaces <strong>risks, conflicts and dependencies</strong> early; infeasible or costly ones can often be simplified while still meeting business objectives.</p>`, `<p>Làm việc với lập trình viên để đánh giá mỗi yêu cầu có xây được với chi phí/hiệu năng chấp nhận được trong môi trường đích không. Việc này lộ <strong>rủi ro, xung đột và phụ thuộc</strong> sớm; cái bất khả thi/đắt thường có thể đơn giản hoá mà vẫn đạt mục tiêu nghiệp vụ.</p>`],
      [25, '4. Prioritize the requirements', `<p>Prioritize so the team builds the <strong>highest-value or most time-critical</strong> functionality first; use an analytical method, map priority to release/increment, and re-adjust as needs, market and goals evolve. (Chapter 16.)</p>`, `<p>Ưu tiên để nhóm xây chức năng <strong>giá trị cao nhất hoặc gấp nhất</strong> trước; dùng phương pháp phân tích, gán ưu tiên cho release/increment, và điều chỉnh lại khi nhu cầu, thị trường và mục tiêu tiến hoá. (Chương 16.)</p>`],
      [26, '5. Create a data dictionary', `<p>A <strong>data dictionary</strong> holds definitions of data items and structures so everyone uses consistent definitions. Define problem-domain data items as requirements develop, to ease customer–developer communication. (Chapter 13.)</p>`, `<p>Một <strong>data dictionary</strong> chứa định nghĩa các mục và cấu trúc dữ liệu để mọi người dùng định nghĩa nhất quán. Định nghĩa các mục dữ liệu miền vấn đề khi yêu cầu phát triển, để dễ giao tiếp khách hàng–lập trình viên. (Chương 13.)</p>`],
      [27, '6. Model the requirements', `<p>An <strong>analysis model</strong> depicts requirements visually (vs. a textual list) and can reveal incorrect, inconsistent, missing or superfluous requirements. Examples: DFDs, ER diagrams, state-transition diagrams, state tables, dialog maps, decision trees. (Chapter 12.)</p>`, `<p>Một <strong>analysis model</strong> mô tả yêu cầu bằng hình (thay vì danh sách chữ) và có thể lộ yêu cầu sai, mâu thuẫn, thiếu hoặc thừa. Ví dụ: DFD, ER, sơ đồ chuyển trạng thái, state table, dialog map, decision tree. (Chương 12.)</p>`],
      [28, '7. Analyze external interfaces', `<p>Every system connects to the world: information systems have UIs and data exchanges; embedded systems link software and hardware; networked apps have communication interfaces. Analysing these ensures your app <strong>fits smoothly into its environment</strong>.</p>`, `<p>Mọi hệ thống nối với thế giới: hệ thông tin có UI và trao đổi dữ liệu; hệ nhúng nối phần mềm và phần cứng; app mạng có giao diện truyền thông. Phân tích chúng đảm bảo app <strong>khớp mượt vào môi trường</strong>.</p>`],
      [29, '8. Allocate requirements to subsystems', `<p>For a product of multiple subsystems, apportion requirements among software, hardware and human components. Example: a secure-building access system (badges, scanners, cameras, door locks, human guards) — each requirement lands on the right subsystem.</p>`, `<p>Với sản phẩm nhiều hệ con, phân bổ yêu cầu giữa thành phần phần mềm, phần cứng và con người. Ví dụ: hệ kiểm soát ra vào toà nhà (thẻ từ, scanner, camera, khoá cửa, bảo vệ) — mỗi yêu cầu rơi vào đúng hệ con.</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Requirements analysis" practices; then Chapters 12–13, 15–16', 'Chương 3, các thực hành "Requirements analysis"; rồi Chương 12–13, 15–16']]),
  ].join('\n'),
};

/* 3G.4 — specification practices */
const G4 = {
  title: '3G.4 — Slides: specification good practices (Ch.3 · 30–35)|||3G.4 — Slide: thực hành tốt khi đặc tả (Ch.3 · 30–35)',
  slug: 'swr302-3g-4-ch3-specification',
  type: 'DOCUMENT',
  description: 'Slide 30–35: 5 thực hành đặc tả — dùng template chuẩn, ghi nguồn gốc yêu cầu, gán nhãn định danh duy nhất, ghi business rule (tài sản cấp doanh nghiệp), và đặc tả yêu cầu phi chức năng.',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.4 · Book Ch.3 slides 30–35</span>
<h2>Specification good practices (5)</h2>
<p class="lead">Writing the requirements down well — templates, origins, unique labels, business rules and nonfunctional requirements.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.4 · Slide 30–35 sách Ch.3</span>
<h2>Thực hành tốt khi đặc tả (5)</h2>
<p class="lead">Viết yêu cầu ra cho tốt — template, nguồn gốc, nhãn duy nhất, business rule và yêu cầu phi chức năng.</p>`,
    ),
    walkHead('ch3', 30, 35),
    walk('ch3', [
      [30, 'Specification practices — the list', `<p>Five next: adopt document templates · identify requirement origins · uniquely label each requirement · record business rules · specify nonfunctional requirements.</p>`, `<p>Năm cái ngay sau: dùng template tài liệu · ghi nguồn gốc yêu cầu · gán nhãn duy nhất mỗi yêu cầu · ghi business rule · đặc tả yêu cầu phi chức năng.</p>`],
      [31, '1. Adopt requirement document templates', `<p>Standardise templates — the <strong>Vision &amp; Scope</strong> (Ch.5), <strong>use case</strong> (Ch.8) and <strong>SRS</strong> (Ch.10) templates — for a consistent structure. Even without traditional documents, the template reminds you which kinds of requirements information to explore.</p>`, `<p>Chuẩn hoá template — <strong>Vision &amp; Scope</strong> (Ch.5), <strong>use case</strong> (Ch.8) và <strong>SRS</strong> (Ch.10) — để có cấu trúc nhất quán. Kể cả không dùng tài liệu truyền thống, template nhắc bạn loại thông tin yêu cầu nào cần khám phá.</p>`],
      [32, '2. Identify requirement origins', `<p><strong>Trace each requirement back to its origin</strong> (a use case, customer input, higher-level requirement, or business rule) so everyone knows why it's needed. Record affected stakeholders so you know whom to contact on a change. Do this with traceability links or a requirement attribute.</p>`, `<p><strong>Truy vết mỗi yêu cầu về nguồn gốc</strong> (use case, đầu vào khách hàng, yêu cầu cấp cao, hoặc business rule) để ai cũng biết vì sao cần. Ghi stakeholder bị ảnh hưởng để biết liên hệ ai khi có thay đổi. Làm bằng liên kết truy vết hoặc một thuộc tính yêu cầu.</p>`],
      [33, '3. Uniquely label each requirement', `<p>Give each requirement a <strong>unique ID</strong> under a convention robust to additions, deletions and changes over time. Labels enable traceability and change tracking — a prerequisite for the management practices.</p>`, `<p>Cho mỗi yêu cầu một <strong>ID duy nhất</strong> theo một quy ước bền với thêm/xoá/đổi theo thời gian. Nhãn cho phép truy vết và theo dõi thay đổi — điều kiện tiên quyết cho các thực hành quản lý.</p>`],
      [34, '4. Record business rules', `<p>Document business rules (policies, regulations, standards, algorithms) <strong>separately from a project's requirements</strong> — treat them as an <strong>enterprise-level asset</strong> because they outlive any one project. Some rules produce functional requirements that enforce them; link those requirements to their rules. (Chapter 9.)</p>`, `<p>Ghi business rule (chính sách, quy định, chuẩn, thuật toán) <strong>tách khỏi yêu cầu của một dự án</strong> — coi chúng là <strong>tài sản cấp doanh nghiệp</strong> vì chúng sống lâu hơn bất kỳ dự án nào. Một số rule sinh yêu cầu chức năng thực thi chúng; liên kết các yêu cầu đó với rule. (Chương 9.)</p>`],
      [35, '5. Specify nonfunctional requirements', `<p>A solution can do exactly what's asked yet fail on <strong>quality expectations</strong>. Go beyond functionality to capture quality attributes (performance, reliability, usability, modifiability…) with customer input on their relative importance, plus external interfaces, constraints and internationalization. (Chapter 14.)</p>`, `<p>Một giải pháp có thể làm đúng yêu cầu mà vẫn hỏng ở <strong>kỳ vọng chất lượng</strong>. Vượt qua chức năng để nắm thuộc tính chất lượng (hiệu năng, độ tin cậy, khả dụng, khả sửa đổi…) với ý kiến khách hàng về tầm quan trọng tương đối, cộng giao diện ngoài, ràng buộc và quốc tế hoá. (Chương 14.)</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Requirements specification" practices; then Chapters 9–11, 14', 'Chương 3, các thực hành "Requirements specification"; rồi Chương 9–11, 14']]),
  ].join('\n'),
};

/* 3G.5 — validation practices */
const G5 = {
  title: '3G.5 — Slides: validation good practices (Ch.3 · 36–40)|||3G.5 — Slide: thực hành tốt khi thẩm định (Ch.3 · 36–40)',
  slug: 'swr302-3g-5-ch3-validation',
  type: 'DOCUMENT',
  description: 'Slide 36–40: 4 thực hành thẩm định — review (nhất là inspection), viết test cho yêu cầu, định nghĩa acceptance criteria, và mô phỏng (simulation) yêu cầu.',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.5 · Book Ch.3 slides 36–40</span>
<h2>Validation good practices (4)</h2>
<p class="lead">Confirming the requirements are the <em>right</em> ones and are correct — review, test, acceptance criteria and simulation.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.5 · Slide 36–40 sách Ch.3</span>
<h2>Thực hành tốt khi thẩm định (4)</h2>
<p class="lead">Xác nhận yêu cầu là <em>đúng</em> yêu cầu và chính xác — review, test, acceptance criteria và simulation.</p>`,
    ),
    walkHead('ch3', 36, 40),
    walk('ch3', [
      [36, 'Validation practices — the list', `<p>Four next: review the requirements · test the requirements · define acceptance criteria · simulate the requirements.</p>`, `<p>Bốn cái ngay sau: review yêu cầu · test yêu cầu · định nghĩa acceptance criteria · mô phỏng yêu cầu.</p>`],
      [37, '1. Review the requirements', `<p><strong>Peer review — especially the rigorous form called inspection — is one of the highest-value quality practices.</strong> Assemble a small team of different perspectives (analyst, customer, developer, tester) to examine requirements, models and related info for defects. Informal reviews during development help too; train the team and adopt a process. (Chapter 17.)</p>`, `<p><strong>Peer review — nhất là dạng chặt chẽ gọi là inspection — là một trong những thực hành chất lượng giá trị nhất.</strong> Tập một nhóm nhỏ nhiều góc nhìn (analyst, khách hàng, lập trình viên, tester) để soi yêu cầu, mô hình và thông tin liên quan tìm lỗi. Review không chính thức khi phát triển cũng hữu ích; đào tạo nhóm và áp dụng quy trình. (Chương 17.)</p>`],
      [38, '2. Test the requirements', `<p>Tests are an <strong>alternative view</strong> of the requirements — writing them forces you to think how you'd tell if functionality was implemented correctly. Derive tests from user requirements, walk through them with customers, map tests to functional requirements (so none is overlooked), and use them to verify models and prototypes. Agile often uses acceptance tests <em>instead of</em> detailed functional requirements.</p>`, `<p>Test là một <strong>góc nhìn khác</strong> của yêu cầu — viết test buộc bạn nghĩ cách biết chức năng đã hiện thực đúng chưa. Suy test từ user requirement, đi qua chúng cùng khách hàng, ánh xạ test tới yêu cầu chức năng (để không sót cái nào), và dùng test để kiểm mô hình và prototype. Agile thường dùng acceptance test <em>thay cho</em> yêu cầu chức năng chi tiết.</p>`],
      [39, '3. Define acceptance criteria', `<p>Ask users how they'll judge the solution fit for use. Acceptance criteria combine: passing <strong>acceptance tests</strong> based on user requirements, satisfying specific nonfunctional requirements, tracking open defects/issues, and having infrastructure and training ready for rollout.</p>`, `<p>Hỏi người dùng họ sẽ đánh giá giải pháp dùng được ra sao. Acceptance criteria kết hợp: qua <strong>acceptance test</strong> dựa trên user requirement, thoả yêu cầu phi chức năng cụ thể, theo dõi defect/issue còn mở, và có sẵn hạ tầng và đào tạo để triển khai.</p>`],
      [40, '4. Simulate the requirements', `<p>Commercial tools let a team <strong>simulate</strong> a proposed system — executable mock-ups users can interact with to validate requirements and make design choices, "bringing requirements to life before they're cast into the concrete of code." A powerful supplement to — not a substitute for — thoughtful elicitation and analysis.</p>`, `<p>Công cụ thương mại cho nhóm <strong>mô phỏng</strong> hệ đề xuất — mock-up chạy được để người dùng tương tác nhằm validate yêu cầu và chọn thiết kế, "làm yêu cầu sống dậy trước khi đúc vào bê-tông của code." Một bổ trợ mạnh — không thay thế — cho elicitation và analysis kỹ lưỡng.</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Requirements validation" practices; then Chapter 17', 'Chương 3, các thực hành "Requirements validation"; rồi Chương 17']]),
  ].join('\n'),
};

/* 3G.6 — management practices */
const G6 = {
  title: '3G.6 — Slides: management good practices (Ch.3 · 41–49)|||3G.6 — Slide: thực hành tốt khi quản lý (Ch.3 · 41–49)',
  slug: 'swr302-3g-6-ch3-management',
  type: 'DOCUMENT',
  description: 'Slide 41–49: 8 thực hành quản lý — quy trình kiểm soát thay đổi (CCB), phân tích tác động, baseline & phiên bản, lịch sử thay đổi, theo dõi trạng thái từng yêu cầu, theo dõi issue, ma trận truy vết (traceability matrix), và dùng công cụ quản lý yêu cầu.',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.6 · Book Ch.3 slides 41–49</span>
<h2>Management good practices (8)</h2>
<p class="lead">Controlling requirements once they exist — change control, impact analysis, baselines, history, status, issues, traceability and tooling. (Depth in Chapters 27–29.)</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.6 · Slide 41–49 sách Ch.3</span>
<h2>Thực hành tốt khi quản lý (8)</h2>
<p class="lead">Kiểm soát yêu cầu khi chúng đã có — kiểm soát thay đổi, phân tích tác động, baseline, lịch sử, trạng thái, issue, truy vết và công cụ. (Sâu ở Chương 27–29.)</p>`,
    ),
    walkHead('ch3', 41, 49),
    walk('ch3', [
      [41, 'Management practices — the list', `<p>Eight next: change control process · impact analysis · baselines &amp; versions · change history · track each requirement's status · track issues · traceability matrix · use a requirements management tool.</p>`, `<p>Tám cái ngay sau: quy trình kiểm soát thay đổi · phân tích tác động · baseline &amp; phiên bản · lịch sử thay đổi · theo dõi trạng thái từng yêu cầu · theo dõi issue · ma trận truy vết · dùng công cụ quản lý yêu cầu.</p>`],
      [42, '1. Establish a change control process', `<p>Accept that changes will happen and build a mechanism so they don't cause chaos: define how changes are proposed, analysed and resolved, and route all changes through it. A <strong>Change Control Board (CCB)</strong> of stakeholders decides which to accept and sets priorities/target releases; defect-tracking tools can support it.</p>`, `<p>Chấp nhận thay đổi sẽ xảy ra và dựng cơ chế để chúng không gây hỗn loạn: định cách đề xuất, phân tích và giải quyết thay đổi, và đưa mọi thay đổi qua đó. Một <strong>Change Control Board (CCB)</strong> gồm các bên quyết cái nào nhận và đặt ưu tiên/release đích; công cụ theo dõi lỗi có thể hỗ trợ.</p>`],
      [43, '2. Perform impact analysis on changes', `<p>For each proposed change, assess its effect so the CCB decides with facts: use the <strong>traceability matrix</strong> to find the other requirements, design, code and tests to modify; identify the tasks; and estimate the effort. (Chapter 28.)</p>`, `<p>Với mỗi thay đổi đề xuất, đánh giá tác động để CCB quyết dựa trên dữ kiện: dùng <strong>ma trận truy vết</strong> để tìm các yêu cầu, thiết kế, code và test khác cần sửa; xác định công việc; và ước lượng công sức. (Chương 28.)</p>`],
      [44, '3. Establish baselines & control versions', `<p>A <strong>baseline</strong> is a set of agreed requirements (usually for a release/iteration); after baselining, change only through the change process. Give every version a unique identifier to avoid confusing drafts, baselines and previous/current versions.</p>`, `<p>Một <strong>baseline</strong> là tập yêu cầu đã thống nhất (thường cho một release/iteration); sau baseline, chỉ đổi qua quy trình thay đổi. Cho mỗi phiên bản một định danh duy nhất để khỏi nhầm bản nháp, baseline và bản trước/hiện tại.</p>`],
      [45, '4. Maintain a history of changes', `<p>Keep the change history of each requirement — you may need to revert or understand how a requirement reached its current form. Record <em>when</em> it changed, <em>what</em> changed, <em>who</em> changed it and <em>why</em>. A version-control or RM tool helps.</p>`, `<p>Giữ lịch sử thay đổi của từng yêu cầu — bạn có thể cần lùi lại hoặc hiểu vì sao yêu cầu thành hình như hiện tại. Ghi <em>khi nào</em> đổi, <em>đổi gì</em>, <em>ai</em> đổi và <em>vì sao</em>. Công cụ version-control hoặc RM giúp việc này.</p>`],
      [46, '5. Track the status of each requirement', `<p>Keep a repository with one record per requirement and store key attributes including <strong>status</strong> (proposed, approved, implemented, verified). Counting requirements by status at any time gives real insight into overall project progress.</p>`, `<p>Giữ một kho với một bản ghi cho mỗi yêu cầu và lưu các thuộc tính chính gồm <strong>trạng thái</strong> (đề xuất, duyệt, đã hiện thực, đã kiểm chứng). Đếm số yêu cầu theo trạng thái bất kỳ lúc nào cho cái nhìn thật về tiến độ dự án.</p>`],
      [47, '6. Track requirements issues', `<p>On a complex project, open questions, gaps and review findings are easy to lose. Use issue-tracking tools, assign a <strong>single owner</strong> per issue, and monitor status to judge the overall state of the requirements.</p>`, `<p>Trên dự án phức tạp, câu hỏi mở, lỗ hổng và phát hiện review dễ bị lạc. Dùng công cụ theo dõi issue, gán <strong>một chủ sở hữu</strong> cho mỗi issue, và theo dõi trạng thái để đánh giá tình trạng chung của yêu cầu.</p>`],
      [48, '7. Maintain a requirements traceability matrix', `<p>Link each functional requirement to the design and code that implement it and the tests that verify it — the <strong>traceability matrix</strong> confirms all requirements are implemented and verified, aids maintenance, and connects functional requirements up to their higher-level origins. <strong>Populate it during development, not at the end</strong>; tooling is essential beyond small projects. (Chapter 29.)</p>`, `<p>Liên kết mỗi yêu cầu chức năng với thiết kế và code hiện thực nó và test kiểm chứng nó — <strong>ma trận truy vết</strong> xác nhận mọi yêu cầu đã được hiện thực và kiểm chứng, hỗ trợ bảo trì, và nối yêu cầu chức năng lên nguồn gốc cấp cao. <strong>Điền nó trong lúc phát triển, không phải ở cuối</strong>; cần công cụ với dự án không nhỏ. (Chương 29.)</p>`],
      [49, '8. Use a requirements management tool', `<p>Commercial RM tools store requirements of all types in a database and <strong>automate many of the other management practices</strong> above (status, history, traceability, versioning). (Chapter 30.)</p>`, `<p>Công cụ RM thương mại lưu mọi loại yêu cầu trong CSDL và <strong>tự động hoá nhiều thực hành quản lý</strong> ở trên (trạng thái, lịch sử, truy vết, phiên bản). (Chương 30.)</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Requirements management" practices; then Chapters 27–30', 'Chương 3, các thực hành "Requirements management"; rồi Chương 27–30']]),
  ].join('\n'),
};

/* 3G.7 — knowledge & project management practices */
const G7 = {
  title: '3G.7 — Slides: knowledge & project-management good practices (Ch.3 · 50–65)|||3G.7 — Slide: thực hành tốt về tri thức & quản lý dự án (Ch.3 · 50–65)',
  slug: 'swr302-3g-7-ch3-knowledge-pm',
  type: 'DOCUMENT',
  description: 'Slide 50–65: 5 thực hành tri thức (đào tạo BA, giáo dục stakeholder & developer, định nghĩa quy trình RE, glossary) và 9 thực hành quản lý dự án (chọn vòng đời, kế hoạch, ước lượng công sức, dựa kế hoạch trên yêu cầu, người quyết, thương lượng lại cam kết, rủi ro, theo dõi công sức, bài học kinh nghiệm).',
  content: [
    bi(
      `<span class="eyebrow">RE Good Practices · Lesson 3G.7 · Book Ch.3 slides 50–65</span>
<h2>Knowledge &amp; project-management good practices (5 + 9)</h2>
<p class="lead">The two enabling groups: <strong>knowledge</strong> (training, education, process, glossary) and <strong>project management</strong> (lifecycle, planning, estimation, risk, lessons learned). These make everything else stick.</p>`,
      `<span class="eyebrow">Thực hành tốt · Bài 3G.7 · Slide 50–65 sách Ch.3</span>
<h2>Thực hành tốt về tri thức &amp; quản lý dự án (5 + 9)</h2>
<p class="lead">Hai nhóm nền: <strong>tri thức</strong> (đào tạo, giáo dục, quy trình, glossary) và <strong>quản lý dự án</strong> (vòng đời, kế hoạch, ước lượng, rủi ro, bài học). Chúng làm mọi thứ khác trụ được.</p>`,
    ),
    walkHead('ch3', 50, 65),
    walk('ch3', [
      [50, 'Knowledge practices — the list', `<p>Five next: train BAs · educate stakeholders about requirements · educate developers about the domain · define a requirements engineering process · create a glossary.</p>`, `<p>Năm cái ngay sau: đào tạo BA · giáo dục stakeholder về yêu cầu · giáo dục developer về miền ứng dụng · định nghĩa quy trình RE · tạo glossary.</p>`],
      [51, '1. Train business analysts', `<p>Everyone doing BA tasks (with or without the title) needs requirements training — specialists need several days across the diverse BA activities. Beyond a toolkit of techniques, a skilled analyst is patient, well-organised, communicates well and understands the domain. (Chapter 4.)</p>`, `<p>Ai làm việc BA (dù có chức danh hay không) đều cần đào tạo yêu cầu — chuyên viên cần vài ngày cho các hoạt động BA đa dạng. Ngoài bộ kỹ thuật, một analyst giỏi kiên nhẫn, ngăn nắp, giao tiếp tốt và hiểu miền. (Chương 4.)</p>`],
      [52, '2. Educate stakeholders about requirements', `<p>The best requirements classes mix <strong>all functional areas</strong>, not just BAs. Give participating users 1–2 days on terminology, key practices and why requirements matter; managers benefit too. It's also great <strong>team building</strong> — each side appreciates the others' challenges.</p>`, `<p>Lớp yêu cầu tốt nhất trộn <strong>mọi bộ phận</strong>, không chỉ BA. Cho người dùng tham gia 1–2 ngày về thuật ngữ, thực hành chính và vì sao yêu cầu quan trọng; quản lý cũng hưởng lợi. Nó còn là <strong>gắn kết nhóm</strong> — mỗi bên hiểu khó khăn của bên kia.</p>`],
      [53, '3. Educate developers about the application domain', `<p>Run a seminar on the customer's business, terminology and objectives to cut confusion and rework. <strong>“Day-in-the-life”</strong> visits (developers shadowing users) and pairing each developer with a <strong>“user buddy”</strong> to translate jargon are sound investments.</p>`, `<p>Tổ chức seminar về nghiệp vụ, thuật ngữ và mục tiêu của khách hàng để giảm nhầm lẫn và làm lại. Chuyến <strong>“một ngày trong đời”</strong> (developer đi theo user) và ghép mỗi developer với một <strong>“user buddy”</strong> để dịch thuật ngữ là khoản đầu tư đáng.</p>`],
      [54, '4. Define a requirements engineering process', `<p>Document the steps your organisation follows to elicit, analyse, specify, validate and manage requirements. Guidance yields consistent quality and makes planning each project's requirements tasks, schedule and resources easier. The PM should put requirements activities as <strong>discrete tasks</strong> in the plan.</p>`, `<p>Ghi lại các bước tổ chức bạn theo để elicit, analyse, specify, validate và manage yêu cầu. Hướng dẫn cho chất lượng nhất quán và giúp lập kế hoạch công việc, lịch, nguồn lực yêu cầu dễ hơn. PM nên đưa hoạt động yêu cầu thành <strong>công việc riêng</strong> trong kế hoạch.</p>`],
      [55, '5. Create a glossary', `<p>A <strong>glossary</strong> of domain terms minimises misunderstanding — include synonyms, acronyms, multi-meaning terms and terms with both domain and everyday meanings. It's a reusable enterprise asset, and a good task for new team members (who are most confused by the jargon).</p>`, `<p>Một <strong>glossary</strong> các thuật ngữ miền giảm hiểu lầm — gồm từ đồng nghĩa, viết tắt, từ đa nghĩa và từ vừa nghĩa miền vừa nghĩa đời thường. Nó là tài sản doanh nghiệp tái dùng, và là việc tốt cho thành viên mới (những người bối rối nhất với thuật ngữ).</p>`],
      [56, 'Project-management practices — the list', `<p>Nine next: select a lifecycle · plan the requirements approach · estimate requirements effort · base project plans on requirements · identify decision makers · renegotiate commitments on change · manage requirements risks · track requirements effort · review lessons learned.</p>`, `<p>Chín cái ngay sau: chọn vòng đời · lập kế hoạch tiếp cận yêu cầu · ước lượng công sức yêu cầu · dựa kế hoạch dự án trên yêu cầu · xác định người quyết · thương lượng lại cam kết khi có thay đổi · quản lý rủi ro yêu cầu · theo dõi công sức yêu cầu · rà bài học kinh nghiệm.</p>`],
      [57, '1. Select an appropriate development life cycle', `<p>Define several lifecycles for different project types and degrees of requirements uncertainty; each PM selects and adapts the best fit, with requirements activities included. Where possible, deliver functionality <strong>incrementally</strong> for early value. (Chapter 20.)</p>`, `<p>Định nghĩa vài vòng đời cho các loại dự án và mức độ bất định yêu cầu khác nhau; mỗi PM chọn và điều chỉnh cái hợp nhất, có kèm hoạt động yêu cầu. Khi được, giao chức năng <strong>tăng dần</strong> để có giá trị sớm. (Chương 20.)</p>`],
      [58, '2. Plan the requirements approach', `<p>Each team plans how it will develop and manage requirements. An <strong>elicitation plan</strong> ensures the right stakeholders give input at the right stages with the right techniques; the BA and PM ensure requirements tasks/deliverables appear in the project plan.</p>`, `<p>Mỗi nhóm lập kế hoạch cách phát triển và quản lý yêu cầu. Một <strong>elicitation plan</strong> đảm bảo đúng stakeholder cho đầu vào ở đúng giai đoạn với đúng kỹ thuật; BA và PM đảm bảo công việc/sản phẩm yêu cầu có trong kế hoạch dự án.</p>`],
      [59, '3. Estimate requirements effort', `<p>Stakeholders want to know how long requirements will take and what share of total effort they should get. It depends on many factors — consciously weigh those pushing you to spend more or less than average so requirements form a solid foundation.</p>`, `<p>Stakeholder muốn biết yêu cầu tốn bao lâu và chiếm bao nhiêu phần công sức. Tuỳ nhiều yếu tố — cân nhắc có ý thức những yếu tố khiến bạn tốn nhiều hay ít hơn trung bình để yêu cầu tạo nền vững.</p>`],
      [60, '4. Base project plans on requirements', `<p>Build plans and schedules <strong>iteratively</strong> as scope and detail clarify; start by estimating the effort to develop user requirements from the vision and scope. Early estimates on fuzzy requirements are highly uncertain but improve with understanding. On agile, timeboxed iterations mean adjusting scope to fit fixed schedule/resources. (Chapter 19.)</p>`, `<p>Dựng kế hoạch và lịch <strong>lặp</strong> khi phạm vi và chi tiết rõ dần; bắt đầu bằng ước lượng công sức phát triển user requirement từ vision và scope. Ước lượng sớm trên yêu cầu mờ rất bất định nhưng cải thiện theo hiểu biết. Với agile, iteration timebox nghĩa là nắn phạm vi vừa lịch/nguồn lực cố định. (Chương 19.)</p>`],
      [61, '5. Identify requirements decision makers', `<p>Development means constant decisions — resolving conflicting inputs, selecting COTS components, evaluating change requests. Because so many involve requirements, <strong>identify and empower the requirements decision makers early</strong>, before the first big decision hits. (Chapter 2.)</p>`, `<p>Phát triển nghĩa là quyết định liên tục — giải xung đột đầu vào, chọn thành phần COTS, đánh giá yêu cầu thay đổi. Vì nhiều cái dính tới yêu cầu, <strong>xác định và trao quyền cho người quyết yêu cầu từ sớm</strong>, trước khi quyết định lớn đầu tiên ập đến. (Chương 2.)</p>`],
      [62, '6. Renegotiate commitments when requirements change', `<p>A team commits to deliver certain requirements within a schedule and budget. When new requirements come in, check if the commitments still hold with available resources; if not, communicate reality to management and <strong>negotiate new, achievable commitments</strong>.</p>`, `<p>Nhóm cam kết giao một số yêu cầu trong một lịch và ngân sách. Khi yêu cầu mới đến, kiểm xem cam kết còn giữ được với nguồn lực hiện có không; nếu không, báo thực tế cho quản lý và <strong>thương lượng cam kết mới, khả thi</strong>.</p>`],
      [63, '7. Manage requirements-related risks', `<p>Unanticipated events can wreck an unprepared project. As part of risk management, <strong>identify and document requirements risks</strong>, brainstorm mitigations, implement them, and track their progress and effectiveness. (Chapter 32.)</p>`, `<p>Sự kiện bất ngờ có thể phá một dự án không chuẩn bị. Trong quản lý rủi ro, <strong>xác định và ghi rủi ro yêu cầu</strong>, nghĩ cách giảm thiểu, thực hiện, và theo dõi tiến độ và hiệu quả. (Chương 32.)</p>`],
      [64, '8. Track the effort spent on requirements', `<p>Record the effort your team spends on requirements development and management to <strong>improve future estimates</strong>, and monitor the effect of your requirements activities to judge the return on investment.</p>`, `<p>Ghi công sức nhóm dành cho phát triển và quản lý yêu cầu để <strong>cải thiện ước lượng tương lai</strong>, và theo dõi ảnh hưởng của hoạt động yêu cầu để đánh giá lợi tức đầu tư.</p>`],
      [65, '9. Review lessons learned on other projects', `<p>A learning organisation runs periodic <strong>retrospectives</strong> to collect lessons from completed projects or earlier iterations. Studying past requirements experiences helps PMs and BAs steer more confidently next time. (Chapter 31.)</p>`, `<p>Một tổ chức học hỏi chạy <strong>retrospective</strong> định kỳ để thu bài học từ dự án đã xong hoặc iteration trước. Nghiên cứu kinh nghiệm yêu cầu quá khứ giúp PM và BA cầm lái tự tin hơn lần sau. (Chương 31.)</p>`],
    ]),
    books([['wiegers', 'Chapter 3, "Knowledge" and "Project management" practices; then Chapters 4, 19–20, 31–32', 'Chương 3, các thực hành "Knowledge" và "Project management"; rồi Chương 4, 19–20, 31–32']]),
  ].join('\n'),
};

/** The whole book-Ch.3 survey as one academy section. */
export default {
  title: 'RE Good Practices — the big picture (book Ch.3)|||Thực hành tốt kỹ nghệ yêu cầu — bức tranh tổng (Ch.3 sách)',
  description: 'Toàn bộ ~50 thực hành tốt của kỹ nghệ yêu cầu (Chương 3 sách Wiegers), tách 7 bài theo nhóm: tổng quan, elicitation, analysis, specification, validation, management, knowledge & project management. Là bản đồ để đi vào các chương chi tiết.',
  lessons: [G1, G2, G3, G4, G5, G6, G7],
};
