/**
 * SWR302 · New section — book chapter Ch.30 "Tools for requirements engineering"
 * (16 slides). A stand-alone section, split into TWO focused lessons: RD & RM
 * tools + capabilities (1–11), and selecting/implementing a tool (12–16).
 * Exported as a SECTION object inserted into the sections array. Grounded
 * slide-by-slide in CHAPTER_30_Tools for requirements engineering.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 30T.1 — RD & RM tools, capabilities */
const G1 = {
  title: '30T.1 — Slides: RD & RM tools and their capabilities (Ch.30 · 1–11)|||30T.1 — Slide: công cụ RD & RM và năng lực (Ch.30 · 1–11)',
  slug: 'swr302-30t-1-ch30-tools',
  type: 'DOCUMENT',
  description: 'Slide 1–11: công cụ requirements development (elicitation, prototyping, modeling — kém trưởng thành hơn); công cụ requirements management (DB đa người dùng, 10 lợi ích: version/attribute/impact/status/access/reuse...); và năng lực RM tool (kiểu yêu cầu, nhãn phân cấp, import, trace, tích hợp công cụ khác — Fig 30-1/30-2).',
  content: [
    bi(
      `<span class="eyebrow">Tools for requirements engineering · Lesson 30T.1 · Book Ch.30 slides 1–11</span>
<h2>RD &amp; RM tools and their capabilities</h2>
<p class="lead">Two families of tools: requirements <strong>development</strong> tools (elicitation, prototyping, modeling) that help you discover and craft requirements, and requirements <strong>management</strong> tools — a multiuser database that fixes the limits of storing requirements in documents. No tool replaces thinking and peer review.</p>`,
      `<span class="eyebrow">Công cụ kỹ nghệ yêu cầu · Bài 30T.1 · Slide 1–11 sách Ch.30</span>
<h2>Công cụ RD &amp; RM và năng lực của chúng</h2>
<p class="lead">Hai họ công cụ: công cụ <strong>development</strong> (elicitation, prototyping, modeling) giúp bạn khám phá và soạn yêu cầu, và công cụ <strong>management</strong> — một database đa người dùng chữa giới hạn của việc lưu yêu cầu trong tài liệu. Không công cụ nào thay được suy nghĩ và peer review.</p>`,
    ),
    walkHead('ch30', 1, 11),
    walk('ch30', [
      [1, 'Tools for requirements engineering', `<p>Title slide — the benefits of requirements tools and the general capabilities you can expect, alongside their real costs: annual maintenance fees, upgrades, installation, configuration, administration, vendor support and user training.</p>`, `<p>Slide bìa — lợi ích của công cụ yêu cầu và các năng lực chung có thể mong đợi, cùng chi phí thật của chúng: phí bảo trì hằng năm, nâng cấp, cài đặt, cấu hình, quản trị, hỗ trợ nhà cung cấp và đào tạo người dùng.</p>`],
      [2, 'Objectives & contents', `<p>Understand the purpose of requirements tools and that dozens of commercial products exist — but every tool brings <strong>maintenance fees, upgrades, installation, configuration, administration, support and training</strong> costs. Topics: requirements development tools, requirements management tools, RM tool capabilities, and selecting/implementing a tool.</p>`, `<p>Hiểu mục đích của công cụ yêu cầu và rằng có hàng chục sản phẩm thương mại — nhưng mọi công cụ mang chi phí <strong>phí bảo trì, nâng cấp, cài đặt, cấu hình, quản trị, hỗ trợ và đào tạo</strong>. Chủ đề: công cụ RD, công cụ RM, năng lực RM tool, và chọn/hiện thực một công cụ.</p>`],
      [3, 'Requirements development (RD) tools', `<p>RD tools help BAs work with stakeholders to <strong>elicit and document requirements more effectively</strong> than manual methods. Since stakeholders consume information <strong>textually, visually, or audibly</strong>, RD tools improve collaboration by accommodating varied communication methods. RD tools subdivide into <strong>elicitation, prototyping, and modeling</strong> tools; some provide all three (and even RM capabilities). In general, RD tools are <strong>less mature than RM tools</strong> and their project impact is typically smaller.</p>`, `<p>Công cụ RD giúp BA làm với stakeholder để <strong>khơi gợi và ghi yêu cầu hiệu quả hơn</strong> phương pháp thủ công. Vì stakeholder tiêu thụ thông tin <strong>bằng chữ, hình ảnh, hoặc âm thanh</strong>, công cụ RD cải thiện cộng tác bằng cách đón nhiều cách giao tiếp. Công cụ RD chia thành <strong>elicitation, prototyping, và modeling</strong>; vài cái cung cấp cả ba (và cả năng lực RM). Nhìn chung, công cụ RD <strong>kém trưởng thành hơn công cụ RM</strong> và tác động dự án thường nhỏ hơn.</p>`],
      [4, '1. Elicitation tools', `<p>Elicitation tools include those for <strong>recording notes</strong> during sessions — organizing ideas and annotating follow-up questions, action items and core terms. <strong>Mind-mapping</strong> tools aid brainstorming and organizing. <strong>Audio pens/recorders</strong> allow playback (some tie audio to the text written at the same moment, so you can replay a specific part). Tools that <strong>scan for vague/ambiguous words</strong> help write clearer requirements; some <strong>auto-generate diagrams from text</strong>; and certain tools enable <strong>collaborative voting</strong> to prioritize requirements.</p>`, `<p>Công cụ elicitation gồm cái để <strong>ghi chú</strong> trong phiên — tổ chức ý và chú thích câu hỏi tiếp theo, action item và thuật ngữ lõi. Công cụ <strong>mind-mapping</strong> hỗ trợ brainstorm và tổ chức. <strong>Audio pen/máy ghi</strong> cho phát lại (vài cái buộc audio với chữ viết cùng lúc, nên phát lại một phần cụ thể được). Công cụ <strong>quét từ mơ hồ/nhập nhằng</strong> giúp viết yêu cầu rõ hơn; vài cái <strong>tự sinh sơ đồ từ chữ</strong>; và vài công cụ cho <strong>bỏ phiếu cộng tác</strong> để ưu tiên yêu cầu.</p>`],
      [5, '2. Prototyping tools', `<p>Prototyping tools create work products from electronic mock-ups to full application simulations. Simple tools offer basic shapes for <strong>low-fidelity wireframes</strong> (even PowerPoint can mock up screens and navigation or annotate screenshots). Sophisticated tools enable <strong>clickable mocked-up functionality</strong>; some support version control, feedback management, requirements linking and code generation. Heed Chapter 15's cautions — don't over-invest in prototypes. For high-fidelity prototypes, make clear they're <strong>just possible models</strong>; a <strong>"hand-drawn" style</strong> helps manage customer expectations.</p>`, `<p>Công cụ prototyping tạo sản phẩm từ mock-up điện tử tới mô phỏng ứng dụng đầy đủ. Công cụ đơn giản cho hình cơ bản để làm <strong>wireframe low-fidelity</strong> (kể cả PowerPoint mock màn hình và điều hướng hay chú thích screenshot). Công cụ tinh vi cho <strong>chức năng mock bấm được</strong>; vài cái hỗ trợ version control, quản lý phản hồi, liên kết yêu cầu và sinh code. Nghe lời cảnh báo Chương 15 — đừng đầu tư quá vào prototype. Với prototype high-fidelity, làm rõ chúng <strong>chỉ là mô hình khả dĩ</strong>; một <strong>kiểu "vẽ tay"</strong> giúp quản lý kỳ vọng khách.</p>`],
      [6, '3. Modeling tools', `<p>Modeling tools help BAs draw diagrams with <strong>standard shapes, notations and syntax</strong> per established conventions, often with templates and examples; they <strong>auto-connect shapes</strong> to speed drawing and ensure correctness, and produce cleaner, more consistent diagrams than manual drawing (specialized tools drag connected arrows/labels when you move a symbol — general drawing tools may not). Many RM tools include modeling; the most sophisticated let you <strong>trace requirements to models or to specific model elements</strong> (e.g. trace requirements to steps in a swimlane diagram). Crucially, <strong>no tool tells you if a requirement or model element is missing, logically incorrect, or unnecessary</strong> — tools help represent and spot some errors, but don't eliminate thinking and peer review.</p>`, `<p>Công cụ modeling giúp BA vẽ sơ đồ với <strong>hình, ký hiệu và cú pháp chuẩn</strong> theo quy ước, thường có template và ví dụ; chúng <strong>tự nối hình</strong> để tăng tốc vẽ và bảo đảm đúng, và cho sơ đồ sạch, nhất quán hơn vẽ tay (công cụ chuyên kéo mũi tên/nhãn nối khi bạn di chuyển một ký hiệu — công cụ vẽ chung có thể không). Nhiều công cụ RM gồm modeling; cái tinh vi nhất cho <strong>trace yêu cầu tới mô hình hoặc phần tử mô hình cụ thể</strong> (vd trace yêu cầu tới bước trong một swimlane). Quan trọng, <strong>không công cụ nào cho biết một yêu cầu hay phần tử mô hình thiếu, sai logic, hay không cần</strong> — công cụ giúp biểu diễn và bắt vài lỗi, nhưng không loại bỏ suy nghĩ và peer review.</p>`],
      [7, 'Requirements management (RM) tools', `<p>An RM tool stores requirements in a <strong>multiuser database</strong>, a robust answer to the limits of documents. Small teams can just enter requirement text and a few attributes; larger teams benefit from <strong>importing requirements from source documents, defining attribute values, filtering/displaying the database, exporting in various formats, defining traceability links, and connecting requirements to items in other dev tools</strong>. RM tools are <strong>more plentiful and mature</strong> than RD tools — fairly, because their problem (storing and manipulating requirements) is more tractable than helping a BA discover knowledge and craft correct requirements. Some tools combine RD and RM.</p>`, `<p>Một công cụ RM lưu yêu cầu trong một <strong>database đa người dùng</strong>, một đáp án vững cho giới hạn của tài liệu. Đội nhỏ chỉ cần nhập chữ yêu cầu và vài thuộc tính; đội lớn hưởng lợi từ <strong>import yêu cầu từ tài liệu nguồn, định giá trị thuộc tính, lọc/hiển thị database, export nhiều định dạng, định trace link, và nối yêu cầu tới mục trong công cụ dev khác</strong>. Công cụ RM <strong>phong phú và trưởng thành hơn</strong> công cụ RD — công bằng mà nói, vì vấn đề của chúng (lưu và thao tác yêu cầu) dễ hơn giúp BA khám phá kiến thức và soạn yêu cầu đúng. Vài công cụ kết hợp RD và RM.</p>`],
      [8, 'Benefits of using an RM tool', `<p>An RM tool can: <strong>manage versions and changes</strong> (baselining, per-requirement change history); <strong>store requirement attributes</strong> (system-defined like creation date/version, plus your own of various types); <strong>facilitate impact analysis</strong> via tracing; <strong>identify missing/extraneous requirements</strong> through trace gaps; <strong>track requirement status</strong>; <strong>control access</strong> (per-user/group permissions); <strong>communicate with stakeholders</strong> (a master repository so everyone works from one set); <strong>reuse requirements</strong> across projects; <strong>track issue status</strong> (linking issues to related requirements); and <strong>generate tailored subsets</strong> for a particular purpose.</p>`, `<p>Một công cụ RM có thể: <strong>quản lý phiên bản và thay đổi</strong> (baselining, lịch sử thay đổi mỗi yêu cầu); <strong>lưu thuộc tính yêu cầu</strong> (hệ định như ngày tạo/phiên bản, cộng của bạn nhiều kiểu); <strong>hỗ trợ impact analysis</strong> qua tracing; <strong>nhận diện yêu cầu thiếu/thừa</strong> qua khe trace; <strong>theo dõi trạng thái yêu cầu</strong>; <strong>kiểm soát truy cập</strong> (quyền mỗi người/nhóm); <strong>giao tiếp với stakeholder</strong> (một repository chủ để mọi người làm từ một tập); <strong>tái dùng yêu cầu</strong> qua các dự án; <strong>theo dõi trạng thái issue</strong> (nối issue tới yêu cầu liên quan); và <strong>sinh tập con tuỳ chỉnh</strong> cho một mục đích.</p>`],
      [9, 'RM tool capabilities (features)', `<p>Figure 30-1 shows common RM tool features. RM tools let you define <strong>different requirement types</strong> (business, use case, functional, hardware, constraints) with strong <strong>per-type attribute</strong> support — a major advantage over documents.</p>`, `<p>Hình 30-1 chỉ các tính năng RM tool phổ biến. Công cụ RM cho định <strong>các kiểu yêu cầu khác nhau</strong> (business, use case, functional, hardware, constraint) với hỗ trợ <strong>thuộc tính theo kiểu</strong> mạnh — một ưu thế lớn so với tài liệu.</p>`],
      [10, 'RM tool capabilities (in depth)', `<p>RM tools support <strong>hierarchical numeric labels</strong> plus a unique internal ID (often a type prefix like <code>UR</code> + an integer); <strong>import</strong> from various source formats and incorporate <strong>nontextual objects</strong> (graphics, spreadsheets). A specification document is then just a <strong>report generated by query</strong>, formatted to look like an SRS (some tools sync offline edits back to the database). Features include <strong>user groups and CRUD permissions</strong>, learning aids (tutorials, sample projects), and robust <strong>tracing</strong> (links between two object types or same-type objects, and element-level model links). Some <strong>agile PM tools</strong> also provide RM capabilities — managing/prioritizing backlogs, allocating requirements to iterations, and generating test cases from requirements.</p>`, `<p>Công cụ RM hỗ trợ <strong>nhãn số phân cấp</strong> cộng một ID nội bộ duy nhất (thường một prefix kiểu như <code>UR</code> + một số nguyên); <strong>import</strong> từ nhiều định dạng nguồn và đưa vào <strong>đối tượng phi văn bản</strong> (đồ hoạ, spreadsheet). Một tài liệu đặc tả rồi chỉ là một <strong>report sinh theo query</strong>, định dạng trông như SRS (vài công cụ đồng bộ sửa offline về database). Tính năng gồm <strong>nhóm người dùng và quyền CRUD</strong>, trợ giúp học (tutorial, dự án mẫu), và <strong>tracing</strong> vững (link giữa hai kiểu đối tượng hoặc cùng kiểu, và link mô hình cấp phần tử). Vài <strong>công cụ PM agile</strong> cũng cung cấp năng lực RM — quản lý/ưu tiên backlog, phân yêu cầu cho iteration, và sinh test case từ yêu cầu.</p>`],
      [11, 'Integration with other tools', `<p>RM tools often <strong>integrate with other application-development tools</strong> (Figure 30-2). As Chapter 29 describes, individual requirements can be linked to objects in those tools — e.g. trace requirements to <strong>design elements in a design-modeling tool</strong> or to <strong>tests in a test-management tool</strong>. When selecting an RM product, determine whether it can <strong>exchange data with your other tools</strong>: consider how you'd define trace links between functional requirements and design/code elements, and how you'd verify that all tests linked to a functional requirement have passed.</p>`, `<p>Công cụ RM thường <strong>tích hợp với công cụ phát triển ứng dụng khác</strong> (Hình 30-2). Như Chương 29 mô tả, từng yêu cầu có thể nối tới đối tượng trong các công cụ đó — vd trace yêu cầu tới <strong>design element trong công cụ design-modeling</strong> hoặc tới <strong>test trong công cụ test-management</strong>. Khi chọn một sản phẩm RM, xác định nó có thể <strong>trao đổi dữ liệu với công cụ khác của bạn</strong> không: cân nhắc cách định trace link giữa functional requirement và design/code element, và cách verify mọi test nối tới một functional requirement đã pass.</p>`],
    ]),
    books([['wiegers', 'Chapter 30, "Requirements development tools", "Requirements management tools" (Figure 30-1), "RM tool capabilities" (Figure 30-2)', 'Chương 30, "Requirements development tools", "Requirements management tools" (Hình 30-1), "RM tool capabilities" (Hình 30-2)']]),
  ].join('\n'),
};

/* 30T.2 — selecting & implementing */
const G2 = {
  title: '30T.2 — Slides: selecting & implementing a requirements tool (Ch.30 · 12–16)|||30T.2 — Slide: chọn & triển khai một công cụ yêu cầu (Ch.30 · 12–16)',
  slug: 'swr302-30t-2-ch30-selecting',
  type: 'DOCUMENT',
  description: 'Slide 12–16: chọn công cụ (quy trình 7 bước có trọng số + hai câu hỏi cuối); thiết lập công cụ & quy trình (cam kết dùng, không nhét cả SRS thành 1 type, đặt ngày database là repository chính thức); và tạo điều kiện adoption (tool advocate, đào tạo, pilot dự án không trọng yếu).',
  content: [
    bi(
      `<span class="eyebrow">Tools for requirements engineering · Lesson 30T.2 · Book Ch.30 slides 12–16</span>
<h2>Selecting &amp; implementing a requirements tool</h2>
<p class="lead">A tool can lift your practices — but only if you select the right one and get teams to actually adopt it. This lesson: a weighted selection process, how to set up the tool and processes, and how to overcome the culture change that adoption demands.</p>`,
      `<span class="eyebrow">Công cụ kỹ nghệ yêu cầu · Bài 30T.2 · Slide 12–16 sách Ch.30</span>
<h2>Chọn &amp; triển khai một công cụ yêu cầu</h2>
<p class="lead">Một công cụ có thể nâng tầm thực hành — nhưng chỉ khi bạn chọn đúng và khiến đội thật sự nhận nó. Bài này: quy trình chọn có trọng số, cách thiết lập công cụ và quy trình, và cách vượt thay đổi văn hoá mà adoption đòi hỏi.</p>`,
    ),
    walkHead('ch30', 12, 16),
    walk('ch30', [
      [12, 'Selecting and implementing — overview', `<p>Any of these tools can raise your requirements practices to a higher plane — but success depends on <strong>selecting the most appropriate tool</strong> for your organization and <strong>getting teams to adopt it</strong> as routine. Three parts follow: selecting a tool, setting up the tool and processes, and facilitating user adoption.</p>`, `<p>Bất kỳ công cụ nào cũng nâng thực hành yêu cầu lên tầm cao hơn — nhưng thành công phụ thuộc vào <strong>chọn công cụ phù hợp nhất</strong> cho tổ chức và <strong>khiến đội nhận nó</strong> thành thường quy. Ba phần theo sau: chọn công cụ, thiết lập công cụ và quy trình, và tạo điều kiện adoption.</p>`],
      [13, '1. Selecting a tool', `<p>Select on the combination of <strong>features, platform and pricing</strong> that fits your environment and culture. A <strong>BA should lead</strong> — defining criteria and doing the assessment (some companies outsource to consultants). The process: <strong>1.</strong> identify your tool requirements as evaluation criteria; <strong>2.</strong> prioritize and <strong>weight</strong> them; <strong>3.</strong> set up demos / get evaluation copies; <strong>4.</strong> score each tool consistently; <strong>5.</strong> compute a <strong>weighted total</strong>; <strong>6.</strong> use each strong tool on a <strong>real project</strong> to see if it behaves as scored; <strong>7.</strong> combine scores, licensing/ongoing costs, vendor support, current-user input and subjective impressions. Two great final questions: <em>"Which tool would you most want to use?"</em> and <em>"Which would you be most upset to be forced to use?"</em></p>`, `<p>Chọn theo tổ hợp <strong>tính năng, nền và giá</strong> hợp môi trường và văn hoá. Một <strong>BA nên dẫn</strong> — định tiêu chí và làm đánh giá (vài công ty thuê tư vấn ngoài). Quy trình: <strong>1.</strong> nhận diện yêu cầu công cụ làm tiêu chí đánh giá; <strong>2.</strong> ưu tiên và <strong>gán trọng số</strong>; <strong>3.</strong> dựng demo / lấy bản dùng thử; <strong>4.</strong> chấm mỗi công cụ nhất quán; <strong>5.</strong> tính <strong>tổng có trọng số</strong>; <strong>6.</strong> dùng mỗi công cụ điểm cao trên một <strong>dự án thật</strong> xem nó có hành xử như điểm; <strong>7.</strong> kết hợp điểm, chi phí license/vận hành, hỗ trợ nhà cung cấp, ý người dùng hiện tại và ấn tượng chủ quan. Hai câu hỏi cuối hay: <em>"Công cụ nào bạn muốn dùng nhất?"</em> và <em>"Cái nào bạn bực nhất nếu bị ép dùng?"</em></p>`],
      [14, '2. Setting up the tool and processes', `<p>Recognize the effort: <strong>installing, loading requirements, defining attributes and trace links, keeping content current, defining access groups, and adapting processes</strong>. Make an <strong>organization-wide commitment to actually use it</strong> — don't let it become expensive shelfware. Suggestions: assign an <strong>experienced BA to own setup</strong>; don't treat every SRS section as a separate requirement type, but don't stuff the whole SRS into one type either; set access privileges to allow enough input <strong>without letting everyone change everything</strong>; don't capture requirements directly in the tool during early elicitation workshops (store them once they stabilize, for visibility and refinement); use RD tools in elicitation only if they won't slow discovery; don't define <strong>trace links until requirements stabilize</strong>; and set a <strong>date after which the database is the definitive repository</strong> — after which requirements living only in documents aren't valid.</p>`, `<p>Nhận ra công sức: <strong>cài đặt, nạp yêu cầu, định thuộc tính và trace link, giữ nội dung cập nhật, định nhóm truy cập, và thích nghi quy trình</strong>. Ra <strong>cam kết toàn tổ chức thật sự dùng nó</strong> — đừng để nó thành shelfware đắt tiền. Gợi ý: giao một <strong>BA có kinh nghiệm sở hữu setup</strong>; đừng coi mọi mục SRS là một requirement type riêng, nhưng cũng đừng nhét cả SRS vào một type; đặt quyền truy cập cho đủ input <strong>mà không để mọi người đổi mọi thứ</strong>; đừng nắm yêu cầu thẳng vào công cụ khi workshop elicitation sớm (lưu khi chúng ổn định, để hữu hình và tinh chỉnh); dùng công cụ RD trong elicitation chỉ nếu chúng không làm chậm khám phá; đừng định <strong>trace link tới khi yêu cầu ổn định</strong>; và đặt một <strong>ngày sau đó database là repository chính thức</strong> — sau đó yêu cầu chỉ nằm trong tài liệu không còn hợp lệ.</p>`],
      [15, '3. Facilitating user adoption', `<p>Buying a tool is easy; <strong>changing culture and processes to accept it is much harder</strong>. Some people prefer not to share an imperfect requirement set, yet the database is open for all. People resist changing familiar habits (working in documents). Eventually the tool won't require more time, but users must first climb the <strong>learning curve</strong>. Suggestions: identify a <strong>tool advocate</strong> (a local enthusiast/experienced BA who masters it, mentors others, and owns adoption); overcome the belief that the tool adds no value by <strong>sharing stories of harm caused by its absence</strong>; <strong>train</strong> people rather than expecting them to figure out the full capabilities alone; and <strong>don't bet a project's success on a first-time tool</strong> — begin with a <strong>pilot on a noncritical project</strong> to learn the administration and support effort.</p>`, `<p>Mua công cụ dễ; <strong>đổi văn hoá và quy trình để chấp nhận nó khó hơn nhiều</strong>. Vài người thích không chia sẻ một tập yêu cầu chưa hoàn hảo, nhưng database mở cho mọi người. Người ta kháng cự đổi thói quen quen (làm trong tài liệu). Cuối cùng công cụ sẽ không tốn thêm thời gian, nhưng người dùng phải leo <strong>learning curve</strong> trước. Gợi ý: nhận diện một <strong>tool advocate</strong> (một người nhiệt tình/BA kinh nghiệm địa phương thạo nó, hướng dẫn người khác, và sở hữu adoption); vượt niềm tin rằng công cụ không thêm giá trị bằng cách <strong>chia sẻ chuyện về tác hại do thiếu nó</strong>; <strong>đào tạo</strong> người thay vì mong họ tự tìm ra toàn bộ năng lực; và <strong>đừng đặt cược thành công một dự án vào một công cụ lần đầu</strong> — bắt đầu bằng một <strong>pilot trên một dự án không trọng yếu</strong> để học công sức quản trị và hỗ trợ.</p>`],
      [16, 'Tools — the takeaway', `<p>Requirements tools amplify good practice; they don't create it. An RM tool's database, attributes and traceability solve the real limits of document-based requirements — but only if selected against weighted criteria, set up by an owner with clear conventions, and adopted through an advocate, training and a low-risk pilot. Buy the tool <em>and</em> budget the culture change, or the tool becomes shelfware.</p>`, `<p>Công cụ yêu cầu khuếch đại thực hành tốt; chúng không tạo ra nó. Database, thuộc tính và traceability của một công cụ RM giải các giới hạn thật của yêu cầu dựa-tài-liệu — nhưng chỉ khi được chọn theo tiêu chí có trọng số, thiết lập bởi một chủ với quy ước rõ, và nhận qua một advocate, đào tạo và một pilot ít rủi ro. Mua công cụ <em>và</em> dự trù thay đổi văn hoá, nếu không công cụ thành shelfware.</p>`],
    ]),
    books([['wiegers', 'Chapter 30, "Selecting and implementing a requirements tool" (selecting, setting up, facilitating adoption)', 'Chương 30, "Selecting and implementing a requirements tool" (chọn, thiết lập, tạo điều kiện adoption)']]),
  ].join('\n'),
};

export default {
  title: 'Tools for requirements engineering (book Ch.30)|||Công cụ kỹ nghệ yêu cầu (Ch.30 sách)',
  description: 'Chương 30 sách Wiegers: công cụ RD (elicitation/prototyping/modeling) & RM (database, 10 lợi ích, năng lực, tích hợp), và cách chọn + triển khai + tạo adoption. Tách 2 bài.',
  lessons: [G1, G2],
};
