/**
 * SWR302 · New section — book chapter Ch.31 "Improving your requirements
 * processes" (25 slides). A stand-alone section, split into THREE focused
 * lessons: requirements & other processes + gaining commitment (1–10),
 * SPI fundamentals + root cause + the cycle (11–16), and the cycle's steps +
 * process assets + road map (17–25). Exported as a SECTION object inserted into
 * the sections array. Grounded slide-by-slide in
 * CHAPTER_31_Improving your requirements processes.pptx.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 31I.1 — requirements & other processes, commitment */
const I1 = {
  title: '31I.1 — Slides: requirements & other processes; gaining commitment (Ch.31 · 1–10)|||31I.1 — Slide: yêu cầu & quy trình khác; giành cam kết (Ch.31 · 1–10)',
  slug: 'swr302-31i-1-ch31-relate-commitment',
  type: 'DOCUMENT',
  description: 'Slide 1–10: yêu cầu là trái tim của mọi quy trình dự án (planning, tracking, change control, testing, construction, user docs — Fig 31-1); đóng góp từ các nhóm stakeholder (Fig 31-2); và giành cam kết thay đổi (hiểu & hoá giải kháng cự, "what’s in it for me", cam kết quản lý — Fig 31-3).',
  content: [
    bi(
      `<span class="eyebrow">Improving requirements processes · Lesson 31I.1 · Book Ch.31 slides 1–10</span>
<h2>Requirements &amp; other processes; gaining commitment</h2>
<p class="lead">Requirements sit at the heart of every well-run project — change how you develop and manage them and you affect planning, tracking, change control, testing, construction and documentation. And any process change meets resistance, so you must understand it, defuse it, and earn genuine management commitment.</p>`,
      `<span class="eyebrow">Cải thiện quy trình yêu cầu · Bài 31I.1 · Slide 1–10 sách Ch.31</span>
<h2>Yêu cầu &amp; quy trình khác; giành cam kết</h2>
<p class="lead">Yêu cầu nằm ở trái tim mọi dự án vận hành tốt — đổi cách bạn phát triển và quản lý chúng là ảnh hưởng planning, tracking, change control, testing, construction và tài liệu. Và mọi thay đổi quy trình gặp kháng cự, nên bạn phải hiểu nó, hoá giải nó, và giành cam kết quản lý thật.</p>`,
    ),
    walkHead('ch31', 1, 10),
    walk('ch31', [
      [1, 'Improving your requirements processes', `<p>Title slide — how requirements relate to other project processes and stakeholders, basic software-process-improvement (SPI) concepts, useful requirements "process assets," and a road map for implementing improved requirements processes.</p>`, `<p>Slide bìa — yêu cầu liên quan quy trình dự án và stakeholder khác thế nào, khái niệm cơ bản về software-process-improvement (SPI), các "process asset" yêu cầu hữu ích, và một road map để triển khai quy trình yêu cầu cải thiện.</p>`],
      [2, 'Objectives & contents', `<p>Understand how requirements relate to other processes and stakeholders, basic SPI concepts and a suggested improvement cycle, useful requirements process assets, and an improvement road map. Topics: how requirements relate to other processes, requirements and stakeholder groups, and gaining commitment to change.</p>`, `<p>Hiểu yêu cầu liên quan quy trình và stakeholder khác thế nào, khái niệm SPI cơ bản và một chu kỳ cải thiện đề xuất, process asset yêu cầu hữu ích, và một road map cải thiện. Chủ đề: yêu cầu liên quan quy trình khác, yêu cầu và nhóm stakeholder, và giành cam kết thay đổi.</p>`],
      [3, 'How requirements relate to other processes', `<p>Figure 31-1: requirements lie at the <strong>heart of every well-run project</strong>, supporting and enabling the other technical and management activities. Changes you make in requirements development and management <strong>affect these other processes, and vice versa</strong> — so improving requirements is never an isolated act.</p>`, `<p>Hình 31-1: yêu cầu nằm ở <strong>trái tim mọi dự án vận hành tốt</strong>, hỗ trợ và cho phép các hoạt động kỹ thuật và quản lý khác. Thay đổi bạn làm trong phát triển và quản lý yêu cầu <strong>ảnh hưởng các quy trình khác, và ngược lại</strong> — nên cải thiện yêu cầu không bao giờ là một hành động cô lập.</p>`],
      [4, 'Planning, tracking & control', `<p><strong>Project planning:</strong> requirements are the foundation — planners pick a life cycle and estimate resources/schedule from them; planning may reveal you can't deliver the full feature set in the available bounds, leading to scope reduction or staged releases (agile defines scope via the backlog and implements it per iteration, planning future scope from earlier <strong>velocity</strong>). <strong>Project tracking and control:</strong> monitoring status shows whether construction/verification proceed as intended; if not, stakeholders may request scope modification through planning (changing the requirement set) — on agile, scope adjusts by moving lower-priority items to future iterations.</p>`, `<p><strong>Project planning:</strong> yêu cầu là nền — người lập kế hoạch chọn một vòng đời và ước lượng tài nguyên/lịch từ chúng; lập kế hoạch có thể lộ rằng bạn không giao được cả tập feature trong giới hạn có, dẫn tới giảm scope hoặc release theo giai đoạn (agile định scope qua backlog và hiện thực nó mỗi iteration, lập kế hoạch scope tương lai từ <strong>velocity</strong> trước). <strong>Project tracking và control:</strong> theo dõi trạng thái cho biết construction/verification có tiến như định không; nếu không, stakeholder có thể yêu cầu sửa scope qua planning (đổi tập yêu cầu) — trên agile, scope điều chỉnh bằng cách dời mục ưu tiên thấp sang iteration sau.</p>`],
      [5, 'Change control, testing & construction', `<p><strong>Change control:</strong> after baselining, all changes go through a defined process; requirement changes modify the backlog and its priorities, and tracing helps assess scope-change impact. <strong>Acceptance and system testing:</strong> user requirements and functional requirements are essential inputs to acceptance and system testing respectively — unclear expected behavior makes verification hard. <strong>Construction:</strong> requirements are the basis for design and implementation and tie the work products together — use <strong>design reviews</strong> to confirm designs address all requirements, <strong>unit testing</strong> to confirm code satisfies design and requirements, and <strong>tracing</strong> to identify design/code derived from each requirement.</p>`, `<p><strong>Change control:</strong> sau baseline, mọi thay đổi qua một quy trình xác định; thay đổi yêu cầu sửa backlog và ưu tiên của nó, và tracing giúp đánh giá tác động thay đổi scope. <strong>Acceptance và system testing:</strong> user requirement và functional requirement là đầu vào thiết yếu cho acceptance và system testing tương ứng — hành vi mong đợi không rõ làm verify khó. <strong>Construction:</strong> yêu cầu là nền cho thiết kế và hiện thực và buộc các sản phẩm với nhau — dùng <strong>design review</strong> để xác nhận thiết kế phủ mọi yêu cầu, <strong>unit test</strong> để xác nhận code thoả thiết kế và yêu cầu, và <strong>tracing</strong> để nhận diện design/code dẫn từ mỗi yêu cầu.</p>`],
      [6, 'User documentation & the food chain', `<p><strong>User documentation:</strong> the product's requirements feed the user docs, so poorly written or late-breaking requirements cause documentation problems. A technical writer once explained her long hours: <em>"We're at the end of the food chain — we have to respond to the final UI changes and features dropped or added at the last minute."</em> No surprise, then, that people at the end of the requirements chain — <strong>technical writers and testers</strong> — are often the most enthusiastic supporters of improved requirements engineering and of being engaged earlier.</p>`, `<p><strong>User documentation:</strong> yêu cầu của sản phẩm nuôi tài liệu người dùng, nên yêu cầu viết dở hoặc đến muộn gây vấn đề tài liệu. Một technical writer từng giải thích giờ làm dài: <em>"Chúng tôi ở cuối chuỗi thức ăn — phải đáp ứng thay đổi UI cuối và feature bị bỏ hoặc thêm vào phút chót."</em> Không lạ khi người cuối chuỗi yêu cầu — <strong>technical writer và tester</strong> — thường là người ủng hộ nhiệt tình nhất cho kỹ nghệ yêu cầu cải thiện và cho việc được tham gia sớm hơn.</p>`],
      [7, 'Requirements & various stakeholder groups', `<p>Figure 31-2 depicts the <strong>requirements-related contributions from various stakeholders</strong> to the development team — customers, product champions, management, developers, testers, writers each feed and consume requirements differently. Improving the requirements process changes these interactions, which is exactly why some groups resist (next slides).</p>`, `<p>Hình 31-2 mô tả <strong>đóng góp liên quan yêu cầu từ các stakeholder</strong> tới đội phát triển — khách, product champion, quản lý, developer, tester, người viết mỗi nhóm nuôi và tiêu thụ yêu cầu khác nhau. Cải thiện quy trình yêu cầu đổi các tương tác này, đúng vì sao vài nhóm kháng cự (slide sau).</p>`],
      [8, 'Gaining commitment — understanding resistance', `<p>Changing requirements processes changes interactions with other stakeholder communities, and <strong>people don't like being forced out of their comfort zone</strong> — expect resistance; understand its origins to both respect and defuse it. Much comes from <strong>fear of the unknown</strong>: communicate your rationale and the benefits other groups will gain. Forms of resistance: people <strong>too busy</strong> to invest in better practices (but without the investment, why expect a smoother next project?); a change process seen as a <strong>barrier</strong> (it's a structure, not a barrier — it lets informed people make and communicate good decisions); developers/managers viewing writing/reviewing requirements as <strong>bureaucratic time-wasters</strong> (explain the high cost of rewriting code while figuring out what the system should do).</p>`, `<p>Đổi quy trình yêu cầu đổi tương tác với cộng đồng stakeholder khác, và <strong>người ta không thích bị ép ra khỏi vùng thoải mái</strong> — chờ kháng cự; hiểu nguồn gốc để vừa tôn trọng vừa hoá giải. Phần lớn từ <strong>sợ cái chưa biết</strong>: truyền đạt lý do và lợi ích các nhóm khác được. Các dạng kháng cự: người <strong>quá bận</strong> để đầu tư thực hành tốt hơn (nhưng không đầu tư, sao mong dự án sau trơn hơn?); một quy trình thay đổi bị coi là <strong>rào cản</strong> (nó là cấu trúc, không phải rào — nó cho người có căn cứ ra và truyền đạt quyết định tốt); developer/quản lý coi viết/review yêu cầu là <strong>thủ tục phí thời gian</strong> (giải thích chi phí cao của viết lại code trong khi cố đoán hệ thống nên làm gì).</p>`],
      [9, 'Gaining commitment — "what’s in it for me" & management', `<p>When asked to change, people naturally ask <strong>"What's in it for me?"</strong> Process changes don't always give immediate personal benefit — but if people understand the investment pays off in <strong>reduced rework, lower support costs, and more customer value</strong>, they may be more willing to spend the time now. On management: as a professional you <strong>don't need permission to work in the best way you know</strong> — that's your job. But a project- or organization-wide improvement effort <strong>needs management commitment</strong> to be sustained; <strong>behaviors, not pronouncements, are the evidence of commitment</strong> (Figure 31-3 lists 10 behaviors that show management is truly committed to excellent requirements processes).</p>`, `<p>Khi được yêu cầu đổi, người ta tự nhiên hỏi <strong>"Tôi được gì?"</strong> Thay đổi quy trình không luôn cho lợi ích cá nhân tức thì — nhưng nếu người ta hiểu đầu tư sinh lợi qua <strong>giảm rework, giảm chi phí hỗ trợ, và nhiều giá trị khách hơn</strong>, họ có thể sẵn lòng bỏ thời gian bây giờ. Về quản lý: là chuyên gia bạn <strong>không cần phép để làm theo cách tốt nhất bạn biết</strong> — đó là việc của bạn. Nhưng một nỗ lực cải thiện toàn dự án/tổ chức <strong>cần cam kết quản lý</strong> để bền; <strong>hành vi, không phải tuyên bố, là bằng chứng của cam kết</strong> (Hình 31-3 liệt kê 10 hành vi cho thấy quản lý thật sự cam kết với quy trình yêu cầu xuất sắc).</p>`],
      [10, 'The commitment behaviors', `<p>Figure 31-3's list of behaviors is the practical test: does management fund training and review time, protect requirements activities from schedule pressure, participate in prioritization, and hold people accountable for following the process? <strong>Commitment is what management does, not what it says</strong> — a poster about quality proves nothing; budgeting review hours and defending them under deadline pressure proves everything.</p>`, `<p>Danh sách hành vi của Hình 31-3 là phép thử thực tế: quản lý có tài trợ đào tạo và thời gian review, bảo vệ hoạt động yêu cầu khỏi áp lực lịch, tham gia ưu tiên, và buộc người ta chịu trách nhiệm theo quy trình không? <strong>Cam kết là cái quản lý làm, không phải cái nó nói</strong> — một poster về chất lượng chẳng chứng minh gì; dự trù giờ review và bảo vệ chúng dưới áp lực deadline chứng minh mọi thứ.</p>`],
    ]),
    books([['wiegers', 'Chapter 31, "How requirements relate to other project processes" (Figure 31-1), "Requirements and various stakeholder groups" (Figure 31-2), "Gaining commitment to change" (Figure 31-3)', 'Chương 31, "How requirements relate to other project processes" (Hình 31-1), "Requirements and various stakeholder groups" (Hình 31-2), "Gaining commitment to change" (Hình 31-3)']]),
  ].join('\n'),
};

/* 31I.2 — SPI fundamentals, root cause, the cycle */
const I2 = {
  title: '31I.2 — Slides: SPI fundamentals & root cause analysis (Ch.31 · 11–16)|||31I.2 — Slide: nền tảng SPI & phân tích nguyên nhân gốc (Ch.31 · 11–16)',
  slug: 'swr302-31i-2-ch31-spi-rootcause',
  type: 'DOCUMENT',
  description: 'Slide 11–16: bốn nền tảng cải tiến quy trình (tiến hoá & liên tục, cần động lực — "nỗi đau", hướng mục tiêu, coi như mini-project); root cause analysis (hỏi "vì sao" nhiều lần, fishbone/Ishikawa, Pareto 80/20); và chu kỳ cải tiến quy trình (Fig 31-5).',
  content: [
    bi(
      `<span class="eyebrow">Improving requirements processes · Lesson 31I.2 · Book Ch.31 slides 11–16</span>
<h2>SPI fundamentals &amp; root cause analysis</h2>
<p class="lead">Process improvement works when it's evolutionary, incentivized by real pain, goal-oriented, and run like a project. And before changing anything, do root cause analysis — ask "why" repeatedly, draw a fishbone diagram, and use the 80/20 rule to attack the vital few causes.</p>`,
      `<span class="eyebrow">Cải thiện quy trình yêu cầu · Bài 31I.2 · Slide 11–16 sách Ch.31</span>
<h2>Nền tảng SPI &amp; phân tích nguyên nhân gốc</h2>
<p class="lead">Cải tiến quy trình hiệu quả khi nó tiến hoá, được thúc bởi nỗi đau thật, hướng mục tiêu, và chạy như một dự án. Và trước khi đổi gì, làm root cause analysis — hỏi "vì sao" nhiều lần, vẽ sơ đồ fishbone, và dùng quy tắc 80/20 để đánh vào ít nguyên nhân trọng yếu.</p>`,
    ),
    walkHead('ch31', 11, 16),
    walk('ch31', [
      [11, 'Fundamentals of SPI (1): evolutionary & continuous', `<p>Four fundamentals of software process improvement. <strong>1. Evolutionary and continuous:</strong> don't aim for perfection — develop a few improved templates/procedures and start; adjust as the team gains experience; simple easy changes can bring substantial gains, so look for <strong>low-hanging fruit</strong>, the problem areas everyone agrees are ripe for improvement.</p>`, `<p>Bốn nền tảng của cải tiến quy trình phần mềm. <strong>1. Tiến hoá và liên tục:</strong> đừng nhắm hoàn hảo — phát triển vài template/thủ tục cải thiện và bắt đầu; điều chỉnh khi đội có kinh nghiệm; thay đổi đơn giản dễ có thể đem lợi lớn, nên tìm <strong>low-hanging fruit</strong>, vùng vấn đề ai cũng đồng ý chín để cải thiện.</p>`],
      [12, 'Fundamentals (2): incentive — pain', `<p><strong>2. People and organizations change only when they have an incentive.</strong> The strongest incentive is <strong>pain</strong> — the real pain from previous projects. Compelling drivers: missed deadlines because requirements were more extensive than expected; developer overtime from ambiguous requirements; wasted system-test effort because testers didn't understand the product; the right functionality but users dissatisfied by poor performance/usability; high maintenance costs from enhancements that could have been elicited; changes not implemented well so the solution missed customer needs; lost/overwritten requirement edits from no version control; unavailable customers; and slow issue resolution causing rework. <strong>Name the pain to justify the change.</strong></p>`, `<p><strong>2. Người và tổ chức chỉ đổi khi có động lực.</strong> Động lực mạnh nhất là <strong>nỗi đau</strong> — nỗi đau thật từ dự án trước. Động lực thuyết phục: trễ deadline vì yêu cầu nhiều hơn dự kiến; developer làm thêm giờ vì yêu cầu mơ hồ; phí công system-test vì tester không hiểu sản phẩm; đúng chức năng nhưng người dùng bất mãn vì performance/usability kém; chi phí bảo trì cao từ enhancement đáng lẽ khơi gợi được; thay đổi không hiện thực tốt nên giải pháp trượt nhu cầu khách; sửa yêu cầu bị mất/ghi đè do không có version control; khách không sẵn sàng; và giải issue chậm gây rework. <strong>Gọi tên nỗi đau để biện minh thay đổi.</strong></p>`],
      [13, 'Fundamentals (3 & 4): goal-oriented, mini-projects', `<p><strong>3. Goal-oriented:</strong> before the journey, know your objectives — reduce rework from requirements problems? overlook fewer requirements? cut unneeded features sooner? A <strong>road map</strong> to your objectives greatly improves your chances. <strong>4. Treat improvement activities as mini-projects:</strong> many initiatives founder from poor planning or missing resources — include improvement resources/tasks in an overall plan, do the planning/tracking/measurement/reporting you'd do for any project (scaled to size), and write a <strong>simple action plan</strong> for each improvement area.</p>`, `<p><strong>3. Hướng mục tiêu:</strong> trước hành trình, biết mục tiêu — giảm rework từ vấn đề yêu cầu? bỏ sót ít yêu cầu hơn? cắt feature không cần sớm hơn? Một <strong>road map</strong> tới mục tiêu tăng nhiều cơ hội. <strong>4. Coi hoạt động cải tiến như mini-project:</strong> nhiều sáng kiến chìm vì lập kế hoạch kém hoặc thiếu tài nguyên — đưa tài nguyên/task cải tiến vào một kế hoạch tổng, làm planning/tracking/đo/báo cáo như mọi dự án (co theo cỡ), và viết một <strong>action plan đơn giản</strong> cho mỗi vùng cải tiến.</p>`],
      [14, 'Root cause analysis', `<p>Do <strong>root cause analysis before adopting changes</strong> — otherwise you run around blindly trying methods with no confidence they'll address the real problems. Root cause analysis identifies the <strong>underlying factors</strong> behind an observed problem, distinguishing symptoms from causes: ask <strong>"why" several times in succession</strong>, each probing the reason behind the previous answer. Symptoms and causes chain — one symptom can be the root cause of another. Example: <em>too many requirements missed during elicitation</em> → root cause <em>BAs didn't ask the right questions</em> → itself a symptom of <em>the people doing BA work don't know how to do it well</em>.</p>`, `<p>Làm <strong>root cause analysis trước khi nhận thay đổi</strong> — nếu không bạn chạy mù thử các phương pháp mà không chắc chúng giải vấn đề thật. Root cause analysis nhận diện <strong>yếu tố nền</strong> sau một vấn đề quan sát, phân biệt triệu chứng với nguyên nhân: hỏi <strong>"vì sao" nhiều lần liên tiếp</strong>, mỗi lần dò lý do sau câu trả lời trước. Triệu chứng và nguyên nhân nối chuỗi — một triệu chứng có thể là nguyên nhân gốc của cái khác. Ví dụ: <em>quá nhiều yêu cầu bị sót khi khơi gợi</em> → nguyên nhân gốc <em>BA không hỏi đúng câu</em> → chính nó là triệu chứng của <em>người làm vai BA không biết làm tốt</em>.</p>`],
      [15, 'Fishbone diagram & Pareto', `<p>A <strong>cause-and-effect diagram</strong> (fishbone / Ishikawa diagram) depicts a root cause analysis: Figure 31-4 partially analyzes "why don't teams finish projects on time?" The <strong>"bones"</strong> branching off the backbone show answers to the "why" question, and the most highly-branched bones reveal <strong>fundamental root causes</strong>. You needn't tackle every cause — the <strong>Pareto principle</strong> (80/20 rule) suggests ~20% of the vital root causes lead to ~80% of the observed problems, so attack those first.</p>`, `<p>Một <strong>cause-and-effect diagram</strong> (sơ đồ fishbone / Ishikawa) mô tả một root cause analysis: Hình 31-4 phân tích một phần "vì sao đội không xong dự án đúng hạn?" Các <strong>"xương"</strong> nhánh khỏi xương sống chỉ câu trả lời cho câu "vì sao", và các xương phân nhánh nhiều nhất lộ <strong>nguyên nhân gốc căn bản</strong>. Bạn không cần đánh mọi nguyên nhân — <strong>nguyên lý Pareto</strong> (quy tắc 80/20) gợi ~20% nguyên nhân gốc trọng yếu dẫn tới ~80% vấn đề quan sát, nên đánh chúng trước.</p>`],
      [16, 'The process improvement cycle', `<p>Figure 31-5 illustrates an effective <strong>process improvement cycle</strong>: it reflects the importance of <strong>knowing where you are before setting off</strong>, the need to <strong>chart your course</strong>, and the value of <strong>learning from experience</strong> as part of continuous improvement. The cycle's four steps — assess current practices, plan improvement actions, create/pilot/roll out processes, and evaluate results — are covered in the next lesson.</p>`, `<p>Hình 31-5 minh hoạ một <strong>chu kỳ cải tiến quy trình</strong> hiệu quả: nó phản ánh tầm quan trọng của <strong>biết mình đang ở đâu trước khi lên đường</strong>, nhu cầu <strong>vạch lộ trình</strong>, và giá trị của <strong>học từ trải nghiệm</strong> như một phần của cải tiến liên tục. Bốn bước của chu kỳ — đánh giá thực hành hiện tại, lập kế hoạch hành động, tạo/pilot/roll out quy trình, và đánh giá kết quả — được phủ ở bài sau.</p>`],
    ]),
    books([['wiegers', 'Chapter 31, "Fundamentals of software process improvement", "Root cause analysis" (Figure 31-4), "The process improvement cycle" (Figure 31-5)', 'Chương 31, "Fundamentals of software process improvement", "Root cause analysis" (Hình 31-4), "The process improvement cycle" (Hình 31-5)']]),
  ].join('\n'),
};

/* 31I.3 — cycle steps, assets, road map */
const I3 = {
  title: '31I.3 — Slides: the improvement cycle, process assets & road map (Ch.31 · 17–25)|||31I.3 — Slide: chu kỳ cải tiến, process asset & road map (Ch.31 · 17–25)',
  slug: 'swr302-31i-3-ch31-cycle-roadmap',
  type: 'DOCUMENT',
  description: 'Slide 17–25: bốn bước chu kỳ cải tiến (assess → plan action ≤10 mục/2-3 tháng → create/pilot/roll out → evaluate, chấp nhận "valley of despair" Fig 31-7); process assets (Bảng 31-1, Fig 31-8, thư viện dùng chung); và tạo road map cải tiến quy trình (Fig 31-9).',
  content: [
    bi(
      `<span class="eyebrow">Improving requirements processes · Lesson 31I.3 · Book Ch.31 slides 17–25</span>
<h2>The improvement cycle, process assets &amp; road map</h2>
<p class="lead">The four steps of the improvement cycle — assess, plan, pilot &amp; roll out, evaluate — plus the "valley of despair" learning curve, the process assets every requirements organization should keep, and a road map that sequences improvements for the greatest, quickest benefit.</p>`,
      `<span class="eyebrow">Cải thiện quy trình yêu cầu · Bài 31I.3 · Slide 17–25 sách Ch.31</span>
<h2>Chu kỳ cải tiến, process asset &amp; road map</h2>
<p class="lead">Bốn bước của chu kỳ cải tiến — assess, plan, pilot &amp; roll out, evaluate — cộng learning curve "valley of despair", các process asset mà mọi tổ chức yêu cầu nên giữ, và một road map sắp xếp các cải tiến cho lợi ích lớn nhất, nhanh nhất.</p>`,
    ),
    walkHead('ch31', 17, 25),
    walk('ch31', [
      [17, '1. Assess current practices', `<p>Step 1 is to <strong>assess current practices</strong> to identify strengths and shortcomings — the foundation for choosing what to change. Ways to evaluate: <strong>Appendix B</strong>'s troubleshooting guide (symptoms → root causes → solutions); <strong>structured questionnaires</strong> (low-cost insight); <strong>interviews and discussions</strong> (more accurate/comprehensive than questionnaires); and <strong>formal outside-consultant evaluations</strong> (findings of strengths/weaknesses plus recommendations). For a DIY approach, use <strong>Appendix A</strong>'s self-assessment to calibrate your practices, then <strong>focus energy on the practice areas causing the most difficulty</strong> and posing the most future risk.</p>`, `<p>Bước 1 là <strong>đánh giá thực hành hiện tại</strong> để nhận diện điểm mạnh và thiếu sót — nền để chọn cái cần đổi. Cách đánh giá: hướng dẫn troubleshooting của <strong>Phụ lục B</strong> (triệu chứng → nguyên nhân gốc → giải pháp); <strong>bảng câu hỏi có cấu trúc</strong> (hiểu biết chi phí thấp); <strong>phỏng vấn và thảo luận</strong> (chính xác/toàn diện hơn bảng hỏi); và <strong>đánh giá chính thức của tư vấn ngoài</strong> (kết quả điểm mạnh/yếu cộng khuyến nghị). Cho cách DIY, dùng self-assessment của <strong>Phụ lục A</strong> để hiệu chỉnh thực hành, rồi <strong>tập trung vào vùng thực hành gây khó nhất</strong> và rủi ro tương lai nhất.</p>`],
      [18, '2. Plan improvement actions', `<p>Following the assessment, write an <strong>action plan</strong> (treating improvement as a project). <strong>Tactical action plans</strong> target specific areas (e.g. how you elicit or prioritize), each with <strong>measurable improvement goals</strong>, participants, and individual action items. Keep <strong>≤ ~10 items per plan</strong>, scoped to finish in <strong>2–3 months</strong>. Example (an RM improvement plan): draft a change-control process; review/revise it; pilot it on Project A; revise from pilot feedback; evaluate and select a problem-tracking tool; procure/customize it; roll it out. Assign each item to a <strong>specific individual</strong> — never "the team." If you need more than ~10 items, focus the first cycle on the most important issues and address the rest later — improvement is <strong>incremental and ongoing</strong>.</p>`, `<p>Sau đánh giá, viết một <strong>action plan</strong> (coi cải tiến như một dự án). <strong>Tactical action plan</strong> nhắm vùng cụ thể (vd cách khơi gợi hay ưu tiên), mỗi cái với <strong>mục tiêu cải tiến đo được</strong>, người tham gia, và action item riêng. Giữ <strong>≤ ~10 mục mỗi plan</strong>, co để xong trong <strong>2–3 tháng</strong>. Ví dụ (một RM improvement plan): soạn quy trình change-control; review/sửa; pilot nó trên Project A; sửa từ phản hồi pilot; đánh giá và chọn một công cụ problem-tracking; mua/tuỳ chỉnh; roll out. Gán mỗi mục cho một <strong>cá nhân cụ thể</strong> — không bao giờ "cả đội". Nếu cần hơn ~10 mục, tập trung chu kỳ đầu vào vấn đề quan trọng nhất và giải phần còn lại sau — cải tiến <strong>tăng dần và liên tục</strong>.</p>`],
      [19, '3. Create, pilot & roll out processes', `<p>Implementing a plan means <strong>developing processes you believe will beat your current ways</strong> — but don't expect perfection first try; <strong>pilot most new procedures/templates on a small scale</strong> before real use, then adjust from what you learn. Tips for pilots: pick participants who'll give a <strong>fair try</strong> and helpful feedback (allies or skeptics, not strong opponents); <strong>quantify the evaluation criteria</strong>; inform the stakeholders who need to know; consider <strong>piloting portions on different projects</strong> (more people, more feedback, more buy-in); and ask participants how they'd feel <strong>going back to the old way</strong>. If the pilot succeeds, make final adjustments and <strong>roll out</strong> with a plan for distributing methods/materials and providing <strong>training, coaching and assistance</strong>.</p>`, `<p>Hiện thực một plan nghĩa là <strong>phát triển quy trình bạn tin sẽ hơn cách hiện tại</strong> — nhưng đừng mong hoàn hảo lần đầu; <strong>pilot đa số thủ tục/template mới ở quy mô nhỏ</strong> trước khi dùng thật, rồi điều chỉnh từ cái học được. Mẹo pilot: chọn người sẽ <strong>thử công bằng</strong> và phản hồi hữu ích (đồng minh hoặc hoài nghi, không phản đối mạnh); <strong>lượng hoá tiêu chí đánh giá</strong>; báo stakeholder cần biết; cân nhắc <strong>pilot từng phần trên các dự án khác nhau</strong> (nhiều người, nhiều phản hồi, nhiều đồng thuận); và hỏi người tham gia họ thấy sao khi <strong>quay lại cách cũ</strong>. Nếu pilot thành công, điều chỉnh cuối và <strong>roll out</strong> với một kế hoạch phân phối phương pháp/tài liệu và cung cấp <strong>đào tạo, coaching và hỗ trợ</strong>.</p>`],
      [20, '4. Evaluate results', `<p>The final step: <strong>evaluate the activities and results</strong> to do better next time. Assess how smoothly the <strong>pilots</strong> ran and how well they resolved uncertainties; would you change anything? Assess the <strong>rollout</strong> — was availability communicated to everyone affected? Did participants understand and apply the new processes? A critical step: assess whether the new processes are <strong>yielding the desired results</strong>. Some deliver visible improvement quickly (a change-control process); others take time (a new document template as people get used to it). <strong>Give new approaches adequate time to work, and select measures early</strong> that will demonstrate each change's success.</p>`, `<p>Bước cuối: <strong>đánh giá các hoạt động và kết quả</strong> để làm tốt hơn lần sau. Đánh giá <strong>pilot</strong> chạy trơn thế nào và giải bất định tốt ra sao; có đổi gì không? Đánh giá <strong>rollout</strong> — độ sẵn có được truyền đạt tới mọi người liên quan chưa? Người tham gia hiểu và áp quy trình mới chưa? Một bước then chốt: đánh giá quy trình mới có <strong>cho kết quả mong muốn</strong> không. Vài cái cho cải thiện thấy được nhanh (một quy trình change-control); số khác cần thời gian (một template tài liệu mới khi người ta quen). <strong>Cho cách mới đủ thời gian, và chọn thước đo sớm</strong> để chứng minh thành công của mỗi thay đổi.</p>`],
      [21, 'The learning curve — the "valley of despair"', `<p>Accept the reality of the <strong>learning curve</strong> — the short-term <strong>productivity drop</strong> as practitioners assimilate new ways of working (Figure 31-7), sometimes called the <strong>"valley of despair."</strong> This dip is <strong>part of the investment</strong>, not a sign of failure. People who don't understand it may <strong>abandon the effort before it pays off</strong>, achieving a zero — or worse — return. <strong>Educate managers and peers about the learning curve, and commit to seeing the change through.</strong></p>`, `<p>Chấp nhận thực tế của <strong>learning curve</strong> — sự <strong>tụt năng suất</strong> ngắn hạn khi người ta thấm cách làm mới (Hình 31-7), đôi khi gọi <strong>"valley of despair."</strong> Cái hõm này là <strong>một phần của đầu tư</strong>, không phải dấu thất bại. Người không hiểu nó có thể <strong>bỏ nỗ lực trước khi nó sinh lợi</strong>, đạt lợi tức bằng không — hoặc tệ hơn. <strong>Giáo dục quản lý và đồng nghiệp về learning curve, và cam kết theo thay đổi tới cùng.</strong></p>`],
      [22, 'Requirements engineering process assets', `<p>Table 31-1 lists <strong>types of process assets</strong> — the reusable templates, procedures, checklists and examples that let a team apply good practice consistently. A process asset captures "how we do requirements here" so it survives beyond any one person, and improves with experience rather than being reinvented per project.</p>`, `<p>Bảng 31-1 liệt kê <strong>các loại process asset</strong> — template, thủ tục, checklist và ví dụ tái dùng cho một đội áp thực hành tốt nhất quán. Một process asset nắm "cách chúng ta làm yêu cầu ở đây" để nó sống ngoài một người, và cải thiện theo kinh nghiệm thay vì phát minh lại mỗi dự án.</p>`],
      [23, 'Key process assets', `<p>Figure 31-8 identifies valuable requirements process assets — templates (V&amp;S, SRS, use case), procedures (elicitation, status tracking, change control), checklists (defect, impact analysis), and models/examples. Keep them <strong>no larger than needed</strong> for consistent, effective use; they needn't be separate documents (an overall RM process could include the status-tracking procedure, change-control process and impact-analysis checklist). Store them in a <strong>shared process-assets library</strong> for easy access, and establish mechanisms to <strong>improve them with experience</strong>.</p>`, `<p>Hình 31-8 nhận diện các process asset yêu cầu giá trị — template (V&amp;S, SRS, use case), thủ tục (elicitation, status tracking, change control), checklist (defect, impact analysis), và mô hình/ví dụ. Giữ chúng <strong>không lớn hơn cần</strong> để dùng nhất quán, hiệu quả; chúng không cần là tài liệu riêng (một quy trình RM tổng có thể gồm thủ tục status-tracking, quy trình change-control và checklist impact-analysis). Lưu chúng trong một <strong>thư viện process-assets dùng chung</strong> để dễ truy cập, và lập cơ chế <strong>cải thiện chúng theo kinh nghiệm</strong>.</p>`],
      [24, 'Creating a process improvement road map', `<p>Rather than diving in, develop a <strong>road map</strong> for implementing improved requirements practices — it <strong>sequences improvement actions to yield the greatest, quickest benefit for the smallest investment</strong>. There's no one-size-fits-all road map; Figure 31-9 shows one organization's. The <strong>circles are intermediate milestones</strong> along paths toward the business goals; implement each threaded set of activities <strong>left to right</strong>.</p>`, `<p>Thay vì lao vào, phát triển một <strong>road map</strong> để triển khai thực hành yêu cầu cải thiện — nó <strong>sắp xếp các hành động cải tiến để cho lợi ích lớn nhất, nhanh nhất với đầu tư nhỏ nhất</strong>. Không có road map một-cỡ-cho-tất; Hình 31-9 chỉ của một tổ chức. Các <strong>vòng tròn là milestone trung gian</strong> trên đường tới mục tiêu nghiệp vụ; hiện thực mỗi tập hoạt động theo luồng <strong>trái sang phải</strong>.</p>`],
      [25, 'From road map to action', `<p>Once you have a road map, <strong>give ownership of each milestone to an individual</strong>, who then writes an <strong>action plan for achieving that milestone</strong> — and then <strong>turn those action plans into actions</strong>. This closes the loop of the whole chapter: assess honestly, target root causes, plan small improvement projects, pilot and roll out, evaluate, and sequence it all on a road map owned milestone by milestone. Process improvement is not an event but a discipline the organization sustains.</p>`, `<p>Khi có một road map, <strong>giao quyền sở hữu mỗi milestone cho một cá nhân</strong>, người đó rồi viết một <strong>action plan để đạt milestone đó</strong> — và rồi <strong>biến các action plan thành hành động</strong>. Việc này khép vòng của cả chương: đánh giá thành thật, nhắm nguyên nhân gốc, lập các dự án cải tiến nhỏ, pilot và roll out, đánh giá, và sắp xếp tất cả trên một road map sở hữu từng milestone. Cải tiến quy trình không phải một sự kiện mà một kỷ luật tổ chức duy trì.</p>`],
    ]),
    books([['wiegers', 'Chapter 31, "The process improvement cycle" (Figure 31-7), "Requirements engineering process assets" (Table 31-1, Figure 31-8), "Creating a requirements process improvement road map" (Figure 31-9)', 'Chương 31, "The process improvement cycle" (Hình 31-7), "Requirements engineering process assets" (Bảng 31-1, Hình 31-8), "Creating a requirements process improvement road map" (Hình 31-9)']]),
  ].join('\n'),
};

export default {
  title: 'Improving your requirements processes (book Ch.31)|||Cải thiện quy trình yêu cầu (Ch.31 sách)',
  description: 'Chương 31 sách Wiegers: yêu cầu liên quan mọi quy trình dự án, giành cam kết thay đổi, nền tảng SPI, root cause (fishbone/Pareto), chu kỳ cải tiến 4 bước, process assets, và road map. Tách 3 bài.',
  lessons: [I1, I2, I3],
};
