/**
 * SWR302 · NEW section for book chapter Ch.6 "Finding the voice of the user"
 * (21 slides). Own section, split into THREE focused lessons: user classes &
 * personas (1–9), the product champion (10–19), agile representation &
 * resolving conflicts (20–21). Grounded slide-by-slide in
 * CHAPTER_6_Finding the voice of the user.pdf.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

/* 6U.1 — user classes & personas */
const U1 = {
  title: '6U.1 — Slides: user classes & personas (Ch.6 · 1–9)|||6U.1 — Slide: lớp người dùng & persona (Ch.6 · 1–9)',
  slug: 'swr302-6u-1-ch6-user-classes-personas',
  type: 'DOCUMENT',
  description: 'Slide 1–9: đưa tiếng nói người dùng tới tai lập trình viên; phân lớp người dùng (theo quyền/tác vụ/tần suất/kinh nghiệm…), favored/disfavored/ignored, cách xác định lớp người dùng (context diagram, org chart), và user persona (ví dụ "Fred" của Chemical Tracking System).',
  content: [
    bi(
      `<span class="eyebrow">Voice of the User · Lesson 6U.1 · Book Ch.6 slides 1–9</span>
<h2>User classes &amp; personas</h2>
<p class="lead">Success depends on getting <strong>the voice of the user close to the ear of the developer</strong>. That starts by classifying who your users are — into <strong>user classes</strong> — and making them concrete with <strong>personas</strong>.</p>`,
      `<span class="eyebrow">Tiếng nói người dùng · Bài 6U.1 · Slide 1–9 sách Ch.6</span>
<h2>Lớp người dùng &amp; persona</h2>
<p class="lead">Thành công phụ thuộc việc đưa <strong>tiếng nói người dùng tới sát tai lập trình viên</strong>. Bắt đầu bằng phân loại người dùng — thành các <strong>user class</strong> — và làm chúng cụ thể bằng <strong>persona</strong>.</p>`,
    ),
    walkHead('ch6', 1, 9),
    walk('ch6', [
      [1, 'Finding the voice of the user', `<p>Title slide — the chapter on who speaks for the user and how.</p>`, `<p>Slide bìa — chương về ai nói thay người dùng và nói thế nào.</p>`],
      [2, 'Objectives', `<p>Understand that success depends on getting the user's voice to the developer; learn to find that voice step by step; classify users and know what information each type supplies based on role and department; and understand how user representation differs on agile projects.</p>`, `<p>Hiểu rằng thành công phụ thuộc đưa tiếng nói người dùng tới lập trình viên; học cách tìm tiếng nói đó từng bước; phân loại người dùng và biết mỗi loại cung cấp thông tin gì theo vai trò và phòng ban; và hiểu đại diện người dùng khác ra sao trên dự án agile.</p>`],
      [3, 'Contents', `<p>Road map: user classes, user personas, connecting with user representatives, the product champion, and user representation on agile. Lessons 6U.1–6U.3 follow.</p>`, `<p>Bản đồ: user class, persona, kết nối với đại diện người dùng, product champion, và đại diện người dùng trên agile. Bài 6U.1–6U.3 theo đây.</p>`],
      [4, 'Finding the voice of the user — the steps', `<p>Three steps: <strong>identify</strong> the different user classes; <strong>select and work with</strong> individuals who represent each class and other stakeholders; and <strong>agree who the requirements decision makers are</strong>. Do these early — they shape everything downstream.</p>`, `<p>Ba bước: <strong>xác định</strong> các lớp người dùng khác nhau; <strong>chọn và làm việc với</strong> người đại diện mỗi lớp và các bên khác; và <strong>thống nhất ai là người quyết yêu cầu</strong>. Làm sớm — chúng định hình mọi thứ về sau.</p>`],
      [5, 'Classifying users into user classes', `<p>Group users into <strong>user classes</strong> by their differences: access/security level (user, guest, admin), tasks performed, features used, frequency of use, domain &amp; computer expertise, platform (PC, tablet, phone, special device), native language, and whether they interact directly or indirectly. Each dimension can define a class.</p>`, `<p>Nhóm người dùng thành <strong>user class</strong> theo khác biệt: cấp quyền/bảo mật (user, guest, admin), tác vụ thực hiện, feature dùng, tần suất, kinh nghiệm miền &amp; máy tính, nền tảng (PC, tablet, điện thoại, thiết bị chuyên dụng), ngôn ngữ mẹ đẻ, và tương tác trực tiếp hay gián tiếp. Mỗi chiều có thể định một lớp.</p>`],
      [6, 'Favored, disfavored & ignored user classes', `<p>Don't group by <em>location</em> or <em>company type</em> — that's market segments, not user classes; group by the <strong>tasks</strong> users perform (banking: teller, loan officer, branch manager). Classes differ in importance: <strong>favored</strong> classes (satisfaction aligns most with business objectives) get preference in conflicts/priorities; <strong>disfavored</strong> classes shouldn't use the product (legal/security/safety) — you may add features to block them (access control, privilege levels, logging); <strong>ignored</strong> classes will use it but you don't build for them. Others are of equal importance.</p>`, `<p>Đừng nhóm theo <em>vị trí</em> hay <em>loại công ty</em> — đó là phân khúc thị trường, không phải user class; nhóm theo <strong>tác vụ</strong> người dùng làm (ngân hàng: teller, loan officer, branch manager). Các lớp khác nhau về tầm quan trọng: lớp <strong>favored</strong> (sự hài lòng khớp nhất với mục tiêu nghiệp vụ) được ưu tiên khi xung đột/ưu tiên; lớp <strong>disfavored</strong> không được dùng sản phẩm (pháp lý/bảo mật/an toàn) — có thể thêm feature chặn họ (kiểm soát truy cập, cấp quyền, logging); lớp <strong>ignored</strong> sẽ dùng nhưng bạn không xây cho họ. Các lớp khác quan trọng ngang nhau.</p>`],
      [7, 'Identifying user classes for your project', `<p>Techniques: a <strong>collaboration pattern</strong> (Gottesdiener); the <strong>external entities</strong> on a context diagram are candidate user classes; and a corporate <strong>org chart</strong> helps discover users and stakeholders (Beatty &amp; Chen).</p>`, `<p>Kỹ thuật: một <strong>collaboration pattern</strong> (Gottesdiener); các <strong>thực thể ngoài</strong> trên context diagram là ứng viên user class; và <strong>sơ đồ tổ chức</strong> công ty giúp phát hiện người dùng và stakeholder (Beatty &amp; Chen).</p>`],
      [8, 'Studying the org chart', `<p>In the org chart, look for departments that <strong>participate in</strong> or are <strong>affected by</strong> the business process, roles where direct/indirect users are found, user classes spanning multiple departments, and departments that interface to external stakeholders. Document each user class's characteristics, responsibilities and locations in the SRS/requirements plan, cross-check against the Vision &amp; Scope stakeholder profiles to avoid duplication, and record size and which classes are favored — this helps prioritise changes and assess impact later.</p>`, `<p>Trong org chart, tìm phòng ban <strong>tham gia</strong> hoặc <strong>bị ảnh hưởng bởi</strong> quy trình nghiệp vụ, vai trò có user trực tiếp/gián tiếp, user class trải nhiều phòng, và phòng có giao diện với stakeholder ngoài. Ghi đặc điểm, trách nhiệm và vị trí từng user class vào SRS/kế hoạch yêu cầu, đối chiếu với hồ sơ stakeholder ở Vision &amp; Scope để tránh trùng, và ghi kích cỡ và lớp nào favored — giúp ưu tiên thay đổi và đánh giá tác động về sau.</p>`],
      [9, 'User personas', `<p>A <strong>persona</strong> is a description of a hypothetical, generic person standing in for a user class with similar characteristics and needs — used to understand requirements and design the experience. The Chemical Tracking System's "<strong>Fred, 41, a chemist</strong> with little patience for computers, needing four chemicals a day, wanting his monthly usage report emailed automatically" makes an abstract class vividly concrete, so the team designs for a real person, not a label.</p>`, `<p>Một <strong>persona</strong> là mô tả một người giả định, khái quát đại diện cho một user class có đặc điểm và nhu cầu tương tự — dùng để hiểu yêu cầu và thiết kế trải nghiệm. Ví dụ "<strong>Fred, 41 tuổi, nhà hoá học</strong> ít kiên nhẫn với máy tính, cần bốn hoá chất mỗi ngày, muốn báo cáo sử dụng hằng tháng tự gửi email" của Chemical Tracking System làm một lớp trừu tượng thành sống động cụ thể, để nhóm thiết kế cho một người thật, không phải một cái nhãn.</p>`],
    ]),
    books([
      ['wiegers', 'Chapter 6, "User classes" and "User personas"', 'Chương 6, "User classes" và "User personas"'],
      ['cos', 'the COS artifacts name their user classes — compare with your project', 'các tài liệu COS nêu tên user class — so với dự án của bạn'],
    ]),
  ].join('\n'),
};

/* 6U.2 — the product champion */
const U2 = {
  title: '6U.2 — Slides: connecting with users & the product champion (Ch.6 · 10–19)|||6U.2 — Slide: kết nối người dùng & product champion (Ch.6 · 10–19)',
  slug: 'swr302-6u-2-ch6-product-champion',
  type: 'DOCUMENT',
  description: 'Slide 10–19: vì sao mỗi user class cần người đại diện, các đường giao tiếp user–developer; và mô hình product champion — định nghĩa, việc họ làm, external champion, kỳ vọng, nhiều champion, thuyết phục áp dụng, và các bẫy cần tránh.',
  content: [
    bi(
      `<span class="eyebrow">Voice of the User · Lesson 6U.2 · Book Ch.6 slides 10–19</span>
<h2>Connecting with users &amp; the product champion</h2>
<p class="lead">Each user class needs a real person to speak for it. The strongest model is the <strong>product champion</strong> — an actual user who is the primary interface between their class and the BA. This lesson covers who they are, what they do, and the traps to avoid.</p>`,
      `<span class="eyebrow">Tiếng nói người dùng · Bài 6U.2 · Slide 10–19 sách Ch.6</span>
<h2>Kết nối người dùng &amp; product champion</h2>
<p class="lead">Mỗi user class cần một người thật nói thay. Mô hình mạnh nhất là <strong>product champion</strong> — một người dùng thật làm giao diện chính giữa lớp của họ và BA. Bài này bàn họ là ai, làm gì, và bẫy cần tránh.</p>`,
    ),
    walkHead('ch6', 10, 19),
    walk('ch6', [
      [10, 'Connecting with user representatives', `<p>Every project needs representatives to provide the voice of the user, <strong>involved throughout the lifecycle</strong> — not just an isolated phase at the start. Each class needs a spokesperson. Use <strong>focus groups</strong> of current or competitors' users (ask, don't guess) — and ensure they represent the users who <em>should</em> drive the product: include experts and less-experienced users, not just early adopters (or you'll get many sophisticated, useless requirements).</p>`, `<p>Mọi dự án cần đại diện cung cấp tiếng nói người dùng, <strong>tham gia suốt vòng đời</strong> — không chỉ một pha tách rời lúc đầu. Mỗi lớp cần người phát ngôn. Dùng <strong>focus group</strong> của người dùng hiện tại hoặc của đối thủ (hỏi, đừng đoán) — và đảm bảo họ đại diện đúng người <em>nên</em> dẫn dắt sản phẩm: gồm cả chuyên gia lẫn người ít kinh nghiệm, không chỉ early adopter (kẻo có nhiều yêu cầu tinh vi mà vô dụng).</p>`],
      [11, 'Communication pathways user → developer', `<p>The most direct path is a developer talking to users directly — but that means the developer <em>is</em> the BA, which works only on very small projects and doesn't scale. <strong>Intervening layers</strong> between user and developer increase miscommunication and delay — though a <strong>skilled BA</strong> adds value by collecting, evaluating, refining and organising input. The goal: as few, and as high-value, layers as possible.</p>`, `<p>Đường trực tiếp nhất là lập trình viên nói thẳng với người dùng — nhưng nghĩa là lập trình viên <em>chính là</em> BA, chỉ chạy được với dự án rất nhỏ và không mở rộng. <strong>Các lớp trung gian</strong> giữa user và developer tăng hiểu lầm và trễ — dù một <strong>BA giỏi</strong> thêm giá trị bằng cách thu, đánh giá, tinh lọc và tổ chức đầu vào. Mục tiêu: càng ít lớp, và lớp càng giá trị, càng tốt.</p>`],
      [12, 'The product champion — overview', `<p>The section covers: what a product champion is, what they do, external champions, champion expectations, multiple champions, selling the idea, and traps to avoid. It's the book's recommended way to secure the user's voice.</p>`, `<p>Phần này bàn: product champion là gì, làm gì, external champion, kỳ vọng, nhiều champion, thuyết phục áp dụng, và bẫy cần tránh. Đây là cách sách khuyến nghị để đảm bảo tiếng nói người dùng.</p>`],
      [13, 'What a product champion is & does', `<p>A champion is the <strong>primary interface between one user class and the BA</strong> — ideally an <em>actual user</em>, not a surrogate (sponsor, marketing, manager, or a developer imagining themselves a user). They <strong>gather requirements from their class and reconcile inconsistencies</strong> (requirements development is shared with the BA, but the BA writes the documents). The best champions have a clear system vision, are enthusiastic, respected communicators who know the domain — and can lead user adoption.</p>`, `<p>Champion là <strong>giao diện chính giữa một user class và BA</strong> — lý tưởng là <em>người dùng thật</em>, không phải người thay (nhà tài trợ, marketing, quản lý, hay lập trình viên tự tưởng mình là user). Họ <strong>thu yêu cầu từ lớp của mình và hoà giải mâu thuẫn</strong> (phát triển yêu cầu chia sẻ với BA, nhưng BA viết tài liệu). Champion giỏi nhất có tầm nhìn hệ thống rõ, nhiệt tình, giao tiếp được tôn trọng, hiểu miền — và dẫn dắt người dùng chấp nhận sản phẩm.</p>`],
      [14, 'External product champions', `<p>For commercial software, champions from outside are hard to find — companies use internal SMEs or consultants as surrogates, or engage close corporate customers (offer discounts/pay for their time). The risk: hearing <em>only</em> the champions' requirements. With a diverse base, first find the <strong>core requirements common to all</strong>, then add ones specific to individual customers, segments or user classes.</p>`, `<p>Với phần mềm thương mại, champion từ ngoài khó tìm — công ty dùng SME nội bộ hoặc tư vấn làm người thay, hoặc mời khách hàng doanh nghiệp thân (tặng giảm giá/trả công thời gian họ). Rủi ro: chỉ nghe yêu cầu của champion. Với tệp đa dạng, trước hết tìm <strong>yêu cầu lõi chung cho tất cả</strong>, rồi thêm cái riêng cho từng khách hàng, phân khúc hoặc user class.</p>`],
      [15, 'Product champion expectations', `<p><strong>Document what you expect champions to do</strong> — written expectations help build the case for specific individuals and clarify the role. Table 6-2 lists candidate activities; not every champion does all — use it as a starting point to <strong>negotiate</strong> each champion's responsibilities.</p>`, `<p><strong>Ghi rõ bạn kỳ vọng champion làm gì</strong> — kỳ vọng bằng văn bản giúp dựng lý lẽ chọn người cụ thể và làm rõ vai trò. Bảng 6-2 liệt kê hoạt động ứng viên; không champion nào làm hết — dùng nó làm điểm khởi đầu để <strong>thương lượng</strong> trách nhiệm từng champion.</p>`],
      [16, 'Product champion expectations (Table 6-2)', `<p>The table of possible champion activities (Wiegers 1996): eliciting from their class, resolving conflicts, reviewing requirements and prototypes, defining acceptance criteria, championing adoption, and more. Treat it as a menu to select from per champion.</p>`, `<p>Bảng các hoạt động champion có thể làm (Wiegers 1996): khai thác từ lớp của họ, giải xung đột, review yêu cầu và prototype, định acceptance criteria, cổ vũ chấp nhận, và hơn nữa. Coi như một thực đơn để chọn theo từng champion.</p>`],
      [17, 'Multiple product champions', `<p>One person rarely covers all users. Set up a <strong>team of BAs and champions</strong> (part-time, a few hours/week) — BAs elicit/analyse/document, one BA assembles a unified SRS. Example: Don, the Chemist champion, built a <strong>backup team of five chemists</strong> from other areas — a hierarchical approach engaging more users without massive workshops. Don sought consensus but <strong>made decisions when agreement failed</strong> so the project moved on.</p>`, `<p>Một người hiếm khi phủ hết người dùng. Lập một <strong>nhóm BA và champion</strong> (bán thời gian, vài giờ/tuần) — BA elicit/analyse/document, một BA gộp thành SRS thống nhất. Ví dụ: Don, champion của lớp Chemist, dựng một <strong>đội hỗ trợ năm nhà hoá học</strong> từ các bộ phận khác — cách phân cấp thu hút thêm người dùng mà không cần workshop khổng lồ. Don tìm đồng thuận nhưng <strong>tự quyết khi không đạt thoả thuận</strong> để dự án tiến.</p>`],
      [18, 'Selling the product champion idea', `<p>Expect resistance ("users too busy", "management wants to decide"). Ease it by <strong>separating business from user requirements</strong>: the champion decides at the <em>user-requirements</em> level within the scope set by business requirements; the sponsor keeps authority over vision, scope, priorities, schedule and budget. Documenting each champion's role gives comfort. If resisted, remind everyone that <strong>insufficient user involvement is a leading cause of project failure</strong>.</p>`, `<p>Chờ đợi phản kháng ("người dùng quá bận", "quản lý muốn quyết"). Làm dịu bằng cách <strong>tách business khỏi user requirement</strong>: champion quyết ở cấp <em>user requirement</em> trong phạm vi do business requirement đặt; nhà tài trợ giữ quyền về tầm nhìn, phạm vi, ưu tiên, lịch và ngân sách. Ghi rõ vai trò từng champion tạo sự an tâm. Nếu bị cản, nhắc mọi người rằng <strong>thiếu sự tham gia của người dùng là nguyên nhân hàng đầu khiến dự án thất bại</strong>.</p>`],
      [19, 'Product champion traps to avoid', `<p>The model works only when champions understand and accept their duties, have authority at the user-requirements level, and have time. Watch for: managers <strong>overriding</strong> a duly-authorised champion (breeds distrust); a champion pushing <strong>only their own</strong> requirements; a champion without a clear vision who just <strong>defers to the BA</strong>; and a senior user nominating a junior then <strong>backseat-driving</strong>. Beware anyone who claims to speak for a class they don't belong to.</p>`, `<p>Mô hình chỉ chạy khi champion hiểu và nhận nhiệm vụ, có quyền ở cấp user requirement, và có thời gian. Cẩn thận: quản lý <strong>lật</strong> quyết định của champion đã được trao quyền (gieo mất tin); champion chỉ đẩy <strong>yêu cầu của riêng mình</strong>; champion không có tầm nhìn rõ chỉ <strong>nhường cho BA</strong>; và một người dùng cấp cao đề cử người non rồi <strong>chỉ đạo từ sau lưng</strong>. Coi chừng ai tự nhận nói thay một lớp mà họ không thuộc về.</p>`],
    ]),
    books([['wiegers', 'Chapter 6, "Connecting with user representatives" and "The product champion"', 'Chương 6, "Connecting with user representatives" và "The product champion"']]),
  ].join('\n'),
};

/* 6U.3 — agile representation & resolving conflicts */
const U3 = {
  title: '6U.3 — Slides: user representation on agile & resolving conflicts (Ch.6 · 20–21)|||6U.3 — Slide: đại diện người dùng trên agile & giải xung đột (Ch.6 · 20–21)',
  slug: 'swr302-6u-3-ch6-agile-conflicts',
  type: 'DOCUMENT',
  description: 'Slide 20–21: vai trò product owner trên agile và cách phân biệt với product champion; và mở đầu chủ đề giải quyết yêu cầu xung đột.',
  content: [
    bi(
      `<span class="eyebrow">Voice of the User · Lesson 6U.3 · Book Ch.6 slides 20–21</span>
<h2>User representation on agile &amp; resolving conflicts</h2>
<p class="lead">How the voice of the user is secured on agile teams — the <strong>product owner</strong> — and how they differ from a product champion.</p>`,
      `<span class="eyebrow">Tiếng nói người dùng · Bài 6U.3 · Slide 20–21 sách Ch.6</span>
<h2>Đại diện người dùng trên agile &amp; giải xung đột</h2>
<p class="lead">Cách đảm bảo tiếng nói người dùng trên nhóm agile — <strong>product owner</strong> — và họ khác product champion ra sao.</p>`,
    ),
    walkHead('ch6', 20, 21),
    walk('ch6', [
      [20, 'User representation on agile — the product owner', `<p>Some agile methods put a single <strong>product owner</strong> on the team as the voice of the customer: they define the product's vision and develop and prioritise the <strong>product backlog</strong>. Key difference from a product champion: the product owner <strong>spans all three requirement levels</strong> (business, user, functional) — essentially straddling the champion <em>and</em> BA roles: representing the customer, defining features, prioritising. In Scrum, the product owner ultimately decides what capabilities to deliver and when.</p>`, `<p>Một số phương pháp agile đặt một <strong>product owner</strong> duy nhất trong nhóm làm tiếng nói khách hàng: họ định tầm nhìn sản phẩm và phát triển, ưu tiên <strong>product backlog</strong>. Khác biệt then chốt với product champion: product owner <strong>trải cả ba cấp yêu cầu</strong> (business, user, functional) — về cơ bản kiêm cả vai champion <em>và</em> BA: đại diện khách hàng, định feature, ưu tiên. Trong Scrum, product owner cuối cùng quyết năng lực nào giao và khi nào.</p>`],
      [21, 'Resolving conflicting requirements', `<p>Section divider bridging to conflict resolution: when representatives from different user classes (or a champion and other stakeholders) disagree, the decision makers must resolve it — guided by the <strong>business objectives and favored user classes</strong> (from lessons 5V and 6U.1). Document the resolution and its rationale so it isn't re-litigated.</p>`, `<p>Slide phân mục bắc cầu sang giải xung đột: khi đại diện các user class khác nhau (hoặc một champion và các bên khác) bất đồng, người quyết phải giải — dựa vào <strong>business objective và lớp người dùng favored</strong> (từ bài 5V và 6U.1). Ghi lại cách giải và lý do để khỏi tranh lại.</p>`],
    ]),
    books([['wiegers', 'Chapter 6, "User representation on agile projects"; and Chapter 2 on reaching agreement', 'Chương 6, "User representation on agile projects"; và Chương 2 về đạt đồng thuận']]),
  ].join('\n'),
};

export default {
  title: 'Finding the voice of the user (book Ch.6)|||Tìm tiếng nói của người dùng (Ch.6 sách)',
  description: 'Chương 6 sách Wiegers: phân lớp người dùng (favored/disfavored/ignored), user persona, mô hình product champion, và product owner trên agile. Tách 3 bài.',
  lessons: [U1, U2, U3],
};
