/**
 * FER202 · Chapter 7 additions — Props, State and Context (Slot 8, 21 slides:
 * state in class vs function, props, defaultProps, stateless & container
 * components, providing/consuming Context). Grounded slide-by-slide in
 * Slot8_Props_State_and_Context.pptx. Slide 19 points to Exercise 11 (placed in
 * Chapter 5) and slide 20 to Lab 3, so this chapter adds the walkthrough only.
 * Spliced into Chapter 7 before its quiz; existing 7.1 / 7.2 lessons untouched.
 */
import { walk, walkHead, bi, books } from './_slides.mjs';

const SLIDES = {
  title: '7.3 — Slide by slide: Props, State & Context (Slot 8)|||7.3 — Học theo từng slide: Props, State & Context (Slot 8)',
  slug: 'fer202-7-3-slot8-props-context-slides',
  type: 'DOCUMENT',
  description: 'Toàn bộ 21 slide Slot 8: state trong class (setState, không sửa trực tiếp) vs function (useState); props là gì và khác state; defaultProps; stateless (pure) components; container components (tách lấy dữ liệu khỏi hiển thị); và Context (provider/consumer) để tránh prop drilling.',
  content: [
    bi(
      `<span class="eyebrow">Chapter 7 · Lesson 7.3 · Slot 8 deck (21 slides)</span>
<h2>Props, State & Context, slide by slide</h2>
<p class="lead">Three ways data lives in and moves through a React app: <strong>props</strong> (passed in, read-only), <strong>state</strong> (owned, changeable) and <strong>context</strong> (shared across the tree without prop drilling). This deck also introduces the container-component pattern.</p>`,
      `<span class="eyebrow">Chương 7 · Bài 7.3 · Bộ slide Slot 8 (21 slide)</span>
<h2>Props, State & Context, theo từng slide</h2>
<p class="lead">Ba cách dữ liệu tồn tại và di chuyển trong app React: <strong>props</strong> (truyền vào, chỉ đọc), <strong>state</strong> (sở hữu, đổi được) và <strong>context</strong> (chia sẻ khắp cây mà không "khoan" props). Bộ slide cũng giới thiệu mẫu container component.</p>`,
    ),
    walkHead('slot8', 1, 21),
    walk('slot8', [
      [1, 'Props, State and Context', `<p>Title slide.</p>`, `<p>Slide bìa.</p>`],
      [2, 'Objectives', `<p>The map: passing property values, stateless components, container components, and providing/consuming context.</p>`, `<p>Bản đồ: truyền giá trị property, stateless component, container component, và cung cấp/tiêu thụ context.</p>`],
      [3, 'State in class components', `<p>State is declared in the <code>constructor</code> (<code>this.state = {…}</code>) and must only be changed with <code>setState()</code>. <strong>Never</strong> mutate directly (<code>this.state.count = this.state.count + 1</code>) — React would not know to re-render and the change is lost.</p>`, `<p>State khai trong <code>constructor</code> (<code>this.state = {…}</code>) và chỉ được đổi bằng <code>setState()</code>. <strong>Không bao giờ</strong> sửa trực tiếp (<code>this.state.count = this.state.count + 1</code>) — React sẽ không biết để re-render và thay đổi bị mất.</p>`],
      [4, 'State in function components', `<p>Function components use the <code>useState()</code> Hook: <code>import { useState } from 'react'</code>, then <code>const [count, setCount] = useState(0)</code>. Same concept as class state, far less ceremony (full detail in Chapter 8).</p>`, `<p>Function component dùng Hook <code>useState()</code>: <code>import { useState } from 'react'</code>, rồi <code>const [count, setCount] = useState(0)</code>. Cùng ý với state của class, ít rườm rà hơn nhiều (chi tiết ở Chương 8).</p>`],
      [5, 'What are props?', `<p><strong>Props pass data into a component</strong> (in JSX they are written as attributes). Unlike state, props <strong>do not change</strong> after the initial render <em>from the component's own view</em> — they are read-only. If a prop value changes, the parent re-renders the child with the new value; React does this efficiently.</p>`, `<p><strong>Props truyền dữ liệu vào component</strong> (trong JSX viết như thuộc tính). Khác state, props <strong>không đổi</strong> sau render đầu <em>dưới góc nhìn của chính component</em> — chúng chỉ đọc. Nếu giá trị prop đổi, cha re-render con với giá trị mới; React làm việc này hiệu quả.</p>`],
      [6, 'Props with a class component', `<p>Read props via <code>this.props</code>: <code>class Hello extends React.Component { render() { return &lt;h1&gt;Hi {this.props.name}&lt;/h1&gt;; } }</code>, used as <code>&lt;Hello name="An" /&gt;</code>.</p>`, `<p>Đọc props qua <code>this.props</code>: <code>class Hello extends React.Component { render() { return &lt;h1&gt;Hi {this.props.name}&lt;/h1&gt;; } }</code>, dùng như <code>&lt;Hello name="An" /&gt;</code>.</p>`],
      [7, 'Props with a functional component', `<p>Props arrive as the function's first argument: <code>function Hello(props) { return &lt;h1&gt;Hi {props.name}&lt;/h1&gt;; }</code> — usually destructured: <code>function Hello({ name })</code>.</p>`, `<p>Props tới như đối số đầu của hàm: <code>function Hello(props) { return &lt;h1&gt;Hi {props.name}&lt;/h1&gt;; }</code> — thường destructure: <code>function Hello({ name })</code>.</p>`],
      [8, 'Setting component state — initial', `<p>Set initial state (class: in the constructor; function: the <code>useState</code> argument) and render UI from it — e.g. two buttons whose labels depend on state.</p>`, `<p>Đặt state ban đầu (class: trong constructor; function: đối số của <code>useState</code>) và render UI từ nó — ví dụ hai nút có nhãn phụ thuộc state.</p>`],
      [9, 'Setting component state — loading UI', `<p>A common pattern: a <code>loading</code> state flag. Render a spinner "while loading", then the data "when loading is complete" — state drives which UI shows.</p>`, `<p>Mẫu phổ biến: một cờ state <code>loading</code>. Render spinner "khi đang tải", rồi dữ liệu "khi tải xong" — state quyết định UI nào hiện.</p>`],
      [10, 'Setting component state — merging', `<p>Class <code>setState</code> <strong>merges</strong> the object you pass into the existing state (only the keys you provide change). With the <code>useState</code> Hook there is <strong>no auto-merge</strong> — you spread the old state yourself: <code>setUser(u =&gt; ({ ...u, name }))</code>.</p>`, `<p><code>setState</code> của class <strong>gộp</strong> object bạn truyền vào state hiện có (chỉ các key bạn đưa mới đổi). Với Hook <code>useState</code> <strong>không tự gộp</strong> — bạn tự spread state cũ: <code>setUser(u =&gt; ({ ...u, name }))</code>.</p>`],
      [11, 'Passing property values — defaultProps', `<p>Give a prop a fallback: class/older style <code>Component.defaultProps = { color: 'blue' }</code>; in modern function components use a default parameter: <code>function Btn({ color = 'blue' })</code>.</p>`, `<p>Cho prop một giá trị dự phòng: kiểu class/cũ <code>Component.defaultProps = { color: 'blue' }</code>; trong function component hiện đại dùng tham số mặc định: <code>function Btn({ color = 'blue' })</code>.</p>`],
      [12, 'Passing property values — setting values', `<p>Pass literals (<code>title="Hi"</code>), expressions (<code>count={n}</code>), and spread an object of props (<code>&lt;Card {...item} /&gt;</code>). Booleans shorthand: <code>disabled</code> = <code>disabled={true}</code>.</p>`, `<p>Truyền literal (<code>title="Hi"</code>), biểu thức (<code>count={n}</code>), và spread một object props (<code>&lt;Card {...item} /&gt;</code>). Boolean viết tắt: <code>disabled</code> = <code>disabled={true}</code>.</p>`],
      [13, 'Stateless components — pure functions', `<p>A <strong>stateless</strong> (presentational) component is a pure function of its props: same props → same output, no state, no side effects. Easy to test and reuse. Most of your components should be like this.</p>`, `<p>Component <strong>stateless</strong> (trình bày) là một hàm thuần của props: cùng props → cùng kết quả, không state, không side effect. Dễ test và tái dùng. Phần lớn component của bạn nên như vậy.</p>`],
      [14, 'Stateless components — defaults', `<p>Give presentational components sensible prop defaults so they render safely even with missing data: <code>function Avatar({ url = '/placeholder.png' })</code>.</p>`, `<p>Cho component trình bày các default hợp lý để render an toàn kể cả khi thiếu dữ liệu: <code>function Avatar({ url = '/placeholder.png' })</code>.</p>`],
      [15, 'Container components', `<p>The pattern: <strong>do not couple data fetching with rendering</strong>. A <em>container</em> fetches data and passes it to a <em>presentational</em> child that just renders it. Benefits: you can swap the child, reuse the child in another container, and test each independently.</p>`, `<p>Mẫu: <strong>đừng gắn việc lấy dữ liệu với việc hiển thị</strong>. Một <em>container</em> lấy dữ liệu và truyền cho một con <em>trình bày</em> chỉ lo render. Lợi ích: đổi được con, tái dùng con ở container khác, và test từng cái độc lập.</p>`],
      [16, 'Container components — cont’d', `<p>In modern React the container's fetching logic usually lives in a <code>useEffect</code> or a custom Hook (Chapter 8 & 11), while the presentational child stays a pure function of props.</p>`, `<p>Trong React hiện đại, logic lấy dữ liệu của container thường nằm trong một <code>useEffect</code> hoặc một custom Hook (Chương 8 & 11), còn con trình bày vẫn là hàm thuần của props.</p>`],
      [17, 'Providing and consuming context', `<p><strong>Context</strong> shares data across the tree without passing props through every level ("prop drilling"). A <strong>provider</strong> creates data and makes it available; a <strong>consumer</strong> reads it. Example: permission/theme/auth data many components need.</p>`, `<p><strong>Context</strong> chia sẻ dữ liệu khắp cây mà không truyền props qua từng cấp ("prop drilling"). Một <strong>provider</strong> tạo dữ liệu và cung cấp; một <strong>consumer</strong> đọc nó. Ví dụ: dữ liệu quyền/theme/auth mà nhiều component cần.</p>`],
      [18, 'Providing and consuming context — cont’d', `<p>Modern API: <code>const Ctx = createContext()</code>, wrap with <code>&lt;Ctx.Provider value={…}&gt;</code>, and read with the <code>useContext(Ctx)</code> Hook (Chapter 8) instead of the older <code>&lt;Ctx.Consumer&gt;</code> render-prop. This is your lesson 7.1/7.2 in the deck's words.</p>`, `<p>API hiện đại: <code>const Ctx = createContext()</code>, bọc bằng <code>&lt;Ctx.Provider value={…}&gt;</code>, và đọc bằng Hook <code>useContext(Ctx)</code> (Chương 8) thay cho render-prop <code>&lt;Ctx.Consumer&gt;</code> cũ. Đây là bài 7.1/7.2 của bạn, bằng lời của slide.</p>`],
      [19, 'Exercise 11 / Exercise 12: components with props', `<p>The deck points to the component exercises. On this site, <strong>Exercise 11</strong> (to-do, calculator, search filter) is in Chapter 5, and the state/props exercises continue in Chapter 8 (useState/useContext).</p>`, `<p>Slide trỏ tới các bài tập component. Trên trang này, <strong>Exercise 11</strong> (to-do, máy tính, lọc tìm kiếm) nằm ở Chương 5, và các bài state/props tiếp tục ở Chương 8 (useState/useContext).</p>`],
      [20, 'Lab 3: all components', `<p>Points to the larger lab combining everything — props, state, container components and context. Practise it with the Chapter 8 hooks exercises and the practice project.</p>`, `<p>Trỏ tới bài lab lớn gộp mọi thứ — props, state, container component và context. Luyện qua các bài Hooks Chương 8 và dự án luyện tập.</p>`],
      [21, 'Summary', `<p>Recap: props pass data in (read-only) and are set with literals/expressions/spread and defaults; state is owned and changed with <code>setState</code>/<code>useState</code> (class merges, Hook does not); split container (data) from presentational (render) components; and use Context (provider/consumer) to share data without prop drilling.</p>`, `<p>Tóm tắt: props truyền dữ liệu vào (chỉ đọc), đặt bằng literal/biểu thức/spread và default; state được sở hữu và đổi bằng <code>setState</code>/<code>useState</code> (class gộp, Hook không); tách container (dữ liệu) khỏi presentational (render); và dùng Context (provider/consumer) để chia sẻ dữ liệu mà không prop drilling.</p>`],
    ]),
    books([
      ['reactdoc', '“Passing Props to a Component”, “Sharing State Between Components”, “Passing Data Deeply with Context”', '“Passing Props to a Component”, “Sharing State Between Components”, “Passing Data Deeply with Context”'],
    ]),
  ].join('\n'),
};

export default [SLIDES];
