// AUTO-GENERATED by scripts/build-fe-exam.mjs from bank-JPD123-D46.jsonl — re-run the builder, do not hand-edit.
export default {
  "course": {
    "courseCode": "JPD123"
  },
  "exams": [
    {
      "kind": "FE",
      "code": "D46",
      "title": "Đề 46 — Final Exam (SP2023-RE)|||Đề 46 — Thi cuối kỳ (SP2023-RE)",
      "description": "Japanese language (JPD123) exam (SP2023-RE), bilingual EN/VI MCQs with Japanese text preserved.|||Đề thi tiếng Nhật JPD123 (SP2023-RE), trắc nghiệm song ngữ Anh/Việt, giữ nguyên chữ Nhật.",
      "durationMinutes": 45,
      "totalPoints": 10,
      "passMark": 4,
      "source": "REAL",
      "shuffleQuestions": false,
      "shuffleOptions": false,
      "instructions": "<div class=\"ml-en\"><p>This is a real FPTU <b>Final Exam</b> paper for <b>Japanese Language (JPD123)</b>. Every question is <b>multiple choice</b> and auto-graded.</p><ul><li>Some questions say \"choose TWO\" — they are only correct when both right answers are selected.</li><li>Read code, tables and diagrams carefully; several questions turn on a subtle detail.</li><li>The original scanned question is available under <b>\"Show original image\"</b> on each question.</li></ul><p>You can flag a question and come back. The timer auto-submits at the end. After you submit, every question shows a bilingual explanation.</p></div><div class=\"ml-vi\"><p>Đây là đề <b>thi cuối kỳ (Final Exam)</b> thật của FPTU môn <b>Japanese Language (JPD123)</b>. Mọi câu đều là <b>trắc nghiệm</b>, chấm tự động.</p><ul><li>Một số câu ghi \"chọn HAI\" — chỉ đúng khi chọn đủ cả hai đáp án đúng.</li><li>Đọc kỹ code, bảng và sơ đồ; nhiều câu ăn thua ở một chi tiết nhỏ.</li><li>Ảnh đề gốc đã quét nằm ở nút <b>\"Xem ảnh đề gốc\"</b> trên mỗi câu.</li></ul><p>Bạn có thể đánh dấu câu để quay lại sau. Hết giờ hệ thống tự nộp. Nộp xong, mỗi câu đều có lời giải song ngữ.</p></div>",
      "isPublished": true,
      "questions": [
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>おおさかから とうきょうまで ひこうきで（　　）ですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>おおさかから とうきょうまで ひこうきで（　　）ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q1.png",
          "options": [
            {
              "text": "どんな|||どんな"
            },
            {
              "text": "どれ|||どれ"
            },
            {
              "text": "どのくらい|||どのくらい"
            },
            {
              "text": "どうして|||どうして"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>どのくらい (&quot;about how much/how long&quot;) asks about a duration or degree — here, how long the flight from Osaka to Tokyo takes. どんな = what kind of, どれ = which one (of a set), どうして = why — none fit asking about flight duration.</p></div><div class=\"ml-vi\"><p>どのくらい (khoảng bao lâu/bao nhiêu) dùng để hỏi về thời lượng hoặc mức độ — ở đây là hỏi chuyến bay từ Osaka đến Tokyo mất bao lâu. どんな = loại nào, どれ = cái nào (trong một nhóm), どうして = tại sao — đều không phù hợp để hỏi thời gian bay.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>＿＿＿＿＿＿＿＿＿へ　かばんを　買いに　行きます。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>＿＿＿＿＿＿＿＿＿へ　かばんを　買いに　行きます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q2.png",
          "options": [
            {
              "text": "としょかん|||としょかん"
            },
            {
              "text": "レストラン|||レストラン"
            },
            {
              "text": "デパート|||デパート"
            },
            {
              "text": "きっさてん|||きっさてん"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Going to buy a bag&quot; (かばんを買いに行きます) points to デパート (department store), the natural place to buy a bag. としょかん = library, レストラン = restaurant, きっさてん = coffee shop — none sell bags.</p></div><div class=\"ml-vi\"><p>&quot;Đi mua cặp/túi xách&quot; (かばんを買いに行きます) phù hợp với デパート (cửa hàng bách hóa), nơi tự nhiên để mua cặp. としょかん = thư viện, レストラン = nhà hàng, きっさてん = quán cà phê — không nơi nào bán cặp.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>田中：いっしょに　かいものに　行きませんか。<br/>ミラー：＿＿＿＿＿＿＿＿＿＿＿＿＿＿。行きましょう。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>田中：いっしょに　かいものに　行きませんか。<br/>ミラー：＿＿＿＿＿＿＿＿＿＿＿＿＿＿。行きましょう。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q3.png",
          "options": [
            {
              "text": "すみません|||すみません"
            },
            {
              "text": "ちょっと|||ちょっと"
            },
            {
              "text": "いいですね|||いいですね"
            },
            {
              "text": "そうですね|||そうですね"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Tanaka invites Miller shopping (&quot;Won&#39;t you go shopping with me?&quot;). Miller accepts happily before saying &quot;Let&#39;s go&quot; (行きましょう), and いいですね (&quot;Sounds good!&quot;) is the natural upbeat acceptance leading into that. すみません/ちょっと are used to decline, and そうですね is more of a neutral &quot;I see/let me think&quot; filler, not a direct enthusiastic acceptance.</p></div><div class=\"ml-vi\"><p>Tanaka rủ Miller đi mua sắm (&quot;Cùng đi mua sắm không?&quot;). Miller vui vẻ đồng ý trước khi nói &quot;Đi thôi&quot; (行きましょう), nên いいですね (&quot;Hay đấy!&quot;) là câu chấp nhận tự nhiên, hào hứng dẫn tới câu sau. すみません/ちょっと thường dùng để từ chối, còn そうですね thiên về &quot;để xem/ừ nhỉ&quot; hơn là chấp nhận nhiệt tình.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it read? Choose the correct answer.<br/>まいあさ、ほんを【読みます】。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng<br/>まいあさ、ほんを【読みます】。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q4.png",
          "options": [
            {
              "text": "よみます|||よみます"
            },
            {
              "text": "のみます|||のみます"
            },
            {
              "text": "しみます|||しみます"
            },
            {
              "text": "かみます|||かみます"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>読む (to read) → polite form よみます. のみます = drink, かみます = bite, しみます is not a standard verb here.</p></div><div class=\"ml-vi\"><p>動詞 読む (đọc) → thể lịch sự よみます. のみます = uống, かみます = cắn, しみます không phải động từ chuẩn trong ngữ cảnh này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>今年の　ふゆ、＿＿＿＿＿＿＿＿＿へ　スキーを　しに　行きます。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>今年の　ふゆ、＿＿＿＿＿＿＿＿＿へ　スキーを　しに　行きます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q5.png",
          "options": [
            {
              "text": "ほっかいどう|||ほっかいどう"
            },
            {
              "text": "レストラン|||レストラン"
            },
            {
              "text": "デパート|||デパート"
            },
            {
              "text": "きっさてん|||きっさてん"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Going to ski this winter&quot; needs a ski destination — ほっかいどう (Hokkaido), Japan&#39;s famous ski region. The other three are indoor commercial venues (restaurant, department store, coffee shop), not ski destinations.</p></div><div class=\"ml-vi\"><p>&quot;Mùa đông năm nay đi trượt tuyết&quot; cần một địa điểm trượt tuyết — ほっかいどう (Hokkaido), vùng nổi tiếng trượt tuyết ở Nhật. Ba lựa chọn còn lại là địa điểm trong nhà (nhà hàng, bách hóa, quán cà phê), không phải nơi trượt tuyết.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>せんしゅう、こいびと（　　）会いました。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>せんしゅう、こいびと（　　）会いました。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q6.png",
          "options": [
            {
              "text": "を|||を"
            },
            {
              "text": "に|||に"
            },
            {
              "text": "へ|||へ"
            },
            {
              "text": "で|||で"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The verb 会う (&quot;to meet&quot;) takes the target particle に: 〜に会う = &quot;to meet (someone)&quot;. を, へ, で do not fit this fixed pattern.</p></div><div class=\"ml-vi\"><p>Động từ 会う (gặp) đi với trợ từ に: 〜に会う = &quot;gặp (ai đó)&quot;. を, へ, で không phù hợp với mẫu câu cố định này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>ともだち（　　）おかね（　　）かりました。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>ともだち（　　）おかね（　　）かりました。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q7.png",
          "options": [
            {
              "text": "を／に|||を／に"
            },
            {
              "text": "に／を|||に／を"
            },
            {
              "text": "に／で|||に／で"
            },
            {
              "text": "で／に|||で／に"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>かりる (&quot;to borrow&quot;) marks the source person with に and the borrowed item with を: ともだちに おかねを かりました (&quot;borrowed money from a friend&quot;).</p></div><div class=\"ml-vi\"><p>かりる (mượn) đánh dấu người cho mượn bằng に và vật được mượn bằng を: ともだちに おかねを かりました (mượn tiền từ bạn).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>A：マルコさん、やさいを（　　　　）。<br/>B：はい、わかりました。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：マルコさん、やさいを（　　　　）。<br/>B：はい、わかりました。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q8.png",
          "options": [
            {
              "text": "あらいますか|||あらいますか"
            },
            {
              "text": "あらってください|||あらってください"
            },
            {
              "text": "あらいませんか|||あらいませんか"
            },
            {
              "text": "あらいましたか|||あらいましたか"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>B&#39;s response &quot;わかりました&quot; (&quot;understood/got it&quot;) is the natural reply to a request or instruction, so A must be making a polite request: あらってください (&quot;please wash [the vegetables]&quot;), the 〜てください request form.</p></div><div class=\"ml-vi\"><p>Câu trả lời của B &quot;わかりました&quot; (đã hiểu/rõ rồi) là phản hồi tự nhiên cho một yêu cầu hoặc chỉ dẫn, nên câu A phải là lời yêu cầu lịch sự: あらってください (hãy rửa [rau]), dùng mẫu 〜てください.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>毎日、りょうりを　＿＿＿＿＿＿＿＿＿。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>毎日、りょうりを　＿＿＿＿＿＿＿＿＿。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q9.png",
          "options": [
            {
              "text": "つくります|||つくります"
            },
            {
              "text": "あいます|||あいます"
            },
            {
              "text": "かいものします|||かいものします"
            },
            {
              "text": "のぼります|||のぼります"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>りょうりを つくります (&quot;make/cook food&quot;) is the natural collocation. あいます = meet (takes に, not を), かいものします = shop (doesn&#39;t take りょうりを), のぼります = climb.</p></div><div class=\"ml-vi\"><p>りょうりを つくります (nấu ăn) là cụm từ tự nhiên nhất. あいます = gặp (đi với に, không phải を), かいものします = mua sắm (không đi với りょうりを), のぼります = leo/trèo.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the word that is a different type from the following words:<br/>① しずか<br/>② ひま<br/>③ きれい<br/>④ やすい</p></div><div class=\"ml-vi\"><p>Chọn từ khác loại trong những từ sau:<br/>① しずか<br/>② ひま<br/>③ きれい<br/>④ やすい</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q10.png",
          "options": [
            {
              "text": "たいへん|||たいへん"
            },
            {
              "text": "ひま|||ひま"
            },
            {
              "text": "きれい|||きれい"
            },
            {
              "text": "やすい|||やすい"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>しずか, ひま, and きれい are all na-adjectives (na-keiyoushi). やすい is an i-adjective (ends in い and conjugates differently, e.g. やすくない not やすじゃない), so it is the odd one out. Note option A in the answer list (たいへん) is not one of the four numbered words but is also a na-adjective; the correct pick among the four listed words (①-④) is ④ やすい, shown as option D.</p></div><div class=\"ml-vi\"><p>しずか, ひま, và きれい đều là tính từ đuôi -na (na-keiyoushi). やすい là tính từ đuôi -i (kết thúc bằng い và chia khác, ví dụ やすくない chứ không phải やすじゃない), nên là từ khác loại. Lưu ý phương án A trong danh sách (たいへん) không nằm trong 4 từ được đánh số nhưng cũng là tính từ -na; từ đúng trong 4 từ ①-④ là ④ やすい, tương ứng phương án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>肉が　きらいですから、＿＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>肉が　きらいですから、＿＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q11.png",
          "options": [
            {
              "text": "食べません|||食べません"
            },
            {
              "text": "国（くに）へ　かえりません|||国（くに）へ　かえりません"
            },
            {
              "text": "どこへも　行きませんでした|||どこへも　行きませんでした"
            },
            {
              "text": "こんばん、うちで　べんきょうします|||こんばん、うちで　べんきょうします"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Because I dislike meat, ___&quot; logically continues with the direct consequence: 食べません (&quot;I don&#39;t/won&#39;t eat it&quot;). The other options (not returning home, not going anywhere, studying tonight) are unrelated to disliking meat.</p></div><div class=\"ml-vi\"><p>&quot;Vì ghét thịt, ___&quot; tiếp nối hợp lý bằng hệ quả trực tiếp: 食べません (không ăn). Các lựa chọn khác (không về nước, không đi đâu cả, tối nay học ở nhà) không liên quan đến việc ghét thịt.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>おんせんは＿＿＿＿＿＿＿＿＿＿＿です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>おんせんは＿＿＿＿＿＿＿＿＿＿＿です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q12.png",
          "options": [
            {
              "text": "むずかしい|||むずかしい"
            },
            {
              "text": "かんたん|||かんたん"
            },
            {
              "text": "きもちが　いい|||きもちが　いい"
            },
            {
              "text": "たいへん|||たいへん"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>A hot spring (おんせん) is most naturally described as きもちがいい (&quot;feels good&quot;). むずかしい (difficult) and かんたん (simple/easy) describe tasks, not the sensation of bathing; たいへん (tough/hard) also doesn&#39;t fit.</p></div><div class=\"ml-vi\"><p>Suối nước nóng (おんせん) tự nhiên được miêu tả là きもちがいい (cảm giác thoải mái/dễ chịu). むずかしい (khó), かんたん (đơn giản) dùng cho việc/nhiệm vụ chứ không phải cảm giác tắm suối; たいへん (vất vả) cũng không phù hợp.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>ペン（　　）なまえを　かいてください。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>ペン（　　）なまえを　かいてください。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q13.png",
          "options": [
            {
              "text": "と|||と"
            },
            {
              "text": "は|||は"
            },
            {
              "text": "が|||が"
            },
            {
              "text": "で|||で"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>で marks the instrument/means used to perform an action: ペンで書く (&quot;write with a pen&quot;). と, は, が don&#39;t express &quot;means/instrument&quot;.</p></div><div class=\"ml-vi\"><p>で đánh dấu công cụ/phương tiện dùng để thực hiện hành động: ペンで書く (viết bằng bút). と, は, が không diễn tả &quot;phương tiện/công cụ&quot;.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it read? Choose the correct answer.<br/>【食べ物】で　なにが　いちばん　すきですか。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng<br/>【食べ物】で　なにが　いちばん　すきですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q14.png",
          "options": [
            {
              "text": "たべもの|||たべもの"
            },
            {
              "text": "たべます|||たべます"
            },
            {
              "text": "かべもの|||かべもの"
            },
            {
              "text": "のべもの|||のべもの"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>食べ物 (&quot;food&quot;) is read たべもの. The other options are not valid readings of this compound.</p></div><div class=\"ml-vi\"><p>食べ物 (đồ ăn/thức ăn) đọc là たべもの. Các lựa chọn còn lại không phải cách đọc hợp lệ của từ ghép này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>ベトナムの　歌手（かしゅ）で　＿＿＿＿＿＿＿＿＿が　いちばん　すきですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>ベトナムの　歌手（かしゅ）で　＿＿＿＿＿＿＿＿＿が　いちばん　すきですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q15.png",
          "options": [
            {
              "text": "なに|||なに"
            },
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "だれ|||だれ"
            },
            {
              "text": "どう|||どう"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>歌手 (&quot;singer&quot;) is a person, so the question word must ask &quot;who&quot;: だれ (&quot;who is your favorite among Vietnamese singers&quot;). なに = what, どこ = where, どう = how — none fit asking about a person.</p></div><div class=\"ml-vi\"><p>歌手 (ca sĩ) là con người, nên từ để hỏi phải là &quot;ai&quot;: だれ (&quot;trong các ca sĩ Việt Nam, bạn thích ai nhất&quot;). なに = cái gì, どこ = ở đâu, どう = như thế nào — không phù hợp khi hỏi về con người.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>ケーキは　＿＿＿＿＿＿＿＿です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>ケーキは　＿＿＿＿＿＿＿＿です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q16.png",
          "options": [
            {
              "text": "からい|||からい"
            },
            {
              "text": "あまい|||あまい"
            },
            {
              "text": "にがい|||にがい"
            },
            {
              "text": "ひくい|||ひくい"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Cake (ケーキ) is naturally described as あまい (&quot;sweet&quot;). からい = spicy, にがい = bitter, ひくい = low (height) — none describe cake.</p></div><div class=\"ml-vi\"><p>Bánh ngọt (ケーキ) tự nhiên được miêu tả là あまい (ngọt). からい = cay, にがい = đắng, ひくい = thấp — không dùng để tả bánh ngọt.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>やさいを（　　　）ください。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>やさいを（　　　）ください。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q17.png",
          "options": [
            {
              "text": "きりて|||きりて"
            },
            {
              "text": "きり|||きり"
            },
            {
              "text": "きって|||きって"
            },
            {
              "text": "きいて|||きいて"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>きる (&quot;to cut&quot;, a godan verb ending in る) forms its te-form as きって (double consonant, う-column irregular te-form group). ください needs the te-form, so きって is correct. きりて is not a valid te-form; きいて is the te-form of きく (hear/ask/listen), not きる.</p></div><div class=\"ml-vi\"><p>きる (cắt, động từ nhóm 1 kết thúc bằng る) chia thể て thành きって (âm ngắt đôi phụ âm, nhóm động từ bất quy tắc theo âm う). ください cần thể て, nên きって là đáp án đúng. きりて không phải thể て hợp lệ; きいて là thể て của きく (nghe/hỏi), không phải きる.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>私の　くには　ちいさいです＿＿＿＿＿＿、人が　おおいです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>私の　くには　ちいさいです＿＿＿＿＿＿、人が　おおいです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q18.png",
          "options": [
            {
              "text": "そして|||そして"
            },
            {
              "text": "が|||が"
            },
            {
              "text": "も|||も"
            },
            {
              "text": "と|||と"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The sentence contrasts &quot;my country is small&quot; with &quot;but its population is large&quot; — a contradictory relationship. が attached after です/ます forms means &quot;but/although&quot; (逆接), which fits here: ちいさいですが、人がおおいです (&quot;it&#39;s small, but there are many people&quot;). そして means &quot;and then/additionally&quot; (順接), which doesn&#39;t express contrast as naturally.</p></div><div class=\"ml-vi\"><p>Câu này đối lập &quot;nước tôi nhỏ&quot; với &quot;nhưng dân số đông&quot; — quan hệ tương phản. が gắn sau です/ます mang nghĩa &quot;nhưng/tuy&quot; (逆接), phù hợp ở đây: ちいさいですが、人がおおいです (nhỏ, nhưng dân số đông). そして mang nghĩa &quot;và rồi/thêm vào đó&quot; (順接), không diễn tả tương phản tự nhiên bằng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it written in Kanji? Choose the correct answer.<br/>私の　まちに【おおきい】おしろが　あります。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng<br/>私の　まちに【おおきい】おしろが　あります。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q19.png",
          "options": [
            {
              "text": "大きい|||大きい"
            },
            {
              "text": "大い|||大い"
            },
            {
              "text": "太きい|||太きい"
            },
            {
              "text": "太い|||太い"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>おおきい (&quot;big/large&quot;) is written 大きい. 大い is missing the き okurigana and isn&#39;t a valid word; 太きい and 太い use 太 (&quot;fat/thick&quot;, read ふとい), the wrong kanji.</p></div><div class=\"ml-vi\"><p>おおきい (to/lớn) viết là 大きい. 大い thiếu okurigana き nên không phải từ hợp lệ; 太きい và 太い dùng chữ 太 (béo/dày, đọc ふとい), sai chữ Hán.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Based on the given word cues, choose the sentence with complete/correct meaning among options A, B, C, D<br/>さむい／とても／1月／私／まち／です</p></div><div class=\"ml-vi\"><p>Dựa vào các từ gợi ý cho sẵn hãy chọn câu có ý nghĩa hoàn chỉnh trong các phương án A,B,C,D<br/>さむい／とても／1月／私／まち／です</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q20.png",
          "options": [
            {
              "text": "私は　1月　まち　とても　さむいです。|||私は　1月　まち　とても　さむいです。"
            },
            {
              "text": "私の　まちは　1月　とても　さむいです。|||私の　まちは　1月　とても　さむいです。"
            },
            {
              "text": "まちは　私の　1月　さむい　とても　です。|||まちは　私の　1月　さむい　とても　です。"
            },
            {
              "text": "とても　さむい　私　まちは　1月です。|||とても　さむい　私　まちは　1月です。"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The correctly ordered sentence is 私の　まちは　1月　とても　さむいです (&quot;My town is very cold in January&quot;): topic 私のまちは, time 1月, degree adverb とても, then the i-adjective+です predicate さむいです. The other options break word order (adverb/predicate placement, missing の, misplaced です).</p></div><div class=\"ml-vi\"><p>Câu sắp xếp đúng là 私の　まちは　1月　とても　さむいです (&quot;Thị trấn của tôi tháng 1 rất lạnh&quot;): chủ đề 私のまちは, thời gian 1月, phó từ mức độ とても, rồi vị ngữ tính từ-i+です là さむいです. Các phương án khác sai trật tự từ (vị trí phó từ/vị ngữ, thiếu の, đặt sai です).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the corresponding Vietnamese meaning of the following word:<br/>&quot;きょうかい&quot;</p></div><div class=\"ml-vi\"><p>Chọn nghĩa tiếng Việt tương ứng của từ sau:<br/>&quot;きょうかい&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q21.png",
          "options": [
            {
              "text": "Suối nước nóng|||Suối nước nóng"
            },
            {
              "text": "Nhà thờ|||Nhà thờ"
            },
            {
              "text": "Lâu đài|||Lâu đài"
            },
            {
              "text": "Đền thờ|||Đền thờ"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>きょうかい (教会) means &quot;church&quot; — Nhà thờ. Suối nước nóng = hot spring (おんせん), Lâu đài = castle (おしろ), Đền thờ = shrine (じんじゃ/おてら).</p></div><div class=\"ml-vi\"><p>きょうかい (教会) nghĩa là &quot;nhà thờ&quot;. Suối nước nóng là おんせん, Lâu đài là おしろ, Đền thờ là じんじゃ/おてら.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The word in brackets [ ] below — how is it written in Kanji? Choose the correct answer.<br/>【とうきょう】は　1月　とても　さむいです。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng<br/>【とうきょう】は　1月　とても　さむいです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q22.png",
          "options": [
            {
              "text": "凍京|||凍京"
            },
            {
              "text": "京東|||京東"
            },
            {
              "text": "東京|||東京"
            },
            {
              "text": "東涼|||東涼"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>とうきょう (Tokyo) is written 東京. 凍京 uses the wrong first kanji (凍 &quot;frozen&quot; instead of 東 &quot;east&quot;), 京東 reverses the kanji order, and 東涼 uses the wrong second kanji.</p></div><div class=\"ml-vi\"><p>とうきょう (Tokyo) viết là 東京. 凍京 dùng sai chữ đầu (凍 &quot;đông lạnh&quot; thay vì 東 &quot;đông/phía đông&quot;), 京東 đảo ngược thứ tự chữ Hán, còn 東涼 dùng sai chữ thứ hai.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it read? Choose the correct answer.<br/>コンビニの【後ろ】に　ごうえんが　あります。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng<br/>コンビニの【後ろ】に　ごうえんが　あります。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q23.png",
          "options": [
            {
              "text": "うしろ|||うしろ"
            },
            {
              "text": "あとろ|||あとろ"
            },
            {
              "text": "まえろ|||まえろ"
            },
            {
              "text": "ごろ|||ごろ"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>後ろ (&quot;behind&quot;) is read うしろ. The other three are not valid readings of this kanji in this context.</p></div><div class=\"ml-vi\"><p>後ろ (phía sau) đọc là うしろ. Ba lựa chọn còn lại không phải cách đọc hợp lệ của chữ Hán này trong ngữ cảnh.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the corresponding Vietnamese meaning of the following word:<br/>&quot;じんじゃ&quot;</p></div><div class=\"ml-vi\"><p>Chọn nghĩa tiếng Việt tương ứng của từ sau:<br/>&quot;じんじゃ&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q24.png",
          "options": [
            {
              "text": "Tòa nhà|||Tòa nhà"
            },
            {
              "text": "Nhà thờ|||Nhà thờ"
            },
            {
              "text": "Lâu đài|||Lâu đài"
            },
            {
              "text": "Đền thờ|||Đền thờ"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>じんじゃ (神社) means &quot;Shinto shrine&quot; — Đền thờ. Tòa nhà = building, Nhà thờ = church (きょうかい), Lâu đài = castle (おしろ).</p></div><div class=\"ml-vi\"><p>じんじゃ (神社) nghĩa là &quot;đền thờ Thần đạo&quot;. Tòa nhà là building, Nhà thờ là きょうかい, Lâu đài là おしろ.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>A：きのう、なにを　しましたか。<br/>B：ともだちの　いえへ　行きました。＿＿＿＿＿＿＿＿、ゲームを　しました。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：きのう、なにを　しましたか。<br/>B：ともだちの　いえへ　行きました。＿＿＿＿＿＿＿＿、ゲームを　しました。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q25.png",
          "options": [
            {
              "text": "すみません|||すみません"
            },
            {
              "text": "またこんど|||またこんど"
            },
            {
              "text": "いまから|||いまから"
            },
            {
              "text": "それから|||それから"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>それから (&quot;after that/then&quot;) correctly links two sequential past events: &quot;went to a friend&#39;s house. After that, played games.&quot; すみません = sorry/excuse me, またこんど = some other time, いまから = from now — none fit linking two past actions.</p></div><div class=\"ml-vi\"><p>それから (sau đó) nối hai sự kiện quá khứ theo trình tự: &quot;đi đến nhà bạn. Sau đó, chơi game.&quot; すみません = xin lỗi, またこんど = lần sau, いまから = từ bây giờ — đều không phù hợp để nối hai hành động đã xảy ra.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>A：なにを　食べたいですか。<br/>B：なにも（　　　　）。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：なにを　食べたいですか。<br/>B：なにも（　　　　）。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q26.png",
          "options": [
            {
              "text": "食べたいです|||食べたいです"
            },
            {
              "text": "食べます|||食べます"
            },
            {
              "text": "食べたくないです|||食べたくないです"
            },
            {
              "text": "食べません|||食べません"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>なにも (&quot;nothing/not anything&quot;) requires a negative predicate, and since A asked about what B wants to eat (食べたい form), B&#39;s negative reply must match that same 〜たい form: 食べたくないです (&quot;[I] don&#39;t want to eat anything&quot;). 食べません is negative but drops the たい (want to) nuance from the question.</p></div><div class=\"ml-vi\"><p>なにも (không gì cả) cần đi với vị ngữ phủ định, và vì A hỏi bằng thể 食べたい (muốn ăn), câu trả lời phủ định của B phải giữ đúng thể 〜たい đó: 食べたくないです (không muốn ăn gì cả). 食べません là phủ định nhưng mất sắc thái &quot;muốn&quot; (たい) trong câu hỏi.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>A：Bさんの　まちは　しずかですか。<br/>B：いいえ、＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：Bさんの　まちは　しずかですか。<br/>B：いいえ、＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q27.png",
          "options": [
            {
              "text": "しずかです|||しずかです"
            },
            {
              "text": "しずかじゃありません|||しずかじゃありません"
            },
            {
              "text": "しずかでした|||しずかでした"
            },
            {
              "text": "しずかくない|||しずかくない"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>いいえ (&quot;no&quot;) requires a negative present-tense answer. しずか is a na-adjective, whose negative present polite form is しずかじゃありません (&quot;is not quiet&quot;). しずかくない wrongly applies i-adjective negative conjugation (くない) to a na-adjective.</p></div><div class=\"ml-vi\"><p>いいえ (không) cần câu trả lời phủ định thì hiện tại. しずか là tính từ đuôi -na, thể phủ định hiện tại lịch sự là しずかじゃありません (không yên tĩnh). しずかくない chia sai theo tính từ đuôi -i (くない) cho một tính từ đuôi -na.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>＿＿＿＿＿＿＿は　とても　にぎやかです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>＿＿＿＿＿＿＿は　とても　にぎやかです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q28.png",
          "options": [
            {
              "text": "きのう|||きのう"
            },
            {
              "text": "かわ|||かわ"
            },
            {
              "text": "パーティー|||パーティー"
            },
            {
              "text": "おしろ|||おしろ"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>パーティー (&quot;party&quot;) is naturally described as にぎやか (&quot;lively/bustling&quot;). きのう = yesterday (a time, not a place/event that can be &quot;lively&quot;), かわ = river, おしろ = castle — quieter, less fitting subjects for &quot;very lively&quot;.</p></div><div class=\"ml-vi\"><p>パーティー (bữa tiệc) tự nhiên được miêu tả là にぎやか (nhộn nhịp/náo nhiệt). きのう = hôm qua (thời gian, không phải nơi/sự kiện &quot;náo nhiệt&quot;), かわ = dòng sông, おしろ = lâu đài — ít phù hợp hơn với &quot;rất náo nhiệt&quot;.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>わたしは　日本料理（りょうり）（　　）すきです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>わたしは　日本料理（りょうり）（　　）すきです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q29.png",
          "options": [
            {
              "text": "を|||を"
            },
            {
              "text": "が|||が"
            },
            {
              "text": "は|||は"
            },
            {
              "text": "に|||に"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>すき (&quot;to like&quot;, a na-adjective) marks the liked object with が: 〜が すきです. This is a fixed pattern; を is not used here.</p></div><div class=\"ml-vi\"><p>すき (thích, tính từ đuôi -na) đánh dấu đối tượng được thích bằng が: 〜が すきです. Đây là mẫu câu cố định; không dùng を ở đây.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>日本語（　　）わかりません。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>日本語（　　）わかりません。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q30.png",
          "options": [
            {
              "text": "が|||が"
            },
            {
              "text": "を|||を"
            },
            {
              "text": "で|||で"
            },
            {
              "text": "へ|||へ"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>わかる (&quot;to understand&quot;) marks the object of understanding with が, not を: 日本語がわかりません (&quot;I don&#39;t understand Japanese&quot;). This is a fixed grammar pattern (わかる is intransitive-like and pairs with が).</p></div><div class=\"ml-vi\"><p>わかる (hiểu) đánh dấu đối tượng được hiểu bằng が, không phải を: 日本語がわかりません (không hiểu tiếng Nhật). Đây là mẫu ngữ pháp cố định (わかる đi với が).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>このけいたいでんわは　とても（　　）です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>このけいたいでんわは　とても（　　）です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q31.png",
          "options": [
            {
              "text": "ひま|||ひま"
            },
            {
              "text": "げんき|||げんき"
            },
            {
              "text": "たかい|||たかい"
            },
            {
              "text": "にぎやか|||にぎやか"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>A mobile phone (けいたいでんわ) is naturally described with たかい (&quot;expensive/high [price]&quot;). ひま = free time, げんき = healthy/energetic, にぎやか = lively — none describe a phone.</p></div><div class=\"ml-vi\"><p>Điện thoại di động (けいたいでんわ) tự nhiên được miêu tả bằng たかい (đắt/giá cao). ひま = rảnh rỗi, げんき = khỏe mạnh, にぎやか = náo nhiệt — không dùng để tả điện thoại.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The word in brackets [ ] below — how is it written in Kanji? Choose the correct answer.<br/>パースは　オーストラリアの【ひがし】です。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng<br/>パースは　オーストラリアの【ひがし】です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q32.png",
          "options": [
            {
              "text": "理|||理"
            },
            {
              "text": "京|||京"
            },
            {
              "text": "東|||東"
            },
            {
              "text": "野|||野"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>ひがし (&quot;east&quot;) is written 東. 理 (&quot;reason/logic&quot;), 京 (&quot;capital&quot;), and 野 (&quot;field/plain&quot;) are unrelated kanji.</p></div><div class=\"ml-vi\"><p>ひがし (đông/phía đông) viết là 東. 理 (lý/lẽ), 京 (kinh đô), và 野 (đồng/cánh đồng) là các chữ Hán không liên quan.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the corresponding Vietnamese meaning of the following word:<br/>&quot;おしろ&quot;</p></div><div class=\"ml-vi\"><p>Chọn nghĩa tiếng Việt tương ứng của từ sau:<br/>&quot;おしろ&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q33.png",
          "options": [
            {
              "text": "Dòng sông|||Dòng sông"
            },
            {
              "text": "Tòa nhà|||Tòa nhà"
            },
            {
              "text": "Lâu đài|||Lâu đài"
            },
            {
              "text": "Ngôi chùa|||Ngôi chùa"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>おしろ (お城) means &quot;castle&quot; — Lâu đài. Dòng sông = river (かわ), Tòa nhà = building, Ngôi chùa = temple (おてら).</p></div><div class=\"ml-vi\"><p>おしろ (お城) nghĩa là &quot;lâu đài&quot;. Dòng sông là かわ, Tòa nhà là building, Ngôi chùa là おてら.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it read? Choose the correct answer.<br/>来年、日本へ【帰ります】。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng<br/>来年、日本へ【帰ります】。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q34.png",
          "options": [
            {
              "text": "かえります|||かえります"
            },
            {
              "text": "おります|||おります"
            },
            {
              "text": "あります|||あります"
            },
            {
              "text": "かぎります|||かぎります"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>帰る (&quot;to return/go home&quot;) → polite form かえります. おります (to be, humble), あります (there is/to have), かぎります (to limit) are unrelated verbs.</p></div><div class=\"ml-vi\"><p>動詞 帰る (trở về) → thể lịch sự かえります. おります (ở, thể khiêm nhường), あります (có/tồn tại), かぎります (giới hạn) là các động từ không liên quan.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>あした、ハノイで　サッカーの＿＿＿＿＿＿＿が　あります。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>あした、ハノイで　サッカーの＿＿＿＿＿＿＿が　あります。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q35.png",
          "options": [
            {
              "text": "しあい|||しあい"
            },
            {
              "text": "まつり|||まつり"
            },
            {
              "text": "ようじ|||ようじ"
            },
            {
              "text": "セール|||セール"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>サッカーの (&quot;of soccer&quot;) most naturally precedes しあい (&quot;match/game&quot;): &quot;there is a soccer match tomorrow in Hanoi&quot;. まつり = festival, ようじ = errand/business, セール = sale — don&#39;t collocate with soccer.</p></div><div class=\"ml-vi\"><p>サッカーの (của bóng đá) tự nhiên đi trước しあい (trận đấu): &quot;ngày mai có trận bóng đá ở Hà Nội&quot;. まつり = lễ hội, ようじ = việc cần làm, セール = giảm giá — không đi kèm với bóng đá.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>A：とうきょうから　アユタヤまで　＿＿＿＿＿＿＿＿＿＿＿ですか。<br/>B：ひこうきで　6時間くらいです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：とうきょうから　アユタヤまで　＿＿＿＿＿＿＿＿＿＿＿ですか。<br/>B：ひこうきで　6時間くらいです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q36.png",
          "options": [
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "どのくらい|||どのくらい"
            },
            {
              "text": "どちら|||どちら"
            },
            {
              "text": "どんな|||どんな"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>B answers with a duration (&quot;about 6 hours by plane&quot;), so A must be asking どのくらい (&quot;about how long&quot;). どこ = where, どちら = which/where (polite), どんな = what kind — none prompt a duration answer.</p></div><div class=\"ml-vi\"><p>B trả lời bằng thời lượng (&quot;khoảng 6 tiếng bằng máy bay&quot;), nên câu hỏi của A phải là どのくらい (khoảng bao lâu). どこ = ở đâu, どちら = cái nào/ở đâu (lịch sự), どんな = loại nào — không dẫn đến câu trả lời về thời lượng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The Kanji in brackets [ ] below — how is it read? Choose the correct answer.<br/>【今年】の　6月、Sa Paへ　行きました。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng<br/>【今年】の　6月、Sa Paへ　行きました。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q37.png",
          "options": [
            {
              "text": "ことし|||ことし"
            },
            {
              "text": "らいねん|||らいねん"
            },
            {
              "text": "らいしゅう|||らいしゅう"
            },
            {
              "text": "きんねん|||きんねん"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>今年 (&quot;this year&quot;) is read ことし. らいねん = next year (来年), らいしゅう = next week (来週), きんねん = recent years (近年) — different words/kanji.</p></div><div class=\"ml-vi\"><p>今年 (năm nay) đọc là ことし. らいねん = năm sau (来年), らいしゅう = tuần sau (来週), きんねん = những năm gần đây (近年) — là các từ/chữ Hán khác.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The word in brackets [ ] below — how is it written in Kanji? Choose the correct answer.<br/>【まいにち】、おんがくを　ききます。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng<br/>【まいにち】、おんがくを　ききます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q38.png",
          "options": [
            {
              "text": "海月|||海月"
            },
            {
              "text": "母月|||母月"
            },
            {
              "text": "海日|||海日"
            },
            {
              "text": "毎日|||毎日"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>まいにち (&quot;every day&quot;) is written 毎日. 海月 (&quot;sea+moon&quot;), 母月 (&quot;mother+month&quot;), and 海日 (&quot;sea+day&quot;) are not valid words for this reading.</p></div><div class=\"ml-vi\"><p>まいにち (mỗi ngày) viết là 毎日. 海月 (&quot;biển+trăng&quot;), 母月 (&quot;mẹ+tháng&quot;), và 海日 (&quot;biển+ngày&quot;) không phải từ hợp lệ cho cách đọc này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>先生（せんせい）の　時計（とけい）は（　　）時計（とけい）ですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>先生（せんせい）の　時計（とけい）は（　　）時計（とけい）ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q39.png",
          "options": [
            {
              "text": "どれ|||どれ"
            },
            {
              "text": "なん|||なん"
            },
            {
              "text": "どの|||どの"
            },
            {
              "text": "どう|||どう"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Since the blank is directly followed by the noun 時計 (&quot;clock&quot;), the adnominal question word どの (&quot;which [noun]&quot;) is needed, not the standalone pronoun どれ (&quot;which one&quot;), which cannot directly modify a following noun. なん = what, どう = how.</p></div><div class=\"ml-vi\"><p>Vì chỗ trống đứng ngay trước danh từ 時計 (đồng hồ), cần từ để hỏi bổ nghĩa danh từ どの (&quot;cái nào&quot; + danh từ), không phải đại từ đứng độc lập どれ (cái nào) vốn không thể bổ nghĩa trực tiếp cho danh từ theo sau. なん = cái gì, どう = như thế nào.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>なつやすみ、日本で　アルバイトを　しますから、＿＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>なつやすみ、日本で　アルバイトを　しますから、＿＿＿＿＿＿＿＿＿＿＿＿＿＿。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q40.png",
          "options": [
            {
              "text": "食べません|||食べません"
            },
            {
              "text": "国（くに）へ　かえりません|||国（くに）へ　かえりません"
            },
            {
              "text": "どこへも　行きませんでした|||どこへも　行きませんでした"
            },
            {
              "text": "こんばん、うちで　べんきょうします|||こんばん、うちで　べんきょうします"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Because I&#39;m working part-time in Japan during summer break, ___&quot; logically continues with 国へかえりません (&quot;I won&#39;t return to my home country&quot;), the direct consequence of staying in Japan to work. Note: this question reuses the same four options as Q11, but here the correct answer is a different option (国へかえりません) because the stem is different.</p></div><div class=\"ml-vi\"><p>&quot;Vì làm thêm ở Nhật vào kỳ nghỉ hè nên ___&quot; tiếp nối hợp lý bằng 国へかえりません (không về nước), hệ quả trực tiếp của việc ở lại Nhật để làm việc. Lưu ý: câu này dùng lại đúng 4 phương án của câu 11, nhưng đáp án đúng ở đây khác (国へかえりません) vì phần đề khác nhau.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>The word in brackets [ ] below — how is it written in Kanji? Choose the correct answer.<br/>【ことし】さくらまつりが　あります。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng<br/>【ことし】さくらまつりが　あります。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q41.png",
          "options": [
            {
              "text": "今年|||今年"
            },
            {
              "text": "来年|||来年"
            },
            {
              "text": "令年|||令年"
            },
            {
              "text": "今缶|||今缶"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>ことし (&quot;this year&quot;) is written 今年. 来年 means &quot;next year&quot; (らいねん, wrong word), 令年 and 今缶 are not valid words.</p></div><div class=\"ml-vi\"><p>ことし (năm nay) viết là 今年. 来年 nghĩa là &quot;năm sau&quot; (らいねん, sai từ), 令年 và 今缶 không phải từ hợp lệ.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer from A, B, C, D to fill in the blank<br/>来月、Da Nang＿＿＿＿＿＿＿＿＿日本の　おまつり＿＿＿＿＿＿＿＿＿あります。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>来月、Da Nang＿＿＿＿＿＿＿＿＿日本の　おまつり＿＿＿＿＿＿＿＿＿あります。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q42.png",
          "options": [
            {
              "text": "に／が|||に／が"
            },
            {
              "text": "に／は|||に／は"
            },
            {
              "text": "で／が|||で／が"
            },
            {
              "text": "で／は|||で／は"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>で marks the location where an event takes place (Da Nangで, &quot;in/at Da Nang&quot;), and が marks the subject of existence with あります (おまつりが あります, &quot;a festival will be held/exist&quot;). に is used for static location of objects/people (いる/ある of fixed things), not for an event&#39;s venue.</p></div><div class=\"ml-vi\"><p>で đánh dấu địa điểm diễn ra sự kiện (Da Nangで, &quot;tại Đà Nẵng&quot;), còn が đánh dấu chủ thể tồn tại đi với あります (おまつりが あります, &quot;sẽ có lễ hội&quot;). に dùng cho vị trí tĩnh của vật/người (いる/ある của vật cố định), không dùng cho địa điểm tổ chức sự kiện.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2326,
          "prompt": "<div class=\"ml-en\"><p>Choose the word that is a different type from the following words:<br/>① おもしろい<br/>② むずかしい<br/>③ いそがしい<br/>④ きらい</p></div><div class=\"ml-vi\"><p>Hãy chọn từ khác loại trong các từ sau:<br/>① おもしろい<br/>② むずかしい<br/>③ いそがしい<br/>④ きらい</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD123/D46/q43.png",
          "options": [
            {
              "text": "おもしろい|||おもしろい"
            },
            {
              "text": "むずかしい|||むずかしい"
            },
            {
              "text": "いそがしい|||いそがしい"
            },
            {
              "text": "きらい|||きらい"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>おもしろい, むずかしい, and いそがしい are all i-adjectives (end in い, conjugate with くない/かった). きらい is a na-adjective (its negative is きらいじゃない, not きらくない), so it is the odd one out, shown as option D.</p></div><div class=\"ml-vi\"><p>おもしろい, むずかしい, và いそがしい đều là tính từ đuôi -i (kết thúc bằng い, chia theo くない/かった). きらい là tính từ đuôi -na (thể phủ định là きらいじゃない, không phải きらくない), nên là từ khác loại, tương ứng phương án D.</p></div>"
        }
      ]
    }
  ]
};
