// AUTO-GENERATED by scripts/build-fe-exam.mjs from bank-JPD113-D35.jsonl — re-run the builder, do not hand-edit.
export default {
  "course": {
    "courseCode": "JPD113"
  },
  "exams": [
    {
      "kind": "FE",
      "code": "D35",
      "title": "Đề 35 — Final Exam (FA2023-4-R-FE)|||Đề 35 — Thi cuối kỳ (FA2023-4-R-FE)",
      "description": "Real JPD113 FE paper (FA2023-4-R-FE), 30 questions on hiragana/katakana readings, kanji, particles, and basic grammar.|||Đề FE thật môn JPD113 (FA2023-4-R-FE), 30 câu về cách đọc kana, Hán tự, trợ từ và ngữ pháp cơ bản.",
      "durationMinutes": 45,
      "totalPoints": 10,
      "passMark": 4,
      "source": "REAL",
      "shuffleQuestions": false,
      "shuffleOptions": false,
      "instructions": "<div class=\"ml-en\"><p>This is a real FPTU <b>Final Exam</b> paper for <b>Japanese (basic vocabulary, kanji, particles, grammar)</b>. Every question is <b>multiple choice</b> and auto-graded.</p><ul><li>Some questions say \"choose TWO\" — they are only correct when both right answers are selected.</li><li>Read code, tables and diagrams carefully; several questions turn on a subtle detail.</li><li>The original scanned question is available under <b>\"Show original image\"</b> on each question.</li></ul><p>You can flag a question and come back. The timer auto-submits at the end. After you submit, every question shows a bilingual explanation.</p></div><div class=\"ml-vi\"><p>Đây là đề <b>thi cuối kỳ (Final Exam)</b> thật của FPTU môn <b>Japanese (basic vocabulary, kanji, particles, grammar)</b>. Mọi câu đều là <b>trắc nghiệm</b>, chấm tự động.</p><ul><li>Một số câu ghi \"chọn HAI\" — chỉ đúng khi chọn đủ cả hai đáp án đúng.</li><li>Đọc kỹ code, bảng và sơ đồ; nhiều câu ăn thua ở một chi tiết nhỏ.</li><li>Ảnh đề gốc đã quét nằm ở nút <b>\"Xem ảnh đề gốc\"</b> trên mỗi câu.</li></ul><p>Bạn có thể đánh dấu câu để quay lại sau. Hết giờ hệ thống tự nộp. Nộp xong, mỗi câu đều có lời giải song ngữ.</p></div>",
      "isPublished": true,
      "questions": [
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the underlined word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>きょうは【ここのか】ですか。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>きょうは【ここのか】ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q1.png",
          "options": [
            {
              "text": "八日|||八日"
            },
            {
              "text": "九日|||九日"
            },
            {
              "text": "七日|||七日"
            },
            {
              "text": "六日|||六日"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>ここのか (kokonoka) means &quot;the 9th day&quot; and is written 九日. Source UI showed A, B, C all pre-checked simultaneously despite &quot;Choose 1 answer&quot; — clearly a broken/artifact key, not a real answer; derived independently as B (九日).</p></div><div class=\"ml-vi\"><p>ここのか nghĩa là &quot;ngày mùng 9&quot;, viết là 九日. Giao diện nguồn tô chọn đồng thời cả A, B, C dù đề ghi &quot;Choose 1 answer&quot; — rõ ràng là lỗi hiển thị, không phải đáp án thật; tự suy luận độc lập ra đáp án B (九日).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: はじめまして。ワンです。<br/>B: (__________) よろしく おねがいします。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：はじめまして。ワンです。<br/>B：(__________）よろしく　おねがいします。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q2.png",
          "options": [
            {
              "text": "すみません|||すみません"
            },
            {
              "text": "あのう|||あのう"
            },
            {
              "text": "はじめまて|||はじめまて"
            },
            {
              "text": "こちらこそ|||こちらこそ"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>After A greets with はじめまして, B replies こちらこそ (&quot;likewise / the pleasure is mine&quot;) before asking for continued good relations. Option C はじめまて is a misspelling of はじめまして (missing ん) and is a distractor, not the answer.</p></div><div class=\"ml-vi\"><p>Sau khi A chào bằng はじめまして, B đáp lại こちらこそ (&quot;tôi mới là người...&quot;/&quot;cũng rất vui được gặp&quot;) trước khi xin được giúp đỡ. Đáp án C はじめまて là lỗi chính tả của はじめまして (thiếu chữ ん), là phương án gây nhiễu chứ không phải đáp án đúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>How is the Kanji in brackets [ ] read? Choose the correct answer among A, B, C, D<br/>ミンさんは 日本語【学校】の 先生です。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D<br/>ミンさんは 日本語【学校】の 先生です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q3.png",
          "options": [
            {
              "text": "かっこう|||かっこう"
            },
            {
              "text": "かくこう|||かくこう"
            },
            {
              "text": "がくこう|||がくこう"
            },
            {
              "text": "がっこう|||がっこう"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>学校 (school) is read がっこう — voiced が and small っ (sokuon). Answer D.</p></div><div class=\"ml-vi\"><p>学校 (trường học) đọc là がっこう — が có dấu và có促音 (っ). Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank;<br/>A: はじめまして、パクです。よろしくおねがいします。<br/>B: ナタポンです。( ) よろしくおねがいします。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống;<br/>A：はじめまして、パクです。よろしくおねがいします。<br/>B：ナタポンです。（　　）よろしくおねがいします。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q4.png",
          "options": [
            {
              "text": "そうですか|||そうですか"
            },
            {
              "text": "こちらこそ|||こちらこそ"
            },
            {
              "text": "どういたしまして|||どういたしまして"
            },
            {
              "text": "ありがとう|||ありがとう"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>B introduces herself after A&#39;s greeting, then responds with こちらこそ (&quot;likewise&quot;) before repeating よろしくおねがいします. Answer B.</p></div><div class=\"ml-vi\"><p>B tự giới thiệu sau lời chào của A rồi đáp こちらこそ (&quot;tôi cũng vậy/rất vui được gặp&quot;) trước khi nhắc lại よろしくおねがいします. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C to fill in the blank<br/>これは （＿＿＿＿＿）ごです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C đáp án thích hợp để điền vào chỗ trống<br/>これは （＿＿＿＿＿）ごです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q5.png",
          "options": [
            {
              "text": "ドイツ|||ドイツ"
            },
            {
              "text": "オーストラリア|||オーストラリア"
            },
            {
              "text": "アメリカ|||アメリカ"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Blank + ご (語) means &quot;the ~ language&quot;. Of the three, only ドイツ (Germany) has a real corresponding language name ドイツ語 (German); オーストラリア and アメリカ are not language names. Answer A.</p></div><div class=\"ml-vi\"><p>Chỗ trống + ご (語) nghĩa là &quot;tiếng ~&quot;. Trong ba lựa chọn, chỉ có ドイツ (Đức) tạo thành tên ngôn ngữ có thật là ドイツ語 (tiếng Đức); オーストラリア và アメリカ không phải là tên ngôn ngữ. Đáp án A.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Based on the given suggested words, choose the sentence with complete meaning among options A, B, C, D below:<br/>これ／です／タイ／りょうり</p></div><div class=\"ml-vi\"><p>Dựa vào các từ gợi ý cho sẵn hãy chọn câu có ý nghĩa hoàn chỉnh trong các phương án A,B,C,D dưới đây:<br/>これ／です／タイ／りょうり</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q6.png",
          "options": [
            {
              "text": "これ りょうりは タイです。|||これ りょうりは タイです。"
            },
            {
              "text": "これは タイの りょうりです。|||これは タイの りょうりです。"
            },
            {
              "text": "りょうりは タイこれです。|||りょうりは タイこれです。"
            },
            {
              "text": "タイは これ りょうりです。|||タイは これ りょうりです。"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;This is Thai food&quot; = これは タイの りょうりです。(This-topic / Thailand&#39;s / food-is). Answer B; the others are grammatically broken word orders.</p></div><div class=\"ml-vi\"><p>&quot;Đây là món ăn Thái&quot; = これは タイの りょうりです。(Đây-chủ đề / của Thái / là món ăn). Đáp án B; các phương án còn lại sai trật tự ngữ pháp.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank: お誕生日(たんじょうび)は （　　）ですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống: お誕生日(たんじょうび)は （　　）ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q7.png",
          "options": [
            {
              "text": "なん|||なん"
            },
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "いつ|||いつ"
            },
            {
              "text": "どちら|||どちら"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;When is your birthday?&quot; uses いつ (&quot;when&quot;). Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Sinh nhật của bạn là khi nào?&quot; dùng いつ (&quot;khi nào&quot;). Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank;<br/>A「日曜日 こうえんで バーベキューを します。」<br/>B「（　　）。」</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống;<br/>A「日曜日　こうえんで　バーベキューを　します。」<br/>B「（　　）。」</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q8.png",
          "options": [
            {
              "text": "いいですね|||いいですね"
            },
            {
              "text": "ありがとうございます|||ありがとうございます"
            },
            {
              "text": "じゃ|||じゃ"
            },
            {
              "text": "おねがいします|||おねがいします"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>A proposes a Sunday BBQ in the park; the natural response is いいですね (&quot;Sounds good!&quot;). Answer A.</p></div><div class=\"ml-vi\"><p>A đề nghị tổ chức BBQ ở công viên vào Chủ nhật; phản hồi tự nhiên là いいですね (&quot;Nghe hay đấy!&quot;). Đáp án A.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: エスカレーターは どこです。<br/>B: （　　）です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：エスカレーターは　どこです。<br/>B：（　　）です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q9.png",
          "options": [
            {
              "text": "これ|||これ"
            },
            {
              "text": "あちら|||あちら"
            },
            {
              "text": "みっか|||みっか"
            },
            {
              "text": "あれ|||あれ"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Asking どこ (&quot;where&quot;) about a fixed location is naturally answered with a polite direction word: あちら (&quot;over there&quot;). Answer B; みっか (&quot;3rd day&quot;) is an unrelated distractor.</p></div><div class=\"ml-vi\"><p>Hỏi どこ (&quot;ở đâu&quot;) về vị trí cố định thì tự nhiên trả lời bằng từ chỉ hướng lịch sự: あちら (&quot;phía đằng kia&quot;). Đáp án B; みっか (&quot;ngày mùng 3&quot;) là phương án gây nhiễu không liên quan.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>日曜日、（　　）も いきません。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>日曜日、（　　）も　いきません。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q10.png",
          "options": [
            {
              "text": "だれ|||だれ"
            },
            {
              "text": "なに|||なに"
            },
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "いつ|||いつ"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>どこも + negative verb = &quot;(don&#39;t go) anywhere&quot;. Answer C どこ (どこも いきません = &quot;I&#39;m not going anywhere&quot;).</p></div><div class=\"ml-vi\"><p>どこも + động từ phủ định = &quot;không đi đâu cả&quot;. Đáp án C どこ (どこも いきません = &quot;tôi không đi đâu cả&quot;).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Find the corresponding Vietnamese meaning for the following word:<br/>&quot;でんししじしょ&quot;</p></div><div class=\"ml-vi\"><p>Hãy tìm nghĩa tiếng Việt tương ứng cho từ sau:<br/>&quot;でんししじしょ&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q11.png",
          "options": [
            {
              "text": "Kim từ điển|||Kim từ điển"
            },
            {
              "text": "Điện thoại di động|||Điện thoại di động"
            },
            {
              "text": "Máy tính cá nhân|||Máy tính cá nhân"
            },
            {
              "text": "Quán giải khát|||Quán giải khát"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>The intended word is 電子辞書 (でんしじしょ, &quot;electronic dictionary&quot;), commonly called &quot;kim từ điển&quot; in Vietnamese. The source image shows an extra し (でんししじしょ), likely a source typo; transcribed verbatim as shown. Answer A.</p></div><div class=\"ml-vi\"><p>Từ gốc dự định là 電子辞書 (でんしじしょ, &quot;từ điển điện tử&quot;), tiếng Việt thường gọi là &quot;kim từ điển&quot;. Ảnh nguồn có thêm một chữ し (でんししじしょ), khả năng là lỗi đánh máy của nguồn; chép nguyên văn như hiển thị. Đáp án A.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>やまださんは（　　）で とけいを かいます。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>やまださんは（　　）で　とけいを　かいます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q12.png",
          "options": [
            {
              "text": "たいいくかん|||たいいくかん"
            },
            {
              "text": "びょういん|||びょういん"
            },
            {
              "text": "スーパー|||スーパー"
            },
            {
              "text": "ゆうびんきょく|||ゆうびんきょく"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Of the four places (gymnasium, hospital, supermarket, post office), スーパー (supermarket) is the only plausible place to buy a watch (とけい). Answer C.</p></div><div class=\"ml-vi\"><p>Trong bốn địa điểm (nhà thi đấu, bệnh viện, siêu thị, bưu điện), スーパー (siêu thị) là nơi hợp lý nhất để mua đồng hồ (とけい). Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>これは【ほん】ですか。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>これは【ほん】ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q13.png",
          "options": [
            {
              "text": "木|||木"
            },
            {
              "text": "本|||本"
            },
            {
              "text": "体|||体"
            },
            {
              "text": "休|||休"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>ほん (&quot;book&quot;) is written 本. Answer B.</p></div><div class=\"ml-vi\"><p>ほん (&quot;sách&quot;) viết là 本. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>私は 土曜日、どこも（　　）。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>私は　土曜日、どこも（　　）。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q14.png",
          "options": [
            {
              "text": "いきます|||いきます"
            },
            {
              "text": "いきません|||いきません"
            },
            {
              "text": "します|||します"
            },
            {
              "text": "しません|||しません"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>どこも pairs with a negative form of &quot;go&quot; to mean &quot;(don&#39;t) go anywhere&quot;: どこも いきません. Answer B.</p></div><div class=\"ml-vi\"><p>どこも đi cùng dạng phủ định của &quot;đi&quot; nghĩa là &quot;không đi đâu cả&quot;: どこも いきません. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>月曜日（　　）金曜日（　　）はたらきます。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>月曜日（　　）金曜日（　　）はたらきます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q15.png",
          "options": [
            {
              "text": "から/に|||から/に"
            },
            {
              "text": "まで/から|||まで/から"
            },
            {
              "text": "から/まで|||から/まで"
            },
            {
              "text": "に/まで|||に/まで"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;I work from Monday to Friday&quot; = 月曜日からから　金曜日まで. Correct particle pair: から／まで. Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Tôi làm việc từ thứ Hai đến thứ Sáu&quot; = 月曜日から　金曜日まで. Cặp trợ từ đúng: から／まで. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the odd one out (different category) among the following words:<br/>①はなや<br/>②とんかつ<br/>③きっさてん<br/>④ほんや</p></div><div class=\"ml-vi\"><p>Hãy chọn từ khác loại trong các từ sau:<br/>①はなや<br/>②とんかつ<br/>③きっさてん<br/>④ほんや</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q16.png",
          "options": [
            {
              "text": "はなや|||はなや"
            },
            {
              "text": "とんかつ|||とんかつ"
            },
            {
              "text": "きっさてん|||きっさてん"
            },
            {
              "text": "ほんや|||ほんや"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>はなや (flower shop), きっさてん (coffee shop), and ほんや (bookstore) are all shops/places; とんかつ (pork cutlet) is a food item, not a place. Answer B.</p></div><div class=\"ml-vi\"><p>はなや (tiệm hoa), きっさてん (quán cà phê), ほんや (tiệm sách) đều là cửa hàng/địa điểm; とんかつ (thịt heo chiên xù) là món ăn, không phải địa điểm. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A「（　　）。おなまえは？」<br/>B「あ、サントスです。」</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A「（　　）。おなまえは？」<br/>B「あ、サントスです。」</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q17.png",
          "options": [
            {
              "text": "そうですか|||そうですか"
            },
            {
              "text": "こちらこそ|||こちらこそ"
            },
            {
              "text": "はじめまして|||はじめまして"
            },
            {
              "text": "あのう、すみません|||あのう、すみません"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>A opens with the introduction greeting はじめまして before asking the other&#39;s name. Answer C.</p></div><div class=\"ml-vi\"><p>A mở đầu bằng lời chào làm quen はじめまして trước khi hỏi tên đối phương. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>これは えいご（　　）なんですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>これは　えいご（　　）なんですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q18.png",
          "options": [
            {
              "text": "に|||に"
            },
            {
              "text": "まで|||まで"
            },
            {
              "text": "で|||で"
            },
            {
              "text": "は|||は"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;What is this called IN English?&quot; uses で (means/language marker): えいごで なんですか。Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Cái này gọi là gì BẰNG tiếng Anh?&quot; dùng で (trợ từ chỉ phương tiện/ngôn ngữ): えいごで なんですか。Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: 「Trứng」は 日本語で 何ですか。<br/>B: （　　）です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：「Trứng」は　日本語で　何ですか。<br/>B：（　　）です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q19.png",
          "options": [
            {
              "text": "とりにく|||とりにく"
            },
            {
              "text": "たまご|||たまご"
            },
            {
              "text": "ぎゅうにく|||ぎゅうにく"
            },
            {
              "text": "たばこ|||たばこ"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Trứng&quot; (Vietnamese for &quot;egg&quot;) in Japanese is たまご. Answer B.</p></div><div class=\"ml-vi\"><p>&quot;Trứng&quot; trong tiếng Nhật là たまご. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank;<br/>A: ひるやすみは いつですか。<br/>B: （　　）です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống;<br/>A：ひるやすみは　いつですか。<br/>B：（　　）です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q20.png",
          "options": [
            {
              "text": "日曜日と土曜日|||日曜日と土曜日"
            },
            {
              "text": "12時から1時まで|||12時から1時まで"
            },
            {
              "text": "ついたち|||ついたち"
            },
            {
              "text": "しがつ|||しがつ"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;When is lunch break?&quot; is answered with a time range: 12時から1時まで (&quot;from 12 to 1 o&#39;clock&quot;). Answer B.</p></div><div class=\"ml-vi\"><p>&quot;Giờ nghỉ trưa là khi nào?&quot; được trả lời bằng khoảng thời gian: 12時から1時まで (&quot;từ 12 giờ đến 1 giờ&quot;). Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: ハンバーグ（＿＿＿＿）みっつ（＿＿＿＿）ください。<br/>てんいん：はい。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：ハンバーグ（＿＿＿＿）みっつ（＿＿＿＿）ください。<br/>てんいん：はい。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q21.png",
          "options": [
            {
              "text": "を／を|||を／を"
            },
            {
              "text": "を／X|||を／X"
            },
            {
              "text": "を／は|||を／は"
            },
            {
              "text": "は／を|||は／を"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Please give me three hamburgers&quot; = ハンバーグを みっつ ください — object marker を on the noun, and no particle after the counter みっつ. Answer B (を／X).</p></div><div class=\"ml-vi\"><p>&quot;Cho tôi ba phần hamburger&quot; = ハンバーグを　みっつ　ください — trợ từ を đánh dấu tân ngữ, và không có trợ từ sau từ đếm みっつ. Đáp án B (を／X).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank for the following sentence;<br/>えいがを（　　）。</p></div><div class=\"ml-vi\"><p>Chọn đáp án thích hợp trong A, B, C, D để điền vào ngoặc cho câu sau;<br/>えいがを（　　）。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q22.png",
          "options": [
            {
              "text": "みます|||みます"
            },
            {
              "text": "かいます|||かいます"
            },
            {
              "text": "ねます|||ねます"
            },
            {
              "text": "のみます|||のみます"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>映画を見ます (&quot;watch a movie&quot;) is the correct verb collocation with えいがを. Answer A みます.</p></div><div class=\"ml-vi\"><p>映画を見ます (&quot;xem phim&quot;) là cách kết hợp động từ đúng với えいがを. Đáp án A みます.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank;<br/>としょかん（　　）いきます。としょかん（　　）日本語を べんきょうします。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống;<br/>としょかん（　　）いきます。としょかん（　　）日本語を　べんきょうします。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q23.png",
          "options": [
            {
              "text": "へ／で|||へ／で"
            },
            {
              "text": "で／へ|||で／へ"
            },
            {
              "text": "を／へ|||を／へ"
            },
            {
              "text": "へ／を|||へ／を"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Go TO the library. AT the library, study Japanese.&quot; へ marks direction (go to), で marks the place an action happens (study at). Answer A へ／で.</p></div><div class=\"ml-vi\"><p>&quot;Đi ĐẾN thư viện. Ở thư viện, học tiếng Nhật.&quot; へ chỉ hướng (đi đến), で chỉ nơi diễn ra hành động (học ở). Đáp án A へ／で.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>私（　　）名前(なまえ)は やまぐちです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>私（　　）名前(なまえ)は　やまぐちです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q24.png",
          "options": [
            {
              "text": "は|||は"
            },
            {
              "text": "も|||も"
            },
            {
              "text": "で|||で"
            },
            {
              "text": "の|||の"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;My name is Yamaguchi&quot; = 私の名前は やまぐちです — possessive の links 私 (I) to 名前 (name). The source UI had C (で) pre-checked, which is grammatically wrong (で cannot connect a pronoun to a possessed noun here); correct answer is D の.</p></div><div class=\"ml-vi\"><p>&quot;Tên tôi là Yamaguchi&quot; = 私の名前は　やまぐちです — trợ từ sở hữu の nối 私 (tôi) với 名前 (tên). Giao diện nguồn tô sẵn đáp án C (で), điều này sai ngữ pháp (で không thể nối đại từ với danh từ sở hữu ở đây); đáp án đúng là D の.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>アリさんは【なんさい】ですか。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>アリさんは【なんさい】ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q25.png",
          "options": [
            {
              "text": "何才|||何才"
            },
            {
              "text": "何ナ|||何ナ"
            },
            {
              "text": "可才|||可才"
            },
            {
              "text": "可ナ|||可ナ"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>なんさい (&quot;how old&quot;) is written 何才. The source UI had D (可ナ, meaningless) pre-checked — clearly wrong; correct answer is A 何才.</p></div><div class=\"ml-vi\"><p>なんさい (&quot;bao nhiêu tuổi&quot;) viết là 何才. Giao diện nguồn tô sẵn đáp án D (可ナ, vô nghĩa) — rõ ràng sai; đáp án đúng là A 何才.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank: A: これは（　　）の ペンですか。<br/>B: せんせいのです。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống: A：これは（　　）の　ペンですか。<br/>B：せんせいのです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q26.png",
          "options": [
            {
              "text": "どちら|||どちら"
            },
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "なに|||なに"
            },
            {
              "text": "だれ|||だれ"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Whose pen is this?&quot; asks about ownership, so だれ (&quot;who&quot;) is used: だれの ペン. Answer D.</p></div><div class=\"ml-vi\"><p>&quot;Đây là bút của ai?&quot; hỏi về chủ sở hữu, nên dùng だれ (&quot;ai&quot;): だれの　ペン. Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>私は まいばん、10時に しんぶんを（　　）。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>私は　まいばん、10時に　しんぶんを（　　）。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q27.png",
          "options": [
            {
              "text": "かいます|||かいます"
            },
            {
              "text": "のみます|||のみます"
            },
            {
              "text": "ねます|||ねます"
            },
            {
              "text": "よみます|||よみます"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>しんぶんを読みます (&quot;read the newspaper&quot;) is the correct collocation. Answer D よみます.</p></div><div class=\"ml-vi\"><p>しんぶんを読みます (&quot;đọc báo&quot;) là cách kết hợp đúng. Đáp án D よみます.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>How is the Kanji in brackets [ ] read? Choose the correct answer among A, B, C, D<br/>まいにち、3【時間】 べんきょうします。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D<br/>まいにち、3【時間】　べんきょうします。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q28.png",
          "options": [
            {
              "text": "しかん|||しかん"
            },
            {
              "text": "じっかん|||じっかん"
            },
            {
              "text": "しがん|||しがん"
            },
            {
              "text": "じかん|||じかん"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>時間 (&quot;hour(s)/time&quot;) is read じかん. Answer D.</p></div><div class=\"ml-vi\"><p>時間 (&quot;giờ/thời gian&quot;) đọc là じかん. Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>ミラーさんは 学生です。やまださん（　　）学生です。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>ミラーさんは　学生です。やまださん（　　）学生です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q29.png",
          "options": [
            {
              "text": "と|||と"
            },
            {
              "text": "で|||で"
            },
            {
              "text": "や|||や"
            },
            {
              "text": "も|||も"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Miller is a student. Yamada is also a student.&quot; uses も (&quot;also&quot;). Answer D.</p></div><div class=\"ml-vi\"><p>&quot;Miller là sinh viên. Yamada cũng là sinh viên.&quot; dùng も (&quot;cũng&quot;). Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>田中さんは【八才】です。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>田中さんは【八才】です。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q30.png",
          "options": [
            {
              "text": "はちさい|||はちさい"
            },
            {
              "text": "はちざい|||はちざい"
            },
            {
              "text": "はっさい|||はっさい"
            },
            {
              "text": "はっざい|||はっざい"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>八才 (&quot;8 years old&quot;) is read はっさい (with sokuon っ and unvoiced さ). The source UI had D (はっざい, wrongly voiced ざ) pre-checked; correct answer is C はっさい.</p></div><div class=\"ml-vi\"><p>八才 (&quot;8 tuổi&quot;) đọc là はっさい (có促音 っ và さ không đọc đục). Giao diện nguồn tô sẵn đáp án D (はっざい, sai vì đọc đục thành ざ); đáp án đúng là C はっさい.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: あさ なにを たべますか。<br/>B: （　　）たべません。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：あさ　なにを　たべますか。<br/>B：（　　）たべません。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q31.png",
          "options": [
            {
              "text": "なにを|||なにを"
            },
            {
              "text": "なに|||なに"
            },
            {
              "text": "なにも|||なにも"
            },
            {
              "text": "なんも|||なんも"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;I don&#39;t eat anything in the morning&quot; uses なにも + negative verb: なにも たべません。Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Tôi không ăn gì vào buổi sáng&quot; dùng なにも + động từ phủ định: なにも　たべません。Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank;<br/>（　　）に かいしゃへ いきますか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống;<br/>（　　）に　かいしゃへ　いきますか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q32.png",
          "options": [
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "なんじ|||なんじ"
            },
            {
              "text": "いつ|||いつ"
            },
            {
              "text": "だれ|||だれ"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The blank is followed by に (time marker), asking &quot;at what time do you go to the company?&quot; → なんじ (&quot;what time&quot;). Answer B.</p></div><div class=\"ml-vi\"><p>Chỗ trống theo sau bởi に (trợ từ thời gian), hỏi &quot;mấy giờ thì đi đến công ty?&quot; → なんじ (&quot;mấy giờ&quot;). Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>How is the Kanji in brackets [ ] read? Choose the correct answer among A, B, C, D<br/>きょうは 【何日】ですか。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D<br/>きょうは　【何日】ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q33.png",
          "options": [
            {
              "text": "なんひ|||なんひ"
            },
            {
              "text": "なにひ|||なにひ"
            },
            {
              "text": "なんにち|||なんにち"
            },
            {
              "text": "なににち|||なににち"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>何日 (&quot;what day of the month&quot;) is read なんにち. Answer C.</p></div><div class=\"ml-vi\"><p>何日 (&quot;ngày mấy&quot;) đọc là なんにち. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank:<br/>おくには（　　）ですか。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống:<br/>おくには（　　）ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q34.png",
          "options": [
            {
              "text": "どこ|||どこ"
            },
            {
              "text": "なん|||なん"
            },
            {
              "text": "どちら|||どちら"
            },
            {
              "text": "だれ|||だれ"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Where is your country (of origin)?&quot; — polite question form uses どちら (polite &quot;where&quot;). Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Quý quốc của bạn là ở đâu?&quot; — dạng hỏi lịch sự dùng どちら (&quot;ở đâu&quot; thể lịch sự). Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A「ただいま」<br/>B「（　　）。」</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A「ただいま」<br/>B「（　　）。」</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q35.png",
          "options": [
            {
              "text": "いってきます|||いってきます"
            },
            {
              "text": "いっていらっしゃい|||いっていらっしゃい"
            },
            {
              "text": "いきます|||いきます"
            },
            {
              "text": "おかえりなさい|||おかえりなさい"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>ただいま (&quot;I&#39;m home&quot;) is answered with おかえりなさい (&quot;Welcome back&quot;). Answer D.</p></div><div class=\"ml-vi\"><p>ただいま (&quot;Tôi về rồi&quot;) được đáp lại bằng おかえりなさい (&quot;Chào mừng về nhà&quot;). Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank for the following sentence:<br/>それは（　　）の ワインです。</p></div><div class=\"ml-vi\"><p>Chọn đáp án thích hợp trong A, B, C, D để điền vào ngoặc cho câu sau:<br/>それは（　　）の　ワインです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q36.png",
          "options": [
            {
              "text": "ライス|||ライス"
            },
            {
              "text": "コーヒー|||コーヒー"
            },
            {
              "text": "フランス|||フランス"
            },
            {
              "text": "レジ|||レジ"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;That is ___&#39;s wine&quot; needs a place name; フランス (France) fits &quot;French wine&quot;, while ライス (rice), コーヒー (coffee), and レジ (cash register) are not places. Answer C.</p></div><div class=\"ml-vi\"><p>&quot;Đó là rượu vang của ___&quot; cần một tên địa danh; フランス (Pháp) phù hợp với &quot;rượu vang Pháp&quot;, còn ライス (cơm), コーヒー (cà phê), レジ (quầy thu ngân) không phải địa danh. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>マリーさんは 【学生】ですか。</p></div><div class=\"ml-vi\"><p>Các chữ Hán trong ngoặc [ ] có cách đọc tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>マリーさんは　【学生】ですか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q37.png",
          "options": [
            {
              "text": "がくせい|||がくせい"
            },
            {
              "text": "かくせい|||かくせい"
            },
            {
              "text": "せんせい|||せんせい"
            },
            {
              "text": "ぜんせい|||ぜんせい"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>学生 (&quot;student&quot;) is read がくせい. Answer A.</p></div><div class=\"ml-vi\"><p>学生 (&quot;học sinh/sinh viên&quot;) đọc là がくせい. Đáp án A.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>まいあさ、【なんじ】に がっこうへ いきますか。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>まいあさ、【なんじ】に　がっこうへ　いきますか。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q38.png",
          "options": [
            {
              "text": "荷寺|||荷寺"
            },
            {
              "text": "荷時|||荷時"
            },
            {
              "text": "何寺|||何寺"
            },
            {
              "text": "何時|||何時"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>なんじ (&quot;what time&quot;) is written 何時. Answer D.</p></div><div class=\"ml-vi\"><p>なんじ (&quot;mấy giờ&quot;) viết là 何時. Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: あのう、すみません。くつやは どこですか。<br/>B: あそこです。<br/>A: そうですか。（________________）</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：あのう、すみません。くつやは　どこですか。<br/>B：あそこです。<br/>A：そうですか。（________________）</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q39.png",
          "options": [
            {
              "text": "よろしく おねがいします|||よろしく おねがいします"
            },
            {
              "text": "ありがとうございます|||ありがとうございます"
            },
            {
              "text": "おはようございます|||おはようございます"
            },
            {
              "text": "おやすみなさい|||おやすみなさい"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>After receiving directions, A politely thanks B: ありがとうございます. Answer B.</p></div><div class=\"ml-vi\"><p>Sau khi được chỉ đường, A cảm ơn B một cách lịch sự: ありがとうございます. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>アリさん「すみません、ちゅうもんを おねがいします。」<br/>てんいん「（　　）。」</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>アリさん「すみません、ちゅうもんを　おねがいします。」<br/>てんいん「（　　）。」</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q40.png",
          "options": [
            {
              "text": "あのう、すみません|||あのう、すみません"
            },
            {
              "text": "いらっしゃいませ|||いらっしゃいませ"
            },
            {
              "text": "どうぞ|||どうぞ"
            },
            {
              "text": "ありがとうございました。|||ありがとうございました。"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>The customer asks to order; the staff invites them to go ahead with どうぞ (&quot;please, go ahead&quot;). いらっしゃいませ is used when a customer enters, not as a reply to an order request. Answer C.</p></div><div class=\"ml-vi\"><p>Khách yêu cầu gọi món; nhân viên mời khách tiếp tục bằng どうぞ (&quot;xin mời&quot;). いらっしゃいませ dùng khi khách bước vào, không phải để đáp lại yêu cầu gọi món. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Find the corresponding Vietnamese meaning for the following word:<br/>&quot;エスカレーター&quot;</p></div><div class=\"ml-vi\"><p>Hãy tìm nghĩa tiếng Việt tương ứng cho từ sau:<br/>&quot;エスカレーター&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q41.png",
          "options": [
            {
              "text": "Nhà vệ sinh|||Nhà vệ sinh"
            },
            {
              "text": "Thang máy|||Thang máy"
            },
            {
              "text": "Thang cuốn|||Thang cuốn"
            },
            {
              "text": "Nơi hút thuốc|||Nơi hút thuốc"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>エスカレーター (escalator) = &quot;Thang cuốn&quot; in Vietnamese. Answer C.</p></div><div class=\"ml-vi\"><p>エスカレーター (escalator) nghĩa là &quot;Thang cuốn&quot;. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Which Chinese character (Kanji) does the word in brackets [ ] below correspond to? Choose the correct answer among A, B, C, D:<br/>このかばんは【にまんよんせんはっぴゃく】えんです。</p></div><div class=\"ml-vi\"><p>Các từ trong ngoặc [ ] dưới đây có chữ Hán tương ứng như thế nào? Hãy chọn đáp án đúng trong A, B, C, D:<br/>このかばんは【にまんよんせんはっぴゃく】えんです。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q42.png",
          "options": [
            {
              "text": "四千八百二万|||四千八百二万"
            },
            {
              "text": "二万四八百千|||二万四八百千"
            },
            {
              "text": "二八百万四千|||二八百万四千"
            },
            {
              "text": "二万四千八百|||二万四千八百"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>にまんよんせんはっぴゃく = 24,800, written in the natural order 二万四千八百 (2-man 4-sen 8-hyaku). The other options scramble the digit-unit order into non-standard/nonsensical forms. Answer D.</p></div><div class=\"ml-vi\"><p>にまんよんせんはっぴゃく = 24.800, viết theo thứ tự tự nhiên 二万四千八百 (2 vạn 4 nghìn 8 trăm). Các phương án khác đảo lộn thứ tự chữ số/đơn vị thành dạng không chuẩn/vô nghĩa. Đáp án D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: あさ、何時に ______へ きますか。<br/>B: 8時に きます。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：あさ、何時に　______へ　きますか。<br/>B：8時に　きます。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q43.png",
          "options": [
            {
              "text": "はる|||はる"
            },
            {
              "text": "学校|||学校"
            },
            {
              "text": "くだもの|||くだもの"
            },
            {
              "text": "しんぶん|||しんぶん"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The blank + へ きます (&quot;come to ~&quot;) needs a place; of はる (spring), 学校 (school), くだもの (fruit), しんぶん (newspaper), only 学校 is a place. Answer B.</p></div><div class=\"ml-vi\"><p>Chỗ trống + へ きます (&quot;đến ~&quot;) cần một địa điểm; trong はる (mùa xuân), 学校 (trường học), くだもの (trái cây), しんぶん (báo), chỉ có 学校 là địa điểm. Đáp án B.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Choose the appropriate answer among A, B, C, D to fill in the blank<br/>A: ふゆやすみ、りょこうを しますか。<br/>B: いいえ、（______________）。</p></div><div class=\"ml-vi\"><p>Chọn trong A, B, C, D đáp án thích hợp để điền vào chỗ trống<br/>A：ふゆやすみ、りょこうを　しますか。<br/>B：いいえ、（______________）。</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q44.png",
          "options": [
            {
              "text": "りょこうをします|||りょこうをします"
            },
            {
              "text": "りょこうじゃありません|||りょこうじゃありません"
            },
            {
              "text": "りょこうをしません|||りょこうをしません"
            },
            {
              "text": "りょこうではありません|||りょこうではありません"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>The question uses りょこうを します (suru-verb with object marker を); the negative reply must keep that structure: りょこうを しません. The じゃ/ではありません forms are noun-predicate negation and don&#39;t fit a を-marked suru-verb here. Answer C.</p></div><div class=\"ml-vi\"><p>Câu hỏi dùng りょこうを　します (động từ する với trợ từ を); câu trả lời phủ định phải giữ cấu trúc đó: りょこうを　しません. Dạng じゃ/ではありません là phủ định danh từ vị ngữ, không phù hợp với động từ する có を ở đây. Đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2222,
          "prompt": "<div class=\"ml-en\"><p>Reading passage (PN=1) — read the passage below then answer the question. This image contains three sub-questions sharing one passage; sub-question 3 (about blank ①, highlighted as the active item in the source navigator) is transcribed as the primary question; sub-questions 1 and 2 are documented in the explanation.</p><p>私は たなかです。日本人です。私は かいしゃいんです。月曜日から金曜日まで、かいしゃへ いきます。あさ、ごぜん9時から ごご5時半まで かいしゃで＿＿＿①＿＿＿。土曜日のごぜん、しんぶんを＿＿＿②＿＿。ごご、うちでDVDを みます。日曜日、こうえんで テニスをします。</p><p>3) Chọn từ thích hợp điền vào chỗ trống ______①______</p></div><div class=\"ml-vi\"><p>Đọc đoạn văn sau rồi trả lời các câu hỏi dưới đây (PN=1). Ảnh này gồm 3 câu hỏi con dùng chung một đoạn văn; câu hỏi con số 3 (về chỗ trống ①, được tô sáng là mục đang chọn trên thanh điều hướng nguồn) được chép làm câu chính; câu hỏi con 1 và 2 được ghi chú trong phần giải thích.</p><p>私は たなかです。日本人です。私は かいしゃいんです。月曜日から金曜日まで、かいしゃへ いきます。あさ、ごぜん9時から ごご5時半まで かいしゃで＿＿＿①＿＿＿。土曜日のごぜん、しんぶんを＿＿＿②＿＿。ごご、うちでDVDを みます。日曜日、こうえんで テニスをします。</p><p>3) Chọn từ thích hợp điền vào chỗ trống ______①______</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/JPD113/D35/q45.png",
          "options": [
            {
              "text": "かいます|||かいます"
            },
            {
              "text": "ねます|||ねます"
            },
            {
              "text": "はたらきます|||はたらきます"
            },
            {
              "text": "かえります|||かえります"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Blank ① follows &quot;from 9am to 5:30pm at the company ___&quot;, describing work hours, so はたらきます (&quot;work&quot;) is correct (Answer C).</p><p>Additional sub-questions sharing this same passage image, documented here rather than fabricated as separate numbered lines with no image:<br/>1) Blank ② fill-in: &quot;土曜日のごぜん、しんぶんを___②___&quot; (Saturday morning, ___ the newspaper) — options きます／いきます／よみます／べんきょうします — correct answer is よみます (&quot;read&quot;, option C), since 新聞を読みます is the natural collocation.<br/>2) &quot;Choose the sentence with INCORRECT content&quot;: A) たなかさんは土曜日のごご、しんぶんをよみます。(reads newspaper Saturday AFTERNOON) B) たなかさんは日曜日、テニスをします。 C) たなかさんは日本人です。 D) たなかさんは月曜日から金曜日までかいしゃではたらきます。 — The passage states the newspaper is read on Saturday MORNING (not afternoon; afternoon is for watching DVDs), so statement A contradicts the passage and is the incorrect one (Answer A).</p></div><div class=\"ml-vi\"><p>Chỗ trống ① theo sau &quot;từ 9 giờ sáng đến 5 rưỡi chiều ở công ty ___&quot;, mô tả giờ làm việc, nên はたらきます (&quot;làm việc&quot;) là đúng (Đáp án C).</p><p>Các câu hỏi con khác dùng chung ảnh đoạn văn này, được ghi chú ở đây thay vì bịa thêm dòng số riêng không có ảnh:<br/>1) Điền chỗ trống ②: &quot;土曜日のごぜん、しんぶんを___②___&quot; (sáng thứ Bảy, ___ báo) — các phương án きます／いきます／よみます／べんきょうします — đáp án đúng là よみます (&quot;đọc&quot;, phương án C), vì 新聞を読みます là cách kết hợp tự nhiên.<br/>2) &quot;Chọn câu có nội dung KHÔNG ĐÚNG&quot;: A) たなかさんは土曜日のごご、しんぶんをよみます。(đọc báo vào CHIỀU thứ Bảy) B) たなかさんは日曜日、テニスをします。 C) たなかさんは日本人です。 D) たなかさんは月曜日から金曜日までかいしゃではたらきます。 — Đoạn văn ghi rõ đọc báo vào SÁNG thứ Bảy (không phải chiều; chiều dùng để xem DVD), nên câu A mâu thuẫn với đoạn văn và là câu sai (Đáp án A).</p></div>"
        }
      ]
    }
  ]
};
