// AUTO-GENERATED by scripts/build-fe-exam.mjs from bank-MLN122-Q2-6.jsonl — re-run the builder, do not hand-edit.
export default {
  "course": {
    "courseCode": "MLN122"
  },
  "exams": [
    {
      "kind": "FE",
      "code": "Q2-6",
      "title": "MLN122 — Quiz Chương 2, Đề 6|||MLN122 — Quiz Chương 2, Đề 6",
      "description": "Quiz ôn tập chương 2 (20 câu).|||Quiz ôn tập chương 2 (20 câu).",
      "durationMinutes": 20,
      "totalPoints": 10,
      "passMark": 4,
      "source": "REAL",
      "shuffleQuestions": false,
      "shuffleOptions": false,
      "instructions": "<div class=\"ml-en\"><p>This is a real FPTU <b>Final Exam</b> paper for <b>this subject</b>. Every question is <b>multiple choice</b> and auto-graded.</p><ul><li>Some questions say \"choose TWO\" — they are only correct when both right answers are selected.</li><li>Read code, tables and diagrams carefully; several questions turn on a subtle detail.</li><li>The original scanned question is available under <b>\"Show original image\"</b> on each question.</li></ul><p>You can flag a question and come back. The timer auto-submits at the end. After you submit, every question shows a bilingual explanation.</p></div><div class=\"ml-vi\"><p>Đây là đề <b>thi cuối kỳ (Final Exam)</b> thật của FPTU môn <b>this subject</b>. Mọi câu đều là <b>trắc nghiệm</b>, chấm tự động.</p><ul><li>Một số câu ghi \"chọn HAI\" — chỉ đúng khi chọn đủ cả hai đáp án đúng.</li><li>Đọc kỹ code, bảng và sơ đồ; nhiều câu ăn thua ở một chi tiết nhỏ.</li><li>Ảnh đề gốc đã quét nằm ở nút <b>\"Xem ảnh đề gốc\"</b> trên mỗi câu.</li></ul><p>Bạn có thể đánh dấu câu để quay lại sau. Hết giờ hệ thống tự nộp. Nộp xong, mỗi câu đều có lời giải song ngữ.</p></div>",
      "isPublished": true,
      "questions": [
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>Choose the correct statement about increasing labor intensity: when labor intensity increases, then:</p></div><div class=\"ml-vi\"><p>Chọn ý đúng về tăng cường độ lao động: khi cường độ lao động tăng lên thì:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q1.png",
          "options": [
            {
              "text": "The quantity of goods produced per unit of time increases.|||Số lượng hàng hoá làm ra trong một đơn vị thời gian tăng lên."
            },
            {
              "text": "The amount of labor expended in that time does not change.|||Số lượng lao động hao phí trong thời gian đó không thay đổi."
            },
            {
              "text": "The value of one unit of goods decreases.|||Giá trị 1 đơn vị hàng hoá giảm đi."
            },
            {
              "text": "The quantity of goods produced by one worker increases.|||Số lượng hàng hóa làm ra của một người tăng lên."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Increasing labor intensity means expending more labor effort within the same unit of time, so the quantity of goods produced in that time increases proportionally, while the value of each unit of goods stays unchanged (unlike a rise in labor productivity, which reduces the value per unit).</p></div><div class=\"ml-vi\"><p>Tăng cường độ lao động là tăng mức độ khẩn trương, hao phí sức lao động trong một đơn vị thời gian, do đó số lượng hàng hoá sản xuất ra trong đơn vị thời gian đó tăng lên tương ứng, còn giá trị của một đơn vị hàng hoá không đổi (khác với tăng năng suất lao động làm giảm giá trị 1 đơn vị hàng hoá).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>In a commodity economy, competition has the effect of</p></div><div class=\"ml-vi\"><p>Trong kinh tế hàng hóa, cạnh tranh có tác dụng</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q2.png",
          "options": [
            {
              "text": "Making production lack humanity|||Nó làm cho sản xuất thiếu tính nhân văn"
            },
            {
              "text": "Forcing producers to be constantly dynamic and responsive.|||Nó buộc người sản xuất phải thường xuyên năng động, nhạy bén."
            },
            {
              "text": "Making production more humane|||Nó làm cho sản xuất mang tính nhân văn hơn"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Competition forces producers to constantly stay dynamic and responsive, improving technology and quality and lowering costs in order to survive and grow.</p></div><div class=\"ml-vi\"><p>Cạnh tranh buộc người sản xuất phải thường xuyên năng động, nhạy bén, cải tiến kỹ thuật, nâng cao chất lượng, hạ giá thành để tồn tại và phát triển.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>How does an increase in the ratio of complex labor to simple labor affect the amount of value created per unit of time?</p></div><div class=\"ml-vi\"><p>Tỷ lệ giữa lao động phức tạp và lao động giản đơn tăng lên có ảnh hưởng như thế nào đến lượng giá trị được tạo ra trong một đơn vị thời gian?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q3.png",
          "options": [
            {
              "text": "It increases|||Tăng lên"
            },
            {
              "text": "It stays unchanged|||Giữ nguyên không thay đổi"
            },
            {
              "text": "It decreases|||Giảm xuống"
            },
            {
              "text": "It increases, but only if tied to technological progress|||Tăng lên nhưng phải gắn với tiến bộ công nghệ"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Complex labor is essentially multiplied simple labor, so as the share of complex labor rises, more value is created within the same unit of time.</p></div><div class=\"ml-vi\"><p>Lao động phức tạp là lao động giản đơn được nhân lên gấp bội, nên khi tỷ trọng lao động phức tạp tăng, trong cùng một đơn vị thời gian sẽ tạo ra lượng giá trị lớn hơn.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The commodity of labor power comes into being based on</p></div><div class=\"ml-vi\"><p>Hàng hóa sức lao động ra đời phải dựa trên</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q4.png",
          "options": [
            {
              "text": "Three conditions|||Ba điều kiện"
            },
            {
              "text": "One condition|||Một điều kiện"
            },
            {
              "text": "Two conditions|||Hai điều kiện"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Labor power becomes a commodity under two conditions: the laborer is personally free and owns their own labor power; and the laborer has no means of production, so must sell their labor power to survive.</p></div><div class=\"ml-vi\"><p>Sức lao động trở thành hàng hoá khi có hai điều kiện: người lao động được tự do về thân thể, có quyền sở hữu sức lao động của mình; và người lao động không có tư liệu sản xuất, buộc phải bán sức lao động để sống.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The more science and technology develop, the more it causes</p></div><div class=\"ml-vi\"><p>Khoa học kỹ thuật càng phát triển làm cho</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q5.png",
          "options": [
            {
              "text": "The use-value of goods to become increasingly rich and diverse|||Giá trị sử dụng của hàng hóa ngày càng phong phú và đa dạng"
            },
            {
              "text": "The use-value of goods to constantly change|||Giá trị sử dụng của hàng hóa luôn thay đổi"
            },
            {
              "text": "The use-value of goods to fluctuate according to the market|||Giá trị sử dụng của hàng hóa biến thiên theo thị trường"
            },
            {
              "text": "The value of goods to become increasingly rich and diverse with more products|||Giá trị của hàng hóa ngày càng phong phú và đa dạng với nhiều sản phẩm"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>As science and technology advance, new properties and uses of objects are discovered, making the use-value of goods increasingly rich and diverse.</p></div><div class=\"ml-vi\"><p>Khoa học kỹ thuật phát triển giúp phát hiện thêm những thuộc tính, công dụng mới của vật phẩm, làm cho giá trị sử dụng của hàng hoá ngày càng phong phú, đa dạng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>For money to become capital?</p></div><div class=\"ml-vi\"><p>Để tiền biến thành tư bản?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q6.png",
          "options": [
            {
              "text": "A large amount of money must be accumulated.|||Phải tích lũy một lượng tiền lớn."
            },
            {
              "text": "A large amount of money must be accumulated; the money must be put into capitalist business for the purpose of earning surplus value.|||Phải tích lũy một lượng tiền lớn; tiền cần phải được đưa vào kinh doanh tư bản với mục đích thu giá trị thặng dư."
            },
            {
              "text": "A large amount of goods must be accumulated; the goods must be put into capitalist business for the purpose of earning surplus value.|||Phải tích lũy được một lượng hàng hóa lớn; hàng hóa cần phải được đưa vào kinh doanh tư bản với mục đích thu giá trị thặng dư."
            },
            {
              "text": "A large amount of machinery must be accumulated; the machinery must be put into capitalist business for the purpose of earning surplus value.|||Phải tích lũy được một lượng máy móc lớn; máy móc cần phải được đưa vào kinh doanh tư bản với mục đích thu giá trị thặng dư"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Money only becomes capital when it is accumulated in sufficient quantity and is put into circulation/business for the purpose of earning surplus value (per the general formula M-C-M&#39;).</p></div><div class=\"ml-vi\"><p>Tiền chỉ biến thành tư bản khi được tích lũy đủ lớn và được đưa vào lưu thông, kinh doanh nhằm mục đích thu về giá trị thặng dư (theo công thức chung T-H-T&#39;).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>What is loan capital?</p></div><div class=\"ml-vi\"><p>Thế nào là tư bản cho vay</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q7.png",
          "options": [
            {
              "text": "Commodity capital that its owner lends to another to use for a certain period in order to earn interest.|||Là tư bản hàng hóa mà người chủ của nó nhường cho người khác sử dụng ở trong một thời gian nhất định để thu lợi tức."
            },
            {
              "text": "Money capital that its owner lends to another to use for a certain period in order to earn interest.|||Là tư bản tiền tệ mà người chủ của nó nhường cho người khác sử dụng ở trong một thời gian nhất định để thu lợi tức."
            },
            {
              "text": "Money capital that its owner lends to another to use for a certain period in order to earn profit.|||Là tư bản tiền tệ mà người chủ của nó nhường cho người khác sử dụng ở trong một thời gian nhất định để thu lợi nhuận."
            },
            {
              "text": "Productive capital that its owner lends to another to use for a certain period in order to earn interest.|||Là tư bản sản xuất mà người chủ của nó nhường cho người khác sử dụng ở trong một thời gian nhất định để thu lợi tức."
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Loan capital is money capital that its owner lends to someone else to use for a specific period in exchange for interest.</p></div><div class=\"ml-vi\"><p>Tư bản cho vay là tư bản tiền tệ mà người chủ sở hữu nhường quyền sử dụng cho người khác trong một thời gian nhất định để thu lợi tức.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The turnover time of capital is understood as:</p></div><div class=\"ml-vi\"><p>Thời gian chu chuyển của tư bản được hiểu:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q8.png",
          "options": [
            {
              "text": "Production time + selling time.|||Thời gian sản xuất + thời gian bán hàng."
            },
            {
              "text": "Production time + circulation time.|||Thời gian sản xuất + thời gian lưu thông."
            },
            {
              "text": "Production-reserve time + circulation time.|||Thời gian dự trữ sản xuất + thời gian lưu thông."
            },
            {
              "text": "Production time + marketing time.|||Thời gian sản xuất + thời gian tiếp thị."
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The turnover time of capital equals production time plus circulation time.</p></div><div class=\"ml-vi\"><p>Thời gian chu chuyển của tư bản = thời gian sản xuất + thời gian lưu thông.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>Which of C. Marx&#39;s economic theories is regarded as the cornerstone?</p></div><div class=\"ml-vi\"><p>Học thuyết kinh tế nào của C.Mác được coi là hòn đá tảng</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q9.png",
          "options": [
            {
              "text": "The theory of surplus value|||Học thuyết giá trị thặng dư"
            },
            {
              "text": "The theory of money|||Học thuyết tiền tệ"
            },
            {
              "text": "The theory of supply and demand|||Học thuyết cung cầu"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>The theory of surplus value is regarded as the &#39;cornerstone&#39; of Marx&#39;s entire economic theory.</p></div><div class=\"ml-vi\"><p>Học thuyết giá trị thặng dư được coi là &#39;hòn đá tảng&#39; trong toàn bộ học thuyết kinh tế của C.Mác.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>What do the methods of producing absolute surplus value and relative surplus value have in common?</p></div><div class=\"ml-vi\"><p>Phương pháp sản xuất giá trị thặng dư tuyệt đối và phương pháp sản xuất giá trị thặng dư tương đối có điểm nào giống nhau?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q10.png",
          "options": [
            {
              "text": "Both increase the rate of surplus value.|||Đều làm tăng tỷ suất giá trị thặng dư."
            },
            {
              "text": "Both make workers expend more labor effort.|||Đều làm cho công nhân tốn sức lao động nhiều hơn."
            },
            {
              "text": "Both reduce the value of workers&#39; labor power.|||Đều làm giảm giá trị sức lao động của công nhân."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Both methods aim to increase the rate of surplus value (m&#39;), though by different means: the absolute method lengthens the working day, while the relative method shortens necessary labor time by raising labor productivity.</p></div><div class=\"ml-vi\"><p>Cả hai phương pháp đều nhằm mục đích tăng tỷ suất giá trị thặng dư (m&#39;), dù cách thức khác nhau: phương pháp tuyệt đối kéo dài ngày lao động, phương pháp tương đối rút ngắn thời gian lao động tất yếu nhờ tăng năng suất lao động.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>In terms of its nature, economic interest is understood as:</p></div><div class=\"ml-vi\"><p>Xét về bản chất, thì lợi ích kinh tế được hiểu là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q11.png",
          "options": [
            {
              "text": "A socio-economic relation|||Quan hệ kinh tế xã hội"
            },
            {
              "text": "A social relation, of a historical character|||Quan hệ xã hội, mang tính lịch sử"
            },
            {
              "text": "A relation of production|||Quan hệ sản xuất"
            },
            {
              "text": "A political relation of an interest-based nature|||Quan hệ chính trị mang tính lợi ích"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>In essence, economic interest reflects the objective purposes and motives of subjects participating in socio-economic activities, so economic interest is fundamentally a socio-economic relation among those subjects.</p></div><div class=\"ml-vi\"><p>Về bản chất, lợi ích kinh tế phản ánh mục đích và động cơ khách quan của các chủ thể khi tham gia vào các hoạt động kinh tế - xã hội, do đó lợi ích kinh tế là quan hệ kinh tế - xã hội giữa các chủ thể.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>Choose the incorrect option: The reason Vietnam needs to complete/perfect the socialist-oriented market economy institution is:</p></div><div class=\"ml-vi\"><p>Chọn phương án sai: Lý do để Việt Nam hoàn thiện thể chế kinh tế thị trường định hướng xã hội chủ nghĩa là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q12.png",
          "options": [
            {
              "text": "Because the socialist-oriented market economy institution is not yet complete|||Do thể chế kinh tế thị trường định hướng xã hội chủ nghĩa chưa hoàn thiện"
            },
            {
              "text": "The institutional system is not yet adequate|||Hệ thống thể chế chưa đầy đủ"
            },
            {
              "text": "The institutional system is still weak in effectiveness and efficiency, lacking market elements and types of markets|||Hệ thống thể chế còn kém hiệu lực, hiệu quả, thiếu các yếu tố thị trường và các loại thị trường"
            },
            {
              "text": "Because the Communist Party provides leadership|||Do đảng cộng sản lãnh đạo"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>A, B, and C are all genuine reasons why Vietnam needs to keep perfecting its socialist-oriented market economy institutions. D (&#39;because the Communist Party leads&#39;) is not a reason for perfecting the institutions — it describes a different matter (the Party&#39;s leadership role) — so it is the incorrect statement.</p></div><div class=\"ml-vi\"><p>A, B, C đều là những lý do thực tế khiến Việt Nam cần tiếp tục hoàn thiện thể chế kinh tế thị trường định hướng XHCN. Riêng D (&#39;do đảng lãnh đạo&#39;) không phải là lý do cần hoàn thiện thể chế, mà là một yếu tố khác (vai trò lãnh đạo), nên đây là phương án sai.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The direct cause leading to the formation of monopoly organizations is:</p></div><div class=\"ml-vi\"><p>Nguyên nhân trực tiếp dẫn tới sự hình thành của các tổ chức độc quyền đó là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q13.png",
          "options": [
            {
              "text": "Capital accumulation|||Tích lũy tư bản"
            },
            {
              "text": "Concentration and centralization of production reaching a high degree|||Tích tụ và tập trung sản xuất ở mức độ cao"
            },
            {
              "text": "The growing strength of companies and enterprises|||Sự lớn mạnh của các công ty, doanh nghiệp"
            },
            {
              "text": "Collusion between enterprises|||Sự thỏa hiệp của các doanh nghiệp với nhau"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>According to Lenin&#39;s theory of monopoly capitalism, the concentration and centralization of production reaching a high degree is the direct cause of the formation of monopoly organizations.</p></div><div class=\"ml-vi\"><p>Tích tụ và tập trung sản xuất phát triển đến một mức độ cao là nguyên nhân trực tiếp dẫn đến sự hình thành các tổ chức độc quyền, theo lý luận của Lênin về chủ nghĩa tư bản độc quyền.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The viewpoint that &#39;renewal (doi moi) must always thoroughly grasp the view that the people are the root,&#39; for the benefit of the people, relying on the people, promoting their mastery role, sense of responsibility, creativity and all resources of the people, and promoting the strength of great national unity, was put forward at which Party Congress?</p></div><div class=\"ml-vi\"><p>Quan điểm &quot;đổi mới phải luôn luôn quán triệt quan điểm dân là gốc&quot; vì lợi ích của nhân dân, dựa vào nhân dân, phát huy vai trò làm chủ, tinh thần trách nhiệm, sức sáng tạo và mọi nguồn lực của nhân dân; phát huy sức mạnh đại đoàn kết dân tộc được đưa ra trong đại hội nào?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q14.png",
          "options": [
            {
              "text": "Party Congress X|||Đại hội đảng X"
            },
            {
              "text": "Party Congress XI|||Đại hội đảng XI"
            },
            {
              "text": "Party Congress XII|||Đại hội đảng XII"
            },
            {
              "text": "Party Congress XIII|||Đại hội đảng XIII"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>The view of &#39;the people as the root&#39; as a consistent lesson of the renewal process was clearly stated in the Documents of the 13th National Party Congress (2021).</p></div><div class=\"ml-vi\"><p>Quan điểm &#39;dân là gốc&#39; như một bài học kinh nghiệm xuyên suốt của công cuộc đổi mới được nêu rõ trong Văn kiện Đại hội Đảng XIII (2021).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The formation of monopoly is based on which of the following causes?</p></div><div class=\"ml-vi\"><p>Sự hình thành độc quyền dựa trên các nguyên nhân nào sau đây?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q15.png",
          "options": [
            {
              "text": "The development of productive forces driving monopoly organizations; competition; crises; the development of the credit system|||Sự phát triển của lực lượng sản xuất thúc đẩy các tổ chức độc quyền; cạnh tranh; khủng hoảng sự phát triển của hệ thống tín dụng"
            },
            {
              "text": "The development of relations of production driving monopoly organizations; competition; crises; the development of the credit system|||Sự phát triển của quan hệ sản xuất thúc đẩy các tổ chức độc quyền; cạnh tranh; khủng hoảng sự phát triển của hệ thống tín dụng"
            },
            {
              "text": "The development of the capitalist mode of production driving monopoly organizations; competition; crises; the development of the credit system|||Sự phát triển của phương thức sản xuất tư bản chủ nghĩa thúc đẩy các tổ chức độc quyền; cạnh tranh; khủng hoảng sự phát triển của hệ thống tín dụng"
            },
            {
              "text": "The development of productive forces driving monopoly organizations; competition; crises in the development of a nation|||Sự phát triển của lực lượng sản xuất thúc đẩy các tổ chức độc quyền; cạnh tranh; khủng hoảng trong sự phát triển của một quốc gia"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>According to Lenin, the causes of monopoly formation include: the development of the productive forces driving the formation of monopoly organizations; competition; economic crises; and the development of the capitalist credit system.</p></div><div class=\"ml-vi\"><p>Theo Lênin, các nguyên nhân hình thành độc quyền gồm: sự phát triển của lực lượng sản xuất thúc đẩy hình thành tổ chức độc quyền; cạnh tranh; khủng hoảng kinh tế; và sự phát triển của hệ thống tín dụng tư bản chủ nghĩa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>Choose the incorrect statement about the characteristics of a market economy.</p></div><div class=\"ml-vi\"><p>Chọn câu sai khi nói về đặc điểm của kinh tế thị trường.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q16.png",
          "options": [
            {
              "text": "A market economy is a highly developed commodity economy|||Kinh tế thị trường là kinh tế hàng hoá phát triển cao"
            },
            {
              "text": "A market economy is based on modern science and technology|||Kinh tế thị trường lấy khoa học công nghệ hiện đại làm cơ sở"
            },
            {
              "text": "A market economy can only develop strongly in feudal society|||Kinh tế thị trường chỉ có thể phát triển mạnh ở xã hội phong kiến"
            },
            {
              "text": "A market economy reaches a high level under capitalism|||Kinh tế thị trường đạt đến trình độ cao trong CNTB"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>A market economy develops most strongly and reaches its highest level under capitalism, not feudal society, so statement C is incorrect.</p></div><div class=\"ml-vi\"><p>Kinh tế thị trường phát triển mạnh mẽ nhất và đạt trình độ cao dưới chủ nghĩa tư bản, chứ không phải xã hội phong kiến, nên C là câu sai.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>Capital export is considered a characteristic of:</p></div><div class=\"ml-vi\"><p>Xuất khẩu tư bản được coi là đặc điểm của:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q17.png",
          "options": [
            {
              "text": "The feudal mode of production|||Phương thức sản xuất phong kiến"
            },
            {
              "text": "The capitalist mode of production|||Phương thức sản xuất tư bản chủ nghĩa"
            },
            {
              "text": "Capitalism in the free-competition stage|||Chủ nghĩa tư bản giai đoạn tự do cạnh tranh"
            },
            {
              "text": "Capitalism in the monopoly stage|||Chủ nghĩa tư bản giai đoạn độc quyền"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Capital export is one of the five basic economic characteristics of monopoly capitalism (imperialism), according to Lenin&#39;s theory.</p></div><div class=\"ml-vi\"><p>Xuất khẩu tư bản là một trong năm đặc điểm kinh tế cơ bản của chủ nghĩa tư bản độc quyền (chủ nghĩa đế quốc) theo lý luận của Lênin.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>In which society did the market economy form?</p></div><div class=\"ml-vi\"><p>Kinh tế thị trường đã hình thành trong xã hội nào?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q18.png",
          "options": [
            {
              "text": "Feudal society|||Phong kiến"
            },
            {
              "text": "Slave-holding society|||Chiếm hữu nô lệ"
            },
            {
              "text": "Capitalist society|||Tư bản chủ nghĩa"
            },
            {
              "text": "Socialist society|||Xã hội chủ nghĩa"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>The market economy took shape within feudal society (as simple commodity production developed to a higher level), and later developed further, reaching its highest level under capitalism.</p></div><div class=\"ml-vi\"><p>Kinh tế thị trường hình thành từ trong lòng xã hội phong kiến (khi kinh tế hàng hoá giản đơn phát triển lên trình độ cao hơn), sau đó phát triển và đạt đến trình độ cao dưới chủ nghĩa tư bản.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>The viewpoints on perfecting the socialist-oriented market economy institution include:</p></div><div class=\"ml-vi\"><p>Quan điểm về hoàn thiện thể chế thị trường định hướng xã hội chủ nghĩa là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q19.png",
          "options": [
            {
              "text": "Ensuring synchronization among the constituent parts of economic institutions, among market elements and types of markets|||Đảm bảo tính đồng bộ giữa các bộ phận cấu thành của các thể chế kinh tế, giữa các yếu tố thị trường và các loại thị trường"
            },
            {
              "text": "Being proactive on theoretical and practical issues, while raising the Party&#39;s leadership capacity and the State&#39;s management effectiveness|||Chủ động, tích cực các vấn đề lý luận và thực tiễn, đồng thời nâng cao năng lực lãnh đạo của Đảng, hiệu lực quản lý của Nhà nước"
            },
            {
              "text": "Selectively inheriting humanity&#39;s achievements in market economy development and the experience drawn from our country&#39;s renewal practice; fully understanding, respecting and correctly applying the objective laws of the market economy|||Kế thừa có chọn lọc thành tựu phát triển kinh tế thị trường của nhân loại và kinh nghiệm tổng kết từ thực tiễn đổi mới ở nước ta; nhận thức đầy đủ, tôn trọng và vận dụng đúng đắn các quy luật khách quan của kinh tế thị trường"
            },
            {
              "text": "All of the above|||Tất cả phương án trên"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>All three contents A, B, and C are official viewpoints stated in Party documents on perfecting the socialist-oriented market economy institution, so the correct answer is D.</p></div><div class=\"ml-vi\"><p>Cả ba nội dung A, B, C đều là những quan điểm chính thức được nêu trong các văn kiện của Đảng về hoàn thiện thể chế kinh tế thị trường định hướng xã hội chủ nghĩa, nên đáp án đúng là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.5,
          "prompt": "<div class=\"ml-en\"><p>One of the positive impacts of monopoly on the economy is:</p></div><div class=\"ml-vi\"><p>Một trong những tác động tích cực của độc quyền đối với nền kinh tế đó là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/MLN122/QUIZ-q26/q20.png",
          "options": [
            {
              "text": "Concentrating resources for research and development and exploiting advances in science and technology|||Tập trung các nguồn lực trong việc nghiên cứu phát triển và khai thác các tiến bộ của khoa học kỹ thuật"
            },
            {
              "text": "Increasing consumers&#39; purchasing power, thereby raising the competitiveness of monopoly organizations|||Tăng sức mua của người tiêu dùng, từ đó nâng cao năng lực cạnh tranh của các tổ chức độc quyền"
            },
            {
              "text": "Creating political and military strength for developed countries|||Tạo ra sức mạnh về chính trị, quân sự cho các quốc gia phát triển"
            },
            {
              "text": "Being dominated by narrow interest groups, thereby increasing the rich-poor divide|||Bị chi phối bởi các nhóm lợi ích cục bộ từ đó làm gia tăng sự phân hóa giàu nghèo"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Because of their large economic resources, monopoly organizations can concentrate resources to invest in research, development and application of scientific and technological advances — this is a positive effect of monopoly on the economy.</p></div><div class=\"ml-vi\"><p>Nhờ có tiềm lực kinh tế lớn, các tổ chức độc quyền có khả năng tập trung nguồn lực đầu tư nghiên cứu, phát triển và ứng dụng những tiến bộ khoa học kỹ thuật, đây là tác động tích cực của độc quyền đối với nền kinh tế.</p></div>"
        }
      ]
    }
  ]
};
