// AUTO-GENERATED by scripts/build-fe-exam.mjs from bank-OSG202-FE26.jsonl — re-run the builder, do not hand-edit.
export default {
  "course": {
    "courseCode": "OSG202"
  },
  "exams": [
    {
      "kind": "FE",
      "code": "D26",
      "title": "Đề 26 — Final Exam (C2-FE-SU23)|||Đề 26 — Thi cuối kỳ (C2-FE-SU23)",
      "description": "Operating Systems final exam (C2-FE-SU23), bilingual MCQs.|||Đề thi cuối kỳ Operating Systems (C2-FE-SU23), trắc nghiệm song ngữ.",
      "durationMinutes": 60,
      "totalPoints": 10,
      "passMark": 5,
      "source": "FUOverflow",
      "shuffleQuestions": false,
      "shuffleOptions": false,
      "instructions": "<div class=\"ml-en\"><p>This is a real FPTU <b>Final Exam</b> paper for <b>Operating Systems</b>. Every question is <b>multiple choice</b> and auto-graded.</p><ul><li>Some questions say \"choose TWO\" — they are only correct when both right answers are selected.</li><li>Read code, tables and diagrams carefully; several questions turn on a subtle detail.</li><li>The original scanned question is available under <b>\"Show original image\"</b> on each question.</li></ul><p>You can flag a question and come back. The timer auto-submits at the end. After you submit, every question shows a bilingual explanation.</p></div><div class=\"ml-vi\"><p>Đây là đề <b>thi cuối kỳ (Final Exam)</b> thật của FPTU môn <b>Operating Systems</b>. Mọi câu đều là <b>trắc nghiệm</b>, chấm tự động.</p><ul><li>Một số câu ghi \"chọn HAI\" — chỉ đúng khi chọn đủ cả hai đáp án đúng.</li><li>Đọc kỹ code, bảng và sơ đồ; nhiều câu ăn thua ở một chi tiết nhỏ.</li><li>Ảnh đề gốc đã quét nằm ở nút <b>\"Xem ảnh đề gốc\"</b> trên mỗi câu.</li></ul><p>Bạn có thể đánh dấu câu để quay lại sau. Hết giờ hệ thống tự nộp. Nộp xong, mỗi câu đều có lời giải song ngữ.</p></div>",
      "isPublished": true,
      "questions": [
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is not special file?</p></div><div class=\"ml-vi\"><p>Loại nào sau đây không phải là special file (tệp đặc biệt)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q1.png",
          "options": [
            {
              "text": "Character special file|||Character special file (tệp đặc biệt theo ký tự)"
            },
            {
              "text": "Stream special file|||Stream special file (tệp đặc biệt dạng luồng)"
            },
            {
              "text": "Block special file|||Block special file (tệp đặc biệt theo khối)"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Unix/Linux only defines two kinds of special files: character special files and block special files. &#39;Stream special file&#39; is not a standard special-file type in this course&#39;s terminology.</p></div><div class=\"ml-vi\"><p>Trong Unix/Linux chỉ có hai loại tệp đặc biệt: character special file và block special file. &#39;Stream special file&#39; không phải là loại tệp đặc biệt chuẩn được dạy trong môn học.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Critical Region (Section) concept used in interprocess communication is:</p></div><div class=\"ml-vi\"><p>Khái niệm Critical Region (Miền găng) dùng trong giao tiếp liên tiến trình là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q2.png",
          "options": [
            {
              "text": "A part of the program where the shared memory is accessed|||Phần của chương trình nơi bộ nhớ dùng chung được truy cập"
            },
            {
              "text": "A part of shared data|||Một phần của dữ liệu dùng chung"
            },
            {
              "text": "A part of shared memory|||Một phần của bộ nhớ dùng chung"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>A critical section/region is defined as the segment of a process&#39;s code where shared resources (shared memory) are accessed, not the data or memory itself.</p></div><div class=\"ml-vi\"><p>Miền găng (critical section) là đoạn mã của tiến trình nơi tài nguyên dùng chung (bộ nhớ chia sẻ) được truy cập, chứ không phải bản thân dữ liệu hay bộ nhớ.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>How much cylinder skew is needed for a 5400-RPM (rotate per minute) disk with the track-to-track seek time of 1 msec? The disk has 200 sectors of 512 bytes on each track.</p></div><div class=\"ml-vi\"><p>Cần bao nhiêu cylinder skew cho một đĩa quay 5400 vòng/phút với thời gian seek giữa hai track liền kề là 1 msec? Đĩa có 200 sector, mỗi sector 512 byte trên mỗi track.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q3.png",
          "options": [
            {
              "text": "24 sectors|||24 sector"
            },
            {
              "text": "12 sectors|||12 sector"
            },
            {
              "text": "18 sectors|||18 sector"
            },
            {
              "text": "36 sectors|||36 sector"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Rotation time = 60/5400 s = 11.111 ms. Time per sector = 11.111/200 = 0.05556 ms. Cylinder skew (in sectors) = seek time / time per sector = 1 / 0.05556 ≈ 18 sectors.</p></div><div class=\"ml-vi\"><p>Thời gian quay 1 vòng = 60/5400 = 11,111 ms. Thời gian mỗi sector = 11,111/200 = 0,05556 ms. Cylinder skew (số sector) = thời gian seek / thời gian mỗi sector = 1/0,05556 ≈ 18 sector.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>One of way to prevent deadlock is __________</p></div><div class=\"ml-vi\"><p>Một trong những cách để ngăn ngừa (prevent) deadlock là __________</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q4.png",
          "options": [
            {
              "text": "Spool everything|||Spool mọi thứ (đưa tất cả vào hàng đợi spool)"
            },
            {
              "text": "Rollback|||Rollback (khôi phục trạng thái trước đó)"
            },
            {
              "text": "Kills one of the processes|||Kết thúc (kill) một trong các tiến trình"
            },
            {
              "text": "Locks one of the processes|||Khoá một trong các tiến trình"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Spooling everything (e.g. for printers) eliminates the mutual-exclusion condition for that resource, which is a classic deadlock-prevention technique (Tanenbaum). Rollback and killing a process are deadlock recovery techniques, not prevention.</p></div><div class=\"ml-vi\"><p>Spool mọi thứ (ví dụ với máy in) loại bỏ điều kiện loại trừ lẫn nhau (mutual exclusion) đối với tài nguyên đó — đây là kỹ thuật ngăn ngừa deadlock kinh điển (Tanenbaum). Rollback và kill tiến trình là kỹ thuật khôi phục (recovery) sau deadlock, không phải ngăn ngừa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which ways are used to keep track of free block in disk space management?</p></div><div class=\"ml-vi\"><p>Những cách nào được dùng để theo dõi các block trống trong quản lý không gian đĩa?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q5.png",
          "options": [
            {
              "text": "A linked list method|||Phương pháp danh sách liên kết (linked list)"
            },
            {
              "text": "A bitmap method|||Phương pháp bản đồ bit (bitmap)"
            },
            {
              "text": "Both linked list method and bitmap method|||Cả hai phương pháp danh sách liên kết và bitmap"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Both the linked-list of free blocks and the bitmap method are standard techniques used by real file systems to track free disk blocks.</p></div><div class=\"ml-vi\"><p>Cả danh sách liên kết các block trống lẫn phương pháp bitmap đều là các kỹ thuật chuẩn được các hệ thống tệp thực tế dùng để theo dõi block trống.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of following statements about the memory hierarchy is false?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây về phân cấp bộ nhớ (memory hierarchy) là SAI?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q6.png",
          "options": [
            {
              "text": "Small amount of fast expensive memory - cache|||Một lượng nhỏ bộ nhớ nhanh, đắt tiền - cache"
            },
            {
              "text": "Some medium-speed medium price main memory|||Một lượng bộ nhớ chính tốc độ trung bình, giá trung bình"
            },
            {
              "text": "Gigabytes of slow cheap disk storage|||Hàng gigabyte lưu trữ đĩa chậm, rẻ"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>All three statements (A, B, C) are accurate textbook descriptions of the memory hierarchy (cache: small/fast/expensive; main memory: medium; disk: large/slow/cheap), so none of them is false — the answer is D.</p></div><div class=\"ml-vi\"><p>Cả ba phát biểu A, B, C đều đúng theo mô tả kinh điển về phân cấp bộ nhớ (cache: nhỏ/nhanh/đắt; bộ nhớ chính: trung bình; đĩa: lớn/chậm/rẻ), nên không phát biểu nào trong số đó là sai — đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Semaphores that are initialized to 1 and used for two or more processes to ensure only one enters critical section at the same time are called:</p></div><div class=\"ml-vi\"><p>Semaphore được khởi tạo bằng 1 và dùng cho hai hay nhiều tiến trình để đảm bảo chỉ một tiến trình vào miền găng tại một thời điểm được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q7.png",
          "options": [
            {
              "text": "Binary semaphores|||Binary semaphore (semaphore nhị phân)"
            },
            {
              "text": "Integer semaphores|||Integer semaphore (semaphore số nguyên)"
            },
            {
              "text": "Counter semaphores|||Counter semaphore (semaphore đếm)"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>A semaphore initialized to 1 and toggling only between 0 and 1 for mutual exclusion is by definition a binary semaphore.</p></div><div class=\"ml-vi\"><p>Semaphore được khởi tạo bằng 1 và chỉ chuyển đổi giữa 0 và 1 để đảm bảo loại trừ lẫn nhau chính là binary semaphore theo định nghĩa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is not an operating mode of CPU?</p></div><div class=\"ml-vi\"><p>Chế độ nào sau đây không phải là chế độ hoạt động của CPU?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q8.png",
          "options": [
            {
              "text": "User mode|||User mode (chế độ người dùng)"
            },
            {
              "text": "Kernel mode|||Kernel mode (chế độ nhân)"
            },
            {
              "text": "Management mode|||Management mode (chế độ quản lý)"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>The CPU has exactly two operating modes: user mode and kernel mode. &#39;Management mode&#39; is not a real CPU mode.</p></div><div class=\"ml-vi\"><p>CPU chỉ có đúng hai chế độ hoạt động: user mode và kernel mode. &#39;Management mode&#39; không phải là một chế độ CPU có thật.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following information bits in the entry of page table is false?</p></div><div class=\"ml-vi\"><p>Bit thông tin nào sau đây trong entry của bảng trang (page table) là SAI (không tồn tại)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q9.png",
          "options": [
            {
              "text": "Present/absent bit|||Bit Present/absent (có mặt/vắng mặt)"
            },
            {
              "text": "Mode bit|||Bit Mode (chế độ)"
            },
            {
              "text": "Protection bit|||Bit Protection (bảo vệ)"
            },
            {
              "text": "Modified bit|||Bit Modified (đã sửa đổi)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Standard page table entry fields include present/absent, protection, modified (dirty), referenced, and caching-disabled bits. &#39;Mode bit&#39; is not a page table entry field — it belongs to the CPU/PSW, not the page table.</p></div><div class=\"ml-vi\"><p>Các trường chuẩn trong entry bảng trang gồm: present/absent, protection, modified (dirty), referenced, caching-disabled. &#39;Mode bit&#39; không phải là trường của bảng trang — nó thuộc về CPU/PSW.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A computer has 2GB RAM of which the operating system occupies 1GB.<br/>The processes are all 450 MB and have the same characteristics. How many percent of the wasted, when these programs are idle waiting for I/O 20% of the time?</p></div><div class=\"ml-vi\"><p>Một máy tính có 2GB RAM, trong đó hệ điều hành chiếm 1GB.<br/>Các tiến trình đều có kích thước 450 MB và có đặc tính giống nhau. Có bao nhiêu phần trăm thời gian CPU bị lãng phí, khi các chương trình này rảnh rỗi chờ I/O 20% thời gian?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q10.png",
          "options": [
            {
              "text": "90%|||90%"
            },
            {
              "text": "96%|||96%"
            },
            {
              "text": "4%|||4%"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Available memory for processes = 2GB - 1GB = 1024MB. Degree of multiprogramming n = floor(1024/450) = 2. CPU utilization = 1 - p^n = 1 - 0.2^2 = 0.96 = 96%. Wasted CPU time = 1 - 0.96 = 4%.</p></div><div class=\"ml-vi\"><p>Bộ nhớ khả dụng cho tiến trình = 2GB - 1GB = 1024MB. Bậc đa chương n = floor(1024/450) = 2. Hiệu suất CPU = 1 - p^n = 1 - 0,2^2 = 0,96 = 96%. Thời gian CPU lãng phí = 1 - 0,96 = 4%.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following I/O software do Device drivers do?</p></div><div class=\"ml-vi\"><p>Phần mềm I/O nào sau đây thuộc về Device driver (trình điều khiển thiết bị)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q11.png",
          "options": [
            {
              "text": "Converting binary integers to ASCII for printing|||Chuyển đổi số nguyên nhị phân sang ASCII để in"
            },
            {
              "text": "Writing commands to the device registers|||Ghi lệnh vào các thanh ghi thiết bị"
            },
            {
              "text": "Checking to see if the user is permitted to use the device|||Kiểm tra xem người dùng có được phép sử dụng thiết bị hay không"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Device drivers directly control hardware by writing commands to device registers. Converting binary to ASCII is device-independent I/O software; permission checking is done by the OS kernel layer above the driver.</p></div><div class=\"ml-vi\"><p>Device driver điều khiển trực tiếp phần cứng bằng cách ghi lệnh vào các thanh ghi thiết bị. Việc chuyển đổi nhị phân sang ASCII thuộc phần mềm I/O độc lập thiết bị; kiểm tra quyền do lớp nhân OS phía trên driver thực hiện.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>What is not correct about system calls?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG đúng về system call?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q12.png",
          "options": [
            {
              "text": "A system call allows a user process to access and execute operating system functions in kernel|||System call cho phép tiến trình người dùng truy cập và thực thi các hàm của hệ điều hành trong nhân"
            },
            {
              "text": "User programs use system calls to invoke operating system services|||Chương trình người dùng dùng system call để gọi các dịch vụ của hệ điều hành"
            },
            {
              "text": "In terms of performance, using system calls is better than using procedure calls|||Về mặt hiệu năng, dùng system call tốt hơn dùng lời gọi hàm (procedure call) thông thường"
            },
            {
              "text": "Every system call involves overhead due to context switch|||Mỗi system call đều có chi phí phụ trội (overhead) do chuyển ngữ cảnh (context switch)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>System calls are actually slower than ordinary procedure calls because they must trap into kernel mode and involve a context switch, so claiming system calls are &#39;better&#39; performance-wise is incorrect.</p></div><div class=\"ml-vi\"><p>System call thực chất chậm hơn lời gọi hàm thông thường vì phải bẫy (trap) vào chế độ kernel và có chuyển ngữ cảnh, nên khẳng định system call &#39;tốt hơn&#39; về hiệu năng là sai.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>_____ are special files with listings of filenames and their attributes.</p></div><div class=\"ml-vi\"><p>_____ là những tệp đặc biệt chứa danh sách tên tệp và thuộc tính của chúng.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q13.png",
          "options": [
            {
              "text": "Databases|||Cơ sở dữ liệu (Databases)"
            },
            {
              "text": "Directories|||Thư mục (Directories)"
            },
            {
              "text": "Programs|||Chương trình (Programs)"
            },
            {
              "text": "Data files|||Tệp dữ liệu (Data files)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Directories are special files that store filenames together with their attributes/metadata.</p></div><div class=\"ml-vi\"><p>Thư mục (directory) là các tệp đặc biệt lưu trữ tên tệp cùng với thuộc tính/metadata của chúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which is a wrong statement about the quantum used in Round Robin algorithm?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây là SAI về quantum dùng trong giải thuật Round Robin?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q14.png",
          "options": [
            {
              "text": "If the quantum is very large, RR is essentially FCFS|||Nếu quantum rất lớn, RR về cơ bản trở thành FCFS"
            },
            {
              "text": "If the quantum is very small, the CPU efficiency is reduced|||Nếu quantum rất nhỏ, hiệu suất CPU bị giảm"
            },
            {
              "text": "A reasonable value of quantum is around 20-50 msec|||Giá trị quantum hợp lý là khoảng 20-50 msec"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>All three statements (A, B, C) are standard, correct facts about Round Robin quantum from the textbook (Tanenbaum), so none of them is wrong — the answer is D.</p></div><div class=\"ml-vi\"><p>Cả ba phát biểu A, B, C đều là những sự thật chuẩn, đúng về quantum trong Round Robin theo giáo trình (Tanenbaum), nên không phát biểu nào sai — đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>File Structure can be:</p></div><div class=\"ml-vi\"><p>Cấu trúc tệp (File Structure) có thể là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q15.png",
          "options": [
            {
              "text": "Byte sequence|||Chuỗi byte (Byte sequence)"
            },
            {
              "text": "Record sequence|||Chuỗi bản ghi (Record sequence)"
            },
            {
              "text": "Tree|||Cây (Tree)"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Tanenbaum describes three classic file structures: an unstructured byte sequence, a sequence of fixed-length records, and a tree of records (indexed). All three are valid, so the answer is D.</p></div><div class=\"ml-vi\"><p>Theo Tanenbaum có ba cấu trúc tệp kinh điển: chuỗi byte không cấu trúc, chuỗi bản ghi độ dài cố định, và cây bản ghi (có chỉ mục). Cả ba đều đúng nên đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A computer uses a programmable clock in square-wave mode. If 500 MHz crystal is used, what value should be loaded into the holding register to achieve a clock resolution of 100 micro-secs (Clock tick)?</p></div><div class=\"ml-vi\"><p>Một máy tính dùng đồng hồ lập trình được ở chế độ sóng vuông. Nếu dùng thạch anh 500 MHz, cần nạp giá trị nào vào thanh ghi giữ (holding register) để đạt độ phân giải đồng hồ 100 micro giây (một tick)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q16.png",
          "options": [
            {
              "text": "500,000|||500.000"
            },
            {
              "text": "50,000|||50.000"
            },
            {
              "text": "5,000,000|||5.000.000"
            },
            {
              "text": "50,000,000|||50.000.000"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Crystal frequency = 500,000,000 cycles/sec. Number of crystal cycles per tick = 500,000,000 × 100×10⁻⁶ s = 50,000. This is the value loaded into the holding register.</p></div><div class=\"ml-vi\"><p>Tần số thạch anh = 500.000.000 chu kỳ/giây. Số chu kỳ thạch anh mỗi tick = 500.000.000 × 100×10⁻⁶ s = 50.000. Đây là giá trị nạp vào thanh ghi giữ.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which is not a goal of a scheduling algorithm for batch systems?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây không phải là mục tiêu của giải thuật định thời cho hệ thống batch?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q17.png",
          "options": [
            {
              "text": "CPU utilization|||Hiệu suất sử dụng CPU (CPU utilization)"
            },
            {
              "text": "Throughput|||Thông lượng (Throughput)"
            },
            {
              "text": "Turnaround time|||Thời gian hoàn thành (Turnaround time)"
            },
            {
              "text": "Response time|||Thời gian đáp ứng (Response time)"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Batch system scheduling goals are CPU utilization, throughput, and turnaround time. Response time is a goal specific to interactive systems, not batch systems.</p></div><div class=\"ml-vi\"><p>Mục tiêu định thời cho hệ batch gồm: hiệu suất CPU, thông lượng, thời gian hoàn thành. Thời gian đáp ứng (response time) là mục tiêu riêng của hệ tương tác, không phải hệ batch.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>As one proceeds down the memory hierarchy (from inboard memory to offline storage), which of the following conditions is correct?</p></div><div class=\"ml-vi\"><p>Khi đi xuống dần trong phân cấp bộ nhớ (từ bộ nhớ trong đến lưu trữ ngoại tuyến), điều kiện nào sau đây là đúng?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q18.png",
          "options": [
            {
              "text": "Increasing cost per bit|||Chi phí trên mỗi bit tăng dần"
            },
            {
              "text": "Decreasing capacity|||Dung lượng giảm dần"
            },
            {
              "text": "Increasing access time|||Thời gian truy cập tăng dần"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Going down the memory hierarchy (cache → main memory → disk → offline storage): cost per bit decreases, capacity increases, and access time increases (gets slower). Only &#39;increasing access time&#39; is correct.</p></div><div class=\"ml-vi\"><p>Đi xuống phân cấp bộ nhớ (cache → bộ nhớ chính → đĩa → lưu trữ ngoại tuyến): chi phí trên bit giảm dần, dung lượng tăng dần, và thời gian truy cập tăng dần (chậm hơn). Chỉ &#39;thời gian truy cập tăng dần&#39; là đúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A computer has 2GB RAM of which the operating system occupies 1GB.<br/>The processes are all 450 MB and have the same characteristics. How many percent is CPU [utilized], when these programs are idle waiting for I/O 20% of the time?</p></div><div class=\"ml-vi\"><p>Một máy tính có 2GB RAM, trong đó hệ điều hành chiếm 1GB.<br/>Các tiến trình đều có kích thước 450 MB và có đặc tính giống nhau. CPU được sử dụng bao nhiêu phần trăm, khi các chương trình này rảnh rỗi chờ I/O 20% thời gian?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q19.png",
          "options": [
            {
              "text": "90%|||90%"
            },
            {
              "text": "96%|||96%"
            },
            {
              "text": "4%|||4%"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Same setup as question 10 but asking for CPU utilization instead of wasted time: degree of multiprogramming n = floor(1024/450) = 2; CPU utilization = 1 - 0.2^2 = 96%.</p></div><div class=\"ml-vi\"><p>Giống thiết lập câu 10 nhưng hỏi hiệu suất sử dụng CPU thay vì phần lãng phí: bậc đa chương n = floor(1024/450) = 2; hiệu suất CPU = 1 - 0,2^2 = 96%.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which approach is used in order to CPU communicate with the control registers of the I/O device?</p></div><div class=\"ml-vi\"><p>Cách tiếp cận nào được dùng để CPU giao tiếp với các thanh ghi điều khiển của thiết bị I/O?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q20.png",
          "options": [
            {
              "text": "Separating I/O and memory space|||Tách biệt không gian I/O và bộ nhớ"
            },
            {
              "text": "Memory-mapped I/O|||I/O ánh xạ bộ nhớ (Memory-mapped I/O)"
            },
            {
              "text": "Hybrid: separating I/O and memory space and memory-mapped I/O|||Lai (Hybrid): kết hợp tách biệt không gian I/O/bộ nhớ và memory-mapped I/O"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Tanenbaum describes all three schemes (separate I/O space, memory-mapped I/O, and hybrid) as approaches actually used by different real computer architectures — the answer is D.</p></div><div class=\"ml-vi\"><p>Theo Tanenbaum, cả ba phương án (không gian I/O riêng, memory-mapped I/O, và lai) đều là các cách tiếp cận thực sự được các kiến trúc máy tính khác nhau sử dụng — đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following file structure is used if the file includes set of fixed-length record?</p></div><div class=\"ml-vi\"><p>Cấu trúc tệp nào sau đây được dùng nếu tệp gồm tập hợp các bản ghi có độ dài cố định?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q21.png",
          "options": [
            {
              "text": "Byte sequence|||Chuỗi byte (Byte sequence)"
            },
            {
              "text": "Record sequence|||Chuỗi bản ghi (Record sequence)"
            },
            {
              "text": "Ring|||Vòng (Ring)"
            },
            {
              "text": "Tree|||Cây (Tree)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>A file organized as a set of fixed-length records is, by definition, the record-sequence file structure.</p></div><div class=\"ml-vi\"><p>Tệp được tổ chức thành tập hợp các bản ghi có độ dài cố định chính là cấu trúc tệp chuỗi bản ghi (record sequence) theo định nghĩa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following statements about the task of device controller of I/O devices is correct?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây về nhiệm vụ của bộ điều khiển thiết bị (device controller) của thiết bị I/O là đúng?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q22.png",
          "options": [
            {
              "text": "Convert serial bit stream to block of bytes|||Chuyển đổi luồng bit nối tiếp thành khối byte"
            },
            {
              "text": "Perform error correction as necessary|||Thực hiện sửa lỗi khi cần thiết"
            },
            {
              "text": "Make available to main memory|||Chuyển dữ liệu vào bộ nhớ chính"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>All three tasks (converting serial bit stream to bytes, error correction, and making data available to main memory) are standard functions of an I/O device controller according to Tanenbaum.</p></div><div class=\"ml-vi\"><p>Cả ba nhiệm vụ (chuyển luồng bit nối tiếp thành byte, sửa lỗi, và đưa dữ liệu vào bộ nhớ chính) đều là chức năng chuẩn của bộ điều khiển thiết bị I/O theo Tanenbaum.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>List of memory locations that contains the executable program, the program&#39;s data, and its stack, is called:</p></div><div class=\"ml-vi\"><p>Danh sách các vị trí bộ nhớ chứa chương trình thực thi, dữ liệu của chương trình, và ngăn xếp (stack) của nó được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q23.png",
          "options": [
            {
              "text": "Set of resources|||Tập hợp tài nguyên (Set of resources)"
            },
            {
              "text": "Address space|||Không gian địa chỉ (Address space)"
            },
            {
              "text": "Address memory|||Bộ nhớ địa chỉ (Address memory)"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The set of memory locations containing a process&#39;s executable program, data, and stack is called its address space.</p></div><div class=\"ml-vi\"><p>Tập hợp các vị trí bộ nhớ chứa chương trình thực thi, dữ liệu và stack của một tiến trình được gọi là không gian địa chỉ (address space).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A page fault means that we referenced a page:</p></div><div class=\"ml-vi\"><p>Page fault (lỗi trang) nghĩa là ta đã tham chiếu tới một trang:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q24.png",
          "options": [
            {
              "text": "That was outside the memory boundaries|||Nằm ngoài giới hạn bộ nhớ"
            },
            {
              "text": "With an incorrect I/O request|||Có yêu cầu I/O không hợp lệ"
            },
            {
              "text": "That was not in secondary storage|||Không nằm trong bộ nhớ phụ (secondary storage)"
            },
            {
              "text": "That was not in main memory|||Không nằm trong bộ nhớ chính (main memory)"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>A page fault occurs when a process references a valid virtual page that is currently not present (loaded) in main/physical memory, requiring it to be fetched from disk.</p></div><div class=\"ml-vi\"><p>Page fault xảy ra khi tiến trình tham chiếu tới một trang ảo hợp lệ nhưng hiện không có mặt (chưa được nạp) trong bộ nhớ chính, buộc phải nạp trang đó từ đĩa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following Operating System does not implement multitasking truly?</p></div><div class=\"ml-vi\"><p>Hệ điều hành nào sau đây không thực sự triển khai đa nhiệm (multitasking)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q25.png",
          "options": [
            {
              "text": "Linux|||Linux"
            },
            {
              "text": "Windows NT|||Windows NT"
            },
            {
              "text": "Windows XP|||Windows XP"
            },
            {
              "text": "MS DOS|||MS DOS"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>MS-DOS is a single-tasking operating system and does not truly support multitasking, unlike Linux, Windows NT, and Windows XP, which are all preemptive multitasking systems.</p></div><div class=\"ml-vi\"><p>MS-DOS là hệ điều hành đơn nhiệm, không thực sự hỗ trợ đa nhiệm, khác với Linux, Windows NT, và Windows XP đều là các hệ đa nhiệm ưu tiên (preemptive multitasking).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A disk queue with requests for I/O to blocks on cylinders in order: 10, 22, 20, 2, 40, 6, 38. Assume that the disk head is initially at cylinder 37. Which is the ordering of cylinders to service using an elevator algorithm?</p></div><div class=\"ml-vi\"><p>Hàng đợi đĩa có yêu cầu I/O tới các block trên các cylinder theo thứ tự: 10, 22, 20, 2, 40, 6, 38. Giả sử đầu đọc đĩa ban đầu ở cylinder 37. Thứ tự phục vụ các cylinder theo giải thuật elevator (thang máy) là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q26.png",
          "options": [
            {
              "text": "37 38 40 2 6 10 20 22|||37 38 40 2 6 10 20 22"
            },
            {
              "text": "37 38 40 22 20 10 6 2|||37 38 40 22 20 10 6 2"
            },
            {
              "text": "37 10 22 20 2 40 6 38|||37 10 22 20 2 40 6 38"
            },
            {
              "text": "37 38 40 2 20 10 6 22|||37 38 40 2 20 10 6 22"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Starting at 37, moving upward first services 38, then 40 (nothing higher). Then the head reverses direction and services the remaining requests in decreasing order: 22, 20, 10, 6, 2. This matches option B: 37 38 40 22 20 10 6 2 (a correct SCAN/elevator sweep).</p></div><div class=\"ml-vi\"><p>Bắt đầu từ 37, di chuyển lên trước sẽ phục vụ 38, rồi 40 (không còn gì cao hơn). Sau đó đầu đọc đảo chiều và phục vụ các yêu cầu còn lại theo thứ tự giảm dần: 22, 20, 10, 6, 2. Khớp với đáp án B: 37 38 40 22 20 10 6 2 (đúng theo giải thuật SCAN/elevator).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A table in main memory storing linked list of allocation of disk blocks is called:</p></div><div class=\"ml-vi\"><p>Một bảng trong bộ nhớ chính lưu trữ danh sách liên kết cấp phát các block đĩa được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q27.png",
          "options": [
            {
              "text": "Disk allocation table|||Bảng cấp phát đĩa (Disk allocation table)"
            },
            {
              "text": "Linked list table|||Bảng danh sách liên kết (Linked list table)"
            },
            {
              "text": "File list table|||Bảng danh sách tệp (File list table)"
            },
            {
              "text": "File allocation table|||Bảng cấp phát tệp (File allocation table)"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>This describes the File Allocation Table (FAT), an in-memory table that keeps a linked-list-style chain of disk block allocations for each file.</p></div><div class=\"ml-vi\"><p>Đây là mô tả của File Allocation Table (FAT) — bảng trong bộ nhớ lưu chuỗi liên kết các block đĩa được cấp phát cho mỗi tệp.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Assume jobs A-D arrive at almost the same time in the READY queue. Determine the average [turnaround time] for Round Robin scheduling (quantum=2). Ignore process switching overhead.<br/>Job: A B C D<br/>CPU cycle: 5 2 6 4</p></div><div class=\"ml-vi\"><p>Giả sử các job A-D đến hàng đợi READY gần như cùng lúc. Tính thời gian hoàn thành (turnaround time) trung bình cho giải thuật Round Robin (quantum=2). Bỏ qua chi phí chuyển đổi tiến trình.<br/>Job: A B C D<br/>Chu kỳ CPU: 5 2 6 4</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q28.png",
          "options": [
            {
              "text": "5.5|||5,5"
            },
            {
              "text": "12.5|||12,5"
            },
            {
              "text": "9.0|||9,0"
            },
            {
              "text": "10.5|||10,5"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Simulating RR with quantum=2, queue order A,B,C,D: A runs 0-2 (rem 3, requeue), B runs 2-4 (done, TAT=4), C runs 4-6 (rem 4), D runs 6-8 (rem 2), A runs 8-10 (rem 1), C runs 10-12 (rem 2), D runs 12-14 (done, TAT=14), A runs 14-15 (done, TAT=15), C runs 15-17 (done, TAT=17). Average = (15+4+17+14)/4 = 50/4 = 12.5.</p></div><div class=\"ml-vi\"><p>Mô phỏng RR với quantum=2, thứ tự hàng đợi A,B,C,D: A chạy 0-2 (còn 3, vào lại hàng đợi), B chạy 2-4 (xong, TAT=4), C chạy 4-6 (còn 4), D chạy 6-8 (còn 2), A chạy 8-10 (còn 1), C chạy 10-12 (còn 2), D chạy 12-14 (xong, TAT=14), A chạy 14-15 (xong, TAT=15), C chạy 15-17 (xong, TAT=17). Trung bình = (15+4+17+14)/4 = 50/4 = 12,5.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>The Linking technique that allows the file to appear in more than one directory are:</p></div><div class=\"ml-vi\"><p>Kỹ thuật liên kết (Linking) cho phép một tệp xuất hiện ở nhiều hơn một thư mục là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q29.png",
          "options": [
            {
              "text": "Hard link|||Hard link (liên kết cứng)"
            },
            {
              "text": "Symbolic link|||Symbolic link (liên kết mềm/tượng trưng)"
            },
            {
              "text": "Both hard link and symbolic link|||Cả hard link và symbolic link"
            },
            {
              "text": "Soft link|||Soft link (liên kết mềm)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Both hard links (multiple directory entries pointing to the same inode) and symbolic links (pointer files to a path) allow the same file to appear in more than one directory, so the answer is C.</p></div><div class=\"ml-vi\"><p>Cả hard link (nhiều mục thư mục cùng trỏ tới một inode) và symbolic link (tệp trỏ tới một đường dẫn) đều cho phép cùng một tệp xuất hiện ở nhiều thư mục, nên đáp án là C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>How many level of scheduling are used in computer?</p></div><div class=\"ml-vi\"><p>Có bao nhiêu mức định thời (level of scheduling) được sử dụng trong máy tính?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q30.png",
          "options": [
            {
              "text": "1|||1"
            },
            {
              "text": "2|||2"
            },
            {
              "text": "3|||3"
            },
            {
              "text": "4|||4"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Standard OS theory (Silberschatz) describes three levels of scheduling: long-term (job) scheduling, medium-term scheduling, and short-term (CPU) scheduling.</p></div><div class=\"ml-vi\"><p>Theo lý thuyết hệ điều hành chuẩn (Silberschatz), có ba mức định thời: định thời dài hạn (long-term), định thời trung hạn (medium-term), và định thời ngắn hạn (short-term, định thời CPU).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>The ways that input/output can be done is?</p></div><div class=\"ml-vi\"><p>Các cách mà thao tác input/output có thể được thực hiện là?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q31.png",
          "options": [
            {
              "text": "Busy waiting|||Busy waiting (chờ bận)"
            },
            {
              "text": "Interrupt|||Interrupt (ngắt)"
            },
            {
              "text": "DMA (Direct Memory Access)|||DMA (Truy cập bộ nhớ trực tiếp)"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>I/O can be performed in three classic ways: programmed I/O (busy waiting), interrupt-driven I/O, and DMA. All three are valid, so the answer is D.</p></div><div class=\"ml-vi\"><p>I/O có thể thực hiện theo ba cách kinh điển: I/O lập trình (busy waiting), I/O điều khiển bằng ngắt, và DMA. Cả ba đều đúng nên đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>What is the table where its entry contains the memory address of Interrupt service routine?</p></div><div class=\"ml-vi\"><p>Bảng nào mà mỗi entry của nó chứa địa chỉ bộ nhớ của thường trình phục vụ ngắt (Interrupt Service Routine)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q32.png",
          "options": [
            {
              "text": "Interrupt vector table|||Bảng vector ngắt (Interrupt vector table)"
            },
            {
              "text": "Interrupt table|||Bảng ngắt (Interrupt table)"
            },
            {
              "text": "Address table|||Bảng địa chỉ (Address table)"
            },
            {
              "text": "Address lines table|||Bảng đường dây địa chỉ (Address lines table)"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>The interrupt vector table stores the memory addresses of each interrupt service routine (ISR), indexed by interrupt number.</p></div><div class=\"ml-vi\"><p>Bảng vector ngắt (interrupt vector table) lưu trữ địa chỉ bộ nhớ của từng thường trình phục vụ ngắt (ISR), được đánh chỉ mục theo số hiệu ngắt.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>What is the way to recover from a deadlock:</p></div><div class=\"ml-vi\"><p>Cách nào để khôi phục (recover) sau một deadlock:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q33.png",
          "options": [
            {
              "text": "Preempt a resource|||Chiếm quyền lại tài nguyên (Preempt a resource)"
            },
            {
              "text": "Rollback|||Rollback (khôi phục về trạng thái trước)"
            },
            {
              "text": "Killing processes|||Kết thúc (kill) các tiến trình"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Standard deadlock recovery techniques include resource preemption, process rollback (checkpointing), and killing one or more processes. All three are valid, so the answer is D.</p></div><div class=\"ml-vi\"><p>Các kỹ thuật khôi phục sau deadlock chuẩn gồm: chiếm quyền lại tài nguyên, rollback tiến trình (dùng checkpoint), và kill một hoặc nhiều tiến trình. Cả ba đều đúng nên đáp án là D.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Typical approaches to handle deadlocks do not include</p></div><div class=\"ml-vi\"><p>Các cách tiếp cận điển hình để xử lý deadlock KHÔNG bao gồm</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q34.png",
          "options": [
            {
              "text": "Prevention|||Ngăn ngừa (Prevention)"
            },
            {
              "text": "Detection|||Phát hiện (Detection)"
            },
            {
              "text": "Deterrence|||Răn đe (Deterrence)"
            },
            {
              "text": "Avoidance|||Tránh né (Avoidance)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>The standard textbook approaches to handling deadlock are prevention, avoidance, and detection (with recovery), plus ignoring it (ostrich algorithm). &#39;Deterrence&#39; is not one of the standard terms.</p></div><div class=\"ml-vi\"><p>Các cách tiếp cận chuẩn theo giáo trình để xử lý deadlock là: ngăn ngừa (prevention), tránh né (avoidance), và phát hiện (detection, kèm khôi phục), cộng với bỏ qua (giải thuật đà điểu). &#39;Deterrence&#39; (răn đe) không phải là thuật ngữ chuẩn.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>The four main structural elements of a computer system are:</p></div><div class=\"ml-vi\"><p>Bốn thành phần cấu trúc chính của một hệ thống máy tính là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q35.png",
          "options": [
            {
              "text": "Processor, Registers, I/O Modules, Main Memory|||Bộ xử lý, Thanh ghi, Mô-đun I/O, Bộ nhớ chính"
            },
            {
              "text": "Processor, Registers, Main Memory, System Bus|||Bộ xử lý, Thanh ghi, Bộ nhớ chính, Bus hệ thống"
            },
            {
              "text": "Processor, Main Memory, I/O Modules, System Bus|||Bộ xử lý, Bộ nhớ chính, Mô-đun I/O, Bus hệ thống"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Per Stallings&#39; top-level computer system model, the four main structural elements are: Processor (CPU), Main Memory, I/O Modules, and System Bus (interconnection) — matching option C.</p></div><div class=\"ml-vi\"><p>Theo mô hình hệ thống máy tính cấp cao của Stallings, bốn thành phần cấu trúc chính là: Bộ xử lý (CPU), Bộ nhớ chính, Mô-đun I/O, và Bus hệ thống (kết nối) — khớp với đáp án C.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Where is the position of the operating system in computer system:</p></div><div class=\"ml-vi\"><p>Vị trí của hệ điều hành trong hệ thống máy tính nằm ở đâu:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q36.png",
          "options": [
            {
              "text": "Above the hardware and under the user interface program|||Phía trên phần cứng và phía dưới chương trình giao diện người dùng"
            },
            {
              "text": "Between the user interface program and the application Program|||Giữa chương trình giao diện người dùng và chương trình ứng dụng"
            },
            {
              "text": "In user space|||Trong không gian người dùng (user space)"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>In the standard layered model (Tanenbaum), the OS sits directly on top of the hardware and below all user-level programs, including the user interface (shell) and application programs.</p></div><div class=\"ml-vi\"><p>Theo mô hình phân lớp chuẩn (Tanenbaum), hệ điều hành nằm ngay trên phần cứng và phía dưới tất cả các chương trình mức người dùng, kể cả giao diện người dùng (shell) và chương trình ứng dụng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>The aspect of disk performance that represents the time it takes to position the head at the desired cylinder is known as</p></div><div class=\"ml-vi\"><p>Khía cạnh của hiệu năng đĩa thể hiện thời gian cần để định vị đầu đọc tới cylinder mong muốn được gọi là</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q37.png",
          "options": [
            {
              "text": "Seek time|||Thời gian tìm kiếm (Seek time)"
            },
            {
              "text": "Rotational delay|||Độ trễ quay (Rotational delay)"
            },
            {
              "text": "Access time|||Thời gian truy cập (Access time)"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Seek time is specifically defined as the time to move the disk head to the desired cylinder/track. Rotational delay is the additional wait for the sector to rotate under the head; access time = seek time + rotational delay.</p></div><div class=\"ml-vi\"><p>Seek time được định nghĩa cụ thể là thời gian để di chuyển đầu đọc đến cylinder/track mong muốn. Rotational delay là thời gian chờ thêm để sector quay tới dưới đầu đọc; access time = seek time + rotational delay.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>A computer with a 32-bit address uses a two-level page table. Virtual addresses are split into a 9-bit first-level page table field, an 11-bit second-level page table field, and an offset. How many pages are there in the virtual address space?</p></div><div class=\"ml-vi\"><p>Một máy tính dùng địa chỉ 32-bit và bảng trang hai cấp. Địa chỉ ảo được chia thành trường bảng trang cấp một 9-bit, trường bảng trang cấp hai 11-bit, và một phần offset. Có bao nhiêu trang trong không gian địa chỉ ảo?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q38.png",
          "options": [
            {
              "text": "2^20 pages|||2^20 trang"
            },
            {
              "text": "2^21 pages|||2^21 trang"
            },
            {
              "text": "2^22 pages|||2^22 trang"
            },
            {
              "text": "2^23 pages|||2^23 trang"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>This is the classic Tanenbaum two-level page table exercise: first-level field = 9 bits, second-level field = 11 bits (offset = 32-9-11 = 12 bits, i.e. 4KB pages). Total page-number bits = 9+11 = 20, so the number of pages in the virtual address space = 2^20.</p></div><div class=\"ml-vi\"><p>Đây là bài tập bảng trang hai cấp kinh điển của Tanenbaum: trường cấp một = 9 bit, trường cấp hai = 11 bit (offset = 32-9-11 = 12 bit, tức trang 4KB). Tổng số bit số hiệu trang = 9+11 = 20, nên số trang trong không gian địa chỉ ảo = 2^20.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following process state transitions is correct, when the external event for which waiting happens?</p></div><div class=\"ml-vi\"><p>Chuyển trạng thái tiến trình nào sau đây là đúng, khi sự kiện bên ngoài mà tiến trình đang đợi xảy ra?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q39.png",
          "options": [
            {
              "text": "Running -&gt; Blocked (waiting)|||Đang chạy (Running) -&gt; Bị chặn (Blocked/waiting)"
            },
            {
              "text": "Running -&gt; ready|||Đang chạy (Running) -&gt; Sẵn sàng (ready)"
            },
            {
              "text": "Blocked (waiting) -&gt; ready|||Bị chặn (Blocked/waiting) -&gt; Sẵn sàng (ready)"
            },
            {
              "text": "Ready -&gt; running|||Sẵn sàng (Ready) -&gt; Đang chạy (running)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>When the external event a process is waiting for occurs (e.g. I/O completion), the process moves from Blocked (waiting) to Ready state.</p></div><div class=\"ml-vi\"><p>Khi sự kiện bên ngoài mà tiến trình đang chờ xảy ra (ví dụ hoàn tất I/O), tiến trình chuyển từ trạng thái Blocked (waiting) sang Ready.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>What is a &quot;striping&quot; in RAID?</p></div><div class=\"ml-vi\"><p>&quot;Striping&quot; trong RAID là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q40.png",
          "options": [
            {
              "text": "Distributing data over multiple drives|||Phân bố dữ liệu trên nhiều ổ đĩa"
            },
            {
              "text": "Take away possessions from someone|||Lấy đi tài sản của ai đó"
            },
            {
              "text": "Get undressed|||Cởi đồ"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Striping in RAID means splitting and distributing data blocks across multiple physical drives to improve performance/throughput.</p></div><div class=\"ml-vi\"><p>Striping trong RAID nghĩa là chia nhỏ và phân bố các khối dữ liệu trên nhiều ổ đĩa vật lý để cải thiện hiệu năng/thông lượng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Many computer users and some operating systems call subdirectories _____.</p></div><div class=\"ml-vi\"><p>Nhiều người dùng máy tính và một số hệ điều hành gọi các thư mục con (subdirectories) là _____.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q41.png",
          "options": [
            {
              "text": "Folders|||Thư mục (Folders)"
            },
            {
              "text": "Files|||Tệp (Files)"
            },
            {
              "text": "Volumes|||Ổ đĩa/Volume (Volumes)"
            },
            {
              "text": "Databases|||Cơ sở dữ liệu (Databases)"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Subdirectories are commonly referred to as &#39;folders&#39; by many users and operating systems (e.g. Windows).</p></div><div class=\"ml-vi\"><p>Thư mục con thường được người dùng và một số hệ điều hành (ví dụ Windows) gọi là &#39;folder&#39;.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Device Driver is usually written by:</p></div><div class=\"ml-vi\"><p>Device Driver (trình điều khiển thiết bị) thường được viết bởi:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q42.png",
          "options": [
            {
              "text": "Device&#39;s Manufacturer|||Nhà sản xuất thiết bị"
            },
            {
              "text": "OS&#39;s Manufacturer|||Nhà sản xuất hệ điều hành"
            },
            {
              "text": "Computer&#39;s Manufacturer|||Nhà sản xuất máy tính"
            },
            {
              "text": "All of the other choices|||Tất cả các đáp án khác"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Device drivers are typically written by the manufacturer of the device itself and shipped along with it, per the standard OS textbook (Tanenbaum).</p></div><div class=\"ml-vi\"><p>Device driver thường do chính nhà sản xuất thiết bị viết và cung cấp kèm theo thiết bị, theo giáo trình hệ điều hành chuẩn (Tanenbaum).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Failure to lock database records before updating them may result in a ____ between processes.</p></div><div class=\"ml-vi\"><p>Việc không khóa (lock) các bản ghi cơ sở dữ liệu trước khi cập nhật có thể dẫn đến ____ giữa các tiến trình.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q43.png",
          "options": [
            {
              "text": "Struggle|||Xung đột (Struggle)"
            },
            {
              "text": "Race|||Điều kiện đua (Race)"
            },
            {
              "text": "Deadlock|||Deadlock (khoá chết)"
            },
            {
              "text": "Livelock|||Livelock (kẹt sống)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Failing to lock shared data (like database records) before updates allows concurrent processes to interleave their operations unpredictably, causing a race condition.</p></div><div class=\"ml-vi\"><p>Không khóa dữ liệu dùng chung (như bản ghi cơ sở dữ liệu) trước khi cập nhật khiến các tiến trình đồng thời có thể xen kẽ thao tác một cách khó lường, gây ra điều kiện đua (race condition).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following statements does not apply to manual deadlock management?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây KHÔNG áp dụng cho cách quản lý deadlock thủ công (manual deadlock management, tức chiến lược &#39;bỏ qua&#39; deadlock)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q44.png",
          "options": [
            {
              "text": "Deadlock is relatively infrequent for some system resources|||Deadlock tương đối hiếm gặp đối với một số tài nguyên hệ thống"
            },
            {
              "text": "OS designers are normally very sensitive to deadlock when designing resource manager|||Người thiết kế hệ điều hành thường rất nhạy cảm với deadlock khi thiết kế trình quản lý tài nguyên"
            },
            {
              "text": "Recovery may involve rebooting the system|||Việc khôi phục có thể liên quan đến khởi động lại (reboot) hệ thống"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&#39;Manual&#39; (ignore/ostrich) deadlock management relies on deadlock being rare and recovery being manual (e.g. reboot). It is the OPPOSITE of designers being highly sensitive to deadlock — that describes prevention/avoidance strategies, not the manual/ignore approach, so B does not apply.</p></div><div class=\"ml-vi\"><p>Quản lý deadlock &#39;thủ công&#39; (chiến lược bỏ qua/đà điểu) dựa trên việc deadlock hiếm xảy ra và việc khôi phục là thủ công (ví dụ reboot). Điều này NGƯỢC LẠI với việc người thiết kế rất nhạy cảm với deadlock — đó là mô tả của chiến lược ngăn ngừa/tránh né, không phải cách tiếp cận thủ công/bỏ qua, nên B không áp dụng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of a system call is to allow the system free up internal table space?</p></div><div class=\"ml-vi\"><p>System call nào cho phép hệ thống giải phóng không gian bảng nội bộ (internal table space)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q45.png",
          "options": [
            {
              "text": "OPEN|||OPEN (mở)"
            },
            {
              "text": "CLOSE|||CLOSE (đóng)"
            },
            {
              "text": "SEEK|||SEEK (di chuyển con trỏ)"
            },
            {
              "text": "DELETE|||DELETE (xóa)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>CLOSE releases the internal table entry (file descriptor/table slot) that OPEN had allocated, freeing up internal table space.</p></div><div class=\"ml-vi\"><p>CLOSE giải phóng entry trong bảng nội bộ (file descriptor/slot) mà OPEN đã cấp phát trước đó, giải phóng không gian bảng nội bộ.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>Which of the following statements is not correct about DMA?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây KHÔNG đúng về DMA?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q46.png",
          "options": [
            {
              "text": "DMA controller has access to the system bus independent of the CPU|||Bộ điều khiển DMA có quyền truy cập bus hệ thống độc lập với CPU"
            },
            {
              "text": "DMA helps reduce the number of interrupts (in comparison with interrupt-driven I/O)|||DMA giúp giảm số lượng ngắt (so với I/O điều khiển bằng ngắt)"
            },
            {
              "text": "DMA controller is usually faster than CPU|||Bộ điều khiển DMA thường nhanh hơn CPU"
            },
            {
              "text": "The operating system can only use DMA if the hardware has a DMA controller|||Hệ điều hành chỉ có thể dùng DMA nếu phần cứng có bộ điều khiển DMA"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>A DMA controller is generally a simpler, dedicated chip for transferring data and is not &#39;faster than the CPU&#39; — that claim is incorrect. The other three statements about DMA are accurate.</p></div><div class=\"ml-vi\"><p>Bộ điều khiển DMA thường là một chip chuyên dụng đơn giản hơn để truyền dữ liệu, không phải là &#39;nhanh hơn CPU&#39; — khẳng định này sai. Ba phát biểu còn lại về DMA đều đúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>OS Win32 uses system call _____, while OS Unix uses system call _____ to create a new process.</p></div><div class=\"ml-vi\"><p>Hệ điều hành Win32 dùng system call _____, còn hệ điều hành Unix dùng system call _____ để tạo một tiến trình mới.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q47.png",
          "options": [
            {
              "text": "CreateProcess; fork|||CreateProcess; fork"
            },
            {
              "text": "fork, CreateProcess|||fork, CreateProcess"
            },
            {
              "text": "copy, CreateProcess|||copy, CreateProcess"
            },
            {
              "text": "CreateProcess; copy|||CreateProcess; copy"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Windows (Win32 API) creates processes with CreateProcess, while Unix/Linux creates processes with the fork system call.</p></div><div class=\"ml-vi\"><p>Windows (Win32 API) tạo tiến trình bằng CreateProcess, còn Unix/Linux tạo tiến trình bằng system call fork.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>_____ gives users the appearance that their programs are being completely loaded in main memory during the entire processing time.</p></div><div class=\"ml-vi\"><p>_____ tạo cho người dùng cảm giác rằng chương trình của họ được nạp hoàn toàn vào bộ nhớ chính trong suốt thời gian xử lý.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q48.png",
          "options": [
            {
              "text": "Segmenting|||Phân đoạn (Segmenting)"
            },
            {
              "text": "Virtual memory|||Bộ nhớ ảo (Virtual memory)"
            },
            {
              "text": "Shared memory|||Bộ nhớ dùng chung (Shared memory)"
            },
            {
              "text": "Multithreading|||Đa luồng (Multithreading)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Virtual memory creates the illusion for a program that it has a full, continuous address space fully resident in main memory, even though only parts of it may actually be loaded at any time.</p></div><div class=\"ml-vi\"><p>Bộ nhớ ảo (virtual memory) tạo ảo giác cho chương trình rằng nó có một không gian địa chỉ đầy đủ, liên tục và luôn nằm hoàn toàn trong bộ nhớ chính, dù thực tế chỉ một phần được nạp tại một thời điểm.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2041,
          "prompt": "<div class=\"ml-en\"><p>If i-node only contains 10 direct addresses and all disk blocks are 1024 KB, what is largest possible file size?</p></div><div class=\"ml-vi\"><p>Nếu i-node chỉ chứa 10 địa chỉ trực tiếp (direct address) và mỗi block đĩa có kích thước 1024 KB, kích thước tệp lớn nhất có thể là bao nhiêu?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/OSG202/D26/q49.png",
          "options": [
            {
              "text": "10 MB|||10 MB"
            },
            {
              "text": "10 GB|||10 GB"
            },
            {
              "text": "1 GB|||1 GB"
            },
            {
              "text": "None of the other choices|||Không có đáp án nào khác đúng"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>With only 10 direct block pointers and no indirect blocks, max file size = 10 blocks × 1024 KB/block = 10,240 KB = 10 MB.</p></div><div class=\"ml-vi\"><p>Với chỉ 10 con trỏ block trực tiếp và không có block gián tiếp, kích thước tệp tối đa = 10 block × 1024 KB/block = 10.240 KB = 10 MB.</p></div>"
        }
      ]
    }
  ]
};
