// AUTO-GENERATED by scripts/build-fe-exam.mjs from bank-WDU203c-FE17.jsonl — re-run the builder, do not hand-edit.
export default {
  "course": {
    "courseCode": "WDU203c"
  },
  "exams": [
    {
      "kind": "FE",
      "code": "FE17",
      "title": "WDU203c — Final Exam Đề 17 (SU25 RE)|||WDU203c — Đề thi cuối kỳ số 17 (SU25 Học lại)",
      "description": "Real SU25 retake final exam paper (50 câu, đầy đủ, thứ tự ảnh gốc xáo trộn đã remap).|||Đề thi cuối kỳ thật, học lại SU25 (50 câu, đầy đủ, thứ tự ảnh gốc xáo trộn đã remap).",
      "durationMinutes": 60,
      "totalPoints": 10,
      "passMark": 4,
      "source": "REAL",
      "shuffleQuestions": false,
      "shuffleOptions": false,
      "instructions": "<div class=\"ml-en\"><p>This is a real FPTU <b>Final Exam</b> paper for <b>this subject</b>. Every question is <b>multiple choice</b> and auto-graded.</p><ul><li>Some questions say \"choose TWO\" — they are only correct when both right answers are selected.</li><li>Read code, tables and diagrams carefully; several questions turn on a subtle detail.</li><li>The original scanned question is available under <b>\"Show original image\"</b> on each question.</li></ul><p>You can flag a question and come back. The timer auto-submits at the end. After you submit, every question shows a bilingual explanation.</p></div><div class=\"ml-vi\"><p>Đây là đề <b>thi cuối kỳ (Final Exam)</b> thật của FPTU môn <b>this subject</b>. Mọi câu đều là <b>trắc nghiệm</b>, chấm tự động.</p><ul><li>Một số câu ghi \"chọn HAI\" — chỉ đúng khi chọn đủ cả hai đáp án đúng.</li><li>Đọc kỹ code, bảng và sơ đồ; nhiều câu ăn thua ở một chi tiết nhỏ.</li><li>Ảnh đề gốc đã quét nằm ở nút <b>\"Xem ảnh đề gốc\"</b> trên mỗi câu.</li></ul><p>Bạn có thể đánh dấu câu để quay lại sau. Hết giờ hệ thống tự nộp. Nộp xong, mỗi câu đều có lời giải song ngữ.</p></div>",
      "isPublished": true,
      "questions": [
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Affordances of user interface don&#39;t have much influence on how easily users learn to use the system.</p></div><div class=\"ml-vi\"><p>Khả năng gợi ý sử dụng (affordance) của giao diện người dùng không có nhiều ảnh hưởng đến việc người dùng học cách sử dụng hệ thống dễ dàng hay không.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q2.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Affordances are strong cues that signal how an object can be used; they heavily influence how quickly and easily users learn a system, so the statement is false.</p></div><div class=\"ml-vi\"><p>Affordance là những gợi ý mạnh cho biết cách sử dụng một đối tượng; chúng ảnh hưởng rất lớn đến việc người dùng học hệ thống nhanh và dễ hay không, nên phát biểu này là sai.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Personas include different types of information, from demographics to motivations and sociocultural context. How should designers decide what information to include?</p></div><div class=\"ml-vi\"><p>Persona bao gồm nhiều loại thông tin khác nhau, từ nhân khẩu học đến động cơ và bối cảnh văn hóa - xã hội. Nhà thiết kế nên quyết định đưa thông tin nào vào persona như thế nào?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q3.png",
          "options": [
            {
              "text": "They should focus on making the information as complete as possible|||Nên tập trung làm cho thông tin càng đầy đủ càng tốt"
            },
            {
              "text": "They should focus on idiosyncratic characteristics of people they encountered in the formative research that will make personas as vivid as possible|||Nên tập trung vào những đặc điểm riêng biệt, khác thường của những người họ gặp trong nghiên cứu ban đầu để persona càng sống động càng tốt"
            },
            {
              "text": "They should focus mostly on demographic information; other types of information are secondary|||Nên tập trung chủ yếu vào thông tin nhân khẩu học; các loại thông tin khác là thứ yếu"
            },
            {
              "text": "They should focus on information that contributes to the distinct needs and potential barriers to and motivations for use that each class of target users has in relation to the technology being developed|||Nên tập trung vào thông tin góp phần thể hiện nhu cầu riêng biệt, rào cản tiềm ẩn và động cơ sử dụng mà mỗi nhóm người dùng mục tiêu có đối với công nghệ đang phát triển"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Persona content should be purposeful: only information relevant to understanding users&#39; needs, barriers, and motivations toward the technology should be included, not everything or only demographics.</p></div><div class=\"ml-vi\"><p>Nội dung persona cần có mục đích: chỉ đưa vào thông tin liên quan đến việc hiểu nhu cầu, rào cản và động cơ của người dùng đối với công nghệ, chứ không phải đưa mọi thứ hay chỉ có nhân khẩu học.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which is not an output modality commonly used in today&#39;s interactive applications?</p></div><div class=\"ml-vi\"><p>Đâu KHÔNG phải là một dạng thức đầu ra (output modality) thường được dùng trong các ứng dụng tương tác ngày nay?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q4.png",
          "options": [
            {
              "text": "Audio|||Âm thanh"
            },
            {
              "text": "Visual|||Hình ảnh"
            },
            {
              "text": "Olfactory|||Khứu giác"
            },
            {
              "text": "Tactile/Haptic|||Xúc giác/Rung phản hồi (Haptic)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Audio, visual, and tactile/haptic output are common in interactive applications; olfactory (smell) output is not commonly used.</p></div><div class=\"ml-vi\"><p>Đầu ra âm thanh, hình ảnh và xúc giác/haptic phổ biến trong các ứng dụng tương tác; đầu ra khứu giác (mùi) thì không phổ biến.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>In order to have a mental model of a system that enable them to use that system effectively, users need to understand the technical underpinnings of that system.</p></div><div class=\"ml-vi\"><p>Để có một mô hình tinh thần (mental model) về một hệ thống giúp họ sử dụng hệ thống đó hiệu quả, người dùng cần hiểu các nền tảng kỹ thuật bên trong của hệ thống đó.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q5.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Users can build effective mental models based purely on observed behavior and conceptual models presented by the interface, without understanding the underlying technical implementation.</p></div><div class=\"ml-vi\"><p>Người dùng có thể xây dựng mô hình tinh thần hiệu quả chỉ dựa trên hành vi quan sát được và mô hình khái niệm mà giao diện thể hiện, mà không cần hiểu cơ chế kỹ thuật bên trong.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Excellent drawing skills are needed to create effective storyboards.</p></div><div class=\"ml-vi\"><p>Cần có kỹ năng vẽ xuất sắc để tạo ra storyboard hiệu quả.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q6.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Storyboards are meant to quickly communicate ideas; simple sketches (even stick figures) are sufficient, so excellent drawing skill is not required.</p></div><div class=\"ml-vi\"><p>Storyboard chỉ nhằm truyền đạt ý tưởng nhanh chóng; những bản phác thảo đơn giản (kể cả hình que) là đủ, nên không cần kỹ năng vẽ xuất sắc.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>It&#39;s typically obvious which design solution, among alternatives they generated, designers should pursue.</p></div><div class=\"ml-vi\"><p>Thông thường, việc nên theo đuổi giải pháp thiết kế nào trong số các phương án đã tạo ra là điều hiển nhiên, dễ thấy đối với nhà thiết kế.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q7.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Choosing among design alternatives usually requires evaluation, critique, and testing; it is rarely obvious which solution is best.</p></div><div class=\"ml-vi\"><p>Việc lựa chọn giữa các phương án thiết kế thường đòi hỏi đánh giá, phản biện và kiểm thử; hiếm khi nào hiển nhiên rõ giải pháp nào là tốt nhất.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following are types of user-entered inputs?<br/>A. GPS<br/>B. Text fields where users enter free-form responses<br/>C. Widgets like calendar pickers or on/off switches<br/>D. Voice input, like dictation typing<br/>E. All options on this list except GPS</p></div><div class=\"ml-vi\"><p>Đâu là các dạng dữ liệu do người dùng nhập vào?<br/>A. GPS<br/>B. Ô nhập văn bản để người dùng nhập câu trả lời tự do<br/>C. Các widget như bộ chọn lịch hoặc công tắc bật/tắt<br/>D. Nhập bằng giọng nói, như đọc chính tả<br/>E. Tất cả các mục trên trừ GPS</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q8.png",
          "options": [
            {
              "text": "GPS|||GPS"
            },
            {
              "text": "Text fields where users enter free-form responses|||Ô nhập văn bản để người dùng nhập câu trả lời tự do"
            },
            {
              "text": "Widgets like calendar pickers or on/off switches|||Các widget như bộ chọn lịch hoặc công tắc bật/tắt"
            },
            {
              "text": "Voice input, like dictation typing|||Nhập bằng giọng nói, như đọc chính tả"
            },
            {
              "text": "All options on this list except GPS|||Tất cả các mục trên trừ GPS"
            }
          ],
          "correctIndexes": [
            4
          ],
          "explanation": "<div class=\"ml-en\"><p>GPS is a sensor-derived input, not something the user directly enters; text fields, widgets, and voice dictation are all user-entered inputs.</p></div><div class=\"ml-vi\"><p>GPS là dữ liệu lấy từ cảm biến, không phải do người dùng trực tiếp nhập; ô văn bản, widget và giọng nói đều là dữ liệu do người dùng nhập.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>While designers have to set defaults for many design elements, these default values rarely matter since users can just change them at any time.</p></div><div class=\"ml-vi\"><p>Mặc dù nhà thiết kế phải thiết lập giá trị mặc định cho nhiều thành phần thiết kế, những giá trị mặc định này hiếm khi quan trọng vì người dùng có thể thay đổi chúng bất cứ lúc nào.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q9.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Defaults matter a great deal because most users never change them; a well-chosen default shapes the majority of users&#39; experience.</p></div><div class=\"ml-vi\"><p>Giá trị mặc định rất quan trọng vì phần lớn người dùng không bao giờ thay đổi chúng; một mặc định được chọn tốt sẽ định hình trải nghiệm của đa số người dùng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>A recommended technique for supporting &quot;flexibility and efficiency of use&quot; is:</p></div><div class=\"ml-vi\"><p>Một kỹ thuật được khuyến nghị để hỗ trợ nguyên tắc &quot;tính linh hoạt và hiệu quả sử dụng&quot; (flexibility and efficiency of use) là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q10.png",
          "options": [
            {
              "text": "The use of keyboard &quot;accelerator&quot; shortcuts|||Sử dụng các phím tắt &quot;tăng tốc&quot; (accelerator) trên bàn phím"
            },
            {
              "text": "Make sure all commands are represented graphically on the screen|||Đảm bảo mọi lệnh đều được thể hiện bằng hình ảnh trên màn hình"
            },
            {
              "text": "Streamline the design to minimize page load times|||Tinh gọn thiết kế để giảm thiểu thời gian tải trang"
            },
            {
              "text": "Eliminate as many commands as possible to prevent possible errors|||Loại bỏ càng nhiều lệnh càng tốt để ngăn ngừa lỗi có thể xảy ra"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Keyboard accelerators let expert users perform actions faster while novices still use the standard interface, a classic technique for flexibility and efficiency of use (a Nielsen heuristic).</p></div><div class=\"ml-vi\"><p>Phím tắt cho phép người dùng thành thạo thao tác nhanh hơn trong khi người mới vẫn dùng giao diện chuẩn, đây là kỹ thuật kinh điển cho nguyên tắc linh hoạt và hiệu quả sử dụng (một nguyên tắc heuristic của Nielsen).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>A feature of an environment or system that communicates through verbiage or imagery what will happen if an action is taken is called:</p></div><div class=\"ml-vi\"><p>Một đặc điểm của môi trường hoặc hệ thống truyền đạt bằng lời hoặc hình ảnh về điều sẽ xảy ra nếu một hành động được thực hiện được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q11.png",
          "options": [
            {
              "text": "A signifier|||Signifier (yếu tố báo hiệu)"
            },
            {
              "text": "A signal|||Signal (tín hiệu)"
            },
            {
              "text": "Feedback|||Feedback (phản hồi)"
            },
            {
              "text": "An icon|||Icon (biểu tượng)"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>A signifier (Don Norman&#39;s term) is any mark or sound that communicates proper behavior/expected outcome to a user, distinct from feedback which occurs after an action is taken.</p></div><div class=\"ml-vi\"><p>Signifier (thuật ngữ của Don Norman) là bất kỳ dấu hiệu hay âm thanh nào truyền đạt cách hành xử đúng/kết quả mong đợi cho người dùng, khác với feedback vốn xảy ra sau khi hành động được thực hiện.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>A change in an environment or system that indicates that a user&#39;s action was recognized and communicates the result of that action is called:</p></div><div class=\"ml-vi\"><p>Một sự thay đổi trong môi trường hoặc hệ thống cho biết hành động của người dùng đã được ghi nhận và truyền đạt kết quả của hành động đó được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q12.png",
          "options": [
            {
              "text": "Response time|||Thời gian phản hồi (response time)"
            },
            {
              "text": "A signal|||Tín hiệu (signal)"
            },
            {
              "text": "Feedback|||Phản hồi (feedback)"
            },
            {
              "text": "A dialogue box|||Hộp thoại (dialogue box)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>This describes feedback: the system&#39;s response confirming that an action was received and showing its result.</p></div><div class=\"ml-vi\"><p>Đây là định nghĩa của feedback: phản hồi của hệ thống xác nhận hành động đã được nhận và cho thấy kết quả của hành động đó.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>When sketching to come up with different design solutions, you should stop the first time you run out of ideas.</p></div><div class=\"ml-vi\"><p>Khi phác thảo để tìm ra các giải pháp thiết kế khác nhau, bạn nên dừng lại ngay lần đầu tiên hết ý tưởng.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q13.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Designers should push past the initial exhaustion of ideas; the best solutions often come after continuing to generate more alternatives.</p></div><div class=\"ml-vi\"><p>Nhà thiết kế nên tiếp tục vượt qua giai đoạn cạn ý tưởng ban đầu; những giải pháp tốt nhất thường xuất hiện sau khi tiếp tục tạo thêm phương án.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>If a user of a system is unable to find an option for action that they believe will move them closer to achieving their goal, we would say that the system fails to bridge:</p></div><div class=\"ml-vi\"><p>Nếu người dùng của một hệ thống không thể tìm thấy một lựa chọn hành động mà họ tin sẽ giúp họ tiến gần hơn đến mục tiêu, ta nói hệ thống đó không thu hẹp được:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q14.png",
          "options": [
            {
              "text": "The Gulf of Inspection|||Khoảng cách Kiểm tra (Gulf of Inspection)"
            },
            {
              "text": "The Gulf of Expectation|||Khoảng cách Kỳ vọng (Gulf of Expectation)"
            },
            {
              "text": "The Gulf of Execution|||Khoảng cách Thực hiện (Gulf of Execution)"
            },
            {
              "text": "The Gulf of Evaluation|||Khoảng cách Đánh giá (Gulf of Evaluation)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>The Gulf of Execution is the gap between a user&#39;s goal and the actions available to achieve it; being unable to find the right action to reach a goal is a failure to bridge this gulf.</p></div><div class=\"ml-vi\"><p>Gulf of Execution là khoảng cách giữa mục tiêu của người dùng và các hành động có sẵn để đạt mục tiêu đó; việc không tìm được hành động đúng để đạt mục tiêu là thất bại trong việc thu hẹp khoảng cách này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>A collection of associated concepts in long-term memory is called what?</p></div><div class=\"ml-vi\"><p>Một tập hợp các khái niệm liên kết với nhau trong trí nhớ dài hạn được gọi là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q15.png",
          "options": [
            {
              "text": "A thought|||Một ý nghĩ (thought)"
            },
            {
              "text": "A schema|||Một lược đồ (schema)"
            },
            {
              "text": "A mule|||Một &quot;mule&quot;"
            },
            {
              "text": "A gestalt|||Một gestalt"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>A schema is a mental structure of associated concepts/knowledge stored in long-term memory that helps organize and interpret information.</p></div><div class=\"ml-vi\"><p>Schema là một cấu trúc tinh thần gồm các khái niệm/kiến thức liên kết với nhau được lưu trong trí nhớ dài hạn, giúp tổ chức và diễn giải thông tin.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Using obscure system codes or non-intuitive imagery to represent system features and/or feedback violates which heuristic?</p></div><div class=\"ml-vi\"><p>Việc sử dụng mã hệ thống khó hiểu hoặc hình ảnh không trực quan để thể hiện các tính năng và/hoặc phản hồi của hệ thống vi phạm nguyên tắc heuristic nào?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q16.png",
          "options": [
            {
              "text": "User control and freedom|||Kiểm soát và tự do của người dùng (user control and freedom)"
            },
            {
              "text": "Flexibility and efficiency of use|||Tính linh hoạt và hiệu quả sử dụng (flexibility and efficiency of use)"
            },
            {
              "text": "Aesthetic and minimalist design|||Thiết kế thẩm mỹ và tối giản (aesthetic and minimalist design)"
            },
            {
              "text": "Match between system and the real world|||Sự tương thích giữa hệ thống và thế giới thực (match between system and the real world)"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>This Nielsen heuristic requires the system to speak the users&#39; language with familiar, real-world conventions rather than obscure system-oriented codes.</p></div><div class=\"ml-vi\"><p>Nguyên tắc heuristic này của Nielsen yêu cầu hệ thống &quot;nói ngôn ngữ&quot; của người dùng, dùng các quy ước quen thuộc trong thế giới thực thay vì mã khó hiểu thiên về hệ thống.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>In UX, &quot;Design&quot; is concerned only with the aesthetic (or beauty-related) aspects of products.</p></div><div class=\"ml-vi\"><p>Trong UX, &quot;Thiết kế&quot; (Design) chỉ liên quan đến khía cạnh thẩm mỹ (hay vẻ đẹp) của sản phẩm.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q1.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>UX Design is concerned with usability, functionality, and the overall user experience, not just visual aesthetics.</p></div><div class=\"ml-vi\"><p>Thiết kế UX quan tâm đến tính khả dụng, chức năng và trải nghiệm tổng thể của người dùng, chứ không chỉ là thẩm mỹ trực quan.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following best describes the social desirability outcomes in interview-led survey modes?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây mô tả tốt nhất kết quả do thiên lệch mong muốn xã hội (social desirability) trong các hình thức khảo sát dẫn dắt bởi phỏng vấn viên?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q17.png",
          "options": [
            {
              "text": "Results can be biased because people want to be agreeable with an interviewer.|||Kết quả có thể sai lệch vì người trả lời muốn tỏ ra dễ chịu, hợp tác với phỏng vấn viên."
            },
            {
              "text": "Results can be biased because interviewers will avoid questions that could be embarrassing.|||Kết quả có thể sai lệch vì phỏng vấn viên sẽ tránh những câu hỏi có thể gây ngại ngùng."
            },
            {
              "text": "Results can be biased because people semi-consciously will try to look acceptable to the interviewer.|||Kết quả có thể sai lệch vì người trả lời một cách bán ý thức sẽ cố gắng thể hiện bản thân theo hướng được xã hội chấp nhận trước mặt phỏng vấn viên."
            },
            {
              "text": "Results can be biased because some interviewers are more able to get people to do surveys.|||Kết quả có thể sai lệch vì một số phỏng vấn viên có khả năng thuyết phục người khác tham gia khảo sát tốt hơn."
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Social desirability bias occurs when respondents, often semi-consciously, shade their answers to appear more acceptable to the person asking (the interviewer), rather than answering fully honestly.</p></div><div class=\"ml-vi\"><p>Thiên lệch mong muốn xã hội xảy ra khi người trả lời, thường một cách bán ý thức, chỉnh câu trả lời để trông đáng chấp nhận hơn trước người hỏi (phỏng vấn viên), thay vì trả lời hoàn toàn trung thực.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a way of reducing the burden for a respondent to participate in your survey?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là cách giảm gánh nặng cho người trả lời khi tham gia khảo sát của bạn?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q18.png",
          "options": [
            {
              "text": "Asking people who use a site&#39;s shopping cart how they feel about that experience.|||Hỏi những người dùng giỏ hàng của trang web về cảm nhận của họ với trải nghiệm đó."
            },
            {
              "text": "Keep the survey as short as you can without compromising quality.|||Giữ khảo sát ngắn nhất có thể mà không làm giảm chất lượng."
            },
            {
              "text": "Reduce the complexity of questions by making them easy to understand.|||Giảm độ phức tạp của câu hỏi bằng cách làm cho chúng dễ hiểu."
            },
            {
              "text": "Asking one group of respondents to forward the survey invite to their social networks.|||Nhờ một nhóm người trả lời chuyển tiếp lời mời khảo sát đến mạng xã hội của họ."
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Asking respondents to forward the invite is a recruitment/sampling technique (snowball sampling), not a way to reduce the burden of participating in the survey itself.</p></div><div class=\"ml-vi\"><p>Việc nhờ người trả lời chuyển tiếp lời mời là một kỹ thuật tuyển mộ/lấy mẫu (lấy mẫu quả cầu tuyết), không phải là cách giảm gánh nặng khi tham gia khảo sát.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following would NOT be an example of a sampling frame?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là một ví dụ về khung mẫu (sampling frame)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q19.png",
          "options": [
            {
              "text": "A social media site, like Twitter|||Một trang mạng xã hội, như Twitter"
            },
            {
              "text": "An organization&#39;s email directory|||Danh bạ email của một tổ chức"
            },
            {
              "text": "All phone numbers in the U.S.|||Tất cả số điện thoại tại Hoa Kỳ"
            },
            {
              "text": "User names of everyone who logged into the site this month|||Tên người dùng của tất cả những ai đã đăng nhập vào trang web trong tháng này"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>A sampling frame is a concrete, enumerable list of the population; &quot;a social media site like Twitter&quot; is a platform, not an enumerable list, unlike the other options which are all actual lists.</p></div><div class=\"ml-vi\"><p>Khung mẫu là một danh sách cụ thể, có thể liệt kê của tổng thể; &quot;một trang mạng xã hội như Twitter&quot; là một nền tảng, không phải một danh sách có thể liệt kê, khác với các lựa chọn còn lại đều là danh sách thực sự.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following best describes why you might choose to use a panel for recruiting respondents?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây mô tả tốt nhất lý do bạn có thể chọn sử dụng một panel (nhóm người sẵn sàng tham gia) để tuyển mộ người trả lời?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q20.png",
          "options": [
            {
              "text": "To make sure you get people who are experienced in answering surveys|||Để đảm bảo có được những người có kinh nghiệm trả lời khảo sát"
            },
            {
              "text": "To reduce recruitment costs|||Để giảm chi phí tuyển mộ"
            },
            {
              "text": "To increase quality|||Để tăng chất lượng"
            },
            {
              "text": "To avoid having a convenience sample|||Để tránh có một mẫu thuận tiện (convenience sample)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Panels are pre-recruited pools of willing respondents, so using one avoids the time and cost of recruiting participants from scratch for each study.</p></div><div class=\"ml-vi\"><p>Panel là nhóm người trả lời đã được tuyển mộ sẵn, nên việc sử dụng panel giúp tránh tốn thời gian và chi phí tuyển mộ người tham gia từ đầu cho mỗi nghiên cứu.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a dimension of survey modes?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là một khía cạnh (dimension) của các hình thức khảo sát (survey modes)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q21.png",
          "options": [
            {
              "text": "Cost|||Chi phí"
            },
            {
              "text": "Respondent burden|||Gánh nặng cho người trả lời"
            },
            {
              "text": "Sampling frame|||Khung mẫu (sampling frame)"
            },
            {
              "text": "Flexibility|||Tính linh hoạt"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Survey mode dimensions typically include cost, respondent burden, and flexibility; the sampling frame is a separate sampling concept, not a dimension of the delivery mode.</p></div><div class=\"ml-vi\"><p>Các khía cạnh của hình thức khảo sát thường bao gồm chi phí, gánh nặng người trả lời và tính linh hoạt; khung mẫu là một khái niệm lấy mẫu riêng biệt, không phải khía cạnh của hình thức khảo sát.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a way to match your UX goals to survey methods?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là cách để khớp mục tiêu UX của bạn với phương pháp khảo sát?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q22.png",
          "options": [
            {
              "text": "Launch an exploratory survey to determine UX goals.|||Triển khai một khảo sát khám phá để xác định mục tiêu UX."
            },
            {
              "text": "Ask why you want to have the data.|||Tự hỏi lý do bạn muốn có dữ liệu này."
            },
            {
              "text": "Have a story for why surveys are the best way to meet this UX goal.|||Có một lý giải rõ ràng cho việc tại sao khảo sát là cách tốt nhất để đạt mục tiêu UX này."
            },
            {
              "text": "Define goals before choosing metrics.|||Xác định mục tiêu trước khi chọn các chỉ số đo lường (metrics)."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>The correct process is to define UX goals first, then choose the appropriate method; launching a survey to determine goals reverses this order.</p></div><div class=\"ml-vi\"><p>Quy trình đúng là xác định mục tiêu UX trước, sau đó mới chọn phương pháp phù hợp; việc triển khai khảo sát để xác định mục tiêu là đảo ngược thứ tự này.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>This is error that is introduced when your questions somehow don&#39;t actually get to the concept you&#39;re interested in.</p></div><div class=\"ml-vi\"><p>Đây là loại lỗi phát sinh khi các câu hỏi của bạn bằng cách nào đó không thực sự chạm đến khái niệm mà bạn quan tâm.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q23.png",
          "options": [
            {
              "text": "Coverage Error|||Lỗi bao phủ (Coverage Error)"
            },
            {
              "text": "Sampling Error|||Lỗi lấy mẫu (Sampling Error)"
            },
            {
              "text": "Measurement error|||Lỗi đo lường (Measurement error)"
            },
            {
              "text": "Nonresponse Error|||Lỗi không phản hồi (Nonresponse Error)"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Measurement error occurs when the question wording or format fails to accurately capture the concept the researcher intended to measure.</p></div><div class=\"ml-vi\"><p>Lỗi đo lường xảy ra khi cách diễn đạt hoặc định dạng câu hỏi không nắm bắt chính xác khái niệm mà nhà nghiên cứu muốn đo.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>This term describes the total set of people you want to be able to represent with your survey.</p></div><div class=\"ml-vi\"><p>Thuật ngữ này mô tả toàn bộ tập hợp người mà bạn muốn khảo sát của mình có thể đại diện được.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q24.png",
          "options": [
            {
              "text": "Sample|||Mẫu (Sample)"
            },
            {
              "text": "Response Rate|||Tỷ lệ phản hồi (Response Rate)"
            },
            {
              "text": "Respondents|||Người trả lời (Respondents)"
            },
            {
              "text": "Population|||Tổng thể (Population)"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>The population is the entire group of people that the survey aims to represent, from which a sample is drawn.</p></div><div class=\"ml-vi\"><p>Tổng thể (population) là toàn bộ nhóm người mà khảo sát muốn đại diện, từ đó một mẫu được rút ra.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a way to increase the perceived benefit of participating in a survey?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là cách để tăng lợi ích cảm nhận (perceived benefit) của việc tham gia khảo sát?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q25.png",
          "options": [
            {
              "text": "Specify how the survey results will be used|||Nêu rõ kết quả khảo sát sẽ được sử dụng như thế nào"
            },
            {
              "text": "Identify the trustworthiness of the sponsoring organization|||Nêu rõ độ tin cậy của tổ chức tài trợ/thực hiện khảo sát"
            },
            {
              "text": "Make the survey as short as possible|||Làm khảo sát ngắn nhất có thể"
            },
            {
              "text": "Stress that opportunities to respond are limited|||Nhấn mạnh rằng cơ hội để trả lời là có hạn"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Making a survey short reduces the perceived cost/burden of participating, but it does not increase the perceived benefit; specifying result use, sponsor trustworthiness, and scarcity all increase perceived benefit.</p></div><div class=\"ml-vi\"><p>Việc rút ngắn khảo sát làm giảm chi phí/gánh nặng cảm nhận khi tham gia, nhưng không làm tăng lợi ích cảm nhận; trong khi nêu rõ mục đích sử dụng kết quả, độ tin cậy của tổ chức và sự khan hiếm cơ hội đều làm tăng lợi ích cảm nhận.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>The methodology you learned in this specialization is often labeled &quot;human-centered.&quot; Why?</p></div><div class=\"ml-vi\"><p>Phương pháp luận bạn học trong chuyên đề này thường được gọi là &quot;lấy con người làm trung tâm&quot; (human-centered). Vì sao?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q26.png",
          "options": [
            {
              "text": "Because it cannot be applied to animals.|||Vì nó không thể áp dụng cho động vật."
            },
            {
              "text": "Because it requires mindfulness training and centeredness to execute well.|||Vì nó đòi hỏi huấn luyện chánh niệm và sự tĩnh tâm để thực hiện tốt."
            },
            {
              "text": "Because it focuses on the needs, preferences, and perspectives of a human user (or potential user).|||Vì nó tập trung vào nhu cầu, sở thích và góc nhìn của người dùng (hoặc người dùng tiềm năng)."
            },
            {
              "text": "Because it focuses only on the human user and ignores the user&#39;s environment.|||Vì nó chỉ tập trung vào người dùng và bỏ qua môi trường của người dùng."
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>Human-centered design is named so because it prioritizes understanding and designing around the needs, preferences, and perspectives of the human users throughout the process.</p></div><div class=\"ml-vi\"><p>Thiết kế lấy con người làm trung tâm được gọi như vậy vì nó ưu tiên việc hiểu và thiết kế xoay quanh nhu cầu, sở thích và góc nhìn của người dùng xuyên suốt quá trình.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>What is qualitative data analysis?</p></div><div class=\"ml-vi\"><p>Phân tích dữ liệu định tính (qualitative data analysis) là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q27.png",
          "options": [
            {
              "text": "The formal analysis of data that is not all quantified or quantifiable.|||Sự phân tích chính thức đối với dữ liệu không hoàn toàn được lượng hóa hoặc không thể lượng hóa."
            },
            {
              "text": "The formal analysis of numerical information.|||Sự phân tích chính thức đối với thông tin số."
            },
            {
              "text": "The formal analysis of product quality.|||Sự phân tích chính thức về chất lượng sản phẩm."
            },
            {
              "text": "The formal analysis of how good something is.|||Sự phân tích chính thức về mức độ tốt của một điều gì đó."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Qualitative data analysis is the formal, systematic analysis of non-numerical (or not fully quantifiable) data such as interview transcripts, observations, and open-ended responses.</p></div><div class=\"ml-vi\"><p>Phân tích dữ liệu định tính là sự phân tích chính thức, có hệ thống đối với dữ liệu không phải dạng số (hoặc không thể lượng hóa hoàn toàn) như bản ghi phỏng vấn, quan sát và câu trả lời mở.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is the best-scoped question for a small user needs assessment project?</p></div><div class=\"ml-vi\"><p>Câu hỏi nào sau đây có phạm vi phù hợp nhất cho một dự án đánh giá nhu cầu người dùng quy mô nhỏ?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q28.png",
          "options": [
            {
              "text": "What kinds of problems do users face when using Microsoft Word&#39;s spell-checking feature?|||Người dùng gặp phải những vấn đề gì khi sử dụng tính năng kiểm tra chính tả của Microsoft Word?"
            },
            {
              "text": "What kinds of problems do users face when using Microsoft products?|||Người dùng gặp phải những vấn đề gì khi sử dụng các sản phẩm của Microsoft?"
            },
            {
              "text": "What kinds of problems do users face when using Microsoft Word?|||Người dùng gặp phải những vấn đề gì khi sử dụng Microsoft Word?"
            },
            {
              "text": "What kinds of problems do users face when fixing a spelling error identified by Microsoft Word&#39;s spell-checking feature?|||Người dùng gặp phải những vấn đề gì khi sửa lỗi chính tả được tính năng kiểm tra chính tả của Microsoft Word phát hiện?"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>This question is specific enough (one feature) to be manageable for a small project, yet broad enough to explore multiple kinds of problems, unlike the overly broad (B, C) or overly narrow (D) options.</p></div><div class=\"ml-vi\"><p>Câu hỏi này đủ cụ thể (một tính năng) để phù hợp với dự án nhỏ, nhưng vẫn đủ rộng để khám phá nhiều loại vấn đề, khác với các lựa chọn quá rộng (B, C) hoặc quá hẹp (D).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is worth noticing in an observation?<br/>I. The physical context where the user is.<br/>II. Pauses or missteps the user makes.<br/>III. Comments the user makes during a task.</p></div><div class=\"ml-vi\"><p>Điều nào sau đây đáng chú ý khi thực hiện quan sát?<br/>I. Bối cảnh vật lý nơi người dùng đang ở.<br/>II. Những khoảng dừng hoặc sai sót người dùng mắc phải.<br/>III. Những lời nhận xét người dùng đưa ra trong khi thực hiện nhiệm vụ.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q29.png",
          "options": [
            {
              "text": "II only|||Chỉ II"
            },
            {
              "text": "III only|||Chỉ III"
            },
            {
              "text": "II and III|||II và III"
            },
            {
              "text": "I, II and III|||I, II và III"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>All three — physical context, pauses/missteps, and verbal comments — are valuable data points to notice during an observation.</p></div><div class=\"ml-vi\"><p>Cả ba yếu tố — bối cảnh vật lý, khoảng dừng/sai sót, và lời nhận xét — đều là những điểm dữ liệu quan trọng cần chú ý khi quan sát.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is a good open-ended question to ask in a semi-structured interview?</p></div><div class=\"ml-vi\"><p>Câu hỏi nào sau đây là một câu hỏi mở tốt để hỏi trong một cuộc phỏng vấn bán cấu trúc?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q30.png",
          "options": [
            {
              "text": "How many times a week do you use a GPS device recently?|||Gần đây bạn sử dụng thiết bị GPS bao nhiêu lần một tuần?"
            },
            {
              "text": "Can you tell me about the most recent time when you used a GPS device?|||Bạn có thể kể cho tôi nghe về lần gần đây nhất bạn sử dụng thiết bị GPS không?"
            },
            {
              "text": "Was the GPS interface poorly designed?|||Giao diện GPS có được thiết kế kém không?"
            },
            {
              "text": "Why didn&#39;t you use the landmark feature on your GPS device?|||Tại sao bạn không sử dụng tính năng mốc định vị (landmark) trên thiết bị GPS của bạn?"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>This is a genuinely open-ended, non-leading question that invites a detailed narrative, unlike the others which are closed, leading, or presumptive.</p></div><div class=\"ml-vi\"><p>Đây là câu hỏi mở thực sự, không dẫn dắt, mời gọi người trả lời kể chi tiết, khác với các câu còn lại là câu hỏi đóng, dẫn dắt hoặc mang tính giả định sẵn.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following should you NOT do when trying to establish rapport with an interview participant?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây bạn KHÔNG nên làm khi cố gắng tạo mối quan hệ thân thiện (rapport) với người tham gia phỏng vấn?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q31.png",
          "options": [
            {
              "text": "Talk about what other participants have been saying.|||Nói về những gì các người tham gia khác đã chia sẻ."
            },
            {
              "text": "Make small talk at first.|||Bắt đầu bằng những câu chuyện phiếm nhẹ nhàng."
            },
            {
              "text": "Listen and observe how they respond.|||Lắng nghe và quan sát cách họ phản hồi."
            },
            {
              "text": "Adopt a learning mindset.|||Áp dụng tư duy học hỏi (learning mindset)."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Sharing what other participants said breaches confidentiality and can bias the current participant&#39;s answers; it is not an appropriate rapport-building technique.</p></div><div class=\"ml-vi\"><p>Việc chia sẻ những gì người tham gia khác đã nói vi phạm tính bảo mật và có thể làm sai lệch câu trả lời của người tham gia hiện tại; đây không phải là kỹ thuật xây dựng mối quan hệ phù hợp.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>What is an affinity note?</p></div><div class=\"ml-vi\"><p>Affinity note (ghi chú tương đồng) là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q32.png",
          "options": [
            {
              "text": "A sticky note on which you write relevant bits from your interview notes/recording and which is probably relevant for the user needs assessment.|||Một tờ giấy note trên đó bạn viết các nội dung liên quan trích từ ghi chú/bản ghi phỏng vấn, có khả năng liên quan đến việc đánh giá nhu cầu người dùng."
            },
            {
              "text": "A comment you write during an interview that indicates a common, recurring theme.|||Một lời bình bạn viết trong lúc phỏng vấn cho thấy một chủ đề chung, lặp lại."
            },
            {
              "text": "A short summary that includes your analysis of a single interview.|||Một bản tóm tắt ngắn gồm phân tích của bạn về một cuộc phỏng vấn duy nhất."
            },
            {
              "text": "A follow-up message from an interview participant that contains additional information.|||Một tin nhắn theo dõi từ người tham gia phỏng vấn chứa thêm thông tin."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>An affinity note is a single sticky note capturing one relevant piece of data from interview notes/recordings, used as the raw unit for building an affinity diagram/wall.</p></div><div class=\"ml-vi\"><p>Affinity note là một tờ giấy note ghi lại một mẩu dữ liệu liên quan từ ghi chú/bản ghi phỏng vấn, dùng làm đơn vị thô để xây dựng sơ đồ/bức tường tương đồng (affinity wall).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>What does it mean to balance abstraction and precision in an affinity wall cluster summary?</p></div><div class=\"ml-vi\"><p>Cân bằng giữa tính trừu tượng và tính chính xác trong bản tóm tắt cụm của affinity wall nghĩa là gì?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q33.png",
          "options": [
            {
              "text": "The summary should be neither too long nor too short.|||Bản tóm tắt không nên quá dài cũng không quá ngắn."
            },
            {
              "text": "The summary should use some of the same vocabulary used in the notes in the cluster.|||Bản tóm tắt nên dùng một số từ vựng giống với các ghi chú trong cụm."
            },
            {
              "text": "The summary should be applicable to most but not all of the notes in the cluster.|||Bản tóm tắt nên áp dụng được cho hầu hết nhưng không phải tất cả các ghi chú trong cụm."
            },
            {
              "text": "The summary should represent all of the notes in the cluster while being as specific and insightful as possible.|||Bản tóm tắt nên đại diện cho tất cả các ghi chú trong cụm trong khi vẫn cụ thể và sâu sắc nhất có thể."
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Balancing abstraction and precision means the summary must be general enough to cover every note in the cluster (abstraction) while still being specific and insightful rather than vague (precision).</p></div><div class=\"ml-vi\"><p>Cân bằng giữa trừu tượng và chính xác nghĩa là bản tóm tắt phải đủ khái quát để bao trùm mọi ghi chú trong cụm (trừu tượng) trong khi vẫn cụ thể, sâu sắc chứ không mơ hồ (chính xác).</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is a method one would use to learn more about users&#39; attitudes, preferences, context, and needs?<br/>I. Interviews (Remote or in-person)<br/>II. Clickstream analytics<br/>III. Behavioral analytics (surveys)<br/>IV. A/B Testing</p></div><div class=\"ml-vi\"><p>Phương pháp nào sau đây được dùng để tìm hiểu thêm về thái độ, sở thích, bối cảnh và nhu cầu của người dùng?<br/>I. Phỏng vấn (từ xa hoặc trực tiếp)<br/>II. Phân tích clickstream<br/>III. Phân tích hành vi (khảo sát)<br/>IV. Kiểm thử A/B</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q34.png",
          "options": [
            {
              "text": "I and II|||I và II"
            },
            {
              "text": "I and III|||I và III"
            },
            {
              "text": "I, II, and IV|||I, II và IV"
            },
            {
              "text": "I, II, III, and IV|||I, II, III và IV"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Interviews and surveys ask users directly about attitudes, preferences, context, and needs, while clickstream analytics and A/B testing only capture observed behavior, not underlying attitudes.</p></div><div class=\"ml-vi\"><p>Phỏng vấn và khảo sát hỏi trực tiếp người dùng về thái độ, sở thích, bối cảnh và nhu cầu, trong khi phân tích clickstream và kiểm thử A/B chỉ ghi nhận hành vi quan sát được, không phản ánh thái độ bên trong.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a method one would use to understand why people are using a product at certain times?</p></div><div class=\"ml-vi\"><p>Phương pháp nào sau đây KHÔNG được dùng để hiểu lý do tại sao mọi người sử dụng một sản phẩm vào những thời điểm nhất định?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q35.png",
          "options": [
            {
              "text": "Surveys|||Khảo sát"
            },
            {
              "text": "Clickstream analytics|||Phân tích clickstream"
            },
            {
              "text": "Concept Testing|||Kiểm thử khái niệm (Concept Testing)"
            },
            {
              "text": "Interviews|||Phỏng vấn"
            },
            {
              "text": "Remote testing|||Kiểm thử từ xa (Remote testing)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Clickstream analytics shows when and what users do, but not why; it is purely behavioral data without explanatory context, unlike surveys, interviews, concept testing, or remote testing which can elicit reasons.</p></div><div class=\"ml-vi\"><p>Phân tích clickstream cho biết người dùng làm gì và khi nào, nhưng không cho biết tại sao; đó thuần túy là dữ liệu hành vi không có bối cảnh giải thích, khác với khảo sát, phỏng vấn, kiểm thử khái niệm hay kiểm thử từ xa vốn có thể khai thác lý do.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is the MOST TRUE statement about how people remember things?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây là ĐÚNG NHẤT về cách con người ghi nhớ mọi thứ?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q36.png",
          "options": [
            {
              "text": "People remember their past behavior well enough to give accurate survey responses.|||Con người nhớ đủ chính xác hành vi trong quá khứ để đưa ra câu trả lời khảo sát chính xác."
            },
            {
              "text": "Memory can be guided back to accuracy through careful prompts.|||Trí nhớ có thể được dẫn dắt trở lại chính xác thông qua các gợi ý cẩn thận."
            },
            {
              "text": "Memory fades over time, but people are good at remembering routine actions.|||Trí nhớ phai nhạt theo thời gian, nhưng con người nhớ tốt các hành động thường lệ."
            },
            {
              "text": "Memory fades over time, and often doesn&#39;t capture routine actions.|||Trí nhớ phai nhạt theo thời gian, và thường không ghi lại được các hành động thường lệ (routine)."
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Human memory is unreliable over time and is especially poor at recalling routine, habitual actions since they aren&#39;t distinctly encoded.</p></div><div class=\"ml-vi\"><p>Trí nhớ con người không đáng tin cậy theo thời gian và đặc biệt kém trong việc nhớ lại những hành động thường lệ, theo thói quen vì chúng không được mã hóa một cách rõ rệt.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is the MOST IMPORTANT consideration in picking what type of question type to use?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây là cân nhắc QUAN TRỌNG NHẤT khi lựa chọn loại câu hỏi cần sử dụng?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q37.png",
          "options": [
            {
              "text": "The demographic makeup of your population|||Thành phần nhân khẩu học của tổng thể của bạn"
            },
            {
              "text": "The type of analysis you plan on doing|||Loại phân tích bạn dự định thực hiện"
            },
            {
              "text": "The type of sampling you&#39;re using|||Loại phương pháp lấy mẫu bạn đang sử dụng"
            },
            {
              "text": "The mode your survey will be delivered in|||Hình thức khảo sát của bạn sẽ được triển khai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The planned analysis method determines what kind of data (and thus question type - closed, open-ended, scaled, etc.) is needed, making it the most important consideration.</p></div><div class=\"ml-vi\"><p>Phương pháp phân tích dự kiến quyết định loại dữ liệu cần thu thập (và do đó loại câu hỏi - đóng, mở, thang đo, v.v.), khiến đây là cân nhắc quan trọng nhất.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following statement about open-ended questions is most FALSE?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây về câu hỏi mở là SAI nhất?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q38.png",
          "options": [
            {
              "text": "They are the easiest type of question to analyze.|||Chúng là loại câu hỏi dễ phân tích nhất."
            },
            {
              "text": "They allow respondents to answer without limiting the range of responses.|||Chúng cho phép người trả lời trả lời mà không giới hạn phạm vi câu trả lời."
            },
            {
              "text": "They are more frequently skipped than other types of questions.|||Chúng thường bị bỏ qua nhiều hơn so với các loại câu hỏi khác."
            },
            {
              "text": "They are often used when we haven&#39;t pre-defined response categories.|||Chúng thường được dùng khi chúng ta chưa xác định trước các nhóm câu trả lời."
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Open-ended questions are actually the hardest to analyze since responses are unstructured and require qualitative coding; the other statements about them are true.</p></div><div class=\"ml-vi\"><p>Câu hỏi mở thực ra là loại khó phân tích nhất vì câu trả lời không có cấu trúc và cần mã hóa định tính; các phát biểu còn lại về chúng đều đúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Under what circumstances is remote testing appropriate?<br/>I. It is difficult to access the product/experience.<br/>II. Participants from a variety of geographic locations are needed.<br/>III. Time is limited.<br/>IV. There is a lot of Personally Identifiable Information required.<br/>V. All of the above</p></div><div class=\"ml-vi\"><p>Trong những trường hợp nào thì kiểm thử từ xa (remote testing) là phù hợp?<br/>I. Khó tiếp cận sản phẩm/trải nghiệm.<br/>II. Cần người tham gia từ nhiều vị trí địa lý khác nhau.<br/>III. Thời gian có hạn.<br/>IV. Cần rất nhiều thông tin định danh cá nhân (PII).<br/>V. Tất cả các mục trên</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q39.png",
          "options": [
            {
              "text": "I, II, III|||I, II, III"
            },
            {
              "text": "I, IV|||I, IV"
            },
            {
              "text": "I, III, IV|||I, III, IV"
            },
            {
              "text": "II, III|||II, III"
            },
            {
              "text": "V|||V"
            }
          ],
          "correctIndexes": [
            0
          ],
          "explanation": "<div class=\"ml-en\"><p>Remote testing suits situations of difficult access, geographically dispersed participants, and limited time; heavy PII requirements are not a reason favoring remote testing and can actually raise privacy/security concerns.</p></div><div class=\"ml-vi\"><p>Kiểm thử từ xa phù hợp với các tình huống khó tiếp cận, người tham gia phân tán về địa lý, và thời gian hạn chế; yêu cầu nhiều thông tin định danh cá nhân không phải lý do ủng hộ kiểm thử từ xa mà còn có thể gây lo ngại về quyền riêng tư/bảo mật.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is the LEAST true statement about open-ended questions?</p></div><div class=\"ml-vi\"><p>Phát biểu nào sau đây về câu hỏi mở là ĐÚNG ÍT NHẤT (sai nhiều nhất)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q40.png",
          "options": [
            {
              "text": "Responses require effort for coding and analysis.|||Câu trả lời đòi hỏi công sức để mã hóa và phân tích."
            },
            {
              "text": "Respondents are more likely to skip open-ended questions.|||Người trả lời có xu hướng bỏ qua câu hỏi mở nhiều hơn."
            },
            {
              "text": "They can require more data cleaning.|||Chúng có thể cần nhiều công đoạn làm sạch dữ liệu hơn."
            },
            {
              "text": "They provide bad data because responses are not standardized.|||Chúng cung cấp dữ liệu tệ vì câu trả lời không được chuẩn hóa."
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Open-ended responses are not inherently &quot;bad data&quot; — they provide rich, unanticipated insight even though unstandardized; the other statements (effort to code, more likely skipped, need cleaning) are commonly true.</p></div><div class=\"ml-vi\"><p>Câu trả lời mở không hề là &quot;dữ liệu tệ&quot; một cách vốn dĩ — chúng cung cấp thông tin sâu sắc, bất ngờ dù không được chuẩn hóa; các phát biểu còn lại (tốn công mã hóa, dễ bị bỏ qua, cần làm sạch) thường đúng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following are the hallmarks of good research questions?<br/>I. Clarity<br/>II. Consistency<br/>III. Ability to be answered<br/>IV. Ethical excellence<br/>V. Significance</p></div><div class=\"ml-vi\"><p>Điều nào sau đây là những đặc điểm nổi bật của một câu hỏi nghiên cứu tốt?<br/>I. Rõ ràng<br/>II. Nhất quán<br/>III. Có khả năng trả lời được<br/>IV. Đạo đức xuất sắc<br/>V. Ý nghĩa/quan trọng</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q41.png",
          "options": [
            {
              "text": "I, II, and III|||I, II và III"
            },
            {
              "text": "I, II, and V|||I, II và V"
            },
            {
              "text": "IV and V|||IV và V"
            },
            {
              "text": "II, IV, and V|||II, IV và V"
            },
            {
              "text": "I, III, IV, and V|||I, III, IV và V"
            }
          ],
          "correctIndexes": [
            4
          ],
          "explanation": "<div class=\"ml-en\"><p>Good research questions are typically characterized by clarity, being answerable, ethical soundness, and significance; &quot;consistency&quot; is not a standard hallmark of a research question.</p></div><div class=\"ml-vi\"><p>Câu hỏi nghiên cứu tốt thường được đặc trưng bởi tính rõ ràng, khả năng trả lời được, tính đạo đức và ý nghĩa; &quot;tính nhất quán&quot; không phải là một đặc điểm chuẩn của câu hỏi nghiên cứu.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is NOT a best practice in writing nominal closed-ended questions?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là thực hành tốt khi viết câu hỏi đóng dạng định danh (nominal)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q42.png",
          "options": [
            {
              "text": "Avoid unequal response options|||Tránh các lựa chọn trả lời không cân bằng"
            },
            {
              "text": "Use &quot;select all that apply&quot; responses rather than forced choices.|||Sử dụng câu trả lời &quot;chọn tất cả các mục phù hợp&quot; thay vì lựa chọn bắt buộc (forced choice)"
            },
            {
              "text": "Constrain the number of response options that you provide|||Giới hạn số lượng lựa chọn trả lời bạn cung cấp"
            },
            {
              "text": "Randomize response options when necessary|||Ngẫu nhiên hóa thứ tự các lựa chọn trả lời khi cần thiết"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>&quot;Select all that apply&quot; is generally discouraged as a best practice because respondents tend to satisfice and stop selecting; forced-choice (yes/no per item) formats yield more reliable data.</p></div><div class=\"ml-vi\"><p>&quot;Chọn tất cả các mục phù hợp&quot; nhìn chung không được khuyến khích là thực hành tốt vì người trả lời có xu hướng làm qua loa và ngừng chọn sớm; định dạng lựa chọn bắt buộc (có/không cho từng mục) cho dữ liệu đáng tin cậy hơn.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>When designing the set of tasks you will use in a test, it&#39;s a good idea to:</p></div><div class=\"ml-vi\"><p>Khi thiết kế bộ nhiệm vụ (tasks) sẽ dùng trong một bài kiểm thử, nên làm điều gì sau đây:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q43.png",
          "options": [
            {
              "text": "Order them from hardest to easiest, to get the hard stuff out of the way.|||Sắp xếp từ khó nhất đến dễ nhất, để giải quyết phần khó trước."
            },
            {
              "text": "Order them from easiest to hardest, so that your participants feel more comfortable.|||Sắp xếp từ dễ nhất đến khó nhất, để người tham gia cảm thấy thoải mái hơn."
            },
            {
              "text": "Ask individual participants to perform several very similar tasks one after another, to ensure that they perform consistently.|||Yêu cầu từng người tham gia thực hiện nhiều nhiệm vụ rất giống nhau liên tiếp, để đảm bảo họ thực hiện nhất quán."
            },
            {
              "text": "Exhaustively test every possible path a user could take through the interface, even if it means testing with dozens of users.|||Kiểm thử toàn diện mọi đường đi có thể của người dùng qua giao diện, dù điều đó có nghĩa là phải kiểm thử với hàng chục người dùng."
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>Ordering tasks from easiest to hardest helps participants build confidence and comfort early in the session, a standard best practice in test design.</p></div><div class=\"ml-vi\"><p>Sắp xếp nhiệm vụ từ dễ đến khó giúp người tham gia xây dựng sự tự tin và thoải mái ngay từ đầu phiên kiểm thử, đây là thực hành chuẩn trong thiết kế bài kiểm thử.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>The design process is highly iterative. Which of the following are iterative loops that a designer might do in the course of a project?</p></div><div class=\"ml-vi\"><p>Quy trình thiết kế mang tính lặp đi lặp lại cao. Điều nào sau đây là những vòng lặp mà nhà thiết kế có thể thực hiện trong quá trình của một dự án?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q44.png",
          "options": [
            {
              "text": "From ideation to problem framing|||Từ tạo ý tưởng (ideation) quay lại xác định vấn đề (problem framing)"
            },
            {
              "text": "From creation of scenarios and storyboards to ideation|||Từ tạo kịch bản (scenarios) và storyboard quay lại tạo ý tưởng"
            },
            {
              "text": "From creation of scenarios and storyboards to problem framing|||Từ tạo kịch bản và storyboard quay lại xác định vấn đề"
            },
            {
              "text": "From prototyping to ideation|||Từ tạo mẫu (prototyping) quay lại tạo ý tưởng"
            },
            {
              "text": "All of the others|||Tất cả các mục còn lại"
            },
            {
              "text": "None of the others|||Không mục nào ở trên"
            }
          ],
          "correctIndexes": [
            4
          ],
          "explanation": "<div class=\"ml-en\"><p>The design process is non-linear; designers commonly loop back from any later stage (ideation, scenarios/storyboards, prototyping) to any earlier stage (problem framing, ideation) as understanding deepens.</p></div><div class=\"ml-vi\"><p>Quy trình thiết kế không tuyến tính; nhà thiết kế thường quay lại từ bất kỳ giai đoạn sau nào (tạo ý tưởng, kịch bản/storyboard, tạo mẫu) về bất kỳ giai đoạn trước nào (xác định vấn đề, tạo ý tưởng) khi hiểu biết sâu hơn.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following best describes the role of a participant in a user test?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây mô tả tốt nhất vai trò của người tham gia trong một bài kiểm thử người dùng?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q45.png",
          "options": [
            {
              "text": "They are being evaluated to see if they are competent enough to use the system tested|||Họ đang được đánh giá xem có đủ năng lực để sử dụng hệ thống được kiểm thử hay không"
            },
            {
              "text": "Once they have agreed to participate, they are obligated to complete all tasks and answer all questions, regardless of their discomfort|||Một khi đã đồng ý tham gia, họ có nghĩa vụ phải hoàn thành mọi nhiệm vụ và trả lời mọi câu hỏi, bất kể cảm thấy khó chịu ra sao"
            },
            {
              "text": "They are partners with the researchers administering the test, working with together to find flaws in the system design|||Họ là đối tác của các nhà nghiên cứu thực hiện bài kiểm thử, cùng nhau tìm ra những thiếu sót trong thiết kế hệ thống"
            },
            {
              "text": "They should remain ignorant of the goals of the test, so that they can offer more creative feedback and design suggestions|||Họ nên giữ sự không biết về mục tiêu của bài kiểm thử, để có thể đưa ra phản hồi và đề xuất thiết kế sáng tạo hơn"
            }
          ],
          "correctIndexes": [
            2
          ],
          "explanation": "<div class=\"ml-en\"><p>In user testing, it&#39;s the system being evaluated, not the participant; participants act as partners helping researchers uncover design flaws, and can stop or skip tasks at any time.</p></div><div class=\"ml-vi\"><p>Trong kiểm thử người dùng, hệ thống mới là đối tượng được đánh giá, không phải người tham gia; người tham gia đóng vai trò đối tác giúp nhà nghiên cứu phát hiện thiếu sót thiết kế, và có thể dừng hoặc bỏ qua nhiệm vụ bất cứ lúc nào.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>The primary concern of design is to create artifacts and systems that are aesthetically pleasing.</p></div><div class=\"ml-vi\"><p>Mối quan tâm chính của thiết kế là tạo ra các sản phẩm và hệ thống đẹp mắt về mặt thẩm mỹ.</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q46.png",
          "options": [
            {
              "text": "True|||Đúng"
            },
            {
              "text": "False|||Sai"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The primary concern of design is solving problems and fulfilling user needs effectively and usably; aesthetics is one factor but not the primary concern.</p></div><div class=\"ml-vi\"><p>Mối quan tâm chính của thiết kế là giải quyết vấn đề và đáp ứng nhu cầu người dùng một cách hiệu quả, khả dụng; thẩm mỹ chỉ là một yếu tố chứ không phải mối quan tâm chính.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>Which of the following is not an example of a subjective measure that might be collected during a user test?</p></div><div class=\"ml-vi\"><p>Điều nào sau đây KHÔNG phải là ví dụ về một thước đo chủ quan (subjective measure) có thể được thu thập trong một bài kiểm thử người dùng?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q47.png",
          "options": [
            {
              "text": "Perceived usability|||Tính khả dụng cảm nhận (perceived usability)"
            },
            {
              "text": "Perceived usefulness|||Tính hữu ích cảm nhận (perceived usefulness)"
            },
            {
              "text": "Desirability|||Sự mong muốn/hấp dẫn (desirability)"
            },
            {
              "text": "Task completion speed|||Tốc độ hoàn thành nhiệm vụ"
            }
          ],
          "correctIndexes": [
            3
          ],
          "explanation": "<div class=\"ml-en\"><p>Task completion speed is an objective, directly measurable quantity, while perceived usability, perceived usefulness, and desirability are subjective measures based on user opinion.</p></div><div class=\"ml-vi\"><p>Tốc độ hoàn thành nhiệm vụ là một đại lượng khách quan, đo trực tiếp được, trong khi tính khả dụng cảm nhận, tính hữu ích cảm nhận và sự hấp dẫn là các thước đo chủ quan dựa trên ý kiến người dùng.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>About how many &quot;key findings&quot; should be included in a typical user test report?</p></div><div class=\"ml-vi\"><p>Một báo cáo kiểm thử người dùng điển hình nên bao gồm khoảng bao nhiêu &quot;phát hiện chính&quot; (key findings)?</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q48.png",
          "options": [
            {
              "text": "1|||1"
            },
            {
              "text": "2-3|||2-3"
            },
            {
              "text": "5-10|||5-10"
            },
            {
              "text": "20-50|||20-50"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>A typical user test report should highlight a small, focused set of 2-3 key findings so stakeholders can easily grasp and act on the most important issues.</p></div><div class=\"ml-vi\"><p>Một báo cáo kiểm thử người dùng điển hình nên nêu bật một số lượng nhỏ, tập trung khoảng 2-3 phát hiện chính để các bên liên quan dễ nắm bắt và hành động theo những vấn đề quan trọng nhất.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>What is the problem with the following task description?<br/>&quot;Go to coursera.org and find a course that looks interesting to you. Find out more about it.&quot;</p></div><div class=\"ml-vi\"><p>Vấn đề với mô tả nhiệm vụ sau đây là gì?<br/>&quot;Hãy vào coursera.org và tìm một khóa học mà bạn thấy thú vị. Tìm hiểu thêm về khóa học đó.&quot;</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q49.png",
          "options": [
            {
              "text": "It is not realistic|||Nó không thực tế"
            },
            {
              "text": "It is not verifiable|||Nó không thể kiểm chứng được"
            },
            {
              "text": "It &quot;leads the witness&quot;|||Nó &quot;dẫn dắt câu trả lời&quot; (leads the witness)"
            },
            {
              "text": "It is not the most efficient way of learning about a Coursera course|||Nó không phải là cách hiệu quả nhất để tìm hiểu về một khóa học trên Coursera"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The task has no clear, objective success criterion — &quot;interesting to you&quot; and &quot;find out more&quot; are subjective and open-ended, so there&#39;s no way to verify whether the participant succeeded.</p></div><div class=\"ml-vi\"><p>Nhiệm vụ này không có tiêu chí thành công rõ ràng, khách quan — &quot;thú vị với bạn&quot; và &quot;tìm hiểu thêm&quot; là chủ quan và mở, nên không có cách nào để kiểm chứng liệu người tham gia đã hoàn thành thành công hay chưa.</p></div>"
        },
        {
          "kind": "MCQ",
          "points": 0.2,
          "prompt": "<div class=\"ml-en\"><p>The person who greets participants and communicates with them throughout a user test session is called the:</p></div><div class=\"ml-vi\"><p>Người chào đón người tham gia và giao tiếp với họ trong suốt phiên kiểm thử người dùng được gọi là:</p></div>",
          "imageUrl": "https://media.cuongthai.com/images/exam-questions/WDU203c/FE-SU25RE/q50.png",
          "options": [
            {
              "text": "Logger|||Người ghi chép (Logger)"
            },
            {
              "text": "Moderator|||Người điều phối (Moderator)"
            },
            {
              "text": "Interviewer|||Người phỏng vấn (Interviewer)"
            },
            {
              "text": "Technician|||Kỹ thuật viên (Technician)"
            }
          ],
          "correctIndexes": [
            1
          ],
          "explanation": "<div class=\"ml-en\"><p>The moderator is the person who runs the session, greeting the participant, giving instructions, and communicating with them throughout the test.</p></div><div class=\"ml-vi\"><p>Người điều phối (moderator) là người chủ trì phiên kiểm thử, chào đón người tham gia, đưa ra hướng dẫn và giao tiếp với họ trong suốt bài kiểm thử.</p></div>"
        }
      ]
    }
  ]
};
