/**
 * Math for Machine Learning — khoá học CuongThai (Courses, GENERAL). KHUNG dựng 01/10/2026 theo kế hoạch lộ trình 6 nghề
 * (content/courses/_KE-HOACH-LO-TRINH-NGHE-0110.md, gói A). Khoá này SỞ HỮU: đại số tuyến tính, giải tích, tối ưu, xác suất
 * và lý thuyết thông tin cho ML. machine-learning Ch1–2 sẽ thu gọn thành bài ôn nhanh + link về đây.
 * Ranh giới: thống kê SUY LUẬN (kiểm định, khoảng tin cậy, A/B, nhân quả) thuộc `statistics-data-science`; numpy/pandas
 * thuộc python Ch10 + machine-learning Ch3–4; autograd/optimizer bằng PyTorch thuộc deep-learning.
 * Soạn chi tiết sau theo quy trình khoá Docker (content/courses/docker/_HOP-DONG.md). Xem _chung/khung.mjs.
 */
import { khung } from './_chung/khung.mjs';

export default {
  category: { slug: 'ai', name: 'AI & Tự động hoá', icon: 'Sparkles', sortOrder: 6 },
  course: {
    slug: 'math-for-ml',
    title: 'Math for Machine Learning',
    level: 'BEGINNER',
    language: 'Vietnamese',
    status: 'PUBLISHED',
    isFeatured: false,
    syncOrder: true,
    thumbnailUrl: 'https://media.cuongthai.com/images/course-covers/math-for-ml.png?v=4',
    shortDescription: 'The math behind machine learning from zero, with code instead of proofs: vectors, matrices, SVD and PCA, derivatives and gradients, optimization, probability, MLE and cross-entropy — then a neural network and attention written in plain numpy.|||Toán đằng sau machine learning từ con số 0, bằng code thay vì chứng minh: vector, ma trận, SVD và PCA, đạo hàm và gradient, tối ưu, xác suất, MLE và cross-entropy — rồi tự viết mạng nơ-ron và attention bằng numpy thuần.',
    description: 'Khoá toán cho người học AI mà sợ toán: mỗi khái niệm đi theo thứ tự hình ảnh trực giác → công thức → vài dòng numpy chạy được → nó xuất hiện ở đâu trong ML/LLM. Bắt đầu từ cách đọc ký hiệu (Σ, ∂, ‖x‖, argmax), đi qua đại số tuyến tính (vector, ma trận như phép biến đổi, hạng, trị riêng, SVD, PCA), giải tích một và nhiều biến (đạo hàm, quy tắc chuỗi, gradient, Jacobian, Hessian), tối ưu (gradient descent, SGD, momentum, Adam, lồi/không lồi, Lagrange), xác suất (Bayes, phân phối, kỳ vọng, hiệp phương sai), ước lượng và lý thuyết thông tin (MLE, MAP, entropy, cross-entropy, KL), số học máy tính (float16/bf16, tràn số, lượng tử hoá, FLOPs). Cuối khoá tự viết hồi quy logistic, mạng nơ-ron hai lớp có backprop và một khối attention chỉ bằng numpy, rồi làm dự án phát hiện bất thường cảm biến cho LabFlow AI.',
    whatYouLearn: 'Đọc được ký hiệu toán trong tài liệu và paper ML; giải thích vector, ma trận, trị riêng, SVD, PCA bằng hình; tính đạo hàm, gradient và áp quy tắc chuỗi để hiểu backpropagation; tự cài gradient descent, momentum, Adam; dùng xác suất, Bayes và phân phối đúng chỗ; hiểu vì sao loss của phân loại là cross-entropy (MLE) và KL divergence đo gì; tránh tràn số với log-sum-exp; ước lượng FLOPs và bộ nhớ của một model; tự viết mạng nơ-ron và attention bằng numpy thuần.',
    requirements: 'Toán THPT (hàm số, đạo hàm cơ bản — quên cũng được, Chương 1 ôn lại), Python cơ bản. Nên học trước khoá Python (/courses/python) tới Chương 10 (numpy). Học xong nên học tiếp Machine Learning (/courses/machine-learning), Thống kê & Khoa học dữ liệu (/courses/statistics-data-science) và Deep Learning (/courses/deep-learning).',
    documentsNote: 'Tài liệu chính: "Mathematics for Machine Learning" (Deisenroth, Faisal, Ong — Cambridge University Press 2020, bản PDF miễn phí tại mml-book.github.io) • MIT OpenCourseWare 18.06 Linear Algebra (Gilbert Strang, ocw.mit.edu) • 3Blue1Brown — "Essence of linear algebra" và "Essence of calculus" (3blue1brown.com) • Stanford CS229 lecture notes (cs229.stanford.edu) • "Deep Learning" (Goodfellow, Bengio, Courville — Phần I, deeplearningbook.org) • numpy.org/doc • Khan Academy (khanacademy.org).',
  },
  sections: khung('math-ml', [
    ['Section 0 — Why math for ML, and how to learn it without fear', 'Mục 0 — Vì sao cần toán cho ML, và học không sợ', 'Toán nào thật sự cần, vì sao, và học theo cách nào để không bỏ cuộc.', [
      ['bat-dau-tai-day', 'Start here (1/2) — What "math for ML" really is, where it came from, and the failures caused by not understanding it', 'Bắt đầu tại đây (1/2) — "Toán cho ML" thật ra là gì, nó từ đâu ra, và những thất bại vì không hiểu nó', 'Ba trụ cột bằng lời đời thường: đại số tuyến tính (dữ liệu là bảng số), giải tích (đi xuống dốc), xác suất (đo sự không chắc chắn) · Mốc lịch sử: Legendre/Gauss bình phương tối thiểu 1805–1809, Cauchy gradient descent 1847, Bayes 1763, Rosenblatt perceptron 1958, backpropagation Rumelhart–Hinton–Williams 1986, Transformer 2017 · Thất bại thật: mô hình tài chính Gaussian copula và khủng hoảng 2008 (giả định phân phối sai), loss NaN vì tràn số, chuẩn hoá quên làm khiến gradient descent không hội tụ · Vì sao "chỉ gọi thư viện" đủ để chạy nhưng không đủ để sửa khi hỏng'],
      ['bat-dau-hoc-xong', 'Start here (2/2) — What you can do after this course, where it sits in the AI/Data roadmap, and how to study it', 'Bắt đầu tại đây (2/2) — Học xong làm được gì, khoá nằm ở đâu trong lộ trình AI/Data, và học thế nào', 'Học xong: đọc paper, debug loss, hiểu vì sao model hỏng, qua vòng phỏng vấn toán của vị trí AI/ML/Data Scientist · Vị trí trong lộ trình nghề: tầng nền chung (python · math-for-ml) → machine-learning → deep-learning → llm-apps/rag/ai-agents → mlops-llmops; nhánh Data Scientist: math-for-ml → statistics-data-science · Cách học: hình trước, công thức sau, code luôn; mỗi bài một bài tập numpy 10 dòng · Mẹo cho người yếu tiếng Anh: bảng thuật ngữ Anh–Việt mỗi chương'],
      ['cai-dat', 'Your math lab: Python, Jupyter, numpy, SymPy and matplotlib', 'Phòng lab toán: Python, Jupyter, numpy, SymPy và matplotlib', 'Cài bằng uv + Jupyter/VS Code notebook · numpy để tính số, SymPy để tính ký hiệu (đạo hàm, giải phương trình), matplotlib để vẽ · Kiểm đáp án bằng hai cách: tính tay và numpy · Trỏ khoá Python Chương 6 (uv) nếu chưa cài'],
      ['neu-da-hoc-ml', 'If you took Machine Learning Ch1–2: what this course adds', 'Nếu đã học Machine Learning Chương 1–2: khoá này thêm gì', 'ML Ch1–2 dạy "toán vừa đủ" bằng trực giác: vector, đạo hàm, gradient descent, xác suất cơ bản · Ở đây đi sâu: ma trận như phép biến đổi, SVD, đạo hàm nhiều biến, Adam, MLE, entropy · Bảng đối chiếu bài ML ↔ chương ở đây để bỏ qua phần đã vững · Link /courses/machine-learning'],
    ]],
    ['Chapter 1 — Reading math: notation, functions, exponentials and logs', 'Chương 1 — Đọc toán: ký hiệu, hàm số, mũ và logarit', 'Ôn lại toán THPT vừa đủ và học đọc ký hiệu mà paper ML dùng.', [
      ['ky-hieu', 'Reading the notation: Σ, Π, ∈, ∀, argmax, ‖x‖ and indices', 'Đọc ký hiệu: Σ, Π, ∈, ∀, argmax, ‖x‖ và chỉ số', 'Σ chính là vòng for · Chỉ số trên/dưới x_i, x^(i), W_ij · argmax vs max · Dịch một công thức trong paper thành code Python dòng-đối-dòng'],
      ['ham-so', 'Functions as machines: domain, composition and plotting', 'Hàm số như cỗ máy: miền xác định, hàm hợp và vẽ đồ thị', 'f(g(x)) — mạng nơ-ron là hàm hợp nhiều tầng · Hàm tuyến tính vs phi tuyến · Vẽ bằng matplotlib để "nhìn" hàm · ReLU, sigmoid, tanh là hàm gì'],
      ['mu-log', 'Exponentials and logarithms, and why ML loves log', 'Mũ và logarit, và vì sao ML mê log', 'Quy tắc log biến tích thành tổng · log-likelihood · Thang log trên biểu đồ · e và ln · Vì sao xác suất nhân nhiều lần sẽ về 0 trên máy tính'],
      ['tap-hop-logic', 'Sets, logic and proofs you actually need (very little)', 'Tập hợp, logic và chứng minh bạn thật sự cần (rất ít)', 'Tập hợp, ℝⁿ, khoảng · "Nếu… thì…" và phản ví dụ · Đọc một định lý mà không cần chứng minh nó · Khi nào nên dừng đào sâu'],
    ]],
    ['Chapter 2 — Vectors', 'Chương 2 — Vector', 'Một điểm dữ liệu, một embedding, một hàng trọng số — đều là vector.', [
      ['vector-la-gi', 'What a vector is: arrows, lists of numbers and data points', 'Vector là gì: mũi tên, danh sách số và điểm dữ liệu', 'Ba góc nhìn: vật lý, tin học, toán · Một học sinh = vector điểm số · Không gian ℝⁿ · numpy array 1 chiều'],
      ['phep-toan-vector', 'Vector addition, scaling and linear combinations', 'Cộng vector, nhân vô hướng và tổ hợp tuyến tính', 'Hình học của phép cộng · Tổ hợp tuyến tính · Span (bao tuyến tính) bằng hình · Ví dụ "vua − đàn ông + phụ nữ ≈ nữ hoàng" của word2vec 2013'],
      ['tich-vo-huong', 'Dot product, length (norms) and angle', 'Tích vô hướng, độ dài (chuẩn) và góc', 'Dot product = tổng các tích · Chuẩn L1, L2, L∞ và khi nào dùng · Cosine similarity — nền của tìm kiếm embedding (trỏ /courses/rag-vector-search 1.3, không dạy lại) · Vector đơn vị và chuẩn hoá'],
      ['chieu', 'Projection: the shadow of one vector on another', 'Phép chiếu: bóng của vector này lên vector kia', 'Công thức chiếu · Trực giao (vuông góc) · Phần dư · Chuẩn bị cho hồi quy tuyến tính và PCA'],
    ]],
    ['Chapter 3 — Matrices', 'Chương 3 — Ma trận', 'Ma trận là bảng dữ liệu và cũng là một phép biến đổi không gian.', [
      ['ma-tran-la-gi', 'Matrices as data tables and as transformations', 'Ma trận như bảng dữ liệu và như phép biến đổi', 'Ma trận dữ liệu X (n mẫu × d đặc trưng) · Ma trận xoay, co giãn, trượt bằng hình · Shape và quy ước hàng/cột trong numpy'],
      ['nhan-ma-tran', 'Matrix multiplication, and why the shapes must match', 'Nhân ma trận, và vì sao shape phải khớp', 'Bốn cách nhìn phép nhân (hàng·cột, tổ hợp cột…) · Nhân ma trận = ghép hai phép biến đổi · Một tầng nơ-ron là y = Wx + b · Lỗi "shapes not aligned" và cách đọc'],
      ['chuyen-vi-nghich-dao', 'Transpose, identity, inverse and determinant', 'Chuyển vị, ma trận đơn vị, nghịch đảo và định thức', 'Định thức = hệ số phóng diện tích · Ma trận suy biến · Vì sao không nên tính nghịch đảo trực tiếp (np.linalg.solve thay vì inv) · Ma trận đối xứng'],
      ['he-phuong-trinh', 'Systems of linear equations and least squares', 'Hệ phương trình tuyến tính và bình phương tối thiểu', 'Ax = b có nghiệm, vô nghiệm, vô số nghiệm · Khử Gauss bằng tay một lần · Bình phương tối thiểu khi dữ liệu nhiễu · Phương trình chuẩn XᵀXw = Xᵀy'],
      ['tensor', 'From matrices to tensors: batches, images and attention shapes', 'Từ ma trận tới tensor: batch, ảnh và shape của attention', 'Tensor 3–4 chiều (batch × kênh × cao × rộng) · Phép nhân theo batch, einsum · Broadcasting nhắc lại (trỏ /courses/machine-learning 3.2) · Đọc shape (B, T, d) trong code LLM'],
    ]],
    ['Chapter 4 — Deeper linear algebra: rank, eigenvectors, SVD and PCA', 'Chương 4 — Đại số tuyến tính sâu hơn: hạng, vector riêng, SVD và PCA', 'Những công cụ nén và hiểu dữ liệu nhiều chiều.', [
      ['doc-lap-hang', 'Linear independence, basis, dimension and rank', 'Độc lập tuyến tính, cơ sở, số chiều và hạng', 'Đặc trưng trùng lặp = phụ thuộc tuyến tính · Cơ sở và đổi cơ sở · Hạng của ma trận dữ liệu · Ma trận hạng thấp — ý tưởng đứng sau LoRA'],
      ['tri-rieng', 'Eigenvalues and eigenvectors, visually', 'Trị riêng và vector riêng, bằng hình', 'Hướng không bị xoay khi biến đổi · Av = λv · Phân rã trị riêng của ma trận đối xứng · PageRank của Google (1998) là một bài toán vector riêng'],
      ['svd', 'Singular Value Decomposition (SVD)', 'Phân tích giá trị suy biến (SVD)', 'Mọi ma trận = xoay · co giãn · xoay · Nén ảnh bằng SVD cắt bớt · Giải thưởng Netflix Prize 2006–2009 và phân rã ma trận gợi ý · np.linalg.svd'],
      ['pca-tu-dau', 'PCA from scratch: covariance, eigenvectors and explained variance', 'PCA từ con số 0: hiệp phương sai, vector riêng và phương sai giải thích', 'Ma trận hiệp phương sai · PCA = SVD của dữ liệu đã trừ trung bình · Tự cài PCA rồi so với sklearn (cách dùng sklearn đã ở /courses/machine-learning 9.3) · Chọn số thành phần'],
      ['chuan-ma-tran', 'Matrix norms, condition number and numerical stability', 'Chuẩn ma trận, số điều kiện và độ ổn định số', 'Chuẩn Frobenius và chuẩn phổ · Số điều kiện lớn = sai số nhỏ thành sai số to · Vì sao chuẩn hoá đặc trưng giúp mô hình hội tụ · Regularization ridge làm ma trận "dễ chịu" hơn'],
    ]],
    ['Chapter 5 — Single-variable calculus', 'Chương 5 — Giải tích một biến', 'Đạo hàm là tốc độ thay đổi — thứ mọi thuật toán học đều cần.', [
      ['gioi-han', 'Limits and continuity, just enough', 'Giới hạn và tính liên tục, vừa đủ', 'Tiến gần tới một điểm · Hàm có góc nhọn (ReLU tại 0) · Không chứng minh epsilon-delta'],
      ['dao-ham', 'The derivative: slope, rate of change and numerical derivatives', 'Đạo hàm: độ dốc, tốc độ thay đổi và đạo hàm số', 'Định nghĩa bằng giới hạn · Tính đạo hàm số bằng sai phân hữu hạn · Kiểm gradient (gradient check) — mẹo debug thật'],
      ['quy-tac', 'Derivative rules and the chain rule', 'Các quy tắc đạo hàm và quy tắc chuỗi', 'Tổng, tích, thương · Quy tắc chuỗi — trái tim của backpropagation · Đạo hàm sigmoid, tanh, ReLU, exp, log · Kiểm bằng SymPy'],
      ['cuc-tri', 'Minima, maxima and convexity in one dimension', 'Cực tiểu, cực đại và tính lồi trong một chiều', 'Đạo hàm bằng 0 · Đạo hàm bậc hai và độ cong · Hàm lồi có một đáy duy nhất · Taylor bậc một/hai — xấp xỉ cục bộ'],
      ['tich-phan', 'Integrals as area and expectation (intuition only)', 'Tích phân như diện tích và kỳ vọng (chỉ trực giác)', 'Diện tích dưới đường cong · Hàm mật độ xác suất có diện tích bằng 1 · Xấp xỉ tích phân bằng tổng và bằng mô phỏng Monte Carlo'],
    ]],
    ['Chapter 6 — Multivariable calculus and backpropagation', 'Chương 6 — Giải tích nhiều biến và backpropagation', 'Gradient cho biết đi hướng nào để loss giảm nhanh nhất.', [
      ['dao-ham-rieng', 'Partial derivatives and the gradient vector', 'Đạo hàm riêng và vector gradient', 'Cố định các biến khác · Gradient chỉ hướng dốc lên nhất · Vẽ mặt loss 3D và đường đồng mức'],
      ['jacobian-hessian', 'Jacobian and Hessian matrices', 'Ma trận Jacobian và Hessian', 'Jacobian khi đầu ra là vector · Hessian và độ cong · Điểm yên ngựa (saddle point) trong mạng sâu'],
      ['chuoi-nhieu-bien', 'The multivariable chain rule and computational graphs', 'Quy tắc chuỗi nhiều biến và đồ thị tính toán', 'Vẽ đồ thị tính toán · Lan truyền ngược = áp quy tắc chuỗi từ cuối về đầu · Chế độ thuận vs chế độ ngược (forward vs reverse mode)'],
      ['backprop-tay', 'Backpropagation by hand for a tiny network', 'Backpropagation bằng tay cho một mạng tí hon', 'Mạng 2 nơ-ron, tính từng đạo hàm trên giấy · Đạo hàm ma trận: dL/dW = δ·xᵀ · Kiểm lại bằng gradient check · Autograd của PyTorch tự làm việc này (trỏ /courses/deep-learning Chương 1, không dạy lại)'],
    ]],
    ['Chapter 7 — Optimization', 'Chương 7 — Tối ưu hoá', 'Huấn luyện mô hình chính là giải một bài toán tối ưu.', [
      ['gradient-descent', 'Gradient descent from scratch, and the learning rate', 'Gradient descent tự viết, và tốc độ học', 'Nếu đã học /courses/machine-learning 1.3: nhắc nhanh trực giác · Tự cài bằng numpy · Learning rate quá lớn/quá nhỏ bằng hình · Điều kiện dừng'],
      ['sgd-minibatch', 'Stochastic and mini-batch gradient descent', 'Gradient descent ngẫu nhiên và theo mini-batch', 'Ước lượng gradient bằng mẫu · Nhiễu có ích · Kích thước batch và tốc độ'],
      ['momentum-adam', 'Momentum, RMSProp and Adam — the math behind the optimizers', 'Momentum, RMSProp và Adam — toán đằng sau các optimizer', 'Trung bình trượt mũ · Momentum như hòn bi lăn · Adam (Kingma & Ba 2014) từng dòng công thức · Tự cài rồi so với torch.optim (cách dùng ở /courses/deep-learning 3.2)'],
      ['loi-khong-loi', 'Convex vs non-convex problems, local minima and saddle points', 'Bài toán lồi và không lồi, cực tiểu địa phương và điểm yên ngựa', 'Vì sao hồi quy tuyến tính có nghiệm duy nhất còn mạng nơ-ron thì không · Khởi tạo trọng số · Learning rate schedule nhìn từ toán'],
      ['rang-buoc', 'Constrained optimization and Lagrange multipliers', 'Tối ưu có ràng buộc và nhân tử Lagrange', 'Tối ưu trên một đường cong · Nhân tử Lagrange bằng hình · Liên hệ SVM và regularization như ràng buộc'],
    ]],
    ['Chapter 8 — Probability', 'Chương 8 — Xác suất', 'Ngôn ngữ để nói về sự không chắc chắn — model nào cũng trả ra xác suất.', [
      ['neu-da-hoc-ml-ch2', 'If you took Machine Learning Ch2: the parts we go deeper on', 'Nếu đã học Machine Learning Chương 2: phần sẽ đi sâu hơn', 'ML Ch2 đã có phân phối, xác suất cơ bản, tương quan ≠ nhân quả, lấy mẫu · Ở đây thêm: xác suất có điều kiện, Bayes, biến ngẫu nhiên nhiều chiều · Thống kê suy luận (kiểm định, khoảng tin cậy) KHÔNG ở đây — xem /courses/statistics-data-science'],
      ['xac-suat-dieu-kien', 'Events, conditional probability and independence', 'Biến cố, xác suất có điều kiện và độc lập', 'Không gian mẫu · P(A|B) bằng bảng đếm · Độc lập vs không tương quan · Mô phỏng bằng numpy để kiểm trực giác'],
      ['bayes', "Bayes' theorem and the base-rate trap", 'Định lý Bayes và cái bẫy tỉ lệ nền', 'Xét nghiệm bệnh hiếm dương tính thì xác suất mắc thật bao nhiêu · Prior, likelihood, posterior · Bộ lọc thư rác Naive Bayes (Paul Graham "A Plan for Spam" 2002)'],
      ['bien-ngau-nhien', 'Random variables, expectation and variance', 'Biến ngẫu nhiên, kỳ vọng và phương sai', 'Rời rạc vs liên tục · Kỳ vọng là trung bình có trọng số · Phương sai, độ lệch chuẩn · Tính chất tuyến tính của kỳ vọng'],
      ['phan-phoi', 'The distributions ML uses: Bernoulli, binomial, categorical, Poisson, uniform, normal', 'Các phân phối ML dùng: Bernoulli, nhị thức, categorical, Poisson, đều, chuẩn', 'Mỗi phân phối một câu chuyện đời thực · Softmax ra một phân phối categorical · Phân phối chuẩn và vì sao nó ở khắp nơi · Lấy mẫu bằng numpy.random'],
      ['nhieu-bien', 'Joint, marginal and conditional distributions; covariance and the multivariate normal', 'Phân phối đồng thời, biên và có điều kiện; hiệp phương sai và phân phối chuẩn nhiều chiều', 'Bảng phân phối đồng thời · Lấy biên = cộng theo hàng/cột · Ma trận hiệp phương sai (nối với Chương 4) · Gaussian nhiều chiều — nền của phát hiện bất thường'],
    ]],
    ['Chapter 9 — Estimation and information theory', 'Chương 9 — Ước lượng và lý thuyết thông tin', 'Vì sao loss của phân loại là cross-entropy, và KL divergence đo cái gì.', [
      ['mle', 'Maximum likelihood estimation (MLE)', 'Ước lượng hợp lý cực đại (MLE)', 'Chọn tham số làm dữ liệu "ít bất ngờ" nhất · MLE của tung đồng xu và của phân phối chuẩn · MSE chính là MLE khi nhiễu Gaussian'],
      ['map', 'MAP estimation, priors and regularization', 'Ước lượng MAP, tiên nghiệm và regularization', 'Thêm prior vào MLE · Prior Gaussian = L2 (ridge), prior Laplace = L1 (lasso) · Khi dữ liệu ít thì prior quan trọng'],
      ['entropy', 'Entropy and information (Shannon, 1948)', 'Entropy và thông tin (Shannon, 1948)', 'Claude Shannon "A Mathematical Theory of Communication" 1948 · Entropy = độ bất ngờ trung bình · Bit và nat · Entropy trong cây quyết định (trỏ /courses/machine-learning 8.1)'],
      ['cross-entropy-kl', 'Cross-entropy, KL divergence and why classifiers use log loss', 'Cross-entropy, KL divergence và vì sao bộ phân loại dùng log loss', 'Cross-entropy = MLE của phân loại · KL không đối xứng · Perplexity của LLM = mũ của cross-entropy · KL trong RLHF/DPO và VAE'],
      ['softmax-on-dinh', 'Softmax, sigmoid and log-sum-exp: computing them without overflow', 'Softmax, sigmoid và log-sum-exp: tính mà không tràn số', 'Softmax với nhiệt độ (temperature của LLM) · Trừ max trước khi exp · log_softmax · Bug NaN thật và cách tìm'],
    ]],
    ['Chapter 10 — The math inside real models, in plain numpy', 'Chương 10 — Toán bên trong mô hình thật, bằng numpy thuần', 'Ráp mọi thứ: tự viết các mô hình mà thư viện vẫn giấu đi.', [
      ['hoi-quy-tuyen-tinh', 'Linear regression three ways: normal equation, gradient descent, SVD', 'Hồi quy tuyến tính ba cách: phương trình chuẩn, gradient descent, SVD', 'Cùng một bài toán, ba lời giải · Khi nào cách nào nhanh/ổn định hơn · So với sklearn LinearRegression'],
      ['logistic', 'Logistic regression: deriving the gradient of log loss', 'Hồi quy logistic: tự suy gradient của log loss', 'Sigmoid + cross-entropy · Gradient gọn bất ngờ (ŷ − y)x · Tự cài và vẽ biên quyết định'],
      ['mang-hai-lop', 'A two-layer neural network with backprop, from scratch', 'Mạng nơ-ron hai lớp có backprop, tự viết từ đầu', 'Forward, loss, backward, update — mỗi bước một dòng toán · Huấn luyện trên dữ liệu chữ số nhỏ · Gradient check để chắc đúng'],
      ['attention-toan', 'Attention as matrix math: QKᵀ, scaling by √d and softmax', 'Attention dưới góc nhìn toán: QKᵀ, chia √d và softmax', 'Vì sao chia √d (phương sai của tích vô hướng) · Mặt nạ nhân quả bằng ma trận tam giác · Tự viết bằng numpy (bản PyTorch ở /courses/deep-learning 5.4)'],
    ]],
    ['Chapter 11 — Numbers on real computers', 'Chương 11 — Con số trên máy tính thật', 'Toán trên giấy là số thực; trên GPU là float có giới hạn.', [
      ['float', 'Floating point: float32, float16, bfloat16 and FP8', 'Số thực dấu phẩy động: float32, float16, bfloat16 và FP8', 'Chuẩn IEEE 754 (1985) · Dấu, mũ, phần định trị · 0.1 + 0.2 ≠ 0.3 · Vì sao Google tạo bfloat16 cho TPU'],
      ['tran-so', 'Overflow, underflow and catastrophic cancellation', 'Tràn số trên, tràn số dưới và triệt tiêu thảm hoạ', 'Loss ra NaN/inf · Xác suất nhân mãi về 0 — vì thế dùng log · Loss scaling trong mixed precision (cách bật ở /courses/deep-learning 7.2)'],
      ['luong-tu-hoa', 'The math of quantization: scale, zero-point and error', 'Toán của lượng tử hoá: scale, zero-point và sai số', 'Ánh xạ float → int8/int4 · Sai số làm tròn · Vì sao model 4-bit vẫn chạy được · Trỏ /courses/deep-learning 9.1 và /courses/mlops-llmops cho phần phục vụ'],
      ['flops-bo-nho', 'Counting FLOPs and memory: how big a model fits on your GPU', 'Đếm FLOPs và bộ nhớ: model cỡ nào vừa GPU của bạn', 'FLOPs của phép nhân ma trận · Quy tắc ~6·N·D FLOPs huấn luyện (scaling laws, Kaplan 2020; Chinchilla 2022) · Bộ nhớ tham số + KV cache · Ví dụ: model 7B ở fp16 cần bao nhiêu GB'],
    ]],
    ['Chapter 12 — Reading papers, interviews and where to go next', 'Chương 12 — Đọc paper, phỏng vấn và học tiếp ở đâu', 'Dùng toán đã học để đọc tài liệu gốc và vượt vòng phỏng vấn.', [
      ['doc-paper', 'Reading an ML paper: "Attention Is All You Need" section by section', 'Đọc một paper ML: "Attention Is All You Need" từng phần', 'Cấu trúc một paper · Dịch các công thức chính sang code · Bỏ qua gì ở lần đọc đầu · Dùng AI làm gia sư đọc paper mà không để nó đọc hộ'],
      ['phong-van', 'Math interview questions for AI/ML and Data Science roles', 'Câu hỏi phỏng vấn toán cho vị trí AI/ML và Data Science', '30 câu hay gặp: dot product, eigen, gradient, Bayes, MLE, cross-entropy, bias–variance · Cách trả lời bằng hình + một dòng công thức · Bẫy hay gặp'],
      ['hoc-tiep', 'Where to go next: real courses and books (there is no "math for ML" certificate)', 'Học tiếp ở đâu: khoá và sách có thật (không có chứng chỉ "toán cho ML")', 'MIT 18.06 (Strang), Imperial College "Mathematics for Machine Learning" trên Coursera, Stanford CS229 · Sách MML (Deisenroth) · Chứng chỉ ML thật nằm ở tầng sau (AWS ML Engineer, Google Professional ML Engineer) — xem /courses/mlops-llmops'],
    ]],
    ['Chapter 13 — Capstone: sensor anomaly detection for LabFlow AI in plain numpy', 'Chương 13 — Dự án cuối khoá: phát hiện bất thường cảm biến cho LabFlow AI bằng numpy thuần', 'Dùng đại số tuyến tính, xác suất và tối ưu trên dữ liệu cảm biến phòng lab.', [
      ['bai-toan', 'The problem: lab sensor readings (temperature, humidity, power) and what "abnormal" means', 'Bài toán: số đo cảm biến phòng lab (nhiệt độ, độ ẩm, điện năng) và "bất thường" nghĩa là gì', 'Dữ liệu AIoT của LabFlow (giả lập có seed) · Định nghĩa bất thường · Chia train/test theo thời gian · Chỉ số đánh giá'],
      ['pca-gaussian', 'PCA plus a multivariate Gaussian: an anomaly score from first principles', 'PCA cộng Gaussian nhiều chiều: điểm bất thường từ nguyên lý gốc', 'Chuẩn hoá · Giảm chiều bằng PCA tự viết · Ước lượng μ, Σ bằng MLE · Khoảng cách Mahalanobis làm điểm bất thường'],
      ['logistic-canh-bao', 'A logistic-regression alert model trained with your own Adam', 'Mô hình cảnh báo bằng hồi quy logistic huấn luyện bằng Adam tự viết', 'Gán nhãn sự cố đã biết · Huấn luyện bằng optimizer Chương 7 · Ngưỡng cảnh báo và đánh đổi báo nhầm/bỏ sót'],
      ['so-sanh-bao-cao', 'Compare with scikit-learn, write it up, and tell the story in an interview', 'So với scikit-learn, viết báo cáo và kể lại khi phỏng vấn', 'Kết quả tự viết vs sklearn phải khớp · Notebook tái lập được · Đoạn này sẽ được dùng lại ở /courses/statistics-data-science và /courses/mlops-llmops · Checklist toàn khoá'],
    ]],
  ]),
};
