/**
 * MLOps & LLMOps — khoá học CuongThai (Courses, GENERAL). KHUNG dựng 01/10/2026 theo kế hoạch lộ trình 6 nghề
 * (content/courses/_KE-HOACH-LO-TRINH-NGHE-0110.md, gói A). Khoá này SỞ HỮU: tái lập & theo dõi thí nghiệm, feature store,
 * pipeline huấn luyện, registry & đóng gói model, phục vụ model (cổ điển + LLM: vLLM, KV cache, batching), pipeline fine-tune,
 * giám sát drift, eval & quan sát LLM trên production, quản trị/tuân thủ AI, nền tảng ML và FinOps cho ML.
 * Ranh giới: LoRA/quantization ở mức thư viện thuộc deep-learning Ch8–9; gọi API/prompt/guardrail cơ bản thuộc llm-apps;
 * eval OFFLINE và LLM-as-judge thuộc ai-agents Ch7–8; RAG eval thuộc rag-vector-search Ch8; log/metric/trace chung thuộc
 * observability-monitoring; Docker/K8s thuộc docker/kubernetes; Airflow/Spark thuộc spark-lakehouse.
 * Soạn chi tiết sau theo quy trình khoá Docker (content/courses/docker/_HOP-DONG.md). Xem _chung/khung.mjs.
 */
import { khung } from './_chung/khung.mjs';

export default {
  category: { slug: 'ai', name: 'AI & Tự động hoá', icon: 'Sparkles', sortOrder: 6 },
  course: {
    slug: 'mlops-llmops',
    title: 'MLOps & LLMOps',
    level: 'ADVANCED',
    language: 'Vietnamese',
    status: 'PUBLISHED',
    isFeatured: false,
    syncOrder: true,
    thumbnailUrl: 'https://media.cuongthai.com/images/course-covers/mlops-llmops.png?v=4',
    shortDescription: 'Models from notebook to production, kept healthy: reproducible training, MLflow registry, serving models and LLMs with vLLM, fine-tuning pipelines, drift monitoring, online evals, tracing, governance and GPU cost.|||Đưa model từ notebook lên production và giữ nó khoẻ: huấn luyện tái lập, registry MLflow, phục vụ model và LLM bằng vLLM, pipeline fine-tune, giám sát drift, eval trực tuyến, tracing, quản trị, chi phí GPU.',
    description: 'Khoá cho người đã huấn luyện được model (Machine Learning / Deep Learning) và đã gọi LLM trong ứng dụng (LLM Apps), giờ cần vận hành chúng thật. Mở đầu bằng "nợ kỹ thuật ẩn trong hệ thống ML" (Google, NeurIPS 2015) và các sự cố có tên: Zillow Offers 2021, chatbot Air Canada 2024, Microsoft Tay 2016. Nội dung: vòng đời và mức trưởng thành MLOps; tái lập (DVC, MLflow tracking, Hydra, Docker); feature store và pipeline huấn luyện; registry, định dạng model (ONNX, safetensors) và an toàn chuỗi cung ứng model; phục vụ model cổ điển (FastAPI, BentoML, KServe, Triton; canary/shadow); phục vụ LLM (vLLM, PagedAttention, continuous batching, KV cache, lượng tử hoá AWQ/GPTQ/FP8, gateway LiteLLM, fallback, cache); pipeline fine-tune (làm sạch dữ liệu, LoRA/QLoRA, DPO, multi-LoRA serving); giám sát drift (PSI, KS, Evidently); LLMOps (tracing Langfuse/OpenTelemetry GenAI, eval trực tuyến, quản lý phiên bản prompt, chi phí theo tính năng); quản trị & tuân thủ (OWASP Top 10 cho LLM, EU AI Act, NIST AI RMF, model card); nền tảng ML và FinOps GPU. Dự án cuối khoá đưa trợ lý AI và model phát hiện bất thường của LabFlow AI lên production.',
    whatYouLearn: 'Làm cho mọi lượt huấn luyện tái lập được và tra lại được; dựng MLflow tracking + registry; đóng gói và phục vụ model bằng FastAPI/BentoML/KServe với canary và rollback; tự host LLM bằng vLLM, đo TTFT/TPOT/throughput và chọn GPU; đặt gateway LLM có fallback và cache; dựng pipeline fine-tune LoRA từ dữ liệu tới đánh giá tới phục vụ; giám sát data drift và chất lượng model khi chưa có nhãn; tracing và eval LLM trên production, regression test prompt trong CI; áp OWASP LLM Top 10 và viết model card; ước lượng và cắt chi phí GPU; trả lời câu hỏi thiết kế hệ thống ML trong phỏng vấn.',
    requirements: 'Python vững, đã huấn luyện được model (khoá Machine Learning /courses/machine-learning và Deep Learning /courses/deep-learning), đã gọi LLM trong ứng dụng (LLM Apps /courses/llm-apps). Docker (/courses/docker) bắt buộc; Kubernetes (/courses/kubernetes) và Observability (/courses/observability-monitoring) nên học trước Chương 5, 8, 9. Biết RAG (/courses/rag-vector-search) và AI Agents (/courses/ai-agents) là lợi thế. Có GPU NVIDIA (máy nhà) giúp làm lab LLM; không có thì dùng GPU thuê theo giờ hoặc model nhỏ trên CPU.',
    documentsNote: 'Tài liệu chính: "Hidden Technical Debt in Machine Learning Systems" (Sculley et al., NeurIPS 2015) • "Designing Machine Learning Systems" (Chip Huyen, O’Reilly 2022) • Google Cloud — "MLOps: Continuous delivery and automation pipelines in machine learning" (cloud.google.com/architecture) • mlflow.org/docs • docs.vllm.ai và paper PagedAttention (Kwon et al., SOSP 2023) • kserve.github.io • docs.evidentlyai.com • langfuse.com/docs • OpenTelemetry GenAI semantic conventions (opentelemetry.io) • OWASP Top 10 for LLM Applications (genai.owasp.org) • NIST AI Risk Management Framework (nist.gov) • Văn bản EU AI Act (Regulation (EU) 2024/1689, eur-lex.europa.eu) • huggingface.co/docs (PEFT, TRL).',
  },
  sections: khung('mlops', [
    ['Section 0 — Why models die in production', 'Mục 0 — Vì sao model chết trên production', 'MLOps/LLMOps là gì, những sự cố thật, và dựng phòng lab.', [
      ['bat-dau-tai-day', 'Start here (1/2) — MLOps and LLMOps in everyday words, their history, and real production failures', 'Bắt đầu tại đây (1/2) — MLOps và LLMOps bằng lời đời thường, lịch sử, và những sự cố production có thật', 'Model chỉ là phần nhỏ của hệ thống ML · Mốc: "Hidden Technical Debt in ML Systems" (Google, NeurIPS 2015), Uber Michelangelo 2017, MLflow và Kubeflow 2018, vLLM/PagedAttention 2023, chữ "LLMOps" phổ biến từ 2023 · Sự cố thật: Zillow Offers đóng cửa 2021 sau thua lỗ vì model định giá nhà, chatbot Air Canada bị toà buộc bồi thường 2024 (Moffatt v. Air Canada), Microsoft Tay bị gỡ sau 16 giờ năm 2016, công cụ tuyển dụng của Amazon bị bỏ vì thiên lệch (Reuters 2018) · Vì sao "model tốt trên notebook" chưa phải sản phẩm'],
      ['bat-dau-hoc-xong', 'Start here (2/2) — What you can do after this course, where it sits in the AI Engineer roadmap, and how to study', 'Bắt đầu tại đây (2/2) — Học xong làm được gì, khoá nằm ở đâu trong lộ trình AI Engineer, và cách học', 'Vị trí: MLOps engineer, ML platform engineer, AI engineer làm hạ tầng LLM · Lộ trình: math-for-ml → machine-learning → deep-learning → llm-apps → rag-vector-search / ai-agents → mlops-llmops; hạ tầng: docker → kubernetes → observability-monitoring · Trong chuỗi LabFlow: nhận dữ liệu từ lakehouse (/courses/spark-lakehouse), đặc trưng từ Data Scientist (/courses/statistics-data-science), đưa lên cloud ở khoá Cloud Architecture · Cách học: mỗi chương một dịch vụ chạy thật trong Docker Compose'],
      ['cai-dat', 'The lab: Docker Compose with MLflow, MinIO, PostgreSQL, Prometheus/Grafana — and a GPU if you have one', 'Phòng lab: Docker Compose gồm MLflow, MinIO, PostgreSQL, Prometheus/Grafana — và GPU nếu có', 'Một file compose cho cả khoá · NVIDIA Container Toolkit trên máy Linux có GPU (trỏ /courses/docker 14.4) · Không có GPU: model nhỏ trên CPU hoặc thuê GPU theo giờ · Kiểm phòng lab bằng một lượt huấn luyện mẫu'],
      ['neu-da-hoc', 'If you took Deep Learning, LLM Apps and AI Agents: what is already covered and what this course adds', 'Nếu đã học Deep Learning, LLM Apps và AI Agents: phần đã có và phần khoá này thêm', 'Đã có: LoRA/quantization ở mức thư viện (/courses/deep-learning Ch8–9), một API phục vụ model (DL 10.3), guardrail & chi phí cơ bản (/courses/llm-apps Ch6–7), eval offline & LLM-as-judge (/courses/ai-agents Ch7–8) · Khoá này thêm: chạy chúng liên tục, có phiên bản, có giám sát, có rollback, nhiều người dùng cùng lúc · Bảng đối chiếu để bỏ qua phần đã vững'],
    ]],
    ['Chapter 1 — The ML lifecycle in production', 'Chương 1 — Vòng đời ML trên production', 'Nhìn toàn cảnh trước khi dựng từng mảnh.', [
      ['vong-doi', 'The lifecycle: data, training, evaluation, deployment, monitoring, retraining', 'Vòng đời: dữ liệu, huấn luyện, đánh giá, triển khai, giám sát, huấn luyện lại', 'Sơ đồ vòng lặp · Ai làm phần nào trong nhóm · Điểm khác với phần mềm thường: code + dữ liệu + model đều có phiên bản'],
      ['muc-truong-thanh', 'MLOps maturity levels (Google level 0–2) and where most teams really are', 'Các mức trưởng thành MLOps (Google mức 0–2) và đa số nhóm thật ra đang ở đâu', 'Mức 0: notebook + copy tay · Mức 1: pipeline huấn luyện tự động · Mức 2: CI/CD cho pipeline · Đừng nhảy cóc: đồ án sinh viên thường cần mức 1'],
      ['skew-no-ky-thuat', 'Training–serving skew and ML-specific technical debt', 'Lệch giữa lúc huấn luyện và lúc phục vụ, và nợ kỹ thuật riêng của ML', 'Cùng một đặc trưng, hai đoạn code tính khác nhau · Phụ thuộc dữ liệu ẩn · Vòng phản hồi (model ảnh hưởng dữ liệu huấn luyện sau) · Danh sách kiểm "ML Test Score" (Google 2017)'],
      ['ci-cd-ct', 'CI, CD and CT: continuous training and what to test in an ML system', 'CI, CD và CT: huấn luyện liên tục và kiểm gì trong một hệ thống ML', 'Kiểm dữ liệu, kiểm model, kiểm hạ tầng · Cổng chất lượng trước khi lên · GitHub Actions cho pipeline ML (cú pháp ở /courses/github-actions)'],
    ]],
    ['Chapter 2 — Reproducibility and experiment tracking', 'Chương 2 — Tái lập và theo dõi thí nghiệm', 'Mọi model trên production phải trả lời được: dữ liệu nào, code nào, cấu hình nào.', [
      ['phien-ban-du-lieu', 'Versioning data with DVC or lakeFS', 'Quản lý phiên bản dữ liệu với DVC hoặc lakeFS', 'Vì sao Git không chứa nổi dữ liệu · DVC trỏ tới object storage (MinIO/R2) · lakeFS như Git cho data lake · Bảng Iceberg time travel là một lựa chọn khác (trỏ /courses/spark-lakehouse Chương 6)'],
      ['mlflow-tracking', 'Experiment tracking with MLflow: params, metrics, artifacts', 'Theo dõi thí nghiệm với MLflow: tham số, chỉ số, artifact', 'Tự host MLflow server với PostgreSQL + MinIO · autolog · So sánh các lượt chạy · Weights & Biases như lựa chọn dịch vụ'],
      ['moi-truong-co-dinh', 'Pinning the environment: lockfiles, Docker images, seeds and determinism on GPU', 'Cố định môi trường: lockfile, ảnh Docker, seed và tính tất định trên GPU', 'uv lock · Ảnh huấn luyện có digest · Seed không đủ: thuật toán cuDNN không tất định · Ghi mã commit vào mỗi lượt chạy'],
      ['cau-hinh', 'Configuration management with Hydra and sweeps', 'Quản lý cấu hình với Hydra và quét siêu tham số', 'Cấu hình phân tầng · Ghi đè từ dòng lệnh · Quét bằng Optuna · Không bao giờ sửa siêu tham số trong code'],
    ]],
    ['Chapter 3 — Features and training pipelines', 'Chương 3 — Đặc trưng và pipeline huấn luyện', 'Biến notebook thành pipeline chạy lại được mỗi tuần.', [
      ['feature-store', 'Feature stores: why they exist, and Feast hands-on', 'Feature store: vì sao tồn tại, và thực hành Feast', 'Một định nghĩa đặc trưng cho cả huấn luyện và phục vụ · Kho offline (Parquet/lakehouse) vs online (Redis) · Khi nào chưa cần feature store'],
      ['point-in-time', 'Point-in-time correct joins and label leakage', 'Join đúng thời điểm và rò rỉ nhãn', 'Đặc trưng "từ tương lai" làm model đẹp giả · As-of join · Rò rỉ dữ liệu cơ bản đã ở /courses/machine-learning 5.4 — ở đây là bản theo thời gian trên production'],
      ['pipeline', 'Training pipelines as code: Prefect, ZenML or Kubeflow Pipelines', 'Pipeline huấn luyện dưới dạng code: Prefect, ZenML hoặc Kubeflow Pipelines', 'Bước = hàm có đầu vào/đầu ra có phiên bản · Bộ nhớ đệm bước · Chọn công cụ theo quy mô · Điều phối dữ liệu bằng Airflow ở /courses/spark-lakehouse Chương 8'],
      ['huan-luyen-phan-tan', 'Distributed training at a glance: DDP, FSDP, DeepSpeed and Ray Train', 'Lướt qua huấn luyện phân tán: DDP, FSDP, DeepSpeed và Ray Train', 'Song song dữ liệu vs song song model · Khi nào một GPU là đủ · Điểm kiểm (checkpoint) và tiếp tục khi bị ngắt · Chi phí mạng giữa GPU'],
    ]],
    ['Chapter 4 — Model registry and packaging', 'Chương 4 — Registry và đóng gói model', 'Một model đã duyệt là một artifact có phiên bản, có chữ ký, có hồ sơ.', [
      ['registry', 'MLflow Model Registry: versions, aliases and promotion', 'MLflow Model Registry: phiên bản, alias và thăng cấp', 'Alias "champion"/"challenger" · Quy trình duyệt · Ghi chỉ số đánh giá kèm phiên bản · Quay lui bằng cách đổi alias'],
      ['dinh-dang', 'Model formats: pickle, TorchScript, ONNX, safetensors, GGUF', 'Định dạng model: pickle, TorchScript, ONNX, safetensors, GGUF', 'Ưu nhược từng định dạng · ONNX Runtime để chạy nhanh trên CPU · GGUF cho llama.cpp · Chọn định dạng theo nơi chạy'],
      ['chuoi-cung-ung-model', 'Model supply-chain security: unsafe pickles, signing and provenance', 'An toàn chuỗi cung ứng model: pickle độc, ký số và nguồn gốc', 'Tải file pickle là chạy code của người khác · safetensors ra đời vì thế (Hugging Face 2022) · Quét model, ký bằng Sigstore · Chuỗi cung ứng phần mềm chung ở /courses/devsecops'],
      ['model-card', 'Model cards, datasheets and the information that must travel with a model', 'Model card, datasheet và thông tin phải đi kèm model', 'Model Cards (Mitchell et al. 2019) · Datasheets for Datasets (Gebru et al. 2018) · Dữ liệu huấn luyện, giới hạn, chỉ số theo nhóm · Mẫu model card cho LabFlow'],
      ['anh-phuc-vu', 'Building lean serving images for models', 'Dựng ảnh phục vụ model gọn nhẹ', 'Tách trọng số khỏi ảnh hay nhúng vào · Ảnh CUDA nặng nhiều GB và cách giảm · Tải model lúc khởi động và readiness probe · Kỹ thuật Dockerfile chung ở /courses/docker Chương 6'],
    ]],
    ['Chapter 5 — Serving classic models', 'Chương 5 — Phục vụ model cổ điển', 'Trả dự đoán nhanh, ổn định và thay model mà không làm người dùng giật mình.', [
      ['kieu-suy-luan', 'Online, batch and streaming inference: choosing the pattern', 'Suy luận trực tuyến, theo lô và theo luồng: chọn mẫu', 'Dự đoán trước theo lô rồi lưu vào bảng · API thời gian thực · Theo luồng từ Kafka (trỏ /courses/kafka) · Bảng chọn theo độ trễ và chi phí'],
      ['cong-cu-phuc-vu', 'FastAPI vs BentoML vs Triton vs KServe', 'FastAPI vs BentoML vs Triton vs KServe', 'Tự viết bằng FastAPI (trỏ /courses/fastapi) · BentoML đóng gói chuẩn · NVIDIA Triton cho nhiều model và GPU · KServe trên Kubernetes · Gom lô động (dynamic batching)'],
      ['kserve-autoscale', 'KServe on Kubernetes: InferenceService, autoscaling and scale-to-zero', 'KServe trên Kubernetes: InferenceService, tự co giãn và co về 0', 'Một manifest phục vụ model · Co giãn theo số request (Knative) · Khởi động lạnh của model lớn · HPA cơ bản ở /courses/kubernetes 6.3'],
      ['trien-khai-an-toan', 'Safe rollouts for models: shadow, canary, A/B and rollback', 'Triển khai model an toàn: shadow, canary, A/B và quay lui', 'Shadow: chạy song song không trả kết quả · Canary theo % lưu lượng · A/B đo tác động kinh doanh (thiết kế thí nghiệm ở /courses/statistics-data-science Chương 8) · Quay lui trong 1 phút'],
      ['hieu-nang', 'Latency budgets, load testing and CPU optimizations for inference', 'Ngân sách độ trễ, kiểm tải và tối ưu CPU cho suy luận', 'p50/p95/p99 · Kiểm tải bằng k6 (trỏ /courses/performance-load-testing) · ONNX Runtime, lượng tử hoá int8 cho CPU · Cache kết quả dự đoán'],
    ]],
    ['Chapter 6 — Serving LLMs', 'Chương 6 — Phục vụ LLM', 'Tự host model ngôn ngữ lớn: bộ nhớ, batching, đo đạc và chi phí.', [
      ['vi-sao-tu-host', 'API vs self-hosting an LLM: cost, privacy, latency and control', 'Gọi API hay tự host LLM: chi phí, quyền riêng tư, độ trễ và quyền kiểm soát', 'Điểm hoà vốn theo số token/ngày · Dữ liệu không được rời máy chủ · Model mở: Llama, Qwen, Mistral, Gemma · So sánh nhanh với "chạy cục bộ" ở /courses/deep-learning Chương 9'],
      ['vllm', 'vLLM: PagedAttention, continuous batching and the OpenAI-compatible server', 'vLLM: PagedAttention, continuous batching và server tương thích OpenAI', 'Paper PagedAttention (SOSP 2023) bằng hình · KV cache là gì và vì sao ngốn VRAM · Continuous batching vs static batching · Chạy vLLM trong Docker với GPU'],
      ['engine-khac', 'Other engines: TGI, SGLang, TensorRT-LLM, llama.cpp and Ollama', 'Các engine khác: TGI, SGLang, TensorRT-LLM, llama.cpp và Ollama', 'Bảng so sánh theo phần cứng và quy mô · Ollama/llama.cpp cho máy cá nhân · Prefix caching và speculative decoding'],
      ['luong-tu-hoa-phuc-vu', 'Quantization for serving: AWQ, GPTQ, FP8 and measuring the quality loss', 'Lượng tử hoá để phục vụ: AWQ, GPTQ, FP8 và đo mức mất chất lượng', 'Toán lượng tử hoá ở /courses/math-for-ml 11.3, thư viện ở /courses/deep-learning 9.1 — ở đây: chọn định dạng cho vLLM · Đo trên bộ eval của chính bạn, không tin bảng xếp hạng'],
      ['do-dac-gpu', 'Measuring LLM serving: TTFT, TPOT, throughput — and sizing GPUs', 'Đo phục vụ LLM: TTFT, TPOT, thông lượng — và chọn cỡ GPU', 'Thời gian tới token đầu, thời gian mỗi token · Benchmark bằng công cụ của vLLM · VRAM = trọng số + KV cache · Bảng chọn GPU (24GB, 48GB, 80GB) cho model 7B–70B'],
      ['gateway', 'LLM gateways: LiteLLM, routing, fallbacks, rate limits and semantic caching', 'Gateway LLM: LiteLLM, định tuyến, dự phòng, giới hạn tần suất và cache ngữ nghĩa', 'Một API cho nhiều nhà cung cấp và model tự host · Fallback khi nhà cung cấp sập · Trần chi phí theo người dùng · Cache theo câu hỏi tương tự và rủi ro trả lời sai ngữ cảnh'],
    ]],
    ['Chapter 7 — Fine-tuning pipelines', 'Chương 7 — Pipeline fine-tune', 'Biến fine-tune từ một lần chạy tay thành quy trình lặp lại được.', [
      ['khi-nao-fine-tune', 'When to fine-tune, when to prompt or use RAG', 'Khi nào fine-tune, khi nào chỉ cần prompt hoặc RAG', 'Cây quyết định · Fine-tune dạy hình thức, RAG cấp kiến thức (so sánh ở /courses/rag-vector-search mục 0) · Chi phí dữ liệu thường lớn hơn chi phí GPU'],
      ['du-lieu-sft', 'Building SFT datasets: collection, cleaning, deduplication, PII removal', 'Dựng bộ dữ liệu SFT: thu thập, làm sạch, khử trùng lặp, gỡ dữ liệu cá nhân', 'Định dạng hội thoại · Khử trùng gần đúng (MinHash) · Gỡ PII bằng Presidio · Tách tập đánh giá trước khi làm gì khác'],
      ['lora-pipeline', 'A reproducible LoRA/QLoRA pipeline with PEFT and TRL', 'Pipeline LoRA/QLoRA tái lập được với PEFT và TRL', 'Cách LoRA hoạt động đã ở /courses/deep-learning 8.3 · Ở đây: cấu hình Hydra, theo dõi MLflow, điểm kiểm, chạy lại được · Gộp adapter hay giữ riêng'],
      ['dpo', 'Preference tuning: RLHF in brief, DPO in practice', 'Tinh chỉnh theo sở thích: RLHF tóm tắt, DPO thực hành', 'RLHF (InstructGPT 2022) bằng hình · DPO (Rafailov et al. 2023) không cần model thưởng · Thu thập cặp ưu/nhược từ phản hồi người dùng'],
      ['danh-gia-truoc-len', 'Gating a fine-tuned model: eval suites, regression checks and human review', 'Chặn cửa cho model đã fine-tune: bộ eval, kiểm hồi quy và người duyệt', 'Không được tệ hơn model gốc ở việc cũ · Bộ eval theo tác vụ (cách xây ở /courses/ai-agents Chương 7) · Ngưỡng tự động + người ký duyệt'],
      ['multi-lora', 'Serving many LoRA adapters on one base model', 'Phục vụ nhiều adapter LoRA trên một model gốc', 'Multi-LoRA trong vLLM · Một adapter cho mỗi khách hàng/tác vụ · Nạp/gỡ adapter lúc chạy · Đặt phiên bản adapter trong registry'],
    ]],
    ['Chapter 8 — Monitoring models', 'Chương 8 — Giám sát model', 'Model không báo lỗi khi nó sai dần — bạn phải đo.', [
      ['loai-drift', 'Kinds of drift: data drift, concept drift, label shift', 'Các kiểu trôi dạt: data drift, concept drift, label shift', 'Ví dụ thật: hành vi người dùng đổi sau COVID-19 làm nhiều model dự báo hỏng năm 2020 · Drift thật vs mùa vụ · Khi nào drift không quan trọng'],
      ['do-drift', 'Measuring drift: PSI, KS test, Wasserstein — with Evidently', 'Đo trôi dạt: PSI, kiểm định KS, Wasserstein — bằng Evidently', 'Cửa sổ tham chiếu vs hiện tại · Ngưỡng cảnh báo hợp lý · Báo cáo Evidently tự host · Kiểm định thống kê nền ở /courses/statistics-data-science Chương 5'],
      ['chua-co-nhan', 'Monitoring quality when labels arrive late or never', 'Giám sát chất lượng khi nhãn đến muộn hoặc không bao giờ đến', 'Chỉ số thay thế (proxy) · Phân phối điểm dự đoán · Lấy mẫu để gán nhãn tay · Phản hồi ngầm của người dùng'],
      ['metric-he-thong', 'Model service metrics in Prometheus and Grafana', 'Chỉ số dịch vụ model trên Prometheus và Grafana', 'Độ trễ, lỗi, GPU util, VRAM, hàng đợi · Nguyên tắc chỉ số và cảnh báo chung đã ở /courses/observability-monitoring Chương 4 và 9 — ở đây là chỉ số riêng của model'],
      ['huan-luyen-lai', 'Retraining triggers: schedule, drift threshold, or performance drop', 'Kích hoạt huấn luyện lại: theo lịch, theo ngưỡng drift, hay theo hiệu năng giảm', 'Ưu nhược từng cách · Huấn luyện lại tự động nhưng lên production có người duyệt · Tránh vòng phản hồi tự khuếch đại'],
    ]],
    ['Chapter 9 — LLMOps: tracing, online evals and prompts in production', 'Chương 9 — LLMOps: tracing, eval trực tuyến và prompt trên production', 'Vận hành ứng dụng LLM khi câu trả lời không có "đúng/sai" rõ ràng.', [
      ['tracing', 'Tracing LLM calls with Langfuse and OpenTelemetry GenAI conventions', 'Tracing lời gọi LLM với Langfuse và quy ước OpenTelemetry GenAI', 'Một trace cho cả chuỗi: truy xuất → prompt → model → tool · Ghi token, chi phí, độ trễ · Tự host Langfuse · Trace agent nhiều bước đã ở /courses/ai-agents 8.3 — ở đây là hạ tầng chạy thường trực'],
      ['eval-truc-tuyen', 'Online evaluation: sampling production traffic, LLM judges and user feedback', 'Đánh giá trực tuyến: lấy mẫu lưu lượng thật, giám khảo LLM và phản hồi người dùng', 'Eval offline đã ở /courses/ai-agents Chương 7–8 và /courses/rag-vector-search Chương 8 · Ở đây: chấm tự động một % request thật, nút thích/không thích, gom lỗi thành bộ eval mới'],
      ['quan-ly-prompt', 'Prompt versioning, a prompt registry and regression tests in CI', 'Quản lý phiên bản prompt, kho prompt và kiểm hồi quy trong CI', 'Prompt là code: có phiên bản, có review · Đổi prompt chạy lại bộ eval trong GitHub Actions · Triển khai prompt bằng cờ tính năng · Viết prompt tốt ở /courses/llm-apps Chương 2'],
      ['doi-model', 'Swapping models safely: when the provider changes or deprecates a model', 'Đổi model an toàn: khi nhà cung cấp thay đổi hoặc ngừng một model', 'Model bị đổi tên/ngừng là sự cố thường gặp · Kiểm hồi quy trước khi đổi · Ghim phiên bản model · Bảng chi phí theo tính năng'],
      ['chi-phi-llm', 'LLM cost observability: cost per feature, per user, per request', 'Quan sát chi phí LLM: chi phí theo tính năng, theo người dùng, theo request', 'Gắn nhãn tính năng cho mỗi lời gọi · Trần ngày và cảnh báo · Token suy luận ẩn của model reasoning · Đặt trần cơ bản đã ở /courses/llm-apps 6.2'],
    ]],
    ['Chapter 10 — Safety, governance and compliance', 'Chương 10 — An toàn, quản trị và tuân thủ', 'Những gì luật pháp và người dùng đòi hỏi khi AI chạy thật.', [
      ['owasp-llm', 'OWASP Top 10 for LLM Applications as a production checklist', 'OWASP Top 10 cho ứng dụng LLM như checklist production', 'Từng mục với ví dụ và biện pháp · Prompt injection đã ở /courses/llm-apps Chương 7 — ở đây là kiểm soát trên hạ tầng · Rò rỉ dữ liệu qua log và trace'],
      ['guardrail-prod', 'Guardrails as a service: input/output classifiers like Llama Guard, policy engines and audit logs', 'Guardrail như một dịch vụ: bộ phân loại đầu vào/đầu ra như Llama Guard, policy engine và log kiểm toán', 'Đặt guardrail ở gateway thay vì rải trong code · Độ trễ thêm và báo nhầm · Ghi log kiểm toán không chứa dữ liệu nhạy cảm'],
      ['phap-ly-ai', 'Regulation and frameworks: EU AI Act, NIST AI RMF, and Vietnam’s personal data rules', 'Luật và khung quản trị: EU AI Act, NIST AI RMF, và quy định dữ liệu cá nhân của Việt Nam', 'EU AI Act (2024) phân loại theo rủi ro · NIST AI RMF 1.0 (2023) · Luật Bảo vệ dữ liệu cá nhân 91/2025/QH15 và Nghị định 356/2025/NĐ-CP (chi tiết ở /courses/privacy-data-law) · Người soạn chi tiết sẽ kiểm văn bản gốc'],
      ['thien-lech-red-team', 'Bias audits and authorized red teaming of your own models', 'Kiểm toán thiên lệch và red team có phép trên model của chính mình', 'Chỉ số theo nhóm · Bộ câu hỏi đối kháng tự xây · Chỉ thử trên hệ thống của mình · Ghi lại và sửa theo vòng'],
    ]],
    ['Chapter 11 — ML platforms and GPU cost', 'Chương 11 — Nền tảng ML và chi phí GPU', 'Tự dựng hay thuê, và làm sao để hoá đơn GPU không làm bạn mất ngủ.', [
      ['build-vs-buy', 'Build vs buy: SageMaker, Vertex AI, Databricks, Azure ML vs open source', 'Tự dựng hay thuê: SageMaker, Vertex AI, Databricks, Azure ML so với mã nguồn mở', 'Bảng so sánh theo quy mô nhóm · Khoá chặt nhà cung cấp · Chi phí ẩn của tự vận hành'],
      ['gpu-k8s', 'GPUs on Kubernetes: device plugin, GPU Operator, MIG and time-slicing', 'GPU trên Kubernetes: device plugin, GPU Operator, MIG và chia thời gian', 'Xin GPU trong manifest · Chia một GPU cho nhiều pod · Node GPU tự co giãn · Đặt lịch theo loại GPU'],
      ['finops-ml', 'FinOps for ML: spot instances, right-sizing, batching and turning things off', 'FinOps cho ML: máy spot, chọn đúng cỡ, gom lô và tắt khi không dùng', 'Huấn luyện trên spot với điểm kiểm · GPU nhàn rỗi là tiền đốt · Thuê GPU theo giờ (RunPod, Lambda, Vast.ai — ghi chú, không quảng cáo) · Tính chi phí mỗi 1.000 dự đoán'],
      ['nha-va-vps', 'A hybrid setup like this site: home GPU for heavy work, VPS for serving, tunnels in between', 'Kiến trúc lai như trang này: GPU ở nhà cho việc nặng, VPS để phục vụ, đường hầm ở giữa', 'Máy nhà huấn luyện và chạy model lớn · VPS chạy gateway và API · Đường hầm SSH/Tailscale · Khi máy nhà tắt thì fallback sang API thuê'],
    ]],
    ['Chapter 12 — Interviews and certifications', 'Chương 12 — Phỏng vấn và chứng chỉ', 'Chuẩn bị cho vị trí MLOps / ML platform / AI engineer.', [
      ['ml-system-design', 'ML system design interviews: recommendation, search ranking, fraud detection, an LLM assistant', 'Phỏng vấn thiết kế hệ thống ML: gợi ý, xếp hạng tìm kiếm, phát hiện gian lận, trợ lý LLM', 'Khung trả lời: yêu cầu → dữ liệu → đặc trưng → model → phục vụ → giám sát · Đánh đổi độ trễ/chi phí/chất lượng · System design chung ở /courses/system-design'],
      ['su-co-kinh-dien', 'Classic MLOps incidents and how to tell them in an interview', 'Sự cố MLOps kinh điển và cách kể khi phỏng vấn', 'Lệch train/serve · Model âm thầm hỏng vì drift · Hết VRAM khi tăng tải · Prompt đổi làm hỏng tính năng · Kể theo STAR'],
      ['cau-hoi', 'Interview questions on MLOps and LLMOps', 'Câu hỏi phỏng vấn về MLOps và LLMOps', '40 câu hay gặp và ý trả lời: registry, canary, drift, KV cache, batching, eval, chi phí'],
      ['chung-chi', 'Real certifications for MLOps and AI engineers', 'Chứng chỉ có thật cho MLOps và AI engineer', 'AWS Certified Machine Learning Engineer – Associate · Google Cloud Professional Machine Learning Engineer · Databricks Certified Machine Learning Associate/Professional · Microsoft Azure AI Engineer Associate (AI-102) · Mỗi chứng chỉ kiểm gì, ai nên thi · Thứ tự hợp lý cho sinh viên · Portfolio với dự án Chương 13 nặng ký hơn một chứng chỉ đơn lẻ'],
    ]],
    ['Chapter 13 — Capstone: running LabFlow AI’s models in production', 'Chương 13 — Dự án cuối khoá: vận hành các model của LabFlow AI trên production', 'Trợ lý AI và model phát hiện bất thường cảm biến, có pipeline, registry, giám sát và runbook.', [
      ['kien-truc', 'Architecture: anomaly model, AI lab assistant, gateway, and where each runs', 'Kiến trúc: model phát hiện bất thường, trợ lý AI phòng lab, gateway, và mỗi thứ chạy ở đâu', 'Đầu vào từ lakehouse (/courses/spark-lakehouse Chương 12) và đặc trưng từ /courses/statistics-data-science Chương 13 · Spring Boot gọi dịch vụ AI Python · Sơ đồ triển khai máy nhà + VPS'],
      ['pipeline-registry', 'Training pipeline and registry for the anomaly model', 'Pipeline huấn luyện và registry cho model phát hiện bất thường', 'Nâng cấp model numpy ở /courses/math-for-ml Chương 13 thành pipeline có phiên bản · MLflow + MinIO · Cổng chất lượng trong CI'],
      ['phuc-vu-llm', 'Serving a small open LLM with vLLM behind a gateway with fallback', 'Phục vụ một LLM mở cỡ nhỏ bằng vLLM sau gateway có dự phòng', 'vLLM trên GPU máy nhà · LiteLLM định tuyến, fallback sang API thuê khi máy nhà tắt · Trần chi phí và giới hạn tần suất'],
      ['giam-sat-eval', 'Monitoring: drift reports, Langfuse traces, online evals and alerts', 'Giám sát: báo cáo drift, trace Langfuse, eval trực tuyến và cảnh báo', 'Evidently theo lịch · Grafana cho độ trễ/GPU · Lấy mẫu câu trả lời để chấm · Cảnh báo về Telegram/email'],
      ['runbook', 'Runbook, rollback drill, model card — and the interview story', 'Runbook, diễn tập quay lui, model card — và câu chuyện phỏng vấn', 'Diễn tập: model mới tệ hơn → quay lui bằng alias · Model card cho cả hai model · Checklist toàn khoá · Kể dự án theo khung system design ML'],
    ]],
  ]),
};
